#!/usr/bin/env python3
"""Generate all PM visualization plots.

Invokes each visualization module's `main()` via `importlib.import_module`
rather than the legacy file-path scan, which fails inside an installed
lib because the simulations are package modules, not source-tree paths.

Output: `AutoGenerated/plots/*.png` (+ `.pdf` for the headline figures).

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

from metaphysica.generators._common import out_dir as _out_dir, autogen_dir as _autogen_dir


VISUALIZATION_MODULES = [
    "metaphysica.simulations.visualizations.certificate_dashboard",
    "metaphysica.simulations.visualizations.four_pattern_orthogonality",
    "metaphysica.simulations.visualizations.four_pattern_stability",
    "metaphysica.simulations.visualizations.torsion_funnel",
    "metaphysica.simulations.visualizations.primary_gates",
    "metaphysica.simulations.visualizations.figure1_m27_decomposition",
    "metaphysica.simulations.visualizations.figure2_convergence_scatter",
    "metaphysica.simulations.visualizations.figure3_alp_discovery_window",
    "metaphysica.simulations.visualizations.figure4_pvalue_distribution",
]


def _run_module(dotted: str) -> bool:
    try:
        mod = importlib.import_module(dotted)
    except ImportError as exc:
        print(f"  [SKIP] {dotted} - {exc}")
        return False

    entry = getattr(mod, "main", None) or getattr(mod, "generate", None)
    if entry is None:
        print(f"  [WARN] {dotted} has no main() or generate()")
        return False

    print(f"\n=== {dotted} ===")
    try:
        rc = entry()
    except Exception as exc:
        print(f"  [ERROR] {dotted}: {type(exc).__name__}: {exc}")
        return False
    if rc not in (None, 0):
        print(f"  [WARN] {dotted} returned {rc}")
        return False
    print(f"  [OK] {dotted}")
    return True


def main() -> int:
    autogen = _autogen_dir()
    plots_dir = autogen / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("PRINCIPIA METAPHYSICA - PLOT GENERATION")
    print(f"Output directory: {plots_dir}")
    print("=" * 70)

    successes = 0
    for dotted in VISUALIZATION_MODULES:
        if _run_module(dotted):
            successes += 1

    print()
    print("=" * 70)
    print(f"PLOT GENERATION COMPLETE: {successes}/{len(VISUALIZATION_MODULES)} successful")
    print("=" * 70)

    pngs = sorted(plots_dir.glob("*.png"))
    pdfs = sorted(plots_dir.glob("*.pdf"))
    print(f"\nGenerated plots ({len(pngs)} PNG + {len(pdfs)} PDF):")
    for f in pngs + pdfs:
        size_kb = f.stat().st_size / 1024
        print(f"  - {f.name} ({size_kb:.1f} KB)")

    print("=" * 70)
    return 0


if __name__ == "__main__":
    sys.exit(main())
