#!/usr/bin/env python3
"""
Generate All PM Visualization Plots
====================================

Runs all visualization scripts to regenerate plots in AutoGenerated/plots/.
This ensures SSOT compliance - plots are generated from simulation data.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

import sys
from pathlib import Path
import importlib.util

from metaphysica.generators._common import out_dir as _out_dir, autogen_dir as _autogen_dir
# Add simulations to path
REPO_ROOT = _out_dir()  # build target dir (defaults to cwd)
sys.path.insert(0, str(REPO_ROOT))

# Define visualization scripts to run
VISUALIZATION_SCRIPTS = [
    "simulations/visualizations/certificate_dashboard.py",
    "simulations/visualizations/four_pattern_orthogonality.py",
    "simulations/visualizations/torsion_funnel.py",
    # Add others as needed
]

def run_script(script_path: str):
    """Run a visualization script by importing and executing it."""
    full_path = REPO_ROOT / script_path

    if not full_path.exists():
        print(f"  [SKIP] {script_path} - file not found")
        return False

    print(f"\n{'='*60}")
    print(f"Running: {script_path}")
    print('='*60)

    try:
        # Import the module
        spec = importlib.util.spec_from_file_location("vis_module", full_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        # Execute main if it exists
        if hasattr(module, 'main'):
            module.main()
        elif hasattr(module, 'generate'):
            module.generate()
        else:
            print(f"  [WARN] No main() or generate() function found")
            return False

        print(f"  [OK] {script_path}")
        return True

    except Exception as e:
        print(f"  [ERROR] {script_path}: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """Generate all plots."""
    print("\n" + "="*70)
    print("PRINCIPIA METAPHYSICA - PLOT GENERATION")
    print("="*70)
    print(f"Output directory: {REPO_ROOT / 'AutoGenerated' / 'plots'}")
    print("="*70)

    # Ensure output directory exists
    output_dir = REPO_ROOT / "AutoGenerated" / "plots"
    output_dir.mkdir(parents=True, exist_ok=True)

    success_count = 0
    total_count = len(VISUALIZATION_SCRIPTS)

    for script in VISUALIZATION_SCRIPTS:
        if run_script(script):
            success_count += 1

    print("\n" + "="*70)
    print(f"PLOT GENERATION COMPLETE: {success_count}/{total_count} successful")
    print("="*70)

    # List generated files
    if output_dir.exists():
        plots = sorted(output_dir.glob("*.png"))
        print(f"\nGenerated plots ({len(plots)}):")
        for plot in plots:
            size_kb = plot.stat().st_size / 1024
            print(f"  - {plot.name} ({size_kb:.1f} KB)")

    print("="*70 + "\n")


if __name__ == "__main__":
    main()
