"""
eml_param_crosscheck.py — Cross-check all eml_description strings in parameters.json.

For every parameter that has an eml_description field, parses and evaluates the
EML expression using EMLEvaluator and compares the result to the registered value.

Results are printed as a table and written to AutoGenerated/eml_crosscheck.json.

Usage:
    python scripts/eml_param_crosscheck.py
    python scripts/eml_param_crosscheck.py --verbose
    python scripts/eml_param_crosscheck.py --tolerance 0.05  # 5% rel tolerance
    python scripts/eml_param_crosscheck.py --only-fails
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any, Optional

from metaphysica.generators._common import out_dir as _out_dir, autogen_dir as _autogen_dir
ROOT = _out_dir()
sys.path.insert(0, str(ROOT))

try:
    from eml_math.evaluator import EMLEvaluator
except ImportError as e:
    print(f"ERROR: cannot import eml_math.evaluator — {e}")
    print("Install or update eml-math: pip install -e H:/Github/EML-Math")
    sys.exit(1)

PARAMS_JSON = ROOT / "AutoGenerated" / "parameters.json"
OUTPUT_JSON = ROOT / "AutoGenerated" / "eml_crosscheck.json"

DEFAULT_TOLERANCE = 0.001  # 0.1% relative tolerance


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_parameters(path: Path) -> dict[str, Any]:
    """Load parameters.json and return the flat {dotted_path: entry} dict.

    parameters.json has the structure::
        {"version": ..., "parameters": {"ckm.V_cb": {...}, ...}}
    so we just return the inner "parameters" dict directly.
    """
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("parameters", data)


def _get_eml_description(entry: dict[str, Any]) -> str:
    """Return eml_description from an entry (top-level or inside metadata)."""
    desc = entry.get("eml_description", "")
    if not desc:
        desc = (entry.get("metadata") or {}).get("eml_description", "")
    return desc or ""


def _build_context(params: dict[str, Any]) -> dict[str, float]:
    """Build {name: float_value} context for EMLEvaluator from all params.

    Aliases (low → high priority, later wins on collision):
      1. last component  ``c``      (e.g. ``lambda_wolfenstein``)
      2. last two parts  ``b.c``    (e.g. ``ckm.lambda_wolfenstein``)
      3. full path       ``a.b.c``  (always available)
      4. FormulasRegistry seeds + symbols — canonical short names like
         ``b3 = 24``, ``chi_eff = 72``, ``M_Planck`` etc. These OVERRIDE
         heuristic short aliases so eml_descriptions referencing the
         well-known seed names get the seed value, not whatever happened
         to be at ``topology.b3_modular`` or ``geometry.chi_eff_total``.
    """
    ctx: dict[str, float] = {}

    # 1+2 — short / medium aliases (low priority)
    for path, entry in params.items():
        val = entry.get("value")
        if val is None: continue
        try:    f = float(val)
        except (TypeError, ValueError): continue
        if not math.isfinite(f): continue

        parts = path.split(".")
        ctx.setdefault(parts[-1], f)
        if len(parts) >= 2:
            ctx.setdefault(".".join(parts[-2:]), f)

    # 3 — full paths (override)
    for path, entry in params.items():
        val = entry.get("value")
        if val is None: continue
        try:    f = float(val)
        except (TypeError, ValueError): continue
        if not math.isfinite(f): continue
        ctx[path] = f

    # 4 — FormulasRegistry canonical seeds + symbols (highest priority)
    #     These are the names physicists actually use and that the
    #     eml_descriptions are written against.
    try:
        from metaphysica.simulations.core.FormulasRegistry import FormulasRegistry
        fr = FormulasRegistry()
        for src in ("get_all_seeds", "get_all_symbols_with_values"):
            if not hasattr(fr, src): continue
            try:    table = getattr(fr, src)()
            except Exception: continue
            if not isinstance(table, dict): continue
            for name, val in table.items():
                try:    f = float(val)
                except (TypeError, ValueError): continue
                if not math.isfinite(f): continue
                ctx[name] = f
    except ImportError:
        pass  # framework not available — fall back to params-only

    return ctx


def _rel_error(evaluated: float, registered: float) -> Optional[float]:
    """Relative error between evaluated and registered values."""
    if registered == 0.0:
        return abs(evaluated - registered)
    return abs(evaluated - registered) / abs(registered)


def _classify(evaluated: float, registered: float, tolerance: float,
              loose: float, missing_refs: list) -> tuple[str, str]:
    """Return (status, diagnostic) — fine-grained AGREE/DISAGREE bucket."""
    if not (math.isfinite(evaluated) and math.isfinite(registered)):
        return "DISAGREE_NONFINITE", "non-finite"

    rel = _rel_error(evaluated, registered)
    if rel is not None and rel <= tolerance:
        return "AGREE", ""
    if rel is not None and rel <= loose:
        return "AGREE_LOOSE", f"within {loose:.0%}"

    # sign-flip: |evaluated + registered| ≈ 0  ⇒ evaluated == −registered
    if registered != 0 and abs(evaluated + registered) / abs(registered) <= tolerance:
        return "DISAGREE_SIGN", "sign flip — magnitudes match"

    # scale: ratio is a clean power of 10
    if evaluated != 0 and registered != 0:
        ratio = evaluated / registered
        if ratio > 0 and math.isfinite(ratio):
            log10 = math.log10(ratio)
            if math.isfinite(log10):
                nearest = round(log10)
                if abs(log10 - nearest) < 0.02 and nearest != 0:
                    return "DISAGREE_SCALE", f"off by 10^{nearest}"

    # missing-context: evaluator flagged unresolved refs
    if missing_refs:
        return "DISAGREE_MISSING_CTX", f"missing: {', '.join(missing_refs[:3])}"

    return "DISAGREE", f"rel_err={rel*100:.2f}%" if rel is not None else "no rel_err"


# ---------------------------------------------------------------------------
# Main check
# ---------------------------------------------------------------------------

def run_crosscheck(
    tolerance: float = DEFAULT_TOLERANCE,
    verbose: bool = False,
    only_fails: bool = False,
    loose_tolerance: float = 0.01,  # 1% — AGREE_LOOSE bucket
) -> dict[str, Any]:
    from collections import Counter
    params = _load_parameters(PARAMS_JSON)
    context = _build_context(params)

    evaluator = EMLEvaluator(context, strict=False)

    results: list[dict[str, Any]] = []
    bucket_counts: Counter = Counter()
    n_agree = n_disagree = n_skip = n_no_value = 0

    for path, entry in sorted(params.items()):
        eml_desc = _get_eml_description(entry)
        if not eml_desc:
            n_skip += 1
            if verbose:
                results.append({"path": path, "status": "SKIP", "reason": "no eml_description"})
            continue

        registered_val = entry.get("value")
        if registered_val is None:
            n_no_value += 1
            results.append({
                "path": path,
                "status": "SKIP",
                "reason": "no registered value",
                "eml_description": eml_desc,
            })
            continue

        try:
            registered_float = float(registered_val)
        except (TypeError, ValueError):
            n_no_value += 1
            results.append({
                "path": path,
                "status": "SKIP",
                "reason": f"non-numeric value: {registered_val!r}",
                "eml_description": eml_desc,
            })
            continue

        err_msg: Optional[str] = None
        try:
            evaluated = evaluator.eval(eml_desc)
        except Exception as exc:
            evaluated = None
            err_msg = str(exc)

        if evaluated is None:
            n_skip += 1
            rec = {
                "path": path,
                "status": "ERROR",
                "reason": err_msg or "eval raised exception",
                "registered": registered_float,
                "eml_description": eml_desc,
            }
            results.append(rec)
            if verbose:
                print(f"  ERROR  {path}: {err_msg}")
            continue

        if not math.isfinite(evaluated) or not math.isfinite(registered_float):
            n_skip += 1
            results.append({
                "path": path,
                "status": "SKIP",
                "reason": "non-finite value",
                "evaluated": evaluated,
                "registered": registered_float,
                "eml_description": eml_desc,
            })
            continue

        missing = list(evaluator.missing_refs)
        evaluator.missing_refs.clear()

        rel_err = _rel_error(evaluated, registered_float)
        status, diag = _classify(
            evaluated, registered_float, tolerance, loose_tolerance, missing,
        )
        bucket_counts[status] += 1

        rec: dict[str, Any] = {
            "path": path,
            "status": status,
            "evaluated": evaluated,
            "registered": registered_float,
            "rel_error": rel_err,
            "eml_description": eml_desc,
        }
        if diag:     rec["diagnostic"]   = diag
        if missing:  rec["missing_refs"] = missing

        results.append(rec)

        if status in ("AGREE", "AGREE_LOOSE"):
            n_agree += 1
            if verbose and not only_fails:
                print(f"  {status}  {path}  (eval={evaluated:.6g}  reg={registered_float:.6g})")
        else:
            n_disagree += 1
            print(
                f"  {status}  {path}\n"
                f"    evaluated={evaluated:.8g}  registered={registered_float:.8g}"
                f"  ({diag})"
            )

    total_with_desc = n_agree + n_disagree
    total = len(params)

    print("\n" + "=" * 60)
    print(f"TOTAL parameters:          {total}")
    print(f"  with eml_description:    {total_with_desc + n_no_value}")
    print(f"  SKIP (no value/error):   {n_skip + n_no_value}")
    print()
    print(f"  AGREE  (<={tolerance:.1%}):              {bucket_counts.get('AGREE', 0)}")
    print(f"  AGREE_LOOSE  (<={loose_tolerance:.0%}):          {bucket_counts.get('AGREE_LOOSE', 0)}")
    print(f"  DISAGREE_SIGN (mag matches):  {bucket_counts.get('DISAGREE_SIGN', 0)}")
    print(f"  DISAGREE_SCALE (x10^k):       {bucket_counts.get('DISAGREE_SCALE', 0)}")
    print(f"  DISAGREE_MISSING_CTX:         {bucket_counts.get('DISAGREE_MISSING_CTX', 0)}")
    print(f"  DISAGREE_NONFINITE:           {bucket_counts.get('DISAGREE_NONFINITE', 0)}")
    print(f"  DISAGREE (other):             {bucket_counts.get('DISAGREE', 0)}")
    if total_with_desc > 0:
        strict = 100 * bucket_counts.get('AGREE', 0) / total_with_desc
        loose  = 100 * (bucket_counts.get('AGREE', 0) + bucket_counts.get('AGREE_LOOSE', 0)) / total_with_desc
        print()
        print(f"  Strict agreement rate:   {strict:.1f}%")
        print(f"  Loose  agreement rate:   {loose:.1f}%")
    print("=" * 60)

    summary = {
        "total": total,
        "with_eml_description": total_with_desc + n_no_value,
        "skip": n_skip + n_no_value,
        "buckets": dict(bucket_counts),
        "agreement_rate_strict": (
            bucket_counts.get('AGREE', 0) / total_with_desc if total_with_desc > 0 else None
        ),
        "agreement_rate_loose": (
            (bucket_counts.get('AGREE', 0) + bucket_counts.get('AGREE_LOOSE', 0))
            / total_with_desc if total_with_desc > 0 else None
        ),
        "tolerance": tolerance,
        "loose_tolerance": loose_tolerance,
        "results": results,
    }

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    def _json_safe(obj: Any) -> Any:
        if isinstance(obj, float) and not math.isfinite(obj):
            return str(obj)
        if isinstance(obj, dict):
            return {k: _json_safe(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_json_safe(v) for v in obj]
        return obj

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(_json_safe(summary), f, indent=2)
    print(f"\nDetailed results -> {OUTPUT_JSON}")

    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Cross-check eml_description fields in parameters.json")
    parser.add_argument("--tolerance", type=float, default=DEFAULT_TOLERANCE,
                        help=f"Relative tolerance for AGREE (default {DEFAULT_TOLERANCE})")
    parser.add_argument("--verbose", action="store_true",
                        help="Print AGREE lines too (default: only DISAGREE)")
    parser.add_argument("--only-fails", action="store_true",
                        help="Only print DISAGREE/ERROR lines")
    args = parser.parse_args()

    summary = run_crosscheck(
        tolerance=args.tolerance,
        verbose=args.verbose,
        only_fails=args.only_fails,
    )

    # Exit non-zero only when there are *real* disagreements (not loose agreements)
    real_disagreements = sum(
        v for k, v in summary["buckets"].items() if k.startswith("DISAGREE")
    )
    if real_disagreements > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
