"""
generate_arithma_dependency_walker.py — Sprint 3 #4.

Walks every formula's symbolic tree back to its b3=24 root (the third Betti
number, the single Ten-Pillar seed the framework claims to derive everything
from). Output ``AutoGenerated/dependency_chains.json`` maps each formula id to
its ordered chain of intermediate quantities terminating at the b3 leaf.

Walk strategy (preferred → degraded):
  1. ``Formula.arithma_compact``  — Sprint 3.2 schema (not yet populated).
  2. EML compact tree from ``eml_trees.json[f][<id>]['c']`` — same structural
     shape (op, kind, *children) the Arithma compact form will take, so it is
     a faithful stand-in.
  3. ``Formula.arithma_latex`` / ``latex`` string mention search — degraded;
     output marks ``degraded_walk: true``.

b3 leaf detection:
  - Parameter id ``topology.elder_kads`` is the canonical b3 param.
  - Numeric leaf ``24`` is *ambiguous* (could be 24-cell, 2*12 generations,
    etc.) — counted in ``raw_24_leaves_count`` and flagged for review.
  - Strings ``b3``/``b_3``/``\\beta_3`` count as b3 mentions (degraded mode).

Transitive chain: each formula's ``input_params`` are followed to producing
formulas via ``output_params``; the chain depth is the number of hops to a
formula whose own input list contains ``topology.elder_kads`` (a direct b3
consumer) or which has no further inputs.

Usage:
    python -m metaphysica.generators.generate_arithma_dependency_walker
"""
from __future__ import annotations

import json
from pathlib import Path

from metaphysica.generators._common import autogen_dir

B3_PARAM = "topology.elder_kads"
# Accept any of the canonical b3-leaf labels emitted by the EML/Arithma
# parsers: `b3_leaf` is what `b3_leaf()` parses to in compact mode;
# `b3` / `b_3` are the bare symbolic spellings used by some legacy entries.
B3_LEAF_LABELS = ("b3", "b_3", "b3_leaf")
B3_LATEX_TOKENS = ("b_3", "b3", "\\beta_3", "topology.elder_kads")

try:
    import arithma  # type: ignore[import-not-found]
    ARITHMA_AVAILABLE = True
except ImportError:
    ARITHMA_AVAILABLE = False


#: Kind tokens that appear FIRST in an arithma compact node. The two compact
#: formats order the pair the opposite way round:
#:
#:     EML      [label, kind]     ["b3_leaf", "c"]   ["144", "#"]
#:     arithma  [kind, label]     ["var", "b3"]      ["num", "6"]
#:
#: This walker only understood the EML order, which was harmless for as long
#: as no arithma tree existed -- and none did, because every arithma
#: expression failed to serialise while `Expression.constant("b3")` had no
#: cached value and `from_f64` used a saturating fixed scale. With those
#: fixed, 169 of 422 formulas now carry a real arithma tree, and reading
#: ["var", "b3"] as label="var" silently found no b3 in any of them.
_ARITHMA_KIND_TOKENS = frozenset({"fn", "num", "var", "const"})


def _compact_label_and_kind(node):
    """Return (label, kind) from a compact node of either dialect."""
    first, second = str(node[0]), str(node[1])
    if first in _ARITHMA_KIND_TOKENS:
        return second, first          # arithma: [kind, label]
    return first, second              # EML:     [label, kind]


def _walk_compact_tree(node, counts):
    """Walk an EML/Arithma compact-form node and tally b3 / raw-24 leaves."""
    if not isinstance(node, list) or len(node) < 2:
        return
    label, kind = _compact_label_and_kind(node)
    children = node[2:]
    if not children:  # leaf
        if kind in ("#", "num"):
            try:
                if float(label) == 24.0:
                    counts["raw_24"] += 1
            except (TypeError, ValueError):
                pass
        elif label.lower() in B3_LEAF_LABELS or label == B3_PARAM:
            counts["b3"] += 1
        return
    for child in children:
        _walk_compact_tree(child, counts)


def _build_chain(fid, formulas, producer_of, seen, depth_cap=12):
    """Return ordered list of formula ids from *fid* up to a b3 root."""
    chain = [fid]
    via = []
    cur = fid
    while len(chain) < depth_cap:
        if cur in seen:
            break
        seen.add(cur)
        inputs = formulas.get(cur, {}).get("input_params") or []
        if B3_PARAM in inputs:
            chain.append("b3_leaf")
            return chain, via
        # Walk to a producing formula of the first non-b3 input that has one.
        nxt = None
        for p in inputs:
            cands = producer_of.get(p)
            if cands:
                nxt = cands[0]
                via.append(p)
                break
        if not nxt or nxt == cur:
            break
        chain.append(nxt)
        cur = nxt
    return chain, via


def main() -> int:
    ag = autogen_dir()
    with open(ag / "formulas.json", encoding="utf-8") as fp:
        formulas = json.load(fp).get("formulas", {})

    # Needed to tell a real declared dependency from a phantom one.
    params = {}
    params_path = ag / "parameters.json"
    if params_path.exists():
        with open(params_path, encoding="utf-8") as fp:
            params = json.load(fp).get("parameters", {})

    eml_trees = {}
    eml_path = ag / "eml_trees.json"
    if eml_path.exists():
        with open(eml_path, encoding="utf-8") as fp:
            eml_trees = json.load(fp).get("f", {})

    producer_of = {}
    for fid, f in formulas.items():
        for out in f.get("output_params") or []:
            producer_of.setdefault(out, []).append(fid)

    chains = {}
    b3_rooted = ambiguous = non_rooted = 0
    degraded_total = 0

    for fid, f in formulas.items():
        counts = {"b3": 0, "raw_24": 0}
        degraded = True
        # Preferred walk: arithma_compact (Sprint 3.2 — usually absent today).
        if f.get("arithma_compact"):
            _walk_compact_tree(f["arithma_compact"], counts)
            degraded = False
        # Fallback 1: structural EML compact tree (same node shape).
        elif fid in eml_trees and isinstance(eml_trees[fid].get("c"), list):
            _walk_compact_tree(eml_trees[fid]["c"], counts)
            degraded = False
        else:
            # Fallback 2: degraded string scan over arithma_latex / latex.
            blob = (f.get("arithma_latex") or f.get("latex") or "")
            for tok in B3_LATEX_TOKENS:
                if tok in blob:
                    counts["b3"] += 1
                    break
            if "24" in blob:
                counts["raw_24"] += 1
        if degraded:
            degraded_total += 1

        path, via = _build_chain(fid, formulas, producer_of, set())
        has_b3 = counts["b3"] > 0 or path[-1] == "b3_leaf" or B3_PARAM in (f.get("input_params") or [])
        if has_b3:
            b3_rooted += 1
        elif counts["raw_24"] > 0:
            ambiguous += 1
        else:
            non_rooted += 1

        depth = len(path)
        chains[fid] = {
            "depth": depth,
            "path": path,
            "via": via,
            "raw_24_leaves_count": counts["raw_24"],
            "b3_leaf_count": counts["b3"],
            "compression_ratio": round(depth / max(1, len(via) or 1), 3),
            "degraded_walk": degraded,
            "b3_rooted": has_b3,
        }

    # A declared input or output that names no registry parameter is
    # invisible to the walk: producer_of simply has no entry for it and the
    # loop moves on. So a formula can declare a dependency that does not
    # exist and still be counted, and b3_rooted_count is then measured over
    # chains that are partly fictional. Counting the phantoms does not
    # repair them, but it stops the rooted count being read as though every
    # declared edge were real.
    known_paths = set(params) if isinstance(params, dict) else set()
    phantom_inputs, phantom_outputs = {}, {}
    if known_paths:
        for fid, f in formulas.items():
            missing_in = sorted(set(f.get("input_params") or []) - known_paths)
            missing_out = sorted(set(f.get("output_params") or []) - known_paths)
            if missing_in:
                phantom_inputs[fid] = missing_in
            if missing_out:
                phantom_outputs[fid] = missing_out
    distinct_phantoms = sorted(
        {p for v in phantom_inputs.values() for p in v}
        | {p for v in phantom_outputs.values() for p in v})


    # registry.get(path, default=X) where the path does not exist. The
    # default then fires on EVERY call and the lookup is decorative -- a
    # hardcoded value wearing the costume of a registry read. This is the
    # same shape as the chi-squared that came from
    # summary.get("global_chi_squared", 0.23) on a key that never existed.
    #
    # Several were load-bearing physics: observational.H0_shoes defaulting
    # to 73.04, observational.H0_planck to 67.4, and -- worst --
    # cosmology.H0_geometric, a PREDICTION, defaulting to 73.04, the SH0ES
    # MEASUREMENT it exists to predict. That is the pattern the R4 ruling
    # struck out elsewhere, reappearing as a default argument.
    silent_defaults = []
    if known_paths:
        try:
            import ast as _ast
            from pathlib import Path as _Path

            # AST, not a regex over raw text. The earlier regex matched any
            # occurrence of the pattern ANYWHERE in a file, including inside
            # the comments written to explain a site that had already been
            # repaired -- so documenting a fix made the count go UP, and the
            # audit punished exactly the behaviour it exists to encourage.
            # Walking the tree counts calls, so prose about a call is prose.
            def _default_arg(call):
                for kw in call.keywords:
                    if kw.arg == "default":
                        try:
                            return _ast.unparse(kw.value)
                        except Exception:
                            return "<unparseable>"
                return None

            _root = _Path(__file__).resolve().parents[1]
            for _f in sorted(_root.rglob("*.py")):
                try:
                    _tree = _ast.parse(_f.read_text(encoding="utf-8"))
                except (OSError, UnicodeDecodeError, SyntaxError):
                    continue
                for _node in _ast.walk(_tree):
                    if not isinstance(_node, _ast.Call):
                        continue
                    _func = _node.func
                    if not (isinstance(_func, _ast.Attribute)
                            and _func.attr == "get"):
                        continue
                    if not (_node.args
                            and isinstance(_node.args[0], _ast.Constant)
                            and isinstance(_node.args[0].value, str)):
                        continue
                    _path = _node.args[0].value
                    _dflt = _default_arg(_node)
                    if _dflt is None or _path in known_paths:
                        continue
                    silent_defaults.append({
                        "path": _path,
                        "default": _dflt[:60],
                        "file": _f.relative_to(_root).as_posix(),
                        "line": _node.lineno,
                    })
        except Exception:
            silent_defaults = []

    out = {
        "version": "1.0",
        "root_seed": "b3=24",
        "arithma_available": ARITHMA_AVAILABLE,
        "degraded_walks": degraded_total,
        "total_formulas": len(formulas),
        "b3_rooted_count": b3_rooted,
        "ambiguous_count": ambiguous,
        "non_b3_rooted_count": non_rooted,
        "silent_registry_defaults": {
            "note": (
                "registry.get(path, default=X) where the path does not "
                "exist, so the default fires on every call and the lookup "
                "reads as provenance it does not have. Reported, not "
                "repaired: whether to register the path or drop the lookup "
                "is a per-site question."
            ),
            "count": len(silent_defaults),
            "distinct_paths": sorted({s["path"] for s in silent_defaults}),
            "sites": silent_defaults,
        },
        "declared_paths_that_do_not_exist": {
            "note": (
                "Formula input_params / output_params naming no registry "
                "parameter. The walker cannot see these edges, so a chain "
                "containing one is shorter than it claims and "
                "b3_rooted_count is measured over partly fictional "
                "dependencies. Reported, not repaired: whether the path "
                "should be created or the declaration dropped is a "
                "per-formula question."
            ),
            "formulas_with_phantom_inputs": len(phantom_inputs),
            "formulas_with_phantom_outputs": len(phantom_outputs),
            "distinct_phantom_paths": len(distinct_phantoms),
            "phantom_paths": distinct_phantoms,
            "by_formula_inputs": phantom_inputs,
            "by_formula_outputs": phantom_outputs,
        },
        "chains": chains,
    }
    out_path = ag / "dependency_chains.json"
    with open(out_path, "w", encoding="utf-8") as fp:
        json.dump(out, fp, ensure_ascii=False, separators=(",", ":"))

    size_kb = out_path.stat().st_size / 1024
    print(f"Arithma dependency walker complete:")
    print(f"  Total formulas:    {len(formulas)}")
    print(f"  b3-rooted:         {b3_rooted}")
    print(f"  Ambiguous (24):    {ambiguous}")
    print(f"  Non-b3-rooted:     {non_rooted}")
    print(f"  Degraded walks:    {degraded_total}")
    print(f"  Output:            {out_path}  ({size_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
