"""Per-parameter validation certificates — computed, not declared.

The 2026-08 validation-coverage audit found that every certificate-shaped
artifact on the site (72 gates, named certs, GATES summary) is declarative
or frozen, while the one genuinely computed validation layer — the sigma
deviations in ``AutoGenerated/parameters.json`` — was connected to nothing
user-facing. ``AutoGenerated/validation_report.json`` (fetched by
``Pages/certificates.html``) had shipped as a permanent empty placeholder.

This generator closes that gap. It walks parameters.json and emits one
validation record per parameter that carries BOTH a value and an
experimental comparison:

    { path, value, experimental_value, experimental_uncertainty,
      sigma, status (from the registry's own validation_status),
      verdict: PASS | MARGINAL | TENSION | FAIL | UNBOUNDED | INPUT | IDENTITY,
      source_simulation, units }

The summary reports honest counts — including the failures. A framework
that shows its 3-sigma misses is worth more than one that claims 72/72.

Output: ``AutoGenerated/validation_report.json`` (replacing the placeholder
shipped with the wheel — this generator runs after copy_static).
"""
from __future__ import annotations

import json
import math
from typing import Any, Dict, List

from metaphysica.generators._common import autogen_dir


def _num(v: Any):
    if isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(float(v)):
        return float(v)
    return None


def _is_input_anchor(rec, value, exp) -> bool:
    """True when the record IS the experimental input, not a prediction.

    2026-08 audit: 56 of the report's 109 PASSes were experimental anchors
    being compared against themselves (an ESTABLISHED:* source whose value
    equals its own experimental_value, sigma identically 0). Counting those
    as passes inflated the scoreboard with tautologies. They are now
    reported as INPUT and excluded from the pass/fail tally.
    """
    src = str(rec.get("source") or "")
    if src.upper().startswith("ESTABLISHED"):
        return True
    if value is None or exp is None:
        return False
    try:
        return float(value) == float(exp)
    except (TypeError, ValueError):
        return False


def _is_roundtrip_identity(value, exp) -> bool:
    """True when a 'prediction' reproduces its own input to machine precision.

    2026-08 audit: the framework's most precise-looking results were
    algebraic round-trips - e.g. bulk_hartree = CODATA/f followed by
    manifest_hartree = bulk_hartree * f, which returns CODATA exactly.
    Four QED constants (hartree, bohr, compton, stefan-boltzmann) shared
    this shape and scored ~1e-12 fractional agreement, i.e. floating-point
    noise reported as a part-per-trillion confirmation. Such records are
    consistency identities (the projection algebra is self-inverse), not
    predictions, and must not enter the pass tally.
    """
    if value is None or exp is None or exp == 0:
        return False
    try:
        return abs((float(value) - float(exp)) / float(exp)) < 1e-10
    except (TypeError, ValueError, ZeroDivisionError):
        return False


#: Adopted policy for whether an UNCITED theory uncertainty may change a
#: verdict. Declared as the `theory_uncertainty_policy` fork in
#: simulations/core/variants.py; override per run with
#: METAPHYSICA_VARIANT_THEORY_UNCERTAINTY_POLICY=<option>.
#:
#: Generalises the R6 ruling. G12 was converted with no invented theory
#: buffer and reads COMPUTED_FAIL at 17.1 sigma. The SAME number
#: (0.23190478152123015) also sits in the registry as
#: gauge.sin2_theta_w_geometric carrying an uncited 0.001 buffer and reads
#: PASS at 0.68 sigma -- one prediction, two published verdicts. A buffer
#: nobody derived should not be able to decide the answer.
DEFAULT_THEORY_UNCERTAINTY_POLICY = "cited_only"


def _resolve_theory_policy() -> str:
    try:
        from metaphysica.simulations.core.variants import resolve
        return resolve("theory_uncertainty_policy")
    except Exception:
        return DEFAULT_THEORY_UNCERTAINTY_POLICY


def _theory_uncertainty_is_cited(meta: Dict[str, Any]) -> bool:
    """A named SOURCE is not a citation.

    `theory_uncertainty_source` holds strings like "geometric_vev_precision"
    and "expansion_history_approximation" -- categories, not references. A
    citation must identify something checkable, so a separate key is
    required and its absence means uncited.
    """
    citation = meta.get("theory_uncertainty_citation")
    return bool(citation and str(citation).strip())


def _registry_band(sigma) -> str:
    """Band a sigma the way PMRegistry.set_param does.

    The registry uses <1 PASS, <2 MARGINAL, <3 TENSION, else FAIL, while
    this report's _verdict uses <2/<3/<5. Both conventions are live. The
    theory-uncertainty comparison must not straddle them: banding the
    experimental sigma with the looser scale while the folded sigma carries
    the registry's own verdict made 'experimental_only' report MORE passes
    than the stricter policy, which is impossible (sigma_exp >= sigma_total
    always). Comparing like with like is what makes the diff mean anything.
    """
    if sigma is None:
        return "UNBOUNDED"
    a = abs(sigma)
    if a < 1.0:
        return "PASS"
    if a < 2.0:
        return "MARGINAL"
    if a < 3.0:
        return "TENSION"
    return "FAIL"


#: Bound types that compare a value against a central value, so a residual
#: exists and an uncertainty is required to form it. One-sided bounds are
#: excluded on purpose: for an `upper` or `lower` bound sigma is legitimately
#: None because a margin is not a residual.
_TWO_SIDED_BOUNDS = frozenset({"measured", "central_value", "two_sided"})


def _verdict(sigma, registry_status: str, bound_type: str = "") -> str:
    """Classify by sigma with the registry's own validation_status as guide.

    A two-sided comparison with no uncertainty cannot score. This check comes
    FIRST, ahead of the registry status, because the status short-circuit is
    what let eight rows reach PASS without a comparison: the registry sets
    validation_status when a bound is present, whether or not an uncertainty
    is, and `sigma is None -> UNBOUNDED` below was then unreachable.
    quantum_bio.topological_pitch published 6.12 against a stated 13.0 -- a
    factor of two -- as a PASS.
    """
    if sigma is None and (bound_type or "").lower() in _TWO_SIDED_BOUNDS:
        return "UNBOUNDED"
    s = (registry_status or "").upper()
    if s in ("PASS", "FAIL", "MARGINAL", "TENSION"):
        return s
    if sigma is None:
        return "UNBOUNDED"
    a = abs(sigma)
    if a < 2.0:
        return "PASS"
    if a < 3.0:
        return "MARGINAL"
    if a < 5.0:
        return "TENSION"
    return "FAIL"


def build_report() -> Dict[str, Any]:
    params_path = autogen_dir() / "parameters.json"
    if not params_path.exists():
        return {
            "schema_version": 2,
            "error": "parameters.json not found — run the simulation stage first",
            "validations": [],
        }
    registry = json.loads(params_path.read_text(encoding="utf-8")).get("parameters", {})

    policy = _resolve_theory_policy()
    validations: List[Dict[str, Any]] = []
    for path, rec in sorted(registry.items()):
        value = _num(rec.get("value"))
        exp = _num(rec.get("experimental_value"))
        if value is None or exp is None:
            continue
        sigma = _num(rec.get("sigma_deviation"))
        unc = _num(rec.get("experimental_uncertainty"))
        status = rec.get("validation_status") or ""
        meta = rec.get("metadata") or {}
        if _is_input_anchor(rec, value, exp):
            verdict = "INPUT"
        elif _is_roundtrip_identity(value, exp):
            verdict = "IDENTITY"
        else:
            verdict = _verdict(sigma, status,
                               rec.get("bound_type") or "")

        # Dual sigma reporting. Where a record declares a theory
        # uncertainty, the registry folds it into sigma in quadrature -
        # legitimate for a tree-level derivation, but it can deflate the
        # deviation by orders of magnitude (G_F_matched reads 0.02 sigma
        # with its 0.12% theory bar and 57 sigma against PDG precision
        # alone). Report both so the reader can judge.
        theory_unc = meta.get("theory_uncertainty")
        sigma_exp_only = None
        if unc:
            try:
                sigma_exp_only = abs(float(value) - float(exp)) / float(unc)
            except (TypeError, ValueError, ZeroDivisionError):
                sigma_exp_only = None

        # All three policy outcomes are computed for every row, so the
        # comparison needs no rebuild -- the active policy only decides
        # which one becomes the headline `verdict`.
        v_with_theory = verdict
        v_exp_only = verdict
        # Only re-decide rows the registry itself scored two-sidedly. Where
        # sigma is None the registry declined to compute one -- a one-sided
        # bound has no two-sided sigma -- and manufacturing a verdict from
        # sigma_exp_only there would convert UNBOUNDED rows into PASS/FAIL
        # on a comparison the registry deliberately did not make.
        if (verdict not in ("INPUT", "IDENTITY")
                and sigma is not None and sigma_exp_only is not None):
            v_exp_only = _registry_band(sigma_exp_only)
        cited = _theory_uncertainty_is_cited(meta)
        load_bearing = bool(theory_unc) and v_with_theory != v_exp_only
        if policy == "experimental_only":
            verdict = v_exp_only
        elif policy == "cited_only" and load_bearing and not cited:
            verdict = v_exp_only
        # policy == "always" leaves the folded verdict in place

        validations.append({
            "path": path,
            "value": value,
            "experimental_value": exp,
            "experimental_uncertainty": unc,
            "experimental_source": rec.get("experimental_source"),
            "sigma": sigma,
            "sigma_experimental_only": sigma_exp_only,
            "theory_uncertainty": _num(theory_unc),
            "theory_uncertainty_cited": cited if theory_unc else None,
            "theory_uncertainty_load_bearing": load_bearing or None,
            "verdict": verdict,
            "verdict_with_theory": v_with_theory,
            "verdict_experimental_only": v_exp_only,
            "registry_status": rec.get("status"),
            "units": meta.get("units"),
            "source_simulation": rec.get("source_simulation"),
            "bound_type": rec.get("bound_type"),
            "relative_margin": _num(rec.get("relative_margin")),
        })

    counts: Dict[str, int] = {}
    for v in validations:
        counts[v["verdict"]] = counts.get(v["verdict"], 0) + 1

    # Every policy's scoreboard, computed from the same rows. Publishing all
    # three is the guard against the switch becoming a way to shop for the
    # flattering one: the alternatives are always visible beside the active
    # verdict, and they are ordered by declaration, never by agreement.
    def _tally(key: str) -> Dict[str, int]:
        out: Dict[str, int] = {}
        for v in validations:
            out[v[key]] = out.get(v[key], 0) + 1
        return dict(sorted(out.items()))

    deflated = [
        {
            "path": v["path"],
            "sigma_with_theory": v["sigma"],
            "sigma_experimental_only": v["sigma_experimental_only"],
            "theory_uncertainty": v["theory_uncertainty"],
            "cited": v["theory_uncertainty_cited"],
            "verdict_with_theory": v["verdict_with_theory"],
            "verdict_experimental_only": v["verdict_experimental_only"],
        }
        for v in validations
        if v.get("theory_uncertainty_load_bearing")
    ]
    deflated.sort(key=lambda d: -(d["sigma_experimental_only"] or 0))

    worst = sorted(
        (v for v in validations if v["sigma"] is not None),
        key=lambda v: -abs(v["sigma"]),
    )[:15]

    return {
        "schema_version": 2,
        "generator": "generate_validation_certificates",
        "framework": "Principia Metaphysica",
        "note": (
            "Computed per-parameter validation: every record compares a "
            "framework value against its experimental anchor with the sigma "
            "the registry computed. Verdicts include failures — this report "
            "is the honest scoreboard, distinct from the declarative gate "
            "certificates. PASS < 2σ, MARGINAL < 3σ, TENSION < 5σ, FAIL ≥ 5σ "
            "(or the registry's own validation_status where set). INPUT "
            "marks experimental anchors compared against themselves - they "
            "are inputs, not predictions, and are excluded from the "
            "pass/fail tally. IDENTITY marks algebraic round-trips that "
            "reproduce their own input to machine precision (a projection "
            "applied and then inverted); they are consistency identities, "
            "not predictions. Where a record declares a theory uncertainty, "
            "sigma folds it in and sigma_experimental_only reports the "
            "deviation against the experimental precision alone - read both."
        ),
        "summary": {
            "total": len(validations),
            **{k.lower(): n for k, n in sorted(counts.items())},
        },
        "theory_uncertainty_policy": {
            "active": policy,
            "default": DEFAULT_THEORY_UNCERTAINTY_POLICY,
            "fork": "theory_uncertainty_policy (see variants.json)",
            "rule": (
                "cited_only: a theory uncertainty may change a verdict only "
                "if metadata carries theory_uncertainty_citation. A named "
                "theory_uncertainty_source ('geometric_vev_precision') is a "
                "category, not a reference, and does not count. Generalises "
                "the R6 ruling from G12 to the whole validation layer."
            ),
            "n_rows_with_theory_uncertainty": sum(
                1 for v in validations if v["theory_uncertainty"]
            ),
            "n_load_bearing": len(deflated),
            "n_load_bearing_cited": sum(1 for d in deflated if d["cited"]),
            "scoreboard_if_always": _tally("verdict_with_theory"),
            "scoreboard_if_experimental_only": _tally("verdict_experimental_only"),
            "load_bearing_rows": deflated,
            # Counted, not spelled out. This note used to read "Ten of the
            # fifteen rows", a census frozen into generated prose that went
            # stale the moment the duplicated uncertainty slots in
            # geometric_anchors were separated and four more rows became
            # load-bearing.
            "note": (
                "A theory uncertainty is load-bearing when it changes the "
                "verdict. %d of the %d rows carrying one are NOT load-bearing "
                "-- the allowance is modest and the answer is the same either "
                "way; those are untouched by this policy. Only where a buffer "
                "decides the answer does its provenance matter."
                % (sum(1 for v in validations if v["theory_uncertainty"])
                   - len(deflated),
                   sum(1 for v in validations if v["theory_uncertainty"]))
            ),
        },
        "worst_offenders": [
            {"path": v["path"], "sigma": v["sigma"], "verdict": v["verdict"]}
            for v in worst
        ],
        "validations": validations,
    }


def main() -> int:
    report = build_report()
    out_path = autogen_dir() / "validation_report.json"
    out_path.write_text(json.dumps(report, indent=2, ensure_ascii=False),
                        encoding="utf-8")
    s = report.get("summary", {})
    print("=" * 60)
    print("Per-parameter validation certificates (computed)")
    print("=" * 60)
    if "error" in report:
        print(f"  SKIPPED: {report['error']}")
        return 0
    print("  " + "  ".join(f"{k}: {v}" for k, v in s.items()))
    for w in report.get("worst_offenders", [])[:8]:
        print(f"  [{w['verdict']:8s}] sigma={w['sigma']:>8.2f}  {w['path']}")
    print(f"\nReport written to: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
