"""generate_mismatches.py — Sprint 3 #8.

Surfaces formulas where the Arithma LaTeX, the EML LaTeX, and the computed
numeric value disagree even when ``triple_assert`` passes its tolerance.

Three kinds of mismatch surfaced:

1. ``latex_divergence`` — after a normalization pass (strip ``$``, whitespace,
   lowercase, common LaTeX wrappers), ``arithma_latex != eml_latex``.
2. ``display_vs_computed`` — the LaTeX renders a numeric token (eg. ``6.9e-8``)
   that disagrees with ``value`` by more than 5 %.
3. ``known_bug`` — hand-curated table of bugs already caught by Sprint 2
   (n_gen=chi_eff/(4·b_3) vs the correct (2·b_3)).

Output: ``AutoGenerated/mismatches.json``.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from metaphysica.generators._common import autogen_dir

# Sprint 2 audit catches that we want surfaced regardless of tolerance.
_KNOWN_BUGS = {
    "abstract-n-gen-derivation": {
        "kind": "known_bug",
        "notes": "LaTeX displays n_gen = chi_eff/(4*b_3) = 144/48 = 3 but 4*b_3 = 96. "
                 "Correct denominator is 2*b_3 = 48. Sprint 2.9 migration routes "
                 "through the correct form; LaTeX still needs human edit.",
    },
}

_NUM_RE = re.compile(r"([+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)")


def _normalize_latex(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.replace("$", "").replace("\\\\", "\\")
    s = re.sub(r"\\(?:left|right)", "", s)
    s = re.sub(r"\s+", "", s)
    return s.lower().strip()


def _extract_numeric_tokens(latex: str) -> list:
    """Pull any standalone numeric tokens from a LaTeX string."""
    if not isinstance(latex, str):
        return []
    out = []
    for m in _NUM_RE.finditer(latex):
        tok = m.group(1)
        try:
            v = float(tok)
            # Skip tiny integers (1, 2, etc.) which are usually structural, not values.
            if abs(v) >= 0.001 or v == 0:
                out.append(v)
        except ValueError:
            continue
    return out


def _check_latex_divergence(arithma_latex: str, eml_latex: str):
    if not arithma_latex or not eml_latex:
        return None
    a = _normalize_latex(arithma_latex)
    e = _normalize_latex(eml_latex)
    if a and e and a != e:
        # Cheap divergence-significance test: if the strings share <60% of their tokens
        # we consider it a real divergence rather than a benign rendering difference.
        a_tokens = set(re.findall(r"[a-z0-9_]+", a))
        e_tokens = set(re.findall(r"[a-z0-9_]+", e))
        if not a_tokens or not e_tokens:
            return None
        overlap = len(a_tokens & e_tokens) / max(1, max(len(a_tokens), len(e_tokens)))
        if overlap < 0.6:
            return {
                "kind": "latex_divergence",
                "arithma_latex": arithma_latex[:200],
                "eml_latex": eml_latex[:200],
                "token_overlap": round(overlap, 2),
                "notes": "Arithma and EML LaTeX disagree by more than 40 % of tokens.",
            }
    return None


def _check_display_vs_computed(latex: str, value):
    if value is None or not isinstance(latex, str):
        return None
    try:
        v = float(value)
    except (TypeError, ValueError):
        return None
    tokens = _extract_numeric_tokens(latex)
    if not tokens:
        return None
    # Find the closest displayed token.
    best = None
    best_pct = None
    for tok in tokens:
        if v == 0:
            pct = abs(tok)
        else:
            pct = abs((tok - v) / v) * 100.0
        if best_pct is None or pct < best_pct:
            best_pct = pct
            best = tok
    if best is not None and best_pct is not None and best_pct > 5.0:
        # Only surface if best_pct is meaningfully large; tiny tokens (1, 2, structural)
        # will always show > 5 % vs the actual value, so require the token to be
        # within an order of magnitude of the value.
        if v != 0 and (0.1 * abs(v) < abs(best) < 10 * abs(v)):
            return {
                "kind": "display_vs_computed",
                "displayed_value": best,
                "computed_value": v,
                "delta_pct": round(best_pct, 2),
                "notes": f"LaTeX displays {best} but computed value is {v}.",
            }
    return None


def main() -> int:
    ag = autogen_dir()
    formulas_path = ag / "formulas.json"
    if not formulas_path.exists():
        print("[mismatches] formulas.json not found; skipping.")
        return 0

    formulas = json.load(open(formulas_path, encoding="utf-8")).get("formulas", {})

    mismatches: dict = {}
    by_kind = {"latex_divergence": 0, "display_vs_computed": 0, "known_bug": 0}

    for fid, f in formulas.items():
        if not isinstance(f, dict):
            continue

        if fid in _KNOWN_BUGS:
            entry = dict(_KNOWN_BUGS[fid])
            entry["arithma_latex"] = (f.get("arithma_latex") or "")[:200]
            entry["eml_latex"] = (f.get("eml_latex") or f.get("latex") or "")[:200]
            entry["computed_value"] = f.get("value")
            mismatches[fid] = entry
            by_kind["known_bug"] += 1
            continue

        arithma_latex = f.get("arithma_latex") or ""
        eml_latex = f.get("eml_latex") or f.get("latex") or ""
        value = f.get("value")

        diverge = _check_latex_divergence(arithma_latex, eml_latex)
        if diverge:
            mismatches[fid] = diverge
            by_kind["latex_divergence"] += 1
            continue

        disp = _check_display_vs_computed(arithma_latex or eml_latex, value)
        if disp:
            mismatches[fid] = disp
            by_kind["display_vs_computed"] += 1

    report = {
        "version": "1.0",
        "total_formulas": len(formulas),
        "mismatch_count": len(mismatches),
        "by_kind": by_kind,
        "mismatches": mismatches,
    }
    out_path = ag / "mismatches.json"
    json.dump(report, open(out_path, "w", encoding="utf-8"),
              ensure_ascii=False, separators=(",", ":"))
    print(f"Mismatch scan complete:")
    print(f"  Total formulas:    {len(formulas)}")
    print(f"  Mismatches:        {len(mismatches)}")
    for k, n in by_kind.items():
        print(f"    {k:<22} {n}")
    print(f"  Output:            {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
