"""Pre-generate JSON datasheets for every quark and curated constant.

Sweeps :data:`metaphysica.datasheets.KNOWN_QUARKS` and
:data:`metaphysica.datasheets.KNOWN_CONSTANTS`, calls the corresponding
builder for each, and writes the result as JSON into the bundled
package data tree::

    src/metaphysica/data/quarks/<CanonName>.json
    src/metaphysica/data/constants/<canon_name>.json

Idempotent: rewrites the same file every time.

Two modes:

* "wheel" mode (default when run as a module) — writes into the
  installed source tree under ``metaphysica/data/``. This is how the
  bundled snapshots get refreshed before a release.
* "out" mode — when the ``METAPHYSICA_OUT`` env var is set (i.e. the
  generator is being run from inside :mod:`metaphysica.build`) the
  snapshots are *also* mirrored under
  ``<out_dir>/AutoGenerated/datasheets/{quarks,constants}/`` so the
  static site has copies for direct fetch.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Iterable, List, Tuple


def _wheel_data_dir() -> Path:
    """Locate ``src/metaphysica/data/`` next to the installed package."""
    import metaphysica
    pkg_root = Path(metaphysica.__file__).parent
    return pkg_root / "data"


def _autogen_mirror_dir() -> Path | None:
    """If a build is in progress, return the AutoGenerated/datasheets dir."""
    raw = os.environ.get("METAPHYSICA_OUT")
    if not raw:
        return None
    return Path(raw).resolve() / "AutoGenerated" / "datasheets"


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )


def _slug_for_quark(name: str) -> str:
    """File-safe canonical filename for a quark datasheet."""
    return name.replace(" ", "") + ".json"


def _slug_for_constant(name: str) -> str:
    """File-safe canonical filename for a constant datasheet."""
    return name.replace("/", "_").replace(" ", "_") + ".json"


def _generate_quarks(targets: Iterable[Path]) -> Tuple[int, List[str]]:
    """Build every quark datasheet and write into each target directory."""
    from metaphysica.datasheets.quark import (
        KNOWN_QUARKS, build_quark_datasheet,
    )
    written = 0
    failures: List[str] = []
    for name in KNOWN_QUARKS:
        try:
            payload = build_quark_datasheet(name, prefer_bundled=False)
        except Exception as exc:
            failures.append(f"{name}: {type(exc).__name__}: {exc}")
            continue
        slug = _slug_for_quark(name)
        for tgt in targets:
            _write_json(tgt / slug, payload)
        written += 1
    return written, failures


def _generate_constants(targets: Iterable[Path]) -> Tuple[int, List[str]]:
    """Build every curated constant datasheet and write into each target."""
    from metaphysica.datasheets.constant import (
        KNOWN_CONSTANTS, build_constant_datasheet,
    )
    written = 0
    failures: List[str] = []
    for name in KNOWN_CONSTANTS:
        try:
            payload = build_constant_datasheet(name, prefer_bundled=False)
        except KeyError:
            # Snapshot may not have this canonical key yet — skip silently.
            continue
        except Exception as exc:
            failures.append(f"{name}: {type(exc).__name__}: {exc}")
            continue
        slug = _slug_for_constant(name)
        for tgt in targets:
            _write_json(tgt / slug, payload)
        written += 1
    return written, failures


def main() -> int:
    wheel_root = _wheel_data_dir()
    quark_targets: List[Path] = [wheel_root / "quarks"]
    const_targets: List[Path] = [wheel_root / "constants"]

    mirror = _autogen_mirror_dir()
    if mirror is not None:
        quark_targets.append(mirror / "quarks")
        const_targets.append(mirror / "constants")

    print(f"Writing quark datasheets into:")
    for t in quark_targets:
        print(f"  - {t}")
    print(f"Writing constant datasheets into:")
    for t in const_targets:
        print(f"  - {t}")

    n_q, fail_q = _generate_quarks(quark_targets)
    n_c, fail_c = _generate_constants(const_targets)

    print(f"\nWrote {n_q} quark datasheet(s), {n_c} constant datasheet(s).")
    if fail_q:
        print(f"Quark failures ({len(fail_q)}):")
        for f in fail_q:
            print(f"  {f}")
    if fail_c:
        print(f"Constant failures ({len(fail_c)}):")
        for f in fail_c:
            print(f"  {f}")

    return 1 if (fail_q or fail_c) else 0


if __name__ == "__main__":
    sys.exit(main())
