#!/usr/bin/env python3
"""Reference-integrity audit: is the bibliography connected to the claims?

WHY THIS EXISTS
---------------
``references.json`` holds 230 entries and ``reference_check.json`` already
verifies that formula ids resolve. Nothing checked the bibliography itself,
and two defects had accumulated behind that gap:

1. **228 of 230 references are orphans.** They are defined, but no formula,
   section or parameter cites them. Each carries a ``source_simulation``
   recording which module registered it, which is provenance, not citation --
   it says where the entry came from, not which claim it supports. A reader
   asking "what backs this number?" cannot get an answer, and a bibliography
   nothing points at cannot be checked for relevance the way a cited one can.

2. **22 titles are duplicated across 66 entries.** Planck 2018 VI alone
   appears eleven times under eleven ids (``planck_2018``, ``planck2018``,
   ``planck2020``, ``ref-planck-2018``, ...). Acharya-Witten's "Chiral
   Fermions from Manifolds of G2 Holonomy" appears five times, Joyce's
   "Compact Manifolds with Special Holonomy" four. The count of 230 therefore
   overstates the distinct literature by roughly a fifth.

This module REPORTS both. It deliberately deletes nothing: near-identical ids
may have been registered by different simulations for different reasons, and
collapsing them is an editorial decision about which id is canonical. Making
the duplication visible and countable is the part that can be automated
honestly.

Output: ``AutoGenerated/reference_integrity.json``
(schema_version / count / n_pass / n_fail / note, per consistency_beacons).

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from metaphysica.generators._common import autogen_dir as _autogen_dir

__all__ = ["audit_references", "write_report", "main"]

#: Fields that make an entry citable by a reader: at least one must resolve.
_IDENTIFIER_FIELDS = ("arxiv", "doi", "url")


def _normalise_title(title: str) -> str:
    """Comparison key for duplicate detection: case, punctuation, spacing."""
    t = (title or "").strip().lower().rstrip(".")
    t = re.sub(r"[^a-z0-9]+", " ", t)
    return re.sub(r"\s+", " ", t).strip()


def audit_references(autogen: Path) -> dict:
    """Return the audit payload for the bibliography in *autogen*."""
    refs_path = autogen / "references.json"
    if not refs_path.is_file():
        return {"status": "SKIPPED", "note": "references.json not present"}

    refs = json.loads(refs_path.read_text(encoding="utf-8")).get("references", {})
    ids = set(refs)

    # Where a citation could plausibly appear. Serialised wholesale because
    # citations are embedded in free text as well as in list fields.
    corpus_parts = []
    for name in ("formulas.json", "sections.json", "parameters.json"):
        path = autogen / name
        if path.is_file():
            corpus_parts.append(path.read_text(encoding="utf-8"))
    corpus = "\n".join(corpus_parts)

    cited = {rid for rid in ids if rid and rid in corpus}
    orphans = sorted(ids - cited)

    by_title = defaultdict(list)
    for rid, ref in refs.items():
        key = _normalise_title(ref.get("title", ""))
        if key:
            by_title[key].append(rid)
    duplicates = {t: sorted(v) for t, v in by_title.items() if len(v) > 1}
    n_dup_entries = sum(len(v) for v in duplicates.values())

    unidentified = sorted(
        rid for rid, ref in refs.items()
        if not any(ref.get(f) for f in _IDENTIFIER_FIELDS)
    )

    by_sim = Counter(r.get("source_simulation") or "(none)" for r in refs.values())

    checks = [
        {
            "id": "every_reference_is_identifiable",
            "claim": "each entry carries an arXiv id, DOI or URL a reader can follow",
            "measured": len(refs) - len(unidentified),
            "expected": len(refs),
            "status": "PASS" if not unidentified else "FAIL",
            "note": "an entry nobody can look up cannot support a claim",
        },
        {
            "id": "no_duplicate_titles",
            "claim": "one paper appears under one id",
            "measured": n_dup_entries,
            "expected": 0,
            "status": "PASS" if not duplicates else "FAIL",
            "note": "duplicates inflate the apparent breadth of the "
                    "literature base and split citations of one paper",
        },
        {
            "id": "references_are_cited",
            "claim": "each entry is cited by a formula, section or parameter",
            "measured": len(cited),
            "expected": len(refs),
            "status": "PASS" if not orphans else "FAIL",
            "note": "source_simulation records which module registered an "
                    "entry -- that is provenance, not citation; it does not "
                    "say which claim the paper supports",
        },
    ]
    n_fail = sum(1 for c in checks if c["status"] == "FAIL")

    return {
        "schema_version": 1,
        "count": len(checks),
        "n_pass": len(checks) - n_fail,
        "n_fail": n_fail,
        "totals": {
            "references": len(refs),
            "cited": len(cited),
            "orphans": len(orphans),
            "distinct_titles": len(by_title),
            "duplicate_titles": len(duplicates),
            "entries_in_duplicate_groups": n_dup_entries,
            "without_identifier": len(unidentified),
        },
        "checks": checks,
        "orphans": orphans,
        "duplicate_groups": duplicates,
        "without_identifier": unidentified,
        "references_per_simulation": dict(by_sim.most_common()),
        "note": (
            "Reports, does not repair. Collapsing duplicate ids is an "
            "editorial decision about which id is canonical, and orphan "
            "entries may be genuinely relevant background that simply has no "
            "citation site yet. Both are surfaced so the choice is "
            "deliberate rather than accidental."
        ),
        "duplicate_caveat": (
            "Detection is by normalised title, so it cannot distinguish an "
            "accidental duplicate from a deliberate one. The seven CODATA "
            "2022 entries (codata2022faraday, codata2022hartree, ...) cite "
            "one release for seven different constants, which is a "
            "defensible convention; the eleven Planck 2018 VI ids are the "
            "same paper reached by inconsistent id spellings, which is not. "
            "The count is a starting point for that judgement, not a verdict."
        ),
    }


def write_report(out_path: Path | None = None) -> Path:
    autogen = _autogen_dir()
    payload = audit_references(autogen)
    out_path = Path(out_path) if out_path else autogen / "reference_integrity.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return out_path


def main(argv=None) -> int:
    out = write_report()
    payload = json.loads(out.read_text(encoding="utf-8"))
    if payload.get("status") == "SKIPPED":
        print(f"  reference integrity: SKIPPED ({payload['note']})")
        return 0

    t = payload["totals"]
    print("=" * 70)
    print(" REFERENCE INTEGRITY")
    print("=" * 70)
    print(f"  references           : {t['references']}")
    print(f"  distinct titles      : {t['distinct_titles']}")
    print(f"  cited by a claim     : {t['cited']}")
    print(f"  orphans              : {t['orphans']}")
    print(f"  duplicate titles     : {t['duplicate_titles']} "
          f"({t['entries_in_duplicate_groups']} entries)")
    print(f"  without identifier   : {t['without_identifier']}")
    print()
    for c in payload["checks"]:
        print(f"  [{c['status']}] {c['id']}: {c['measured']}/{c['expected']}")

    dups = payload["duplicate_groups"]
    if dups:
        print(f"\n  [DEBUG] most-duplicated titles:")
        for title, group in sorted(dups.items(), key=lambda kv: -len(kv[1]))[:8]:
            print(f"    {len(group)}x {title[:58]}")
            print(f"         {', '.join(group)}")

    print(f"\n  Report written to: {out}")
    # Report-only: the bibliography is documentation, and failing the build
    # over it would block releases on an editorial backlog.
    return 0


if __name__ == "__main__":
    sys.exit(main())
