"""
generate_eml_trees.py — Pre-generate EML operator-tree JSON for all formulas.

Reads AutoGenerated/formulas.json, calls parse_eml_tree() on each formula
that has eml_tree_str or eml_description, and writes a compact JSON file
to AutoGenerated/eml_trees.json keyed by formula ID.

Compact schema (v2):
    {
      "_v": 2,                        // schema version
      "_kind_map": {"p":"primitive", "v":"vec", ...},
      "f": {
        "<formula-id>": {
          "p": [...],                 // pure-eml tree, compact array form
          "c": [...],                 // compact-mode tree (operator labels)
          "x": "<latex>"              // auto-rendered LaTeX
        }, ...
      }
    }

Compact tree node form (recursive):
    leaf:     [label, kind_char]
    internal: [label, kind_char, child1, child2, ...]
where kind_char is one of: p,s,c,#,v,P,C,_,? (see _KIND below).

The flow-diagram SVG is *not* baked into the file — the website renders
it client-side from the compact tree (see Pages/formulas.html).

Usage:
    python scripts/generation/generate_eml_trees.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from metaphysica.generators._common import out_dir as _out_dir, autogen_dir as _autogen_dir
ROOT = _out_dir()
sys.path.insert(0, str(ROOT))

try:
    from eml_math.tree import parse_eml_tree, to_compact, KIND_CHAR, CHAR_KIND
    from eml_math.evaluator import ParseError
except ImportError as e:
    print(f"ERROR: {e}")
    print("Install: pip install -e H:/Github/EML-Math")
    sys.exit(1)

FORMULAS_JSON = ROOT / "AutoGenerated" / "formulas.json"
OUTPUT_JSON   = ROOT / "AutoGenerated" / "eml_trees.json"


def _get_expr(formula: dict) -> str | None:
    """Return the best available expression string for a formula."""
    ts = formula.get("eml_tree_str", "")
    if ts:
        return f"EML: {ts}"
    ed = formula.get("eml_description", "")
    if ed and ed.startswith("EML:"):
        return ed
    return None


def main() -> None:
    with open(FORMULAS_JSON, encoding="utf-8") as f:
        data = json.load(f)

    formulas: dict = data.get("formulas", data)

    # Compact tree encoding (EML-Math): leaf = [label, kind_char];
    #                                  internal = [label, kind_char, child1, …]
    entries: dict = {}
    n_ok = n_err = n_skip = 0

    for fid, formula in formulas.items():
        expr = _get_expr(formula)
        if not expr:
            n_skip += 1
            continue
        try:
            pure_tree    = parse_eml_tree(expr, pure_eml=True)
            compact_tree = parse_eml_tree(expr, expand_eml=False)
            entries[fid] = {
                "p": to_compact(pure_tree),       # pure-eml binary tree
                "c": to_compact(compact_tree),    # compact ops tree (drives flow + latex)
                "x": compact_tree.to_latex(),     # LaTeX
            }
            n_ok += 1
        except (ParseError, Exception) as exc:
            entries[fid] = {
                "p": ["<error>", "?"],
                "c": ["<error>", "?"],
                "x": "",
            }
            n_err += 1

    out = {
        "_v": 2,
        "_kind_map": CHAR_KIND,            # char → kind name (matches EML-Math)
        "f": entries,
    }

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        # Minified — no indent — saves ~80% of file size on its own
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))

    size_kb = OUTPUT_JSON.stat().st_size / 1024
    print(f"EML tree generation complete:")
    print(f"  Parsed:  {n_ok}")
    print(f"  Errors:  {n_err}")
    print(f"  Skipped: {n_skip}")
    print(f"  Output:  {OUTPUT_JSON}  ({size_kb:.1f} KB)")

    # ── Sync the EML-Math browser renderer alongside the data file ──────
    try:
        import shutil
        from eml_math.web import FLOW_JS_PATH
        js_target = ROOT / "js" / "eml_flow.js"
        js_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(FLOW_JS_PATH, js_target)
        print(f"  JS sync: {FLOW_JS_PATH.name} -> {js_target.relative_to(ROOT)}")
    except Exception as exc:
        print(f"  WARN: could not sync eml_flow.js — {exc}")


if __name__ == "__main__":
    main()
