"""generate_eml_dependency_walker.py — Sprint 3 #5 (EML counterpart of S3.4).

Walks every formula's EML operator tree back to its b₃=24 root and writes
``AutoGenerated/eml_dependency_chains.json`` keyed by formula id. This is
the EML counterpart of ``generate_arithma_dependency_walker.py`` (S3.4)
and shares :mod:`metaphysica.generators._dependency_walk_common` for the
detection rules and JSON envelope.

Walk strategy (preferred → degraded):
  1. Compact EML tree at ``eml_trees.json[f][<id>]['c']`` — readable
     ops-level tree (mul/div/sqrt/exp/… with explicit numeric leaves).
  2. Pure-EML tree at ``eml_trees.json[f][<id>]['p']`` — every internal
     node is the binary primitive ``eml(L, R)``; numeric scalars survive
     intact so b₃ detection still works (slightly noisier paths).
  3. String scan on ``Formula.eml_tree_str`` / ``eml_description`` —
     last-ditch fallback; output marks ``degraded_walk: true``.

b₃ leaf detection (see ``_dependency_walk_common``):
  - ``kind == "#"`` (scalar) and label parses to ≈ 24.0 — the literal
    ``eml_scalar(24.0)`` shape that ``b3_leaf()`` produces.
  - Labelled leaves ``b3``/``b_3``/``elder_kads`` (future-proofing for
    when the SSoT registry surfaces b₃ as a named leaf).

Raw-24 scalars are ambiguous (could be the 24-cell vertices, 2×12 gens,
24 hyperplane normals…); counted separately in ``raw_24_leaves_count``
but folded into ``b3_rooted`` because every metaphysical 24 *does*
ultimately come from b₃ in this framework.

Usage:
    python -m metaphysica.generators.generate_eml_dependency_walker
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from metaphysica.generators._common import autogen_dir
from metaphysica.generators._dependency_walk_common import (
    is_b3_label,
    is_b3_scalar,
    truncate_paths,
)


# ── Compact-tree walker ──────────────────────────────────────────────────────
#
# Compact node form (from eml_math.tree.to_compact):
#   leaf     : [label, kind_char]
#   internal : [label, kind_char, child1, child2, …]
#
# We collect:
#   - depth        : longest root→leaf chain length
#   - leaves       : total leaf count
#   - b3_leaves    : scalar leaves whose value ≈ 24.0
#   - label_leaves : leaves whose label matches a known b₃ token
#   - paths        : root→leaf token sequences ending at a b₃ leaf

def _walk(node, path, out_paths, counts) -> int:
    """Recurse over a compact EML node. Returns the subtree depth."""
    if not isinstance(node, list) or len(node) < 2:
        counts["leaves"] += 1
        return 0

    label    = str(node[0])
    kind     = str(node[1]) if len(node) > 1 else "?"
    children = node[2:]
    here     = path + [label]

    if not children:
        counts["leaves"] += 1
        # Scalar leaf with value 24 → b₃ via b3_leaf().
        if kind == "#" and is_b3_scalar(label):
            counts["raw_24"] += 1
            out_paths.append(here)
        # Labelled leaf (e.g. an SSoT-exported "b3" name).
        elif is_b3_label(label):
            counts["b3"] += 1
            out_paths.append(here)
        return 0

    max_child_depth = 0
    for c in children:
        d = _walk(c, here, out_paths, counts)
        if d + 1 > max_child_depth:
            max_child_depth = d + 1
    return max_child_depth


def _chain_for_tree(tree, degraded: bool) -> dict:
    counts = {"leaves": 0, "b3": 0, "raw_24": 0}
    paths: list[list[str]] = []
    depth = _walk(tree, [], paths, counts)
    b3_rooted = counts["b3"] > 0 or counts["raw_24"] > 0
    return {
        "depth":               int(depth),
        "leaves":              int(counts["leaves"]),
        "b3_leaf_count":       int(counts["b3"]),
        "raw_24_leaves_count": int(counts["raw_24"]),
        "b3_rooted":           bool(b3_rooted),
        "paths":               truncate_paths(paths),
        "degraded_walk":       bool(degraded),
    }


# ── Tree selection ───────────────────────────────────────────────────────────
#
# eml_trees.json carries two forms per formula:
#   "c" — compact ops-level tree (preferred; numeric leaves preserved).
#   "p" — pure-eml binary tree (deeper; still walkable).
# We prefer "c"; fall back to "p". Anything else is degraded.

def _select_tree(entry):
    if not isinstance(entry, dict):
        return None, "missing"
    if isinstance(entry.get("c"), list) and len(entry["c"]) >= 2:
        return entry["c"], "compact"
    if isinstance(entry.get("p"), list) and len(entry["p"]) >= 2:
        return entry["p"], "pure_eml"
    return None, "malformed"


def _degraded_string_scan(formula: dict) -> dict:
    """Last-ditch path: look for 24 / b3 markers in the raw eml strings."""
    blob = (formula.get("eml_tree_str") or formula.get("eml_description") or "")
    counts = {"leaves": 0, "b3": 0, "raw_24": 0}
    paths: list[list[str]] = []
    # Cheap markers: any 'eml_scalar(24' substring is the canonical
    # b3_leaf() form; bare 'b3'/'elder_kads' tokens are SSoT references.
    if "eml_scalar(24" in blob or "eml_scalar(24.0" in blob:
        counts["raw_24"] += 1
        paths.append(["<string-scan>", "eml_scalar(24)"])
    for tok in ("b3", "b_3", "elder_kads"):
        if tok in blob:
            counts["b3"] += 1
            paths.append(["<string-scan>", tok])
            break
    return {
        "depth":               0,
        "leaves":              counts["leaves"],
        "b3_leaf_count":       counts["b3"],
        "raw_24_leaves_count": counts["raw_24"],
        "b3_rooted":           (counts["b3"] + counts["raw_24"]) > 0,
        "paths":               truncate_paths(paths),
        "degraded_walk":       True,
    }


def main() -> int:
    ag = autogen_dir()
    formulas_path = ag / "formulas.json"
    eml_path      = ag / "eml_trees.json"
    out_path      = ag / "eml_dependency_chains.json"

    if not formulas_path.exists():
        print(f"  formulas.json not found — skipping EML dependency walk "
              f"(run simulations first: pip install metaphysica[sims])")
        return 0

    with open(formulas_path, encoding="utf-8") as fp:
        formulas = json.load(fp).get("formulas", {})

    eml_trees = {}
    if eml_path.exists():
        with open(eml_path, encoding="utf-8") as fp:
            eml_trees = json.load(fp).get("f", {})
    else:
        print(f"WARN: {eml_path} not found — falling back to string-scan mode.")

    chains: dict = {}
    b3_rooted = ambiguous = non_rooted = 0
    n_compact = n_pure = n_degraded = 0

    for fid, formula in formulas.items():
        tree, source = _select_tree(eml_trees.get(fid, {}))
        if tree is None:
            chain = _degraded_string_scan(formula)
            n_degraded += 1
        else:
            chain = _chain_for_tree(tree, degraded=False)
            if source == "compact":
                n_compact += 1
            else:
                n_pure += 1

        chains[fid] = chain

        if chain["b3_leaf_count"] > 0:
            b3_rooted += 1
        elif chain["raw_24_leaves_count"] > 0:
            ambiguous += 1
            b3_rooted += 1     # raw 24s still count as rooted (see header)
        else:
            non_rooted += 1

    # ── Envelope mirrors the Arithma walker so the audit script can diff ──
    out = {
        "version":              "1.0",
        "kind":                 "eml",
        "root_seed":            "b3=24",
        "total_formulas":       len(formulas),
        "b3_rooted_count":      b3_rooted,
        "ambiguous_count":      ambiguous,
        "non_b3_rooted_count":  non_rooted,
        "tree_source_counts": {
            "compact":  n_compact,
            "pure_eml": n_pure,
            "degraded": n_degraded,
        },
        "chains": chains,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fp:
        json.dump(out, fp, ensure_ascii=False, separators=(",", ":"))

    size_kb = out_path.stat().st_size / 1024
    total_depth = sum(c["depth"] for c in chains.values())
    avg_depth = total_depth / max(1, len(chains))

    print("EML dependency walker complete:")
    print(f"  Total formulas:    {len(formulas)}")
    print(f"  b3-rooted:         {b3_rooted}")
    print(f"  Ambiguous (24):    {ambiguous}")
    print(f"  Non-b3-rooted:     {non_rooted}")
    print(f"  Avg tree depth:    {avg_depth:.2f}")
    print(f"  Tree source:       compact={n_compact}  pure_eml={n_pure}  degraded={n_degraded}")
    print(f"  Output:            {out_path}  ({size_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
