"""
generate_formula_renders.py — Pre-render each formula's EML tree into
the full suite of EML-Math output formats (LaTeX / HTML / SVG / PNG / PDF
/ MathML / plain text).

Each format is one of EML-Math's first-class rendering targets:

* ``latex``  — EMLTreeNode.to_latex()                   (cheap)
* ``html``   — flow_html(tree)                          (cheap, inline SVG)
* ``svg``    — flow_svg(tree)                           (cheap)
* ``mathml`` — _formula_to_mathml(eml_tree_str)         (cheap)
* ``png``    — flow_png(tree)                           (heavy, base64 encoded)
* ``pdf``    — flow_pdf(tree)                           (heavy, base64 encoded)
* ``plain``  — eml_tree_str / eml_description           (free)

Output: ``AutoGenerated/formula_renders.json`` keyed by formula id::

    {
      "_v": 1,
      "_formats": ["latex", "html", "svg", "mathml"],
      "f": {
        "<formula-id>": {
          "latex":  "\\frac{144}{4 \\cdot 24}",
          "html":   "<div class='eml-flow'><svg ...>...</svg></div>",
          "svg":    "<svg ...>...</svg>",
          "mathml": "<math>...</math>",
          "plain":  "ops.div(eml_scalar(144), ops.mul(...))"
        },
        ...
      }
    }

Build flag
----------
``--renders=latex,html``         (default — fast, ~MB-scale output)
``--renders=latex,html,svg,mathml`` (recommended for richer widget)
``--renders=latex,html,svg,mathml,png,pdf`` (heavy — base64-encoded blobs)

Usage
-----
    python -m metaphysica.generators.generate_formula_renders
    python -m metaphysica.generators.generate_formula_renders --renders=latex,html,svg,mathml
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
from pathlib import Path

from metaphysica.generators._common import autogen_dir as _autogen_dir

try:
    from eml_math.tree import parse_eml_tree
    from eml_math.evaluator import ParseError
    from eml_math.flow import flow_svg, flow_html, flow_png, flow_pdf
    from eml_math.discover.compress import _formula_to_mathml
except ImportError as exc:
    print(f"ERROR: eml-math missing ({exc}). Install with `pip install eml-math`.")
    sys.exit(1)


# Format identifiers — kept lowercase to match the JS widget tab names.
ALL_FORMATS = ("latex", "html", "svg", "mathml", "png", "pdf", "plain")
DEFAULT_FORMATS = ("latex", "html")


def _get_expr(formula: dict) -> str | None:
    """Return the best available expression string for a formula card."""
    ts = formula.get("eml_tree_str", "")
    if ts:
        return f"EML: {ts}"
    ed = formula.get("eml_description", "")
    if ed and ed.startswith("EML:"):
        return ed
    return None


def _render_one(tree, fmt: str, raw_expr: str) -> str | None:
    """Render *tree* in the requested *fmt*. Returns None on any failure."""
    try:
        if fmt == "latex":
            return tree.to_latex()
        if fmt == "html":
            return flow_html(tree)
        if fmt == "svg":
            return flow_svg(tree)
        if fmt == "mathml":
            # tree-level MathML — use the eml_tree_str as the source string.
            return _formula_to_mathml(raw_expr.replace("EML: ", "", 1))
        if fmt == "png":
            blob = flow_png(tree)
            return "data:image/png;base64," + base64.b64encode(blob).decode("ascii")
        if fmt == "pdf":
            blob = flow_pdf(tree)
            return "data:application/pdf;base64," + base64.b64encode(blob).decode("ascii")
        if fmt == "plain":
            return raw_expr
    except Exception:
        return None
    return None


def _parse_formats(arg: str | None) -> tuple[str, ...]:
    if not arg:
        return DEFAULT_FORMATS
    fmts: list[str] = []
    for raw in arg.split(","):
        f = raw.strip().lower()
        if not f:
            continue
        if f not in ALL_FORMATS:
            print(f"  WARN: unknown format '{f}' (ignored). "
                  f"Available: {','.join(ALL_FORMATS)}")
            continue
        if f not in fmts:
            fmts.append(f)
    if not fmts:
        return DEFAULT_FORMATS
    return tuple(fmts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Pre-render formula EML trees into multiple output formats.",
    )
    parser.add_argument(
        "--renders",
        default=os.environ.get("METAPHYSICA_RENDERS", ""),
        help="Comma-separated list of formats to emit. "
             f"Default: {','.join(DEFAULT_FORMATS)}. "
             f"Available: {','.join(ALL_FORMATS)}.",
    )
    args = parser.parse_args(argv)

    autogen = _autogen_dir()
    formulas_json = autogen / "formulas.json"
    output_json = autogen / "formula_renders.json"

    if not formulas_json.exists():
        print(f"ERROR: {formulas_json} does not exist. Run simulations first.")
        return 1

    fmts = _parse_formats(args.renders)
    print(f"Rendering formats: {', '.join(fmts)}")

    with open(formulas_json, encoding="utf-8") as f:
        data = json.load(f)
    formulas: dict = data.get("formulas", data)

    entries: dict[str, dict[str, str]] = {}
    per_fmt_counts = {fmt: 0 for fmt in fmts}
    n_skip = n_err = 0

    for fid, formula in formulas.items():
        expr = _get_expr(formula)
        if not expr:
            n_skip += 1
            continue
        try:
            tree = parse_eml_tree(expr, expand_eml=False)
        except (ParseError, Exception):
            n_err += 1
            continue

        renders: dict[str, str] = {}
        for fmt in fmts:
            r = _render_one(tree, fmt, expr)
            if r is not None:
                renders[fmt] = r
                per_fmt_counts[fmt] += 1
        if renders:
            entries[fid] = renders

    out = {
        "_v": 1,
        "_formats": list(fmts),
        "f": entries,
    }

    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))

    size_kb = output_json.stat().st_size / 1024
    print(f"Formula render generation complete:")
    print(f"  Formulas rendered: {len(entries)} / {len(formulas)}")
    print(f"  Parse errors:      {n_err}")
    print(f"  Skipped (no EML):  {n_skip}")
    for fmt, cnt in per_fmt_counts.items():
        print(f"  {fmt:7s}: {cnt}")
    print(f"  Output:            {output_json}  ({size_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
