#!/usr/bin/env python3
"""Reference-integrity audit: is the bibliography connected to the claims?

WHY THIS EXISTS
---------------
``references.json`` holds 230 entries and ``reference_check.json`` already
verifies that formula ids resolve. Nothing checked the bibliography itself,
and two defects had accumulated behind that gap:

1. **228 of 230 references were orphans.** They were defined, but no formula,
   section or parameter cited them. Each carries a ``source_simulation``
   recording which module registered it, which is provenance, not citation --
   it says where the entry came from, not which claim it supports. A reader
   asking "what backs this number?" could not get an answer, and a
   bibliography nothing points at cannot be checked for relevance the way a
   cited one can. Closed by the module-level join in
   ``run_all_simulations._attach_module_references``.

2. **22 titles were duplicated across 66 entries.** Planck 2018 VI alone
   appeared eleven times under eleven ids (``planck_2018``, ``planck2018``,
   ``planck2020``, ``ref-planck-2018``, ...). Acharya-Witten's "Chiral
   Fermions from Manifolds of G2 Holonomy" appeared five times, Joyce's
   "Compact Manifolds with Special Holonomy" four. The count of 230
   overstated the distinct literature by roughly a fifth. Closed by
   collapsing each group onto one canonical id at every registration site,
   after checking group by group that the members really were one document.
   One group was deliberately left standing apart: two Super-Kamiokande
   proton-decay searches (2009 PRL 102 141801, 2020 PRD 102 112011) whose
   abbreviated titles had been made identical. Restoring their published
   titles separated them without merging two different papers.

This module REPORTS. It deletes nothing: near-identical ids may have been
registered by different simulations for different reasons, and collapsing
them is an editorial decision about which id is canonical, taken in the
modules that register the entries. Making the duplication visible and
countable is the part that can be automated honestly.

Output: ``AutoGenerated/reference_integrity.json``
(schema_version / count / n_pass / n_fail / note, per consistency_beacons).

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from metaphysica.generators._common import autogen_dir as _autogen_dir

__all__ = ["audit_references", "write_report", "main"]

#: Fields that make an entry citable by a reader: at least one must resolve.
_IDENTIFIER_FIELDS = ("arxiv", "doi", "url")


def _normalise_title(title: str) -> str:
    """Comparison key for duplicate detection: case, punctuation, spacing."""
    t = (title or "").strip().lower().rstrip(".")
    t = re.sub(r"[^a-z0-9]+", " ", t)
    return re.sub(r"\s+", " ", t).strip()


def audit_references(autogen: Path) -> dict:
    """Return the audit payload for the bibliography in *autogen*."""
    refs_path = autogen / "references.json"
    if not refs_path.is_file():
        return {"status": "SKIPPED", "note": "references.json not present"}

    refs = json.loads(refs_path.read_text(encoding="utf-8")).get("references", {})
    ids = set(refs)

    # Where a citation could plausibly appear. Serialised wholesale because
    # citations are embedded in free text as well as in list fields.
    corpus_parts = []
    for name in ("formulas.json", "sections.json", "parameters.json"):
        path = autogen / name
        if path.is_file():
            corpus_parts.append(path.read_text(encoding="utf-8"))
    corpus = "\n".join(corpus_parts)

    cited = {rid for rid in ids if rid and rid in corpus}
    orphans = sorted(ids - cited)

    by_title = defaultdict(list)
    for rid, ref in refs.items():
        key = _normalise_title(ref.get("title", ""))
        if key:
            by_title[key].append(rid)
    duplicates = {t: sorted(v) for t, v in by_title.items() if len(v) > 1}
    n_dup_entries = sum(len(v) for v in duplicates.values())

    # Identifier CONFLICTS, which are a different and worse defect than a
    # shared title.
    #
    # The title check cannot tell an accidental duplicate from a deliberate
    # one, and in practice most of what it flags is deliberate: one PDG
    # release cited under six ids for six different sections, one CODATA
    # release under seven, one Planck paper under eleven. Those split a
    # citation but every id still points at the right document.
    #
    # The serious case is the opposite: two entries that are genuinely
    # DIFFERENT works carrying the SAME identifier, so following the
    # citation lands the reader on the wrong paper. A year mismatch is the
    # reliable signal, since the same document cannot have two publication
    # years. Found this way:
    #
    #   * berger1966 carried 10.24033/bsmf.1464, which is Berger's 1955
    #     holonomy classification in Bull. SMF -- and its own volume and
    #     pages (83, 279-330) were the 1955 ones, so it was that paper
    #     misdated; merged into berger1955
    #   * penrose_2004_road_to_reality carried the OUP identifier of the
    #     1996 gravity-reduction entry. Crossref resolves that identifier to
    #     neither work: 10.1093/oso/9780198539957.001.0001 is "Ion Traps"
    #     (1995). The 1996 paper now carries 10.1007/BF02105068 and the 2004
    #     book an OpenLibrary record; the shared id was wrong for both
    #   * nist-codata-2018 shared the CODATA landing-page URL with the 2022
    #     release entries; each release now carries its Rev. Mod. Phys. DOI
    #
    # None was fixable here without a lookup, and inventing a replacement
    # identifier is exactly what the SSOT rule forbids. The audit reports
    # them; it does not repair them. The repairs above were made at the
    # registration sites in the simulation modules, every identifier checked
    # against Crossref, arXiv or OpenLibrary before it was written. Two more
    # wrong identifiers surfaced the same way and were repaired without ever
    # tripping this check, because a wrong identifier only shows up here when
    # some OTHER entry happens to share it: selberg1956 carried
    # 10.1007/BF02940436, which Crossref resolves to a 1989 paper titled
    # "Altlastensanierung", and connes1994 carried an Elsevier book DOI that
    # doi.org returns 404 for.
    by_identifier = defaultdict(list)
    for rid, ref in refs.items():
        ident = str(
            ref.get("arxiv") or ref.get("arxiv_id") or ref.get("doi")
            or ref.get("url") or ""
        ).strip().lower()
        if ident:
            by_identifier[ident].append(rid)

    identifier_conflicts = {}
    for ident, rids in by_identifier.items():
        if len(rids) < 2:
            continue
        years = {str(refs[r].get("year")) for r in rids}
        if len(years) > 1:
            identifier_conflicts[ident] = sorted(
                {"id": r, "year": refs[r].get("year"),
                 "title": refs[r].get("title")} for r in rids
            ) if False else [
                {"id": r, "year": refs[r].get("year"),
                 "title": refs[r].get("title")}
                for r in sorted(rids)
            ]
    n_conflicting = sum(len(v) for v in identifier_conflicts.values())

    # NEAR-duplicates: titles that agree once a subtitle is dropped, in the
    # same year. Reported as an ADVISORY, never merged automatically.
    #
    # Two entries for Penrose's "The Road to Reality" coexisted -- one as
    # "The Road to Reality", one with the full subtitle -- so the strict
    # title check saw two different works and passed. The short-titled copy
    # carried doi 10.1038/nphys344, which Crossref resolves to "Direct force
    # measurements on DNA in a solid-state nanopore", Nature Physics 2
    # (2006). Weinberg's "Gravitation and Cosmology" had the same shape, its
    # DOI resolving to a magazine subscription price list. Both identifiers
    # were unique, well-formed and resolvable, so no_conflicting_identifiers
    # could not see them either: an id can be wrong without being shared.
    #
    # Automatic merging on this looser key would be WRONG -- it collapses
    # the seven deliberate PDG per-section citations, the distinct CODATA
    # 2014/2018/2022 releases, and two genuinely different Acharya G2-MSSM
    # papers. So this surfaces candidates for a human decision and the
    # strict check remains the gate.
    def _drop_subtitle(title):
        head = str(title).split(":")[0]
        return " ".join(
            "".join(c if c.isalnum() else " " for c in head.lower()).split())

    near = defaultdict(list)
    for rid, ref in refs.items():
        key = (_drop_subtitle(ref.get("title", "")), str(ref.get("year", "")))
        if key[0]:
            near[key].append(rid)
    near_duplicates = {
        f"{title} ({year})": sorted(rids)
        for (title, year), rids in near.items()
        if len(rids) > 1 and sorted(rids) not in
        [sorted(v) for v in duplicates.values()]
    }

    unidentified = sorted(
        rid for rid, ref in refs.items()
        if not any(ref.get(f) for f in _IDENTIFIER_FIELDS)
    )

    by_sim = Counter(r.get("source_simulation") or "(none)" for r in refs.values())

    checks = [
        {
            "id": "every_reference_is_identifiable",
            "claim": "each entry carries an arXiv id, DOI or URL a reader can follow",
            "measured": len(refs) - len(unidentified),
            "expected": len(refs),
            "status": "PASS" if not unidentified else "FAIL",
            "note": "an entry nobody can look up cannot support a claim",
        },
        {
            "id": "no_duplicate_titles",
            "claim": "one paper appears under one id",
            "measured": n_dup_entries,
            "expected": 0,
            "status": "PASS" if not duplicates else "FAIL",
            "note": "duplicates inflate the apparent breadth of the "
                    "literature base and split citations of one paper",
        },
        {
            "id": "no_conflicting_identifiers",
            "claim": "entries from different years do not share an identifier",
            "measured": n_conflicting,
            "expected": 0,
            "status": "PASS" if not identifier_conflicts else "FAIL",
            "note": "a shared TITLE splits one paper's citations, which is "
                    "untidy; a shared IDENTIFIER between works of different "
                    "years sends the reader to the wrong document, which "
                    "breaks the citation. This check exists because the "
                    "title check flagged the PDG and CODATA groups while "
                    "missing berger1966 carrying Berger 1955's DOI and "
                    "penrose_2004_road_to_reality carrying a 1996 "
                    "identifier. Note the blind spot it keeps: an identifier "
                    "that is simply wrong, and shared with nothing, passes",
        },
        {
            "id": "no_near_duplicate_titles",
            "claim": "no two entries share a title once subtitles are dropped",
            "measured": sum(len(v) for v in near_duplicates.values()),
            "expected": 0,
            "status": "ADVISORY",
            "note": "Advisory, not a gate. A looser title key would wrongly "
                    "collapse the deliberate PDG per-section citations, the "
                    "distinct CODATA releases and two different Acharya "
                    "papers, so these are surfaced for a human decision "
                    "rather than merged. This tier is what exposed two "
                    "books whose DOIs resolved to a DNA nanopore experiment "
                    "and a magazine price list -- unique identifiers "
                    "pointing at the wrong document, which no other check "
                    "can detect",
        },
        {
            "id": "references_are_cited",
            "claim": "each entry is cited by a formula, section or parameter",
            "measured": len(cited),
            "expected": len(refs),
            "status": "PASS" if not orphans else "FAIL",
            "note": "source_simulation records which module registered an "
                    "entry -- that is provenance, not citation; it does not "
                    "say which claim the paper supports",
        },
    ]
    n_fail = sum(1 for c in checks if c["status"] == "FAIL")

    return {
        "schema_version": 1,
        "count": len(checks),
        "n_pass": len(checks) - n_fail,
        "n_fail": n_fail,
        "totals": {
            "references": len(refs),
            "cited": len(cited),
            "orphans": len(orphans),
            "distinct_titles": len(by_title),
            "duplicate_titles": len(duplicates),
            "entries_in_duplicate_groups": n_dup_entries,
            "without_identifier": len(unidentified),
        },
        "checks": checks,
        "orphans": orphans,
        "duplicate_groups": duplicates,
        "identifier_conflicts": identifier_conflicts,
        "near_duplicate_titles": near_duplicates,
        "without_identifier": unidentified,
        "references_per_simulation": dict(by_sim.most_common()),
        "note": (
            "Reports, does not repair. Collapsing duplicate ids is an "
            "editorial decision about which id is canonical, and orphan "
            "entries may be genuinely relevant background that simply has no "
            "citation site yet. Both are surfaced so the choice is "
            "deliberate rather than accidental."
        ),
        "duplicate_caveat": (
            "Detection is by normalised title, so it cannot distinguish an "
            "accidental duplicate from a deliberate one, and it cannot tell "
            "two different papers apart once their titles have been "
            "abbreviated to the same string. Both errors were present. The "
            "seven CODATA 2022 entries (codata2022faraday, "
            "codata2022hartree, ...) cited one release for seven different "
            "constants, which looked like a defensible convention until the "
            "entries were compared: all seven were bibliographically "
            "identical, and which constant each supports is recorded by the "
            "citing module, not by the id, so they were merged and nothing "
            "was lost. Two Super-Kamiokande proton-decay searches eight "
            "years apart were NOT merged: there the shared title was itself "
            "the defect, and restoring the published titles separated them. "
            "The count is a starting point for that judgement, not a verdict."
        ),
    }


def write_report(out_path: Path | None = None) -> Path:
    autogen = _autogen_dir()
    payload = audit_references(autogen)
    out_path = Path(out_path) if out_path else autogen / "reference_integrity.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return out_path


def main(argv=None) -> int:
    out = write_report()
    payload = json.loads(out.read_text(encoding="utf-8"))
    if payload.get("status") == "SKIPPED":
        print(f"  reference integrity: SKIPPED ({payload['note']})")
        return 0

    t = payload["totals"]
    print("=" * 70)
    print(" REFERENCE INTEGRITY")
    print("=" * 70)
    print(f"  references           : {t['references']}")
    print(f"  distinct titles      : {t['distinct_titles']}")
    print(f"  cited by a claim     : {t['cited']}")
    print(f"  orphans              : {t['orphans']}")
    print(f"  duplicate titles     : {t['duplicate_titles']} "
          f"({t['entries_in_duplicate_groups']} entries)")
    print(f"  without identifier   : {t['without_identifier']}")
    print()
    for c in payload["checks"]:
        print(f"  [{c['status']}] {c['id']}: {c['measured']}/{c['expected']}")

    dups = payload["duplicate_groups"]
    if dups:
        print(f"\n  [DEBUG] most-duplicated titles:")
        for title, group in sorted(dups.items(), key=lambda kv: -len(kv[1]))[:8]:
            print(f"    {len(group)}x {title[:58]}")
            print(f"         {', '.join(group)}")

    print(f"\n  Report written to: {out}")
    # Report-only: the bibliography is documentation, and failing the build
    # over it would block releases on an editorial backlog.
    return 0


if __name__ == "__main__":
    sys.exit(main())
