"""The free-set reduction must know whether it actually ran.

WHAT THIS GUARDS
================
`free_set._params()` resolved `parameters.json` through
`Path(__file__).resolve().parents[3]`, which is `src/` -- a directory the
artifact is never written to. The only candidate that could ever match was an
absolute Windows path from the author's machine, so on any other machine the
lookup returned an EMPTY dict.

Nothing raised. Every verification below it reports `available: False`, no row
is removed, and `free_set_size` equals `ledger_rows`. Five tests then failed
with messages about the physics -- "the reduction is inert", "unclassified rows
need a reading", "an error bar is not a free parameter" -- while the actual
fault was a path. That is the most expensive shape of defect in this codebase:
a missing input presenting as a result.

Measured 2026-09-22: with the artifact reachable the free set is 37 of 67 rows
(11 DERIVED_ARITHMETIC + 11 DUPLICATE + 8 NOT_A_MODEL_KNOB removed) and the
closure ledger classifies all 37 with nothing left UNCLASSIFIED. With it
unreachable the free set was 67 of 67 and 9 rows were UNCLASSIFIED.

So the reduction is now required to REPORT its input, and these tests fail if it
goes back to guessing.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import pathlib

import pytest

from metaphysica.simulations.core.free_set import (
    _param_candidates,
    build_free_set,
    params_source,
)


def test_no_candidate_path_points_inside_the_source_tree():
    """`src/AutoGenerated/parameters.json` is not a place the build writes.

    This is the exact off-by-one that broke the lookup. A candidate resolving
    inside `src/metaphysica`'s parent `src/` can never match, and a lookup list
    whose first entry can never match is how the Windows absolute path came to
    be load-bearing.
    """
    src_dir = pathlib.Path(__file__).resolve().parents[1] / "src"
    offenders = [str(p) for p in _param_candidates()
                 if p.parent.parent == src_dir]
    assert not offenders, (
        "these candidate paths resolve to src/AutoGenerated, which the build "
        "never writes to: %s" % offenders
    )


def test_the_candidate_list_has_a_machine_independent_entry():
    """At least one candidate must not be someone's absolute local path."""
    candidates = [str(p) for p in _param_candidates()]
    portable = [c for c in candidates if not c.startswith("H:")]
    assert portable, (
        "every candidate is an absolute path from one machine; the lookup "
        "cannot work anywhere else"
    )


def test_the_source_is_reported_either_way():
    """Available or not, the reduction says which file it read."""
    source = params_source()
    assert "available" in source and "checked" in source
    if source["available"]:
        assert source["path"] and source["n_rows"] > 0
        assert pathlib.Path(source["path"]).is_file()
    else:
        assert source["why"], (
            "an unavailable parameter source must explain itself; a silent "
            "empty dict is the defect this file exists for"
        )


def test_build_free_set_carries_whether_the_reduction_ran():
    report = build_free_set()
    assert "reduction_ran" in report
    assert "parameters_source" in report
    assert "params" not in report["parameters_source"], (
        "the 800-row parameter dict must not be copied into the report"
    )


def test_an_unreachable_artifact_does_not_masquerade_as_a_closed_free_set():
    """The failure mode, reproduced deliberately.

    Passing an empty params dict is exactly what the broken lookup produced.
    The reduction must then report that it did NOT run, so that
    `free_set_size == ledger_rows` can never be read as a physics result.
    """
    report = build_free_set(params={})
    assert report["reduction_ran"] is False
    assert report["removed_count"] == 0
    assert report["free_set_size"] == report["ledger_rows"], (
        "with no parameters nothing can be verified, so nothing may be removed"
    )


def test_the_reduction_actually_removes_rows_when_the_artifact_is_there():
    """The positive half: with a real source the reduction is not inert."""
    source = params_source()
    if not source["available"]:
        pytest.skip(
            "no parameters.json reachable; `python -m metaphysica.build --out "
            "./site` must precede pytest on a fresh checkout"
        )
    report = build_free_set()
    assert report["reduction_ran"] is True
    assert report["removed_count"] > 0, (
        "the artifact is present but no row was removed, so the reduction is "
        "inert for a reason other than a missing file"
    )
    assert report["free_set_size"] < report["ledger_rows"]


def test_the_stale_bundled_snapshot_is_not_used_as_a_fallback():
    """The bundled wheel copy is a stale subset and must not silently stand in.

    Measured 2026-09-22: `metaphysica/data/parameters.json` carries 620 of the
    808 built rows, and 111 shared rows hold different values. Reducing against
    it would report verified removals from stale numbers.
    """
    candidates = [str(p) for p in _param_candidates()]
    bundled = [c for c in candidates
               if ("metaphysica" + "/data") in c.replace("\\", "/")]
    assert not bundled, (
        "the bundled wheel snapshot is in the candidate list: %s" % bundled
    )
