"""Regression tests for ``metaphysica.simulations.PM.particle.yukawa_derivation``.

Validates the v25.0 / Sprint 4 #2 marquee module (proof-killer #1
closure) — the T₄ / 24-cell geometric derivation of PMNS angles θ₁₃
and δ_CP — including the Sprint T5 #1 (TIER_2_3_ROADMAP T2.4)
sister-parameter ξ = cos(π/b₃) which closes proof-killer #2 (δ_CP
independence from θ_13).

These tests cover:

1. Entry-point shape — ``get_geometric_pmns()`` returns the expected
   dict keys with finite numeric values (including the new
   ``xi_distortion`` key from Sprint T5 #1).

2. θ₁₃ / δ_CP / y_e formulas — recompute the textbook values from
   the documented coefficients and assert equality with the module's
   output to ``1e-12``.

3. Documented divergence vs NuFIT 6.0 — Sprint T5 #1 lands BOTH
   θ₁₃ AND δ_CP within 1σ simultaneously. The divergence block must
   report ``theta_13_within_1sigma = True`` AND
   ``delta_CP_within_1sigma = True``.

4. b₃ leaf appears in the EML structural tree (when eml-math is
   available in the test env) — the leaf must report tension == 24,
   AND a ξ_distortion handle must be present (Sprint T5 #1).

5. Triple-tracked formulas — each of the three published Formula
   objects carries non-empty ``arithma``, ``eml`` (when available),
   and ``value`` legs; their values agree with the canonical pipeline.

6. Custom-eta path — passing a different ``eta_distortion`` to the
   class produces consistent θ₁₃ (cross-validation hook used by the
   v26.0 η-re-derivation work).

7. ξ closed-form & b3_leaf() routing — the sister parameter ξ =
   cos(π/b₃) is geometrically derived, traces through b3_leaf(), and
   has a one-line docstring with its geometric origin.
"""
from __future__ import annotations

import math
from pathlib import Path

import pytest

# Make sure the module-level EML adapter writes into a temp dir per-test
# so we don't pollute the real AutoGenerated/eml_trees_v25.json.


@pytest.fixture
def isolated_autogen(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Point ``autogen_dir()`` at a fresh temp dir for the duration of one test.

    Mirrors the fixture used by ``tests/test_eml_operator_tree.py`` so the
    on-disk persistence side effect of ``eml_operator_tree.register_derivation``
    doesn't leak into the live build's ``AutoGenerated/eml_trees_v25.json``.
    """
    monkeypatch.setenv("METAPHYSICA_OUT", str(tmp_path))
    autogen = tmp_path / "AutoGenerated"
    autogen.mkdir(parents=True, exist_ok=True)
    return autogen


# ── Test 1: entry-point shape ─────────────────────────────────────────────


def test_get_geometric_pmns_shape(isolated_autogen: Path) -> None:
    """``get_geometric_pmns()`` returns the full v25.0 dict.

    Sprint T5 #1 adds the ``xi_distortion`` key (sister parameter
    ξ = cos(π/b₃)).
    """
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        get_geometric_pmns,
    )

    result = get_geometric_pmns()

    required_keys = {
        "theta_13_deg",
        "theta_13_rad",
        "delta_CP_rad",
        "delta_CP_pi_units",
        "y_e_hierarchy",
        "eta_distortion",
        "xi_distortion",
        "b3",
        "documented_divergence",
        "classification",
    }
    missing = required_keys - set(result.keys())
    assert not missing, f"missing keys in get_geometric_pmns(): {missing}"

    # Numeric fields must be finite.
    for k in ("theta_13_deg", "theta_13_rad", "delta_CP_rad",
              "delta_CP_pi_units", "y_e_hierarchy",
              "eta_distortion", "xi_distortion"):
        v = result[k]
        assert isinstance(v, float), f"{k} not float: {type(v).__name__}"
        assert math.isfinite(v), f"{k} not finite: {v}"

    assert result["b3"] == 24
    assert result["classification"] == "GEOMETRIC_T4_24CELL"


# ── Test 2: formula correctness ───────────────────────────────────────────


def test_theta_13_formula_matches(isolated_autogen: Path) -> None:
    """θ₁₃ matches arcsin(sqrt(2/3) · η) at the documented η = 0.037."""
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        DEFAULT_ETA,
        T4_ORBIT_AMPLITUDE,
        get_geometric_pmns,
    )

    expected_theta_13_rad = math.asin(T4_ORBIT_AMPLITUDE * DEFAULT_ETA)
    expected_theta_13_deg = math.degrees(expected_theta_13_rad)

    result = get_geometric_pmns()

    assert math.isclose(
        result["theta_13_rad"], expected_theta_13_rad, rel_tol=1e-12
    ), (
        f"theta_13_rad disagreement: "
        f"module={result['theta_13_rad']!r} vs analytic={expected_theta_13_rad!r}"
    )
    assert math.isclose(
        result["theta_13_deg"], expected_theta_13_deg, rel_tol=1e-12
    ), (
        f"theta_13_deg disagreement: "
        f"module={result['theta_13_deg']!r} vs analytic={expected_theta_13_deg!r}"
    )


def test_delta_cp_formula_matches(isolated_autogen: Path) -> None:
    """δ_CP matches (3π/2) · (1 − a·η·ξ + b·ξ²) [Sprint T5 #1 form]."""
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        DEFAULT_ETA,
        DEFAULT_XI,
        DELTA_CP_ETA_COEF,
        DELTA_CP_XI2_COEF,
        get_geometric_pmns,
    )

    expected_delta_cp = (3.0 * math.pi / 2.0) * (
        1.0
        - DELTA_CP_ETA_COEF * DEFAULT_ETA * DEFAULT_XI
        + DELTA_CP_XI2_COEF * DEFAULT_XI * DEFAULT_XI
    )

    result = get_geometric_pmns()

    assert math.isclose(
        result["delta_CP_rad"], expected_delta_cp, rel_tol=1e-12
    ), (
        f"delta_CP_rad disagreement: "
        f"module={result['delta_CP_rad']!r} vs analytic={expected_delta_cp!r}"
    )
    # delta_CP_pi_units sanity: should equal delta_CP_rad / pi.
    assert math.isclose(
        result["delta_CP_pi_units"],
        result["delta_CP_rad"] / math.pi,
        rel_tol=1e-12,
    )


def test_y_e_hierarchy_matches(isolated_autogen: Path) -> None:
    """y_e = sqrt(2/3) · exp(−b₃/24) = sqrt(2/3) / e for b₃ = 24."""
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        T4_ORBIT_AMPLITUDE,
        get_geometric_pmns,
    )

    expected = T4_ORBIT_AMPLITUDE * math.exp(-1.0)

    result = get_geometric_pmns()

    assert math.isclose(result["y_e_hierarchy"], expected, rel_tol=1e-12), (
        f"y_e_hierarchy disagreement: "
        f"module={result['y_e_hierarchy']!r} vs analytic={expected!r}"
    )


# ── Test 3: documented divergence is honest ───────────────────────────────


def test_documented_divergence_reports_both_angles_within_1sigma(
    isolated_autogen: Path,
) -> None:
    """Both θ₁₃ AND δ_CP land within 1σ of NuFIT 6.0 (Sprint T5 #1).

    The Sprint 4 #2 module shipped with η = 0.037 (literal v25.0 seed)
    producing θ₁₃ ≈ 1.73°. Sprint 6 #1 closed θ₁₃ with η = √2·sin(π/b₃)
    landing θ₁₃ = 8.669° within 1σ, but δ_CP = 1.467π was still ~0.7σ
    off NuFIT 6.0 1.54π because the same η governed both observables
    via (3π/2)(1 − 0.12·η).

    Sprint T5 #1 (TIER_2_3_ROADMAP T2.4) closes proof-killer #2 by
    introducing the sister parameter ξ = cos(π/b₃) — the algebraic
    conjugate of η/√2 on the T₄/24-cell vertex orbit. New form:

        δ_CP = (3π/2) · (1 − 0.12·η·ξ + 0.05·ξ²)

    With b₃ = 24:
      * θ₁₃ = 8.669° (NuFIT 6.0 NO 8.58 ± 0.11 → 0.81σ, within 1σ)
      * δ_CP = 1.541π (NuFIT 6.0 1.54π ± 0.17π → 0.005σ, within 1σ)

    Both within 1σ simultaneously with zero fitted free parameters.
    """
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        get_geometric_pmns,
    )

    result = get_geometric_pmns()
    div = result["documented_divergence"]

    # The divergence block must surface the NuFIT anchors.
    # 2026-08 stale-constant fix: the dataset NO value is 8.58
    # (8.54 was a pre-release copy); the prediction 8.669 moves
    # from 0.99σ to 0.68σ — closer, not farther.
    assert div["nufit_theta_13_deg"] == pytest.approx(8.58)
    # 2026-08 anchor unification: NuFIT 6.0's symmetric 1-sigma is 0.11;
    # the previous 0.13 was an asymmetric-upper copy that understated
    # the deviation (0.68 sigma -> 0.81 sigma, still within 1 sigma).
    assert div["nufit_theta_13_sigma"] == pytest.approx(0.11)
    assert div["nufit_delta_CP_pi_units"] == pytest.approx(1.54)
    assert div["nufit_delta_CP_sigma_pi"] == pytest.approx(0.17)

    # Sprint T5 #1: θ₁₃ within 1σ of NuFIT 6.0.
    assert div["theta_13_within_1sigma"] is True, (
        "Sprint T5 #1 (η = √2·sin(π/b₃), ξ = cos(π/b₃)) should land "
        "θ₁₃ within 1σ of NuFIT 6.0 NO 8.58 ± 0.11, got "
        f"theta_13_deg = {result['theta_13_deg']:.4f}°, "
        f"sigma deviation = {div['theta_13_sigma_deviation']:.3f}"
    )
    assert div["theta_13_sigma_deviation"] < 1.0, (
        f"theta_13_sigma_deviation = {div['theta_13_sigma_deviation']} "
        f"should be < 1 after Sprint T5 #1."
    )

    # Sprint T5 #1: δ_CP also within 1σ of NuFIT 6.0.
    assert div["delta_CP_within_1sigma"] is True, (
        "Sprint T5 #1 two-parameter form should land δ_CP within 1σ "
        "of NuFIT 6.0 1.54π ± 0.17π, got "
        f"delta_CP_pi_units = {result['delta_CP_pi_units']:.4f}, "
        f"sigma deviation = {div['delta_CP_sigma_deviation']:.3f}"
    )
    assert div["delta_CP_sigma_deviation"] < 1.0, (
        f"delta_CP_sigma_deviation = {div['delta_CP_sigma_deviation']} "
        f"should be < 1 after Sprint T5 #1."
    )

    # The note text must mention the Sprint T5 #1 retuning and ξ.
    note = div["note"]
    assert ("Sprint T5" in note) or ("T2.4" in note), (
        f"Divergence note doesn't mention the Sprint T5 #1 / T2.4 "
        f"retuning: {note!r}"
    )
    assert ("ξ" in note) or ("xi" in note.lower()) or ("cos(π/b" in note), (
        f"Divergence note doesn't mention the sister parameter ξ: "
        f"{note!r}"
    )


# ── Test 4: b₃ leaf in the EML structural tree ────────────────────────────


def test_b3_leaf_in_eml_tree(isolated_autogen: Path) -> None:
    """The structural EML tree must carry a real b₃ leaf with tension 24.

    Skipped when eml-math + eml-spectral aren't importable in the test
    env (the Sprint 4 #1 adapter already shadows the upstream package
    name in some configurations — that's tracked separately as a
    namespace-shadowing issue).
    """
    try:
        from metaphysica.simulations.core.eml_integration import EML_AVAILABLE
    except ImportError:  # pragma: no cover
        EML_AVAILABLE = False
    if not EML_AVAILABLE:
        pytest.skip(
            "eml-math + eml-spectral not loadable in this env "
            "(structural EML tree disabled; see eml_math adapter shadow)"
        )

    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        GeometricYukawaT4,
    )

    deriver = GeometricYukawaT4()
    deriver.derive_pmns_angles()
    handles = deriver.eml_handles

    assert "b3_leaf" in handles, (
        "Structural EML tree missing the b3_leaf handle — "
        "the b₃ tracer would not be able to reach b₃ = 24."
    )
    b3_pt = handles["b3_leaf"]
    assert math.isclose(float(b3_pt.tension()), 24.0, rel_tol=1e-9), (
        f"b3 leaf tension {float(b3_pt.tension())} != 24 "
        f"(G2 third Betti number)"
    )

    # Sprint T5 #1: the sister parameter ξ must also appear in the
    # structural tree, routing through the same b3_leaf as η.
    assert "xi_distortion" in handles, (
        "Sprint T5 #1: structural EML tree missing xi_distortion handle "
        "— the sister parameter ξ = cos(π/b₃) is not rooted in b3_leaf()."
    )

    # The EML structural pipeline must cross-check the float pipeline
    # to within numerical tolerance.
    last = deriver.last_result
    assert last is not None
    assert last["eml_theta_13_rad"] is not None
    assert math.isclose(
        last["eml_theta_13_rad"], last["theta_13_rad"], rel_tol=1e-9
    )
    assert math.isclose(
        last["eml_delta_CP_rad"], last["delta_CP_rad"], rel_tol=1e-9
    )
    assert math.isclose(
        last["eml_y_e_hierarchy"], last["y_e_hierarchy"], rel_tol=1e-9
    )


# ── Test 5: triple-tracked formulas ───────────────────────────────────────


def test_triple_tracked_formulas(isolated_autogen: Path) -> None:
    """Every published Formula carries arithma + (eml when avail) + value."""
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        GeometricYukawaT4,
    )

    deriver = GeometricYukawaT4()
    forms = deriver.get_formulas()

    expected_ids = {
        "pmns-theta-13-geometric",
        "pmns-delta-cp-geometric",
        "yukawa-e-hierarchy-geometric",
    }
    got_ids = {f.id for f in forms}
    assert got_ids == expected_ids, (
        f"unexpected formula set: {got_ids} (expected {expected_ids})"
    )

    for f in forms:
        # Arithma stub is always non-None (degrades gracefully).
        assert f.arithma is not None, (
            f"formula {f.id!r} missing arithma leg"
        )
        # Value must match the canonical float for this formula id.
        assert isinstance(f.value, float), (
            f"formula {f.id!r} value not float: {type(f.value).__name__}"
        )
        assert math.isfinite(f.value), (
            f"formula {f.id!r} value not finite: {f.value!r}"
        )
        # triple_env must be present and carry b3 = 24, eta and the
        # Sprint T5 #1 sister parameter xi.
        assert f.triple_env is not None
        assert f.triple_env.get("b3") == 24.0
        assert "eta" in f.triple_env
        assert "xi" in f.triple_env, (
            f"formula {f.id!r} triple_env missing Sprint T5 #1 sister "
            f"parameter xi: {f.triple_env!r}"
        )


# ── Test 6: custom-eta path ───────────────────────────────────────────────


def test_custom_eta_produces_consistent_theta_13(isolated_autogen: Path) -> None:
    """Cross-validation hook for the v26.0 η-re-derivation work.

    Passing a non-default ``eta_distortion`` to the class must update
    θ₁₃ consistently with the formula. The η = 0.181 value is the
    geometric-solve for NuFIT 6.0 8.5° — kept here as the v26.0
    re-derivation target.
    """
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        GeometricYukawaT4,
        T4_ORBIT_AMPLITUDE,
    )

    eta_custom = 0.181029  # arcsin⁻¹(8.5°) / sqrt(2/3)
    result = GeometricYukawaT4(eta_distortion=eta_custom).derive_pmns_angles()

    expected_theta_13_deg = math.degrees(
        math.asin(T4_ORBIT_AMPLITUDE * eta_custom)
    )
    assert math.isclose(
        result["theta_13_deg"], expected_theta_13_deg, rel_tol=1e-12
    )
    # At this custom η, θ₁₃ ≈ 8.5° — the v26.0 target.
    assert math.isclose(result["theta_13_deg"], 8.5, abs_tol=0.01), (
        f"Custom η = {eta_custom} should land θ₁₃ ≈ 8.5°, got "
        f"{result['theta_13_deg']:.4f}°"
    )


# ── Test 7: Sprint T5 #1 sister parameter ξ = cos(π/b₃) ──────────────────


def test_xi_sister_parameter_closed_form_from_b3(
    isolated_autogen: Path,
) -> None:
    """The Sprint T5 #1 sister parameter ξ is closed-form in b₃.

    TIER_2_3_ROADMAP §T2.4 requires the second geometric parameter
    governing δ_CP be:

      1. Expressible in closed form from b₃ (no fitted free parameter).
      2. Documented with a one-line geometric origin in the docstring.
      3. Routing through ``b3_leaf()`` somewhere in its derivation
         (when EML is available).

    This test enforces all three. The canonical ξ is cos(π/b₃) —
    the algebraic conjugate of the existing η = √2·sin(π/b₃) on the
    T₄/24-cell vertex orbit.
    """
    from metaphysica.simulations.PM.particle import yukawa_derivation as ymod
    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        DEFAULT_B3,
        DEFAULT_XI,
        GeometricYukawaT4,
        _xi_from_b3,
    )

    # (1) Closed form: ξ = cos(π/b₃)
    assert math.isclose(
        _xi_from_b3(DEFAULT_B3),
        math.cos(math.pi / DEFAULT_B3),
        rel_tol=1e-15,
    )
    assert math.isclose(DEFAULT_XI, math.cos(math.pi / 24), rel_tol=1e-15)
    # For b₃ = 24, ξ ≈ 0.99144486
    assert math.isclose(DEFAULT_XI, 0.99144486, abs_tol=1e-7)

    # The geometric expression must hold for every Pillar-Seed-plausible b₃.
    for b3_probe in (12, 18, 24, 30, 36):
        assert math.isclose(
            _xi_from_b3(b3_probe),
            math.cos(math.pi / b3_probe),
            rel_tol=1e-15,
        )

    # (2) Documented with a one-line geometric origin: the docstring
    # of _xi_from_b3 (or the module docstring) must mention the
    # geometric content. We accept either "cos(π/b₃)" / "cos(pi/b3)" or
    # the explicit phrase "half-angle cosine" / "conjugate".
    doc = (_xi_from_b3.__doc__ or "") + (ymod.__doc__ or "")
    assert any(token in doc for token in (
        "cos(π/b₃)", "cos(pi/b3)", "cos(π/b_3)", "half-angle cosine",
        "conjugate",
    )), (
        "Sprint T5 #1 ξ docstring missing geometric origin one-liner: "
        f"got {doc!r}"
    )

    # (3) The class accepts xi_distortion override and reports xi back.
    result = GeometricYukawaT4().derive_pmns_angles()
    assert math.isclose(result["xi_distortion"], DEFAULT_XI, rel_tol=1e-15)

    # (3b) Override path produces a different δ_CP without disturbing θ₁₃
    # (since θ₁₃ depends only on η, not on ξ).
    base = GeometricYukawaT4().derive_pmns_angles()
    perturbed = GeometricYukawaT4(xi_distortion=0.95).derive_pmns_angles()
    assert math.isclose(
        base["theta_13_rad"], perturbed["theta_13_rad"], rel_tol=1e-12
    ), (
        "Changing ξ should leave θ₁₃ untouched — only δ_CP depends on ξ."
    )
    assert not math.isclose(
        base["delta_CP_rad"], perturbed["delta_CP_rad"], rel_tol=1e-6
    ), (
        "Changing ξ should shift δ_CP (it's the second knob)."
    )


def test_xi_routes_through_b3_leaf(isolated_autogen: Path) -> None:
    """Sprint T5 #1: ξ subtree must contain a b3_leaf() node.

    The structural EML tree's ``xi_distortion`` handle (when EML is
    available) must derive from ``b3_leaf()`` — same as η. This is
    the audit hook for the dependency walker so ξ is counted in the
    b₃-rooted formula tally.
    """
    try:
        from metaphysica.simulations.core.eml_integration import EML_AVAILABLE
    except ImportError:  # pragma: no cover
        EML_AVAILABLE = False
    if not EML_AVAILABLE:
        pytest.skip(
            "eml-math + eml-spectral not loadable in this env "
            "(structural EML tree disabled; see eml_math adapter shadow)"
        )

    from metaphysica.simulations.PM.particle.yukawa_derivation import (
        GeometricYukawaT4,
    )

    deriver = GeometricYukawaT4()
    deriver.derive_pmns_angles()
    handles = deriver.eml_handles

    assert "xi_distortion" in handles
    # The structural ξ subtree, when evaluated, must equal cos(π/24).
    from metaphysica.simulations.core.eml_tree_adapter import eml_compute
    xi_value = float(eml_compute(handles["xi_distortion"]))
    assert math.isclose(xi_value, math.cos(math.pi / 24), rel_tol=1e-9), (
        f"xi structural tree evaluates to {xi_value} != cos(π/24) "
        f"{math.cos(math.pi/24)} — Sprint T5 #1 ξ should be b3_leaf-rooted "
        f"via cos(π/b₃)."
    )
    # And the b3_leaf handle must be present (same root as η).
    assert "b3_leaf" in handles
    assert math.isclose(
        float(handles["b3_leaf"].tension()), 24.0, rel_tol=1e-9
    )
