"""b_3 and b_2 must come from the same seed, or the pipeline runs on a chimera.

WHAT THIS CAUGHT, AND IT ALMOST BECAME A REPORTED FINDING
=========================================================
Making the root simulation fork-aware was not enough. `run_all_simulations`
PRE-LOADS the seed before the root runs, and `has_param` makes it
first-writer-wins, so a literal 24 there silently beat g2_geometry's fork-aware
value.

The failure mode was worse than no propagation at all. Nothing pre-loaded b_2,
so b_2 moved to 12 while b_3 stayed 24, and the whole pipeline ran on a MIXED
state. Its outputs looked like the cost of the 43 path:

    mixed (b_3 = 24, b_2 = 12)     theta_13 = 15.09 deg,  58.8 sigma
    consistent (b_3 = 43, b_2 = 12) theta_13 =  8.36 deg,   2.5 sigma

Reporting the first set would have told the author that the 43 path destroys the
neutrino sector. It does not. A partially-propagated fork is more dangerous than
an inert one, because an inert fork is visibly inert.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import pytest

from metaphysica.simulations.PM.geometry.b3_path import PATHS, seed_values

#: Every (b_3, b_2) pair any declared path can produce. A state outside this set
#: is a chimera: two seeds mixed, not a third option.
_COHERENT = {seed_values(name) for name in PATHS}


def _artifact():
    import json
    import os
    import pathlib

    roots = []
    raw = os.environ.get("METAPHYSICA_OUT")
    if raw:
        roots.append(pathlib.Path(raw))
    roots += [pathlib.Path("H:/Github/PrincipiaMetaphysica"),
              pathlib.Path(__file__).resolve().parents[2] / "PrincipiaMetaphysica"]
    for root in roots:
        candidate = root / "AutoGenerated" / "parameters.json"
        if candidate.is_file():
            return json.loads(candidate.read_text(encoding="utf-8"))["parameters"]
    return None


def test_the_declared_paths_give_distinct_coherent_pairs():
    """Guards the guard: if paths shared a pair this would prove nothing.

    Since the reachable family became runnable (2026-09-23) there are five
    declared paths, and the distinctness matters MORE, not less: (19, 4)
    and (24, 4) share b_2 = 4 while carrying different b_3. So a chimera
    check that compared b_2 alone would now pass on a mismatched build.
    The pair is what must match, and every declared pair must be distinct.
    """
    assert _COHERENT == {(spec["b3"], spec["b2"]) for spec in PATHS.values()}
    assert len(_COHERENT) == len(PATHS) == 5, (
        "%d declared paths produced %d distinct pairs -- two paths now "
        "share a (b_3, b_2) pair and the chimera guard below would not be "
        "able to tell them apart" % (len(PATHS), len(_COHERENT))
    )
    by_b2 = {}
    for b3, b2 in _COHERENT:
        by_b2.setdefault(b2, set()).add(b3)
    assert by_b2[4] == {19, 24}, (
        "b_2 = 4 is expected to be claimed by BOTH the reachable (19, 4) "
        "and the off-family (24, 4); if that stops being true the "
        "distinctness argument above needs re-deriving: %s" % by_b2
    )


def test_the_built_artifact_is_not_a_chimera():
    """b_3 and b_2 in the published artifact must come from ONE path."""
    params = _artifact()
    if params is None:
        pytest.skip("no built parameters.json reachable")

    b3 = params["topology.elder_kads"]["value"]
    b2 = params.get("topology.b2", {}).get("value")
    if b2 is None:
        pytest.skip("topology.b2 not present in this build")

    assert (b3, b2) in _COHERENT, (
        "the artifact carries b_3 = %s with b_2 = %s, which no declared path "
        "produces. Two seeds are mixed: the pipeline ran on a state that does "
        "not exist, and every downstream number is a chimera." % (b3, b2)
    )


def test_k_gimel_rides_on_the_same_seed():
    """k_gimel = b_3/2 + 1/pi was hardcoded with a literal 24 in the runner."""
    import math

    params = _artifact()
    if params is None:
        pytest.skip("no built parameters.json reachable")
    b3 = params["topology.elder_kads"]["value"]
    k = params.get("topology.k_gimel", {}).get("value")
    if k is None:
        pytest.skip("topology.k_gimel not present")

    assert k == pytest.approx(b3 / 2.0 + 1.0 / math.pi), (
        "k_gimel = %s does not match b_3/2 + 1/pi for b_3 = %s; it is riding on "
        "a different seed than the one published" % (k, b3)
    )


def test_a_mixed_pair_is_rejected_by_the_same_rule():
    """The rule must reject the state that actually occurred, not just pass."""
    assert (24, 12) not in _COHERENT, (
        "the chimera that shipped -- b_3 = 24 with b_2 = 12 -- is not detected "
        "as incoherent, so this guard would not have caught it"
    )
    assert (43, 4) not in _COHERENT


def test_the_runner_no_longer_hardcodes_the_seed():
    """Traced, so the pre-load cannot silently become a literal again."""
    import inspect

    from metaphysica.simulations import run_all_simulations as runner

    source = inspect.getsource(runner)
    assert "seed_values" in source, (
        "run_all_simulations stopped reading the seed fork; a literal there "
        "beats the root simulation because has_param is first-writer-wins"
    )
    assert 'set_param("topology.elder_kads", 24' not in source, (
        "the literal seed is back in the runner"
    )
