"""The rigor validator must not manufacture a fit statistic.

WHY THIS EXISTS
---------------
Four defects stacked on top of each other, and every one of them pushed the
published conclusion in the flattering direction:

1. ``chi_sq`` came from ``summary.get("global_chi_squared", 0.23)``. The
   report's summary block has no such key -- it carries total/pass/fail
   counts and nothing else -- so the 0.23 default fired on EVERY run. The
   companion ``degrees_of_freedom`` default of 25 fired with it. Both were
   literals carried over from v23.9. The p-value, the EDOF comparison and
   the headline verdict were all computed from those two numbers rather
   than from the 136 rows sitting in the same file.
2. When the file was missing entirely, the constructor set the same two
   literals, set ``validation_results = []``, logged a warning, and then
   published a complete statistical report -- p-value, effective rank,
   "Full Independence: True" -- computed from no data at all.
3. The p-value TAIL was chosen from the data (``chi_sq_old <
   dof_effective``) but the INTERPRETATION branched on the
   ``use_lower_tail`` FLAG. With chi^2 above the DoF the upper tail is
   taken and p ~ 0 means a bad fit; the lower-tail branch reads p < 0.05
   as "TOO_GOOD (suspiciously perfect fit)". The sign of the conclusion
   was inverted.
4. ``recalculate_with_theory_uncertainty`` summed only rows with status
   PASS or MARGINAL. The fit quality was measured over exactly the rows
   that already agreed, every TENSION and FAIL having been dropped first,
   and the result reported as suspiciously perfect -- which it was, by
   construction.

Together these published "chi^2 = 0.23, reduced 0.077, p = 0.97, TOO_GOOD".
The same code on the same file now reports chi^2 = 126676 over 63 scoring
rows, p = 0, POOR_FIT.

These tests are deliberately about PROVENANCE rather than values: they
check that numbers come from the rows, and that a missing input fails
loudly. A future refinement may legitimately move the chi-squared; none of
these should care.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from metaphysica.simulations.PM.validation.statistical_rigor_validator import (
    NON_SCORING_VERDICTS,
    SCORING_VERDICTS,
    StatisticalRigorValidator,
)


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for path in candidates:
        if path.is_dir() and (path / "validation_report.json").is_file():
            return path
    pytest.skip("no validation_report.json found; run the build first")


def _validator() -> StatisticalRigorValidator:
    return StatisticalRigorValidator(
        validation_file=str(_autogen() / "validation_report.json"))


# -- 1. no fabricated statistic ---------------------------------------------


def test_missing_report_raises_rather_than_inventing_one(tmp_path):
    """A missing input is a build failure, not a licence to invent one."""
    with pytest.raises(FileNotFoundError) as excinfo:
        StatisticalRigorValidator(validation_file=str(tmp_path / "absent.json"))
    assert "0.23" in str(excinfo.value), (
        "the error should name the literal it replaced, so the next reader "
        "understands what used to happen here"
    )


def test_chi_squared_is_computed_from_the_rows_not_a_default():
    """The 0.23 default fired on every run because the key never existed."""
    validator = _validator()
    assert validator.chi_sq != pytest.approx(0.23), (
        "chi-squared is still the v23.9 literal -- the summary lookup is "
        "falling back to its default again"
    )
    recomputed, n = StatisticalRigorValidator._chi_squared_from_rows(
        validator.validation_results)
    assert validator.chi_sq == pytest.approx(recomputed)
    assert validator.dof_claimed == n


def test_the_summary_block_genuinely_lacks_the_key_it_was_read_from():
    """Pin the root cause, so re-adding a default cannot pass unnoticed.

    If a future report DOES publish global_chi_squared this test fails and
    should be updated to check the two agree -- which is the right outcome.
    """
    data = json.loads((_autogen() / "validation_report.json")
                      .read_text(encoding="utf-8"))
    assert "global_chi_squared" not in data.get("summary", {})


# -- 2. the fit ranges over failures too ------------------------------------


def test_scoring_and_non_scoring_verdicts_do_not_overlap():
    assert not (SCORING_VERDICTS & NON_SCORING_VERDICTS)


def test_failures_are_included_in_the_fit_statistic():
    """TENSION and FAIL must count. Dropping them is what made it perfect."""
    assert "FAIL" in SCORING_VERDICTS and "TENSION" in SCORING_VERDICTS
    rows = _validator().validation_results
    statuses = {r["status"] for r in rows}
    assert statuses & {"FAIL", "TENSION"}, (
        "no failing row survived into the fit -- the allowlist has narrowed "
        "back to the agreeing members"
    )


def test_theory_uncertainty_recalculation_sees_the_failures_too():
    """The second statistic had its own narrower allowlist."""
    validator = _validator()
    result = validator.recalculate_with_theory_uncertainty()
    if not result:
        pytest.skip("recalculation returned nothing")
    scored = {d["parameter"] for d in result.get("detailed_results", [])}
    failing = {r["path"] for r in validator.validation_results
               if r["status"] == "FAIL"}
    assert failing & scored, (
        "the theory-uncertainty recalculation excluded every failing row"
    )


# -- 3. unscoreable rows stay out -------------------------------------------


def test_unbounded_rows_are_excluded():
    """The report's own non-scoring verdicts must be honoured."""
    rows = _validator().validation_results
    assert all(r["status"] not in NON_SCORING_VERDICTS for r in rows)


def test_one_sided_bounds_are_excluded_from_the_fit():
    """A margin is not a residual.

    gauge.M_GUT_GEOMETRIC once compared 2.1e16 GeV against 1.67e34 -- the
    Super-Kamiokande proton LIFETIME in years, stored in the field meant for
    a mass -- and contributed 3.4e38 to the chi-squared on its own. With the
    unit error fixed it is a genuine lower bound at 1e15 GeV that the value
    clears 20-fold, so it is now a legitimate PASS. It still must not enter
    the fit: the registry sets sigma to None for one-sided bounds precisely
    because "20x above the floor" is not a discrepancy, and squaring
    (value - bound)/uncertainty would turn a comfortable pass into a large
    fictitious contribution.
    """
    from metaphysica.simulations.PM.validation.statistical_rigor_validator import (
        TWO_SIDED_BOUND_TYPES,
    )

    rows = _validator().validation_results
    assert rows, "no rows survived"
    for row in rows:
        assert row.get("bound_type") in TWO_SIDED_BOUND_TYPES, (
            f"{row['path']} is a {row.get('bound_type')!r} bound and has no "
            f"residual, but reached the chi-squared"
        )


# -- 4. the tail interpretation matches the tail used -----------------------


def test_a_bad_fit_is_not_reported_as_a_suspiciously_perfect_one():
    """The inversion: p ~ 0 on the upper tail read as TOO_GOOD."""
    result = _validator().recalculate_with_theory_uncertainty()
    if not result:
        pytest.skip("recalculation returned nothing")
    tail = result.get("tail_used", "")
    status = result.get("status", "")
    if tail.startswith("upper") and result.get("p_value_new", 1.0) < 0.05:
        assert "TOO_GOOD" not in status, (
            f"upper-tail p = {result.get('p_value_new')} means the model does "
            f"not fit, but the status reads {status!r}"
        )


def test_interpretation_follows_the_tail_actually_used():
    """Mutation: the flag must not be able to override the data.

    use_lower_tail stays True (the shipped setting) while the data forces
    the upper tail. Before the fix this combination produced TOO_GOOD.
    """
    validator = _validator()
    assert validator.use_lower_tail is True
    result = validator.recalculate_with_theory_uncertainty()
    if not result:
        pytest.skip("recalculation returned nothing")
    if result.get("tail_used", "").startswith("upper"):
        assert "suspiciously perfect" not in result.get("status", "")


# -- the honest headline ----------------------------------------------------


def test_the_published_report_does_not_claim_a_perfect_fit():
    """Whatever the number is, it must not be the 0.23 fiction."""
    path = _autogen() / "statistical_rigor_report.json"
    if not path.is_file():
        pytest.skip("statistical_rigor_report.json not present")
    report = json.loads(path.read_text(encoding="utf-8"))
    edof = report.get("edof_analysis", {})
    if "chi_squared" in edof:
        assert edof["chi_squared"] != pytest.approx(0.23), (
            "the shipped report still carries the fabricated chi-squared -- "
            "rebuild"
        )
