"""An identifier can be unique, well-formed, resolvable — and wrong.

WHAT THIS CAUGHT
----------------
Two entries carried DOIs that resolve to entirely unrelated documents:

    penrose-2004   "The Road to Reality" (2004)
                   doi 10.1038/nphys344
                   -> "Direct force measurements on DNA in a solid-state
                      nanopore", Nature Physics 2 (2006) 473-477

    weinberg-1972  "Gravitation and Cosmology" (1972)
                   doi 10.1002/piuz.19740050511
                   -> "Preise fuer Jahres-Abonnement 1975", Physik in
                      unserer Zeit 5 (1974) -- a subscription price list

Both were verified against Crossref. A reader following the framework's
Penrose citation arrived at a DNA nanopore experiment.

WHY EVERY EXISTING CHECK PASSED
-------------------------------
* ``every_reference_is_identifiable`` — both HAVE an identifier.
* ``no_conflicting_identifiers`` — it looks for one id claimed by entries of
  different years. These ids were each claimed once. An id can be wrong
  without being shared.
* ``no_duplicate_titles`` — each book had a second, correctly-identified
  entry, but under its full subtitle ("The Road to Reality: A Complete
  Guide..."), so strict title normalisation saw two different works.

The near-duplicate ADVISORY closes the last of those: titles that agree once
a subtitle is dropped, in the same year. It is deliberately not a gate,
because a looser key collapses the seven deliberate PDG per-section
citations, the distinct CODATA releases, and two genuinely different Acharya
G2-MSSM papers. Merging those would be a worse error than the duplicate.

Both DOIs are replaced by identifiers their correctly-formed twins already
carried — nothing invented, per the SSOT rule.

These tests pin the two specific repairs and the advisory's existence. They
cannot verify a DOI's target offline; that took a Crossref lookup, recorded
here so the next reader does not have to repeat it.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

#: DOIs proven to resolve to something other than the work citing them.
#: Verified against api.crossref.org.
KNOWN_WRONG_TARGETS = {
    "10.1038/nphys344":
        "Direct force measurements on DNA in a solid-state nanopore, "
        "Nature Physics 2 (2006) — not Penrose, The Road to Reality (2004)",
    "10.1002/piuz.19740050511":
        "Preise fuer Jahres-Abonnement 1975, Physik in unserer Zeit 5 "
        "(1974) — a price list, not Weinberg, Gravitation and Cosmology",
}


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for path in candidates:
        if path.is_dir() and (path / "references.json").is_file():
            return path
    pytest.skip("no references.json; run the build first")


def _refs() -> dict:
    data = json.loads((_autogen() / "references.json").read_text(encoding="utf-8"))
    refs = data.get("references", data)
    return refs if isinstance(refs, dict) else {r["id"]: r for r in refs}


def _identifier(entry) -> str:
    return str(entry.get("doi") or entry.get("arxiv") or entry.get("arxiv_id")
               or entry.get("url") or "")


def test_no_entry_carries_a_known_wrong_identifier():
    """The core regression guard."""
    offenders = []
    for rid, entry in _refs().items():
        ident = _identifier(entry).lower().replace("https://doi.org/", "")
        for bad, what in KNOWN_WRONG_TARGETS.items():
            if bad.lower() in ident:
                offenders.append(f"{rid} carries {bad} — that DOI is {what}")
    assert not offenders, "\n  ".join(offenders)


def test_the_two_repaired_books_still_have_an_identifier():
    """Removing a wrong id must not leave the entry unidentifiable."""
    refs = _refs()
    for rid in ("penrose-2004", "weinberg-1972"):
        entry = refs.get(rid)
        if entry is None:
            continue
        assert _identifier(entry), (
            f"{rid} lost its identifier entirely; an entry nobody can look "
            f"up cannot support a claim"
        )


def test_the_near_duplicate_advisory_exists_and_is_not_a_gate():
    """It surfaces candidates; auto-merging them would be the worse error."""
    report = json.loads((_autogen() / "reference_integrity.json")
                        .read_text(encoding="utf-8"))
    check = next((c for c in report["checks"]
                  if c["id"] == "no_near_duplicate_titles"), None)
    assert check is not None, "the advisory tier has been removed"
    assert check["status"] == "ADVISORY", (
        "the near-duplicate tier has become a gate; as a gate it would force "
        "merging the deliberate PDG and CODATA groups"
    )


def test_the_advisory_still_sees_the_pairs_that_hid_the_bad_dois():
    """If it stopped seeing them, the detection route is gone."""
    report = json.loads((_autogen() / "reference_integrity.json")
                        .read_text(encoding="utf-8"))
    groups = report.get("near_duplicate_titles", {})
    flattened = {rid for rids in groups.values() for rid in rids}
    for rid in ("penrose-2004", "penrose_2004_road_to_reality",
                "weinberg-1972", "weinberg1972_gravity"):
        if rid in _refs():
            assert rid in flattened, (
                f"{rid} is no longer surfaced as a near-duplicate; this is "
                f"the tier that exposed its wrong DOI"
            )


def test_the_strict_checks_still_pass():
    """The advisory must not have been added by weakening the gates."""
    report = json.loads((_autogen() / "reference_integrity.json")
                        .read_text(encoding="utf-8"))
    for check in report["checks"]:
        if check["id"] in ("no_duplicate_titles", "no_conflicting_identifiers",
                           "references_are_cited",
                           "every_reference_is_identifiable"):
            assert check["status"] == "PASS", (
                f"{check['id']} is failing: {check['measured']}"
            )
