"""Tests for the observable disposition ledger.

WHY THIS EXISTS
---------------
The shadow-derivation auditor reported **0 conflicts** while the framework
shipped three H0 values (71.55, 73.04, 76.34), four S8 values, and two
theta_13 predictions ~0.9 deg apart. The cause was not a bug in the
comparison logic -- it was that OBSERVABLE_GROUPS is a curated allowlist, and
a curated allowlist records what someone remembered to check. It had drifted
until it contained only members that already agreed.

These tests defend the replacement: discovery finds every candidate, and a
disposition must exist for each one, so a contradiction can no longer hide by
being absent from a list.

They also defend the OPPOSITE failure. Naive name-matching would group
H0_early (67.4, Planck) with H0_late_evolved (73.04, SH0ES) and report the
Hubble tension itself as a code defect. False conflicts corrode a report as
fast as false silence, so distinctness must stay declarable -- with a reason.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from metaphysica.simulations.core.observable_groups import (
    DISPOSITIONS,
    DISTINCT,
    INTERMEDIATE,
    MEMBER,
    OBSERVABLE_GROUPS,
    OBSERVABLE_TOKENS,
    UNTRIAGED,
    audit_dispositions,
    discover_candidates,
    effective_groups,
)


def _load_params():
    """Live registry, or skip -- these tests are about real drift."""
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated" / "parameters.json")
    candidates += [
        Path(__file__).resolve().parents[1] / "AutoGenerated" / "parameters.json",
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated/parameters.json"),
    ]
    for path in candidates:
        if path.is_file():
            return json.loads(path.read_text(encoding="utf-8"))["parameters"]
    pytest.skip("parameters.json not available; run the build first")


@pytest.fixture(scope="module")
def params():
    return _load_params()


# ── the ledger must be complete ──────────────────────────────────────────────


def test_every_candidate_has_a_disposition(params):
    """No candidate may be silently absent.

    This is the whole fix: absence used to be invisible, and that is how the
    H0 and S8 contradictions survived. An unclassified parameter is now a
    reported finding.
    """
    audit = audit_dispositions(params)
    assert not audit["undisposed"], (
        "these registry parameters match an observable token but have no "
        "disposition -- classify them in observable_groups.DISPOSITIONS as "
        f"MEMBER / DISTINCT / INTERMEDIATE: {audit['undisposed']}"
    )


def test_untriaged_entries_are_declared_not_hidden(params):
    """UNTRIAGED is allowed, but only as an explicit, visible state.

    The first occupants (two Higgs-named parameters at 504.06 and 414.22
    GeV) have since been triaged: higgs_mass.py's Sprint T3 #4 block turned
    out to document both as failed/pre-projection legs. The state remains
    legal for future candidates; this guards its bookkeeping.
    """
    audit = audit_dispositions(params)
    for name in audit["untriaged"]:
        assert DISPOSITIONS[name][0] == UNTRIAGED
        assert DISPOSITIONS[name][1], f"{name} is UNTRIAGED with no reason"


def test_every_disposition_carries_a_reason():
    """The reason string is what stops silent re-curation back into
    agreement. A disposition without one is just a quieter allowlist."""
    for name, (kind, reason) in DISPOSITIONS.items():
        assert kind in {MEMBER, DISTINCT, INTERMEDIATE, UNTRIAGED}, name
        assert reason and len(reason) > 8, f"{name} has no substantive reason"


def test_ledger_has_no_stale_entries(params):
    """Dispositions for parameters that no longer exist should be removed,
    so the ledger cannot rot into fiction the way the curated groups did."""
    known = set(params)
    stale = [n for n in DISPOSITIONS if n not in known]
    assert not stale, f"dispositions for absent parameters: {stale}"


# ── the fix actually surfaces the hidden contradictions ─────────────────────


def test_effective_groups_are_larger_than_the_curated_ones(params):
    """The curated lists were missing members; that is the defect."""
    eff = effective_groups(params)
    assert len(eff["H0_local"]) > len(OBSERVABLE_GROUPS["H0_local"])
    assert len(eff["S8"]) > len(OBSERVABLE_GROUPS["S8"])
    assert len(eff["theta_13"]) > len(OBSERVABLE_GROUPS["theta_13"])


def test_the_canonical_h0_is_now_checked(params):
    """cosmology.H0_local = 71.55 is the framework's canonical late-time H0
    and was absent from the group, which held two entries both equal to
    73.04 -- so the detector reported CONSISTENT.

    The 76.34 Ricci variant is deliberately NOT a member: triage found a
    prior documented-alternative ruling for it (fitted 31-deg angle) hiding
    under a stale parameter name in the group's own comments."""
    eff = effective_groups(params)
    assert "cosmology.H0_local" in eff["H0_local"]
    assert "cosmology.H0_ricci_variant" not in eff["H0_local"]
    assert DISPOSITIONS["cosmology.H0_ricci_variant"][0] == DISTINCT


def test_the_failing_theta13_derivation_is_now_checked(params):
    """neutrino.theta13_derived = 9.594 deg is the register's 9.31-sigma
    failure and was never compared against the 8.669 deg sibling."""
    eff = effective_groups(params)
    assert "neutrino.theta13_derived" in eff["theta_13"]


def test_s8_group_is_no_longer_a_single_member(params):
    """One member meant the detector reported 'insufficient data' rather
    than comparing four registered S8 values."""
    eff = effective_groups(params)
    assert len(eff["S8"]) >= 4


# ── and does NOT manufacture false conflicts ────────────────────────────────


def test_early_and_late_h0_are_kept_apart(params):
    """The Hubble tension is physics, not a code defect.

    Grouping the Planck value with the SH0ES value would report the tension
    itself as an inconsistency -- the mirror error of the false silence this
    ledger replaces.
    """
    eff = effective_groups(params)
    for early in ("cosmology.H0_early", "geometry.H0_early", "desi.H0"):
        assert early not in eff["H0_local"], (
            f"{early} is an early-universe value and must not be compared "
            "against late-time H0"
        )
        assert DISPOSITIONS[early][0] == DISTINCT


def test_sigmas_and_factors_are_not_treated_as_predictions(params):
    """Tension sigmas, suppression percentages and ratios share the token
    but are not values of the observable."""
    eff = effective_groups(params)
    for name in ("cosmology.H0_tension_sigma",
                 "cosmology.s8_friction_suppression_pct",
                 "cosmology.s8_improvement_factor"):
        assert DISPOSITIONS[name][0] == INTERMEDIATE
        for members in eff.values():
            assert name not in members


def test_experimental_anchors_are_not_rival_derivations(params):
    """An anchor is data, not a competing prediction of the framework."""
    for name in ("desi.S8", "planck.S8", "bounds.sum_m_nu_upper"):
        assert DISPOSITIONS[name][0] == DISTINCT


# ── discovery itself ────────────────────────────────────────────────────────


def test_discovery_over_collects_on_purpose(params):
    """Over-collection costs a disposition line; under-collection costs a
    contradiction nobody sees. The tokens are deliberately wide."""
    found = discover_candidates(params)
    assert set(found) == set(OBSERVABLE_TOKENS)
    assert len(found["S8"]) > 10, "token too narrow to catch the S8 family"
    assert len(found["H0_local"]) > 10


def test_discovery_ignores_non_numeric_entries(params):
    """Strings and booleans are not competing numeric derivations."""
    for names in discover_candidates(params).values():
        for name in names:
            value = params[name]["value"]
            assert isinstance(value, (int, float))
            assert not isinstance(value, bool)
