"""A declared dependency that does not exist must be counted, not skipped.

WHY THIS EXISTS
---------------
``generate_arithma_dependency_walker`` walks a formula's ``input_params``
looking for a producing formula, and reports how many formulas are rooted in
b3 = 24. If a declared input names no registry parameter, ``producer_of``
simply has no entry and the loop moves on. The edge is invisible.

So a formula can declare a dependency that does not exist and still be
counted as rooted through some other input, and the headline
``b3_rooted_count`` is then measured over chains that are partly fictional.
122 formulas declare phantom inputs and 128 declare phantom outputs, over
207 distinct paths that exist nowhere in the registry -- ``topology.euler_chi``
appears twenty times, ``cosmology.H0_geometric`` eleven, ``topology.vol_v7``
ten.

Counting them does not repair them. Whether a phantom path should be created
in the registry or dropped from the declaration is a per-formula question,
and several are near-misses on a rename while most have no analogue at all.
What the count does is stop ``b3_rooted_count`` being read as though every
declared edge were real.

These tests check the audit is present and honest, and that it cannot
silently return zero.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for path in candidates:
        if path.is_dir() and (path / "dependency_chains.json").is_file():
            return path
    pytest.skip("no dependency_chains.json; run the build first")


def _chains() -> dict:
    return json.loads((_autogen() / "dependency_chains.json")
                      .read_text(encoding="utf-8"))


def _params() -> dict:
    return json.loads((_autogen() / "parameters.json")
                      .read_text(encoding="utf-8"))["parameters"]


def test_the_audit_is_published_beside_the_rooted_count():
    report = _chains()
    assert "b3_rooted_count" in report
    audit = report.get("declared_paths_that_do_not_exist")
    assert audit, (
        "b3_rooted_count ships without any statement of how many declared "
        "dependencies do not exist, so it reads as though every edge were "
        "real"
    )
    for key in ("formulas_with_phantom_inputs", "formulas_with_phantom_outputs",
                "distinct_phantom_paths", "phantom_paths"):
        assert key in audit


def test_the_phantom_paths_really_are_absent_from_the_registry():
    """Recomputed, so the audit cannot report a stale or invented list."""
    audit = _chains()["declared_paths_that_do_not_exist"]
    known = set(_params())
    still_present = sorted(set(audit["phantom_paths"]) & known)
    assert not still_present, (
        f"these are listed as phantom but do exist: {still_present[:10]}"
    )


def test_the_count_matches_the_listed_paths():
    audit = _chains()["declared_paths_that_do_not_exist"]
    assert audit["distinct_phantom_paths"] == len(set(audit["phantom_paths"]))


def test_the_audit_would_not_hide_a_regression():
    """It must be derived, not a frozen number that stops tracking reality."""
    audit = _chains()["declared_paths_that_do_not_exist"]
    by_in = audit.get("by_formula_inputs", {})
    by_out = audit.get("by_formula_outputs", {})
    assert audit["formulas_with_phantom_inputs"] == len(by_in)
    assert audit["formulas_with_phantom_outputs"] == len(by_out)
    listed = {p for v in by_in.values() for p in v}
    listed |= {p for v in by_out.values() for p in v}
    assert listed == set(audit["phantom_paths"])


def test_the_audit_says_it_reports_rather_than_repairs():
    note = _chains()["declared_paths_that_do_not_exist"]["note"]
    assert "Reported, not repaired" in note
    assert "b3_rooted_count" in note
