"""The published sigma must be the one the published verdict came from.

WHAT THIS CAUGHT
----------------
Once the theory-uncertainty policy started firing, ``verdict`` and ``sigma``
were being taken from two different computations. ``geometry.alpha_inverse``
published::

    verdict: FAIL          sigma: 0.07026

The FAIL came from the experimental-only deviation, 3.35e+04 sigma; the 0.07026
is the theory-folded value the policy had just declined to honour. A reader
sees a FAIL at seven hundredths of a sigma, which reads as a bug in the
framework rather than a disagreement with CODATA.

It also hid the real misses. ``worst_offenders`` ranks on ``sigma``, so the
largest genuine disagreements in the framework -- two rows at 3.35e+04 and two
at 12.73 -- were absent from the list of worst offenders while a 344.7 sigma
falsified candidate led it.

THE INVARIANT
-------------
A verdict is a band applied to a number. If the row reports a different number
than the one that was banded, the two disagree about what happened. So:
whichever sigma the policy used, that is the one published, and the other is
kept beside it under an explicit name.

This is checked structurally rather than by re-deriving the bands, because the
report deliberately carries two banding conventions (``_registry_band`` at
<1/<2/<3 and ``_verdict`` at <2/<3/<5) and the point here is coherence between
the emitted fields, not agreement between the two scales.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

_SCORED = {"PASS", "FAIL", "TENSION", "MARGINAL"}


def _rows():
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for c in candidates:
        f = c / "validation_report.json"
        if f.is_file():
            data = json.loads(f.read_text(encoding="utf-8"))["validations"]
            return list(data.values()) if isinstance(data, dict) else data
    pytest.skip("no validation_report.json; run the build first")


def test_a_demoted_row_publishes_the_sigma_it_was_judged_on():
    """When the policy drops the theory buffer, sigma must drop with it."""
    wrong = []
    for r in _rows():
        if r.get("verdict") not in _SCORED:
            continue
        v_theory = r.get("verdict_with_theory")
        v_exp = r.get("verdict_experimental_only")
        if v_theory == v_exp:
            continue                      # nothing was demoted
        if r.get("verdict") != v_exp:
            continue                      # the folded verdict still stands
        s, s_exp = r.get("sigma"), r.get("sigma_experimental_only")
        if s_exp is None or s is None:
            continue
        if abs(float(s) - float(s_exp)) > 1e-9 * max(1.0, abs(float(s_exp))):
            wrong.append(
                "  %s: verdict=%s (experimental-only) but sigma=%.6g, while "
                "sigma_experimental_only=%.6g"
                % (r["path"], r["verdict"], float(s), float(s_exp))
            )
    assert not wrong, (
        "these rows publish a verdict reached from one deviation and a sigma "
        "taken from another, so the two disagree about what happened:\n"
        + "\n".join(sorted(wrong))
    )


def test_the_folded_sigma_is_still_reported():
    """Coherence must not cost information.

    Demoting the headline sigma is only honest if the theory-folded value is
    still available -- otherwise the fix would delete the very number the
    `always` policy would publish.
    """
    missing = [
        r["path"] for r in _rows()
        if r.get("theory_uncertainty") and r.get("sigma_with_theory") is None
        and r.get("sigma") is not None
    ]
    assert not missing, (
        "these rows declare a theory uncertainty but report no "
        "sigma_with_theory, so the folded deviation is unrecoverable:\n  "
        + "\n  ".join(sorted(missing))
    )


def test_worst_offenders_ranks_on_the_published_sigma():
    """The worst offender list must reflect the framework's real misses.

    While sigma and verdict disagreed, two 3.35e+04 rows and two at 12.73 were
    absent from worst_offenders entirely, because they were ranked on their
    deflated folded values.
    """
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    report = None
    for c in candidates:
        f = c / "validation_report.json"
        if f.is_file():
            report = json.loads(f.read_text(encoding="utf-8"))
            break
    if report is None:
        pytest.skip("no validation_report.json")

    listed = {w["path"] for w in report.get("worst_offenders", [])}
    if not listed:
        pytest.skip("no worst_offenders block")

    worst_listed = min(
        (float(w["sigma"]) for w in report["worst_offenders"]
         if isinstance(w.get("sigma"), (int, float))),
        default=None,
    )
    if worst_listed is None:
        pytest.skip("worst_offenders carries no sigmas")

    omitted = [
        "  %s at %.6g sigma (%s)" % (r["path"], float(r["sigma"]), r["verdict"])
        for r in _rows()
        if r.get("verdict") in _SCORED
        and isinstance(r.get("sigma"), (int, float))
        and float(r["sigma"]) > worst_listed
        and r["path"] not in listed
    ]
    assert not omitted, (
        "these rows deviate by more than the smallest entry in "
        "worst_offenders (%.6g sigma) and are absent from it:\n" % worst_listed
        + "\n".join(sorted(omitted))
    )
