"""A theory uncertainty must not be published as an experimental one.

WHAT THIS CAUGHT
----------------
``geometry.mu_pe`` scored **0.0000 sigma PASS** against
``CODATA2022, +/- 2.0``. CODATA did not measure the proton-to-electron mass
ratio to +/- 2.0; it measured it to +/- 3.2e-08::

    mu_pe = 1836.152673426(32)

The 2.0 was the framework's own theory uncertainty for missing higher-order
QCD corrections -- the parameter's description said as much -- sitting in the
experimental uncertainty slot with a CODATA attribution. Against the real
sigma the prediction is 12.7 sigma out.

The datasource already knew the difference: ``codata_2022.json`` carries
``uncertainty`` and ``theory_uncertainty`` as separate fields, with a note
recording the split. ``codata.mu_pe`` was therefore correct while
``geometry.mu_pe`` -- the row that actually publishes a verdict -- was not.
The correction had never propagated to the consumer.

It also defeated the machinery built for exactly this. The certificate
generator carries ``theory_uncertainty``, ``theory_uncertainty_cited`` and
``theory_uncertainty_load_bearing``, and a policy that drops an uncited
load-bearing theory uncertainty back to the experimental-only verdict. None of
it can see a theory uncertainty that has been relabelled as experimental.

THE INVARIANT
-------------
Two rows quoting the same experimental source for the same measured quantity
must quote the same experimental uncertainty. A measurement has one sigma. If
two rows disagree about it, at least one of them is not reporting a
measurement.

This is deliberately not a check that any particular number is right -- that
would just be restating the datasource. It is a check that the framework does
not contradict itself about what was measured, which is what actually happened
here and needs no external reference to detect.
"""
from __future__ import annotations

import collections
import json
import os
from pathlib import Path

import pytest

#: Two experimental values are treated as the same measured quantity when they
#: agree to this relative tolerance. Loose enough to group a stale digit
#: (1836.15267343 vs 1836.152673426), tight enough not to group distinct
#: observables.
_SAME_QUANTITY_REL = 1e-6

#: Uncertainties are allowed to differ by up to this factor -- rounding, or one
#: row quoting a symmetrised error. The defect this catches was a factor of
#: 6e7, so nothing subtle is needed.
_MAX_UNC_RATIO = 4.0

#: Conflicts that are OPEN AUTHOR RULINGS, recorded with their evidence rather
#: than resolved here. Keyed by the sorted pair of paths.
#:
#: The electroweak VEV is the live one, and the disagreement is in the shipped
#: datasources themselves, not just in their consumers:
#:
#:     experimental/experiment_ref.json    v_EW       246.22 +/- 0.01  "PDG2024"
#:     experimental/pdg_2024_values.json   higgs.vev  246.22 +/- 0.5
#:
#: Neither is a measurement. PDG does not quote v directly; it follows from
#: G_F, and the same pdg_2024_values.json carries
#: constants.G_F = 1.1663788e-05 +/- 6e-12, which gives
#:
#:     v       = (sqrt(2) G_F)^(-1/2) = 246.2197 GeV
#:     sigma_v = (v/2)(dG_F/G_F)      = 6.3e-05 GeV
#:
#: so 0.01 overstates it by ~160x and 0.5 by ~8000x. Adopting 6.3e-05 would
#: move higgs.vev_geometric (246.37 vs 246.22) from the published 0.3 sigma to
#: roughly 2400 sigma, because the geometric derivation's own tolerance -- not
#: the measurement -- is what that comparison actually rests on. Which
#: datasource is canonical, and how much theory uncertainty v = k_gimel*(b3-4)
#: carries, are the author's calls. Recorded here so the conflict is visible
#: and cannot be mistaken for agreement.
_OPEN_RULINGS = {
    ("higgs.v_ew_derived", "higgs.vev"),
    ("higgs.v_ew_derived", "higgs.vev_geometric"),
}


def _rows():
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for c in candidates:
        f = c / "validation_report.json"
        if f.is_file():
            data = json.loads(f.read_text(encoding="utf-8"))["validations"]
            return list(data.values()) if isinstance(data, dict) else data
    pytest.skip("no validation_report.json; run the build first")


def _normalise_source(src: str) -> str:
    """CODATA2022 / ESTABLISHED:CODATA2022 / codata2022 are one source."""
    s = (src or "").upper().replace("ESTABLISHED:", "").replace("INPUT:", "")
    return "".join(ch for ch in s if ch.isalnum())


def _measured_rows():
    out = []
    for r in _rows():
        exp = r.get("experimental_value")
        unc = r.get("experimental_uncertainty")
        src = _normalise_source(r.get("experimental_source"))
        if not isinstance(exp, (int, float)) or exp == 0:
            continue
        if not isinstance(unc, (int, float)) or unc <= 0:
            continue
        if not src:
            continue
        out.append((src, float(exp), float(unc), r.get("path")))
    return out


def test_one_measurement_has_one_uncertainty():
    """Rows citing the same source for the same value must agree on sigma."""
    by_source = collections.defaultdict(list)
    for src, exp, unc, path in _measured_rows():
        by_source[src].append((exp, unc, path))

    conflicts = []
    for src, entries in by_source.items():
        entries.sort()
        for i, (exp_a, unc_a, path_a) in enumerate(entries):
            for exp_b, unc_b, path_b in entries[i + 1:]:
                if abs(exp_a - exp_b) / abs(exp_a) > _SAME_QUANTITY_REL:
                    continue
                if tuple(sorted((path_a, path_b))) in _OPEN_RULINGS:
                    continue
                lo, hi = sorted((unc_a, unc_b))
                if hi / lo > _MAX_UNC_RATIO:
                    conflicts.append(
                        "  %s cites %s +/- %g  but  %s cites %s +/- %g"
                        " (same source %s, ratio %.3g)"
                        % (path_a, exp_a, unc_a, path_b, exp_b, unc_b,
                           src, hi / lo)
                    )

    assert not conflicts, (
        "two rows quote the same experimental source for the same measured "
        "quantity but disagree about its uncertainty, so at least one is not "
        "reporting a measurement:\n" + "\n".join(sorted(conflicts))
        + "\nA theory uncertainty belongs in Parameter(theory_uncertainty=...),"
          " where the generator's cited / load_bearing policy can see it."
    )


def test_the_recorded_rulings_are_still_open():
    """A stale exemption is as bad as a missing check.

    If the author settles which datasource is canonical for the electroweak
    VEV, the two rows stop disagreeing and the entry here must go, or it will
    silently exempt a future conflict between the same two paths.
    """
    by_source = collections.defaultdict(list)
    for src, exp, unc, path in _measured_rows():
        by_source[src].append((exp, unc, path))

    still_conflicting = set()
    for entries in by_source.values():
        for i, (exp_a, unc_a, path_a) in enumerate(entries):
            for exp_b, unc_b, path_b in entries[i + 1:]:
                if abs(exp_a - exp_b) / abs(exp_a) > _SAME_QUANTITY_REL:
                    continue
                lo, hi = sorted((unc_a, unc_b))
                if hi / lo > _MAX_UNC_RATIO:
                    still_conflicting.add(tuple(sorted((path_a, path_b))))

    stale = [r for r in _OPEN_RULINGS if r not in still_conflicting]
    assert not stale, (
        "these pairs are recorded as open author rulings but no longer "
        "disagree about their uncertainty; remove them so the exemption list "
        "cannot drift:\n  " + "\n  ".join(" / ".join(r) for r in sorted(stale))
    )


def test_the_check_can_actually_fire():
    """A comparison that cannot fail is the bug class this suite exists for.

    The grouping depends on field names that have changed before
    (``experimental_bound`` vs ``experimental_value``), so assert the scan
    reaches real data rather than trusting an empty result.
    """
    measured = _measured_rows()
    assert len(measured) >= 20, (
        "only %d rows carried a usable (source, value, uncertainty) triple; "
        "the field names have probably moved and this check is passing "
        "vacuously" % len(measured)
    )
    sources = {src for src, _, _, _ in measured}
    assert len(sources) >= 3, (
        "experimental sources did not parse: %r" % sorted(sources)[:5]
    )
