"""The published artifacts must describe the model the code actually runs.

MEASURED 2026-09-23, after the b3_seed adoption landed in the ENGINE: the
site still largely described the PREVIOUS model. 883 stale claims across
sections.json, formulas.json and theory_output.json -- b_3 = 24, the
abandoned n_gen = b_3/8 route, chi_eff/48 asserted as live, TCS #187 as the
construction, "24 three-cycles".

That gap is its own defect class, distinct from the seed-blind writers the
engine work closed. A VALUE that follows the seed and PROSE that does not
is worse than either alone: a reader sees b_3 = 43 in the parameter table
and "the 24 associative 3-cycles" in the paragraph beside it, and has no
way to tell which the framework means.

WHAT EACH CLAIM IS, AND WHY IT IS STALE
=======================================
b3_is_24      the adopted seed is 43; 24 is the labelled off-path branch
b3_over_8     n_gen = b_3/8 is ABANDONED: 8 divides no Joyce-reachable
              b_3 (7, 19, 31, 43 are all odd), so it is an integer NOWHERE
              on the family. The count relocated to b_2/4 = rank(Gamma).
chi_over_48   chi_eff/48 = 3 is the UNRULED route; the dichotomy is open,
              so prose may DISCUSS it but must not assert it as live.
tcs_187       the construction is a Joyce orbifold T^7/(Z/2)^3; b_3 = 43
              lies outside the exhibited TCS range 71-155, which the
              register uses as an EXCLUSION.
cycles_24     restates b3_is_24 in words.

These counts are CEILINGS and may only fall. Nothing here asserts the
right number is zero: prose that names a stale claim in order to LABEL it
(a falsified candidate stays on the books) legitimately keeps the tokens,
so the floor is reached by reading, not by sweeping.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import json
import re

import pytest

from metaphysica.generators._common import autogen_dir

_ARTIFACTS = ("sections.json", "formulas.json", "theory_output.json")

_CLAIMS = {
    "b3_is_24": r"b_?3\s*=\s*24|b₃\s*=\s*24",
    "b3_over_8": r"b_?3\s*/\s*8|24\s*/\s*8|b₃/8",
    "chi_over_48": r"144\s*/\s*48|chi_eff\s*/\s*48",
    "tcs_187": r"TCS #?187",
    "cycles_24": r"24 (associative |independent )?3-cycles|24 three-cycles",
}

#: MEASURED 2026-09-23 on a fresh build. Ceilings; each may fall, none rise.
_CEILINGS = {
    # RE-MEASURED 2026-09-27 as ASSERTING occurrences only (see
    # _asserting_hits). Every ceiling TIGHTENED versus the raw counts it
    # replaces -- b3_is_24 776 -> 562, b3_over_8 105 -> 55, chi_over_48
    # 156 -> 136, tcs_187 89 -> 61, cycles_24 83 -> 40 -- because a large
    # share of the raw hits were prose naming a stale claim in order to
    # refute or relocate it. The raw count grew whenever the corpus got
    # MORE correct, which made it useless as a ratchet.
    "b3_is_24": 562,
    "b3_over_8": 55,
    "chi_over_48": 136,
    "tcs_187": 61,
    "cycles_24": 40,
}

#: The two artifact roots disagreed when this was written -- the repo-local
#: tree carried 776 b3_is_24 and the published tree 452, because they were
#: built at different times. Both ship, so BOTH are audited and the ceiling
#: is the worst of them; syncing them lowers the number, which is the
#: direction a ratchet is allowed to move.
_AUDIT_ALL_ROOTS = True


def _roots():
    from pathlib import Path

    seen, out = set(), []
    for root in (autogen_dir(),
                 Path("H:/Github/PrincipiaMetaphysica/AutoGenerated")):
        try:
            key = root.resolve()
        except OSError:
            continue
        if key in seen or not root.is_dir():
            continue
        seen.add(key)
        out.append(root)
    return out


def _corpus():
    """Every shipped artifact root, because every one of them is read."""
    blobs = {}
    for root in _roots():
        for name in _ARTIFACTS:
            path = root / name
            if path.is_file():
                blobs["%s::%s" % (root.name, name)] = path.read_text(
                    encoding="utf-8", errors="replace")
    if not blobs:
        pytest.skip("no built artifacts to audit")
    return blobs


#: Words that mark a stale claim as being NAMED in order to refute, label or
#: relocate it. A sentence carrying one of these is doing the right thing --
#: "8 divides no odd number, so b_3/8 yields an integer nowhere", "n_gen =
#: b_2/4 = 12/4, since b_3/8 fails" -- and counting it as a violation made
#: the ratchet punish honest labelling, so it rose every time the corpus got
#: MORE correct. Measured 2026-09-27: 142 raw b3_over_8 occurrences, of
#: which the majority sit in refutation context.
_REFUTATION_MARKERS = (
    "abandon", "aband", "no longer", "not integral", "non-integral",
    "yields an integer nowhere", "divides no", "fails", "failed", "refut",
    "relocat", "superseded", "retired", "off-path", "off the family",
    "was the", "used to", "previously", "formerly", "conjecture",
    "unruled", "awaiting", "instead", "rather than", "not a live",
    "withdrawn", "deprecated", "stale", "b_2/4", "b₂/4",
)

#: How much context around a hit to inspect for a marker. A JSON artifact has
#: no line breaks to rely on, so a fixed window is used and stated.
_CONTEXT = 240


def _asserting_hits(pattern, text):
    """Occurrences NOT sitting in a refutation/labelling context.

    The ratchet's job is to catch prose that still ASSERTS a superseded
    claim, not prose that names it in order to bury it. Without this split
    the count grew whenever the corpus was corrected, which is the opposite
    of what a ratchet is for.
    """
    rx = re.compile(pattern, re.I)
    hits = 0
    for m in rx.finditer(text):
        lo = max(0, m.start() - _CONTEXT)
        window = text[lo:m.end() + _CONTEXT].lower()
        if not any(mark in window for mark in _REFUTATION_MARKERS):
            hits += 1
    return hits


def _worst_root(pattern):
    """The highest ASSERTING count any single root carries."""
    worst = 0
    for root in _roots():
        total = 0
        for name in _ARTIFACTS:
            path = root / name
            if path.is_file():
                total += _asserting_hits(
                    pattern, path.read_text(encoding="utf-8",
                                            errors="replace"))
        worst = max(worst, total)
    return worst


def _count(pattern, blobs):
    rx = re.compile(pattern, re.I)
    return sum(len(rx.findall(text)) for text in blobs.values())


@pytest.mark.parametrize("claim", sorted(_CLAIMS))
def test_a_stale_model_claim_never_rises(claim):
    _corpus()                      # skips cleanly when nothing is built
    found = _worst_root(_CLAIMS[claim])
    assert found <= _CEILINGS[claim], (
        "published occurrences of the stale claim %r rose to %d, above the "
        "measured ceiling of %d. The engine runs (b_2, b_3) = (12, 43) with "
        "n_gen = b_2/4; prose asserting otherwise contradicts the values "
        "printed beside it. New wording must be generated from the live "
        "seed, not typed." % (claim, found, _CEILINGS[claim])
    )


def test_the_audit_actually_reads_the_artifacts():
    """A ratchet over an empty corpus would pass forever."""
    blobs = _corpus()
    assert sum(len(t) for t in blobs.values()) > 100_000, (
        "the artifacts are too small to be real; this audit is measuring "
        "nothing"
    )


def test_the_adopted_values_are_present_at_all():
    """The other side: the CURRENT model must appear, not merely the old
    one be absent. A build that published neither would pass every ceiling.
    """
    blobs = _corpus()
    assert _count(r"b_?3\s*=\s*43|b₃\s*=\s*43", blobs) > 0, (
        "no artifact states b_3 = 43; the adopted seed does not reach the "
        "published prose at all"
    )
    assert _count(r"b_?2\s*/\s*4|b₂/4", blobs) > 0, (
        "no artifact states the ruled generation route n_gen = b_2/4"
    )


def test_the_ceilings_are_documented_as_a_debt_not_a_target():
    """The count is not supposed to be zero, and the reason is on file."""
    assert __doc__ is not None
    assert "may only fall" in __doc__
    assert "label it" in __doc__ or "LABEL it" in __doc__
