"""The artifact search order is pinned, including WHY each position is there.

WHY THIS EXISTS
---------------
The order used to live in fifty-three copy-pasted blocks, so it was not
really an order at all -- it was fifty-three orders that happened to agree,
and any one of them could drift without anything noticing. Worse, the order
itself was wrong off the author's machine: a Windows absolute path sat ahead
of the repo-local tree and resolved to nothing on POSIX, which is how the
remote environment reached 846 skips.

An order nobody asserts is a convention, not a contract. This makes it a
contract, and it fails in both directions: a reordering fails here, and so
does a root going missing.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from tests._artifact_search import (
    LEGACY_WINDOWS_ROOT,
    artifact,
    autogen_dir,
    provenance,
    search_roots,
)


def test_the_roles_and_their_order_are_exactly_these(monkeypatch):
    """With no override set, three implicit roots in a fixed order."""
    monkeypatch.delenv("METAPHYSICA_OUT", raising=False)
    assert [role for role, _p in search_roots()] == [
        "repo-local",
        "sibling-checkout",
        "legacy-windows",
    ]


def test_an_explicit_out_dir_outranks_every_implicit_root(monkeypatch, tmp_path):
    """METAPHYSICA_OUT is an instruction, not a hint."""
    monkeypatch.setenv("METAPHYSICA_OUT", str(tmp_path))
    roles = [role for role, _p in search_roots()]
    assert roles[0] == "METAPHYSICA_OUT"
    assert search_roots()[0][1] == tmp_path


def test_repo_local_outranks_the_sibling_checkout(monkeypatch):
    """The standing directive: repo-local FIRST among the implicit roots.

    Safe only because resolution is per-file; see the companion test below.
    """
    monkeypatch.delenv("METAPHYSICA_OUT", raising=False)
    roots = dict(search_roots())
    order = [role for role, _p in search_roots()]
    assert order.index("repo-local") < order.index("sibling-checkout")
    assert roots["repo-local"] == Path(__file__).resolve().parents[1]


def test_the_sibling_is_addressed_portably_not_by_a_drive_letter(monkeypatch):
    """The published checkout must be reachable off Windows.

    This is the defect that produced the skips: ``Path("H:/Github/...")`` is
    a RELATIVE path on POSIX, so it named a directory that could not exist
    and the sibling was unreachable by any candidate.
    """
    monkeypatch.delenv("METAPHYSICA_OUT", raising=False)
    roots = dict(search_roots())
    sibling = roots["sibling-checkout"]
    assert sibling.is_absolute()
    assert sibling.name == "PrincipiaMetaphysica"
    assert sibling.parent == Path(__file__).resolve().parents[2]


def test_the_legacy_windows_path_is_last_and_still_present(monkeypatch):
    """Kept, and kept LAST. Removing it would change the author's machine."""
    monkeypatch.delenv("METAPHYSICA_OUT", raising=False)
    order = search_roots()
    assert order[-1][0] == "legacy-windows"
    assert order[-1][1] == LEGACY_WINDOWS_ROOT


def test_resolution_is_per_file_so_a_partial_tree_cannot_shadow(
        monkeypatch, tmp_path):
    """The fix that makes repo-local-first safe.

    A root that exists but lacks the requested file must NOT win. This is
    defect 3 from the helper's docstring -- a partial build-scratch tree
    shadowing a complete published one, which is how a strategy-C gate came
    to look for a per-gate certificate inside a directory holding only
    per-category ones.
    """
    early = tmp_path / "early"
    (early / "AutoGenerated").mkdir(parents=True)
    (early / "AutoGenerated" / "present.json").write_text("{}", encoding="utf-8")

    monkeypatch.setenv("METAPHYSICA_OUT", str(early))
    # A file the early root HAS: the early root supplies it.
    assert provenance("present.json") == "METAPHYSICA_OUT"
    # A file the early root LACKS: the search must continue past it rather
    # than stop at a directory that merely exists.
    assert provenance("present.json") != provenance("parameters.json") or \
        artifact("parameters.json") is None


def test_an_empty_autogen_directory_does_not_win(monkeypatch, tmp_path):
    """An empty directory exists and answers nothing."""
    empty = tmp_path / "empty"
    (empty / "AutoGenerated").mkdir(parents=True)
    monkeypatch.setenv("METAPHYSICA_OUT", str(empty))
    found = autogen_dir()
    assert found is None or found != empty / "AutoGenerated"


def test_the_helper_never_skips_on_its_callers_behalf():
    """A helper that skips makes every caller's failure mode invisible.

    Checked by importing the module and looking for a bound `pytest` name
    rather than by grepping the source, which matched the docstring
    explaining the rule -- a text search over a file that documents its own
    prohibition cannot tell the rule from the explanation.
    """
    from tests import _artifact_search

    assert not hasattr(_artifact_search, "pytest"), (
        "the search helper imported pytest; a helper that can skip hides "
        "every caller's failure mode"
    )
    assert _artifact_search.artifact("no_such_artifact_xyz.json") is None


# ── the order, exercised against the real tree ──────────────────────────────


def test_the_published_parameters_are_reachable_in_this_environment():
    """The end-to-end claim: a real artifact resolves from wherever it is.

    Not a tautology -- before the fix this returned None in the remote
    environment whenever the repo-local tree had not been built, because no
    candidate named the sibling checkout.
    """
    found = artifact("parameters.json")
    if found is None:
        pytest.skip("no parameters.json in any root; run the build first")
    payload = json.loads(found.read_text(encoding="utf-8"))
    assert payload.get("parameters"), found


# ── the suite must not write through to the published checkout ──────────────


def test_the_test_session_never_targets_the_published_checkout():
    """METAPHYSICA_OUT is the WRITE target as well as the read hint.

    conftest points it at a staged COPY of the artifacts rather than at the
    published tree, because generator write paths honour the same variable the
    read paths do. The first version of that conftest pointed it straight at
    the sibling checkout, and one full suite run silently removed FOURTEEN
    rows from the published `parameters.json`.

    A test run that degrades the published build is worse than the skips the
    change was made to fix, so the guarantee is asserted rather than assumed.
    """
    raw = os.environ.get("METAPHYSICA_OUT")
    if not raw:
        pytest.skip("METAPHYSICA_OUT not set in this session")

    target = Path(raw).resolve()
    repo = Path(__file__).resolve().parents[1]
    published = (repo.parent / "PrincipiaMetaphysica").resolve()

    if not published.exists() or published == repo:
        pytest.skip("no separate published checkout in this environment")
    assert target != published, (
        "the suite is writing into the published checkout at %s -- a "
        "generator run from any test will degrade the shipped artifacts"
        % published
    )
