"""An ambiguous short name must not be bound to one of its meanings.

WHY THIS EXISTS
---------------
``_build_context`` gave EML expressions three ways to name a parameter: the
full path, the last two components, and the bare last component. The bare
form was bound with ``ctx.setdefault(parts[-1], value)``, so when several
parameters shared a last component the FIRST one encountered won and the
rest were discarded -- silently, in dictionary insertion order.

Twenty-four names collide, and they are not obscure. Most are a PREDICTION
colliding with its own ANCHOR:

    theta_13        nufit 8.58        vs  geometry 8.54
    theta_23        nufit 42.2        vs  geometry 49
    sin2_theta_W    pdg 0.23122       vs  geometry 0.231905
    wa              desi -0.86        vs  geometry -0.204
    M_PLANCK        reduced 2.435e18  vs  full 1.22089e19

An ``eml_description`` written against the bare name ``theta_13`` evaluated
against whichever of the two came first. Bound to the anchor, a prediction
was compared against the very measurement it is supposed to predict and
agreed trivially -- the fake-pass pattern, reached by dictionary ordering
rather than by any decision. The ``M_PLANCK`` pair is the reduced and full
Planck masses, a factor of sqrt(8 pi) apart; this repository has already had
to correct a 97.65-sigma error caused by exactly that confusion.

A short alias is now bound only when every parameter claiming it agrees.
Otherwise the name stays unbound and the expression must qualify it. The
cost is real and was expected: 35 rows moved out of AGREE into
DISAGREE_MISSING_CTX and the strict agreement rate fell from about 0.79 to
0.68. Those agreements were resting on an arbitrary choice, so the lower
number is the true one.

An ambiguous name is worse than an absent one, because an absent one fails
loudly.
"""
from __future__ import annotations

import json
import math
import os
from pathlib import Path

import pytest

from metaphysica.generators.eml_param_crosscheck import _build_context


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for path in candidates:
        if path.is_dir() and (path / "parameters.json").is_file():
            return path
    pytest.skip("no parameters.json found; run the build first")


def _params() -> dict:
    return json.loads((_autogen() / "parameters.json")
                      .read_text(encoding="utf-8"))["parameters"]


def _collisions(params):
    """Short names claimed by parameters that disagree on the value."""
    seen, clashing = {}, set()
    for path, entry in params.items():
        try:
            value = float(entry.get("value"))
        except (TypeError, ValueError):
            continue
        if not math.isfinite(value):
            continue
        key = path.split(".")[-1]
        if key in seen:
            a, b = seen[key], value
            scale = max(abs(a), abs(b)) or 1.0
            if abs(a - b) / scale > 1e-9:
                clashing.add(key)
        else:
            seen[key] = value
    return clashing


def test_no_ambiguous_short_name_is_bound():
    """The central invariant."""
    params = _params()
    context = _build_context(params)
    bound_but_ambiguous = sorted(_collisions(params) & set(context))
    assert not bound_but_ambiguous, (
        f"these short names have conflicting values yet are bound to one of "
        f"them: {bound_but_ambiguous}. An expression using one would "
        f"evaluate against whichever parameter came first in dict order."
    )


def test_the_prediction_vs_anchor_pairs_stay_unbound():
    """Named explicitly, because these are the dangerous ones."""
    context = _build_context(_params())
    for name in ("theta_13", "theta_23", "sin2_theta_W", "M_PLANCK", "wa"):
        assert name not in context, (
            f"{name!r} is bound. It is claimed by both a measurement and a "
            f"prediction of that measurement, so binding it can make a "
            f"prediction agree with its own anchor."
        )


def test_qualified_names_still_resolve():
    """The fix must not make the context useless."""
    context = _build_context(_params())
    for path in ("nufit.theta_13", "geometry.theta_13"):
        assert path in context, f"{path} should still resolve by full path"
    assert context["nufit.theta_13"] != context["geometry.theta_13"], (
        "the two theta_13 values are supposed to differ; if they no longer "
        "do, this test is checking nothing"
    )


def test_unambiguous_short_names_are_still_bound():
    """Only the colliding names are withheld, not every short name."""
    params = _params()
    context = _build_context(params)
    ambiguous = _collisions(params)
    short_names = {p.split(".")[-1] for p in params}
    kept = (short_names - ambiguous) & set(context)
    assert len(kept) > 100, (
        f"only {len(kept)} unambiguous short names survived; the filter has "
        f"become too aggressive and expressions will fail for the wrong "
        f"reason"
    )


def test_the_refused_names_are_published():
    """Silent suppression would be its own version of the same problem."""
    path = _autogen() / "eml_crosscheck.json"
    if not path.is_file():
        pytest.skip("eml_crosscheck.json not present; run the build first")
    report = json.loads(path.read_text(encoding="utf-8"))
    reported = report.get("ambiguous_short_names")
    assert reported, "the report does not say which names were withheld"
    assert "theta_13" in reported
    assert report.get("ambiguous_short_names_note")


def test_the_collision_set_is_recorded_on_the_builder():
    params = _params()
    _build_context(params)
    recorded = set(getattr(_build_context, "ambiguous_names", []))
    assert _collisions(params) <= recorded
