"""b_3 = 24 is published as DERIVED, and it has been refuted as a derivation.

RECORDED, NOT RESOLVED. half_shift_enumeration proves b_3 = 24 is unreachable by
the Joyce (Z/2)^3 construction -- b_3 = 7 + even is always odd -- and fano_tcs
was already recorded as putting b_3 = 24 far below its exhibited 71-155 range.
So neither construction the framework declares can derive it.

Meanwhile particle.b3 and cosmology.b3 ship with status DERIVED.

Relabelling them is a physics ruling: it changes how the theory presents itself,
moves the free-variable count, and makes w_0 = -23/24 and n_gen = 24/8 into
predictions from a stated input. The standing rule is to prepare the evidence and
leave the decision to the author, so nothing is relabelled here.

What this file does instead is make the contradiction impossible to lose. It is
GREEN while the disagreement stands and FAILS when b_3's published status
changes -- at which point the register must be updated to record the ruling. That
is the same staleness-guard pattern as
test_no_theory_uncertainty_in_experimental_slot's _OPEN_RULINGS.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

#: The rows that publish b_3 and the status each currently carries.
_RECORDED_STATUS = {
    "particle.b3": "DERIVED",
    "cosmology.b3": "DERIVED",
}


def _load_params():
    candidates = []
    raw = os.environ.get("PM_SITE_ROOT")
    if raw:
        candidates.append(Path(raw) / "AutoGenerated" / "parameters.json")
    candidates += [
        Path(__file__).resolve().parents[1] / "AutoGenerated" / "parameters.json",
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated/parameters.json"),
    ]
    for path in candidates:
        if path.is_file():
            return json.loads(path.read_text(encoding="utf-8"))["parameters"]
    pytest.skip("parameters.json not available; run the build first")


@pytest.fixture(scope="module")
def params():
    return _load_params()


def test_the_refutation_stands():
    """If this ever fails, the contradiction below has dissolved on its own."""
    from metaphysica.simulations.PM.geometry.half_shift_enumeration import (
        refutation_report,
    )

    report = refutation_report()
    assert report["twisted_24_is_achievable"] is False
    assert report["b3_parity"] == "odd"
    assert "REFUTED" in report["verdict"]


def test_b3_is_still_published_as_derived(params):
    """The contradiction, recorded.

    Fails when the status changes -- which is the point. A change means the
    author has ruled, and the register must say so.
    """
    for path, recorded in _RECORDED_STATUS.items():
        assert path in params, "%s is no longer published" % path
        actual = params[path].get("status")
        assert actual == recorded, (
            "%s status moved from %s to %s. If b_3 has been relabelled following "
            "the refutation, update this file and record the ruling in "
            "docs/OUTSTANDING_ISSUES.md; the free-variable count moves with it."
            % (path, recorded, actual)
        )


def test_the_value_is_still_24(params):
    for path in _RECORDED_STATUS:
        assert params[path].get("value") == 24


def test_b3_is_consumed_so_it_cannot_be_comparison_only(params):
    """It feeds published outputs, so as an input it would be load-bearing."""
    consumers = [k for k, v in params.items()
                 if "b3" in json.dumps(v).lower() and k not in _RECORDED_STATUS]
    assert len(consumers) >= 5, (
        "expected b_3 to feed several published rows; found %d" % len(consumers)
    )


def test_the_contradiction_is_recorded_in_the_register():
    """The evidence must be written down, not only encoded in a test."""
    reg = Path("H:/Github/PrincipiaMetaphysica/docs/OUTSTANDING_ISSUES.md")
    if not reg.is_file():
        pytest.skip("register not available")
    text = reg.read_text(encoding="utf-8", errors="replace")
    assert "REFUTED" in text
    assert "LOAD_BEARING_INPUT" in text
