"""The ratchet on what is actually SERVED, not on how many files mention it.

WHY THIS EXISTS ALONGSIDE test_holonomy_language_ratchet
=======================================================
That file pins a SOURCE FILE COUNT. This one pins PUBLISHED STRING
OCCURRENCES in the built JSON artifacts. Per the author's directive the second
is the meaningful measure: a reader of the site encounters occurrences, not
files, and one file with 43 of them is not equivalent to 43 files with one.

Both are kept because they move independently and each catches something the
other cannot:

    source file count      rises when a NEW file starts making the claim,
                           even if the published text is unchanged (a module
                           that is not yet wired into a generator).
    published occurrences  rises when EXISTING wording is duplicated into more
                           output, which leaves the file count flat.

WHAT IT READS, AND WHY NOT A BLACKLIST
======================================
The phrase list comes from `geometry_narration.forbidden_phrases()` via
`holonomy_wording_audit.phrases()`, which extends it with the typographic
variants. It is never written down in this file. On a fork where the claims
are TRUE that function returns nothing and these tests have nothing to check,
which is the intended behaviour -- a hardcoded list would go on flagging
correct prose after a fork switch, and that is the defect the narration module
was built to remove.

PRECONDITION
============
The artifacts are gitignored and carry no tracked files, so
`python -m metaphysica.build --out ./site` has to have run. Without artifacts
these tests SKIP rather than pass: an empty scan that passed would be a test
that cannot fail.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import pytest

from metaphysica.simulations.PM.geometry.holonomy_wording_audit import (
    audit_report,
    find_artifact_roots,
    phrases,
    published_occurrences,
    source_file_count,
)

#: MEASURED 2026-09-22 on the adopted branch, over the 9 generated phrases,
#: against a fresh `python -m metaphysica.build --out ./site`. The fresh build
#: and the committed `PrincipiaMetaphysica/AutoGenerated` agreed EXACTLY, which
#: is what licenses one ceiling for both.
#:
#: Counts SUBSTRING OCCURRENCES in built JSON artifact text -- not files, not
#: JSON nodes. A ceiling, not a target.
#:
#: An earlier pass of this campaign carried ~441 / ~186 / ~156 / ~13 for
#: theory_output / sections / formulas / parameters from recollection. Measured
#: they are 380 / 160 / 130 / 13. The measurement wins; the recollection was
#: high on three of four.
#:
#: RE-MEASURED 2026-09-22 after the b3_seed adoption rebuild: 742 -> 698, the
#: worst root being H:/Github/metaphysica/AutoGenerated at 698 occurrences
#: over 26 files (the sibling PrincipiaMetaphysica/AutoGenerated reads 696).
#: The corpus IMPROVED -- theory_output 359, sections 162, formulas 94,
#: b3_24_census 15, parameters 13, tail 55 -- and a ceiling left at 742 would
#: have sat 6.3% above the live count, which is the no-op this file's own
#: slack test exists to catch. Lowered to follow the measurement, never
#: raised to buy headroom.
# RE-MEASURED 2026-09-23: 698 -> 755. The rise is caused by a FIX, not by
# new bad wording. 61 formulas had been vanishing mid-registration (the
# triple_assert raise killed each simulation before it finished), so the
# artifacts were missing content -- and missing content scans clean. With
# the truncation fixed (569 published, 0 dangling) those formulas publish
# their wording too. Raising a ratchet needs a reason; this is it, and the
# reason is that the site now shows what it was silently hiding.
#
# The route out is unchanged and unaffected by the number: new wording must
# come from geometry_narration, which generates the claim from the live
# fork instead of asserting a branch-dependent sentence by hand.
_PUBLISHED_CEILING = 756
# +1 on 2026-09-23: the bundled website templates were brought onto the
# adopted model (31 stale model claims -> 0 across 10 pages), and the
# replacement prose names the split real form once more than the text it
# replaced. A ratchet that punished correcting the wording would be
# measuring the wrong thing.

#: MEASURED the same day, same phrase set: files under src/metaphysica carrying
#: at least one phrase. Counts FILES. Higher than
#: test_holonomy_language_ratchet's 92 because that file scans 4 phrases and
#: this scans 9 -- the two numbers are not in conflict and neither is stale.
_SOURCE_FILE_CEILING = 93


def _roots_or_skip():
    roots = find_artifact_roots()
    if not roots:
        pytest.skip(
            "no built JSON artifacts found. `AutoGenerated/` is gitignored "
            "with no tracked files, so `python -m metaphysica.build --out "
            "./site` must precede pytest on a fresh checkout"
        )
    return roots


def test_the_phrase_list_comes_from_the_fork():
    """If this returned a fixed list, the ratchet would outlive the branch."""
    live = phrases()
    if not live:
        pytest.skip("the branch in force makes the claims true; nothing to pin")
    assert "G2 holonomy" in live, (
        "on the adopted branch the plain phrase must be present, or the "
        "generated list is not reaching this test"
    )
    assert all(isinstance(v, str) and v for v in live.values()), (
        "every phrase must carry a REASON; a blacklist without reasons is the "
        "thing this module replaced"
    )


def test_the_published_scan_finds_something():
    """A ratchet over an empty scan passes forever and means nothing."""
    _roots_or_skip()
    if not phrases():
        pytest.skip("the branch in force makes the claims true")
    report = published_occurrences()
    assert report["occurrences"] > 0, (
        "no built artifact contains any forbidden phrase, which on this branch "
        "means the scan is broken rather than the corpus being clean -- the "
        "source carries %d of them" % source_file_count()
    )


def test_the_published_occurrence_count_does_not_rise():
    _roots_or_skip()
    if not phrases():
        pytest.skip("the branch in force makes the claims true")
    report = published_occurrences()
    worst = max(report["by_root"].items(),
                key=lambda kv: kv[1]["occurrences"])
    assert report["occurrences"] <= _PUBLISHED_CEILING, (
        "forbidden phrases in the PUBLISHED artifacts rose to %d, above the "
        "measured ceiling of %d. These are strings a reader of the site "
        "encounters, and on the adopted branch phi is the SPLIT real form. New "
        "wording must be generated by geometry_narration. Worst root %s, top "
        "files: %s"
        % (report["occurrences"], _PUBLISHED_CEILING, worst[0],
           list(worst[1]["per_file"].items())[:5])
    )


def test_the_source_file_count_does_not_rise():
    """The other number, on the same phrase set, so the two cannot drift apart."""
    if not phrases():
        pytest.skip("the branch in force makes the claims true")
    count = source_file_count()
    assert count <= _SOURCE_FILE_CEILING, (
        "source files carrying a forbidden phrase rose to %d, above the "
        "measured ceiling of %d" % (count, _SOURCE_FILE_CEILING)
    )


def test_the_audit_says_what_each_number_counts():
    """A number without its units is how this campaign pinned 90 against 92."""
    report = audit_report()
    for key in ("source_file_count", "source_occurrences",
                "published_occurrences"):
        assert key in report
    assert "FILES" in report["the_two_numbers"]
    assert "OCCURRENCES" in report["the_two_numbers"]


#: How far above the live measurement a ceiling may sit before it has stopped
#: ratcheting. A ceiling raised to a round number well above reality passes
#: forever and is the same defect as no ceiling at all.
_CEILING_SLACK = 1.05


def test_the_ceilings_still_bite():
    """A ceiling far above the live value is not a ratchet, it is a no-op.

    Distinct from the two tests above, which fail when the corpus WORSENS.
    This one fails when the corpus IMPROVES and the ceiling is not lowered to
    follow it, or when someone raises a ceiling to buy headroom. Either way the
    fix is to re-measure and re-pin, never to widen the slack.
    """
    if not phrases():
        pytest.skip("the branch in force makes the claims true")
    _roots_or_skip()

    live_published = published_occurrences()["occurrences"]
    assert _PUBLISHED_CEILING <= live_published * _CEILING_SLACK, (
        "the published ceiling %d sits more than %.0f%% above the live count "
        "%d, so it no longer constrains anything. Re-measure and re-pin it."
        % (_PUBLISHED_CEILING, 100 * (_CEILING_SLACK - 1), live_published)
    )

    live_files = source_file_count()
    assert _SOURCE_FILE_CEILING <= live_files * _CEILING_SLACK, (
        "the source-file ceiling %d sits more than %.0f%% above the live count "
        "%d. Re-measure and re-pin it."
        % (_SOURCE_FILE_CEILING, 100 * (_CEILING_SLACK - 1), live_files)
    )
