"""One predicted value must not be published as both a PASS and a failure.

WHAT THIS CAUGHT
----------------
Scanning the validation report for values scored under more than one path
turned up three groups, and two of them were defects:

1. ``yukawa.epsilon_fn`` = 0.22313 scored **PASS** against 0.225 while
   ``ckm.V_us`` -- the identical value against the identical PDG row --
   scored **2.791 sigma TENSION**. The Yukawa row declared
   ``experimental_bound`` and ``bound_source`` but no ``uncertainty``, so
   sigma came out ``None`` and the verdict defaulted to PASS. A comparison
   with no uncertainty cannot fail.

2. ``cosmology.w0_tzimtzum`` = -0.95833 scored **0.0167 sigma PASS** against
   an anchor of -0.958 +/- 0.02 labelled "DESI_2025". No such measurement
   exists: the datasources carry desi.w0 = -0.752 +/- 0.057 and
   desi.w0_thawing = -0.957 +/- 0.067. The -0.958 +/- 0.02 was the
   framework's own prediction rounded, with an invented uncertainty. It now
   scores 3.62 sigma FAIL, matching ``cosmology.w0_thawing`` for the same
   number.

The third group is REAL PHYSICS and must keep passing: ``s8_pm_predicted``
against Planck and ``s8_pm_vs_lensing`` against KiDS-1000 disagree because
Planck and weak lensing disagree. That is the S8 tension, correctly scored
twice.

So the check cannot simply forbid the pattern. It records the groups that are
legitimate and fails on any new one, which is what distinguishes a physical
tension between two anchors from one prediction quietly scored against
itself.
"""
from __future__ import annotations

import collections
import json
import os
from pathlib import Path

import pytest

#: Groups where one value is scored against genuinely different anchors that
#: disagree in the world, not in the bookkeeping. Keyed by the sorted paths.
_LEGITIMATE = {
    # Planck vs KiDS-1000: this IS the weak-lensing tension.
    ("cosmology.s8_pm_predicted", "cosmology.s8_pm_vs_lensing"),
    # w0 against the DR2 headline vs against the thawing anchor whose
    # attribution established.py records as UNVERIFIED. Author ruling, open
    # in the register: defend the thawing anchor with a citation or withdraw
    # the PASS. Recorded so the contradiction is visible, not silent.
    ("cosmology.w0_derived", "cosmology.w0_thawing", "cosmology.w0_tzimtzum",
     "geometry.w_zero"),
}

_SCORED = {"PASS", "FAIL", "TENSION", "MARGINAL"}
_FAILING = {"FAIL", "TENSION"}


def _rows():
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for c in candidates:
        f = c / "validation_report.json"
        if f.is_file():
            data = json.loads(f.read_text(encoding="utf-8"))["validations"]
            return list(data.values()) if isinstance(data, dict) else data
    pytest.skip("no validation_report.json; run the build first")


def _contradictions():
    groups = collections.defaultdict(list)
    for r in _rows():
        if r.get("verdict") in _SCORED and isinstance(r.get("value"), (int, float)):
            groups[round(float(r["value"]), 10)].append(r)
    out = []
    for _value, rs in groups.items():
        verdicts = {r["verdict"] for r in rs}
        if "PASS" in verdicts and (verdicts & _FAILING):
            out.append(tuple(sorted(r["path"] for r in rs)))
    return out


#: Bound types that compare against a central value, so a residual exists.
#: One-sided bounds are excluded: for an `upper` or `lower` bound sigma is
#: legitimately None, because a margin is not a residual.
_TWO_SIDED = {"measured", "central_value", "two_sided"}


def test_no_scored_row_lacks_an_uncertainty():
    """A PASS with sigma = None is a comparison that cannot fail.

    Eight rows reached PASS this way, because the registry's own
    validation_status short-circuited the sigma check in _verdict.
    quantum_bio.topological_pitch was the clearest: 6.12 against a stated
    13.0, a factor of two out, published as a PASS.
    """
    offenders = [
        r["path"] for r in _rows()
        if r.get("verdict") in _SCORED and r.get("sigma") is None
        and (r.get("bound_type") or "").lower() in _TWO_SIDED
    ]
    assert not offenders, (
        "these rows carry a scoring verdict but no sigma, so the verdict was "
        "reached without a comparison:\n  " + "\n  ".join(sorted(offenders))
    )


def test_no_new_contradictory_scoring():
    """A value published as both PASS and FAIL needs a recorded reason."""
    new = [g for g in _contradictions() if g not in _LEGITIMATE]
    assert not new, (
        "one predicted value is scored as both a PASS and a failure, and the "
        "group is not recorded as a legitimate two-anchor comparison:\n  "
        + "\n  ".join(" / ".join(g) for g in new)
        + "\nEither the anchors genuinely disagree in the world -- add the "
          "group to _LEGITIMATE with the reason -- or one of the rows is "
          "scoring the prediction against itself."
    )


def test_the_recorded_groups_are_still_real():
    """A stale allowance is as bad as a missing check."""
    found = set(_contradictions())
    stale = [g for g in _LEGITIMATE if g not in found]
    assert not stale, (
        "these groups are recorded as legitimate contradictions but no "
        "longer contradict; remove them so the list cannot drift:\n  "
        + "\n  ".join(" / ".join(g) for g in stale)
    )
