"""Ratchet on b3-root coverage of the formula dependency graphs.

WHY THIS EXISTS
---------------
The framework's central claim is that its formulas trace to the single
topological seed b3 = 24. An external advisory proposed a gate that FAILS any
formula whose leaf set lacks b3. That blanket rule is wrong — experimental
anchors (PDG masses, NuFIT angles) legitimately do NOT trace to b3, and
forcing them to would manufacture fake provenance. What is right is a
RATCHET: the measured coverage must never silently regress.

The advisory also quoted "277 of 419 formulas trace to b3". The real numbers
from the live artifacts are pinned below and differ in both directions:

    arithma walk:  366 / 422 b3-rooted, 55 non-rooted, 1 ambiguous
                   ... and the walk ran DEGRADED (arithma_available=false,
                   12 degraded walks) because the optional `arithma` package
                   is not installed — despite arithma 2.0.2 being on PyPI.
    EML walk:      102 / 422 b3-rooted, 320 non-rooted, 6 ambiguous

That second line deserves attention on its own: by the EML walker's
accounting, over three quarters of formulas do NOT trace to the seed. Either
the walker under-detects (likely, given the arithma walker sees 366) or the
"everything from b3" narrative is much weaker than advertised. The ratchet
records both honestly rather than averaging them into comfort.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

_AUTOGEN = [
    Path(__file__).resolve().parents[1] / "AutoGenerated",
    Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
]


def _load(name: str):
    for base in _AUTOGEN:
        p = base / name
        if p.is_file():
            return json.loads(p.read_text(encoding="utf-8"))
    pytest.skip(f"{name} not available; run the build first")


#: Baselines measured 2026-08-24. Direction of the ratchet:
#:   b3_rooted may only grow, non-rooted / ambiguous / degraded may only
#:   shrink. Improving a walker updates these numbers UPWARD deliberately.
#: non_b3_max 55 -> 56 and ambiguous_max 1 -> 0 on 2026-09-05. This is a
#: measurement correction, not a loosening, and the four formulas that moved
#: are named so the change is auditable:
#:
#:   bulk-metric-ratio           ambiguous -> rooted   (gained)
#:   decad3-projection           non       -> rooted   (gained)
#:   chirality-reversal-operator rooted    -> non      (lost)
#:   dead-mans-switch            rooted    -> non      (lost)
#:
#: The two losses are the point. Both declared an input naming no registry
#: parameter, so the walker could not see that edge, skipped it, and reached
#: b3 by another route -- counting them rooted through a dependency that did
#: not exist. Clearing the phantom made the edge real and the walk now
#: terminates honestly. They were never b3-rooted; the old number was
#: inflated by the gap.
#:
#: b3_rooted_min is deliberately NOT lowered: it stays 366, so a genuine
#: loss of coverage still fails. ambiguous_max TIGHTENS to 0.
_ARITHMA_BASELINE = {"total": 422, "b3_rooted_min": 366,
                     "non_b3_max": 56, "ambiguous_max": 0,
                     "degraded_max": 12}
_EML_BASELINE = {"total": 422, "b3_rooted_min": 102,
                 "non_b3_max": 320, "ambiguous_max": 6}


def test_arithma_b3_coverage_never_regresses():
    d = _load("dependency_chains.json")
    assert d["total_formulas"] >= _ARITHMA_BASELINE["total"]
    assert d["b3_rooted_count"] >= _ARITHMA_BASELINE["b3_rooted_min"], (
        f"b3-rooted coverage fell from >= {_ARITHMA_BASELINE['b3_rooted_min']} "
        f"to {d['b3_rooted_count']} — a formula lost its path to the seed"
    )
    assert d["non_b3_rooted_count"] <= _ARITHMA_BASELINE["non_b3_max"]
    assert d["ambiguous_count"] <= _ARITHMA_BASELINE["ambiguous_max"]


def test_arithma_walk_degradation_is_bounded():
    """The walker runs DEGRADED without the optional arithma package.

    arithma 2.0.2 is on PyPI, so this is fixable by installing it — at which
    point degraded_walks drops and this baseline should be tightened to 0.
    Until then the degradation may not grow.
    """
    d = _load("dependency_chains.json")
    assert d["degraded_walks"] <= _ARITHMA_BASELINE["degraded_max"]
    if d.get("arithma_available"):
        assert d["degraded_walks"] == 0, (
            "arithma is installed but walks still degrade — tighten the "
            "baseline and investigate"
        )


def test_eml_b3_coverage_never_regresses():
    """The uncomfortable one: the EML walker roots only 102 of 422.

    Recorded at its real value, not smoothed. If the walker improves, raise
    the floor; if coverage falls further, that is a finding, not noise.
    """
    d = _load("eml_dependency_chains.json")
    assert d["b3_rooted_count"] >= _EML_BASELINE["b3_rooted_min"]
    assert d["non_b3_rooted_count"] <= _EML_BASELINE["non_b3_max"]
    assert d["ambiguous_count"] <= _EML_BASELINE["ambiguous_max"]


def test_the_two_walkers_disagree_and_that_is_recorded():
    """366 vs 102 b3-rooted from the same 422 formulas is itself a defect.

    Two instruments measuring the same property disagree by 3.6x. This test
    pins the disagreement so it cannot be quietly forgotten; resolving WHICH
    walker is right (or fixing both) removes this test deliberately.
    """
    a = _load("dependency_chains.json")
    e = _load("eml_dependency_chains.json")
    assert a["total_formulas"] == e["total_formulas"], "walkers see different formula sets"
    ratio = a["b3_rooted_count"] / max(e["b3_rooted_count"], 1)
    assert ratio > 3.0, (
        "the walkers now agree within 3x — good; replace this test with a "
        "consistency assertion and tighten both baselines"
    )
