"""An uncited theory uncertainty may not decide a verdict.

WHY THIS EXISTS
---------------
The registry folds a declared theory uncertainty into sigma in quadrature:

    sigma = |predicted - measured| / sqrt(sigma_exp^2 + sigma_theory^2)

Legitimate for a genuinely tree-level prediction. But four rows carried a
buffer 23x to 2333x the experimental uncertainty, which discards the
measurement's precision entirely:

    geometry.G_F_matched          57.1 sigma -> 0.024   PASS
    higgs.m_higgs_pred            41.6 sigma -> 1.14    MARGINAL
    geometry.T_CMB                18.6 sigma -> 0.79    PASS
    gauge.sin2_theta_w_geometric  17.1 sigma -> 0.68    PASS

Two of those buffers were defined as a PERCENTAGE OF THE VALUE UNDER TEST
("0.12% of G_F", "0.5% of T_CMB value") -- a tolerance proportional to the
answer. None was cited.

The sharpest consequence: gauge.sin2_theta_w_geometric and
constants.sin2_theta_W_pred are the SAME number, 0.23190478152123015. G12
evaluates it with no buffer and reports COMPUTED_FAIL at 17.1 sigma, while
the validation row reported PASS at 0.68 sigma. One prediction, two
published verdicts.

The rule generalises R6 (which converted G12 with no invented buffer) from a
single gate to the whole validation layer: a theory uncertainty may change a
verdict only if it is cited. It does NOT delete theory uncertainty -- ten of
the fifteen rows carrying one are not load-bearing and are untouched.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from metaphysica.generators.generate_validation_certificates import (
    DEFAULT_THEORY_UNCERTAINTY_POLICY,
    _registry_band,
    _theory_uncertainty_is_cited,
)


def _report():
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated" / "validation_report.json")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated/validation_report.json"),
        Path(__file__).resolve().parents[1] / "AutoGenerated" / "validation_report.json",
    ]
    for path in candidates:
        if path.is_file():
            payload = json.loads(path.read_text(encoding="utf-8"))
            if "theory_uncertainty_policy" in payload:
                return payload
    pytest.skip("validation_report.json with a policy block not available")


# ── the rule ────────────────────────────────────────────────────────────────


def test_a_named_source_is_not_a_citation():
    """'geometric_vev_precision' names a category, not a reference."""
    assert _theory_uncertainty_is_cited(
        {"theory_uncertainty_source": "geometric_vev_precision"}
    ) is False
    assert _theory_uncertainty_is_cited({}) is False
    assert _theory_uncertainty_is_cited({"theory_uncertainty_citation": "  "}) is False
    assert _theory_uncertainty_is_cited(
        {"theory_uncertainty_citation": "Degrassi et al., arXiv:1205.6497"}
    ) is True


def test_default_policy_is_cited_only():
    assert DEFAULT_THEORY_UNCERTAINTY_POLICY == "cited_only"


# ── the invariant that caught a bug in this very feature ────────────────────


def test_experimental_only_is_never_more_permissive_than_always():
    """sigma_exp >= sigma_total always, so dropping the buffer cannot help.

    The first implementation banded the experimental sigma with this
    report's <2/<3/<5 scale while the folded verdict carried the registry's
    stricter <1/<2/<3 status. That straddled two conventions and made
    'experimental_only' report MORE passes than the stricter policy --
    arithmetically impossible. This pins the comparison to like-for-like.
    """
    tp = _report()["theory_uncertainty_policy"]
    always = tp["scoreboard_if_always"]
    exp_only = tp["scoreboard_if_experimental_only"]
    assert exp_only.get("PASS", 0) <= always.get("PASS", 0), (
        "dropping a theory uncertainty produced more passes -- the two "
        "scoreboards are being banded on different scales"
    )
    assert exp_only.get("FAIL", 0) >= always.get("FAIL", 0)


def test_registry_band_matches_the_registrys_own_thresholds():
    """PMRegistry.set_param uses <1 PASS, <2 MARGINAL, <3 TENSION, else FAIL."""
    assert _registry_band(0.5) == "PASS"
    assert _registry_band(1.5) == "MARGINAL"
    assert _registry_band(2.5) == "TENSION"
    assert _registry_band(17.1) == "FAIL"
    assert _registry_band(None) == "UNBOUNDED"


# ── what the policy actually does to the live build ─────────────────────────


#: The rows where a theory uncertainty decides the verdict. Pinned as a SET,
#: not a count, so that a row entering or leaving has to be looked at.
#:
#: Four of these were invisible until 2026-09-06. geometric_anchors.run()
#: carried an experimental_references table that wrote the SAME number into
#: experimental_uncertainty and theory_uncertainty:
#:
#:     mu_pe          experimental 2.0     theory 2.0     # "Theory uncertainty"
#:     alpha_inverse  experimental 0.01    theory 0.01    # "Theory uncertainty"
#:
#: Since load_bearing is `v_with_theory != v_exp_only`, equal slots move sigma
#: by only sqrt(2) and almost never cross a band, so load_bearing stayed False
#: and this policy never fired on them. The apparatus was inert for precisely
#: the rows built to need it. With the slots independent -- CODATA's real
#: sigmas are 2.1e-08 and 3.2e-08 -- all four are load-bearing and uncited, and
#: the experimental-only verdict is what gets published.
_LOAD_BEARING = {
    "geometry.eta_baryon",
    "geometry.G_F_matched",
    "geometry.T_CMB",
    "gauge.sin2_theta_w_geometric",
    "higgs.m_higgs_pred",
    # added 2026-09-06, when the duplicated uncertainty slots were separated
    "electromagnetic.alpha_inv",
    "fermion.mass_ratio_proton_electron",
    "geometry.alpha_inverse",
    "geometry.mu_pe",
}


def test_load_bearing_buffers_are_identified_and_none_is_cited():
    tp = _report()["theory_uncertainty_policy"]
    assert tp["n_rows_with_theory_uncertainty"] >= 15
    found = {r["path"] for r in tp["load_bearing_rows"]}
    assert found == _LOAD_BEARING, (
        "the set of rows whose verdict rests on a theory uncertainty changed.\n"
        "  newly load-bearing: %s\n"
        "  no longer:          %s\n"
        "Either a buffer started deciding an answer it did not decide before, "
        "or one stopped. Both are worth reading before this list is updated."
        % (sorted(found - _LOAD_BEARING) or "none",
           sorted(_LOAD_BEARING - found) or "none")
    )
    assert tp["n_load_bearing"] == len(_LOAD_BEARING), tp["load_bearing_rows"]
    assert tp["n_load_bearing_cited"] == 0, (
        "a citation appeared -- verify it is real, then this count may rise"
    )


def test_non_load_bearing_rows_are_untouched():
    """A row not carried by its buffer must score the same either way.

    This used to assert `untouched >= 10`, a census that went stale the moment
    four rows became load-bearing. The count was never the point: what matters
    is that the policy bites ONLY where a buffer decides the answer, which is
    checkable directly and cannot drift.
    """
    report = _report()
    load_bearing = {r["path"] for r in
                    report["theory_uncertainty_policy"]["load_bearing_rows"]}

    demoted = []
    for r in report["validations"]:
        if not r.get("theory_uncertainty") or r["path"] in load_bearing:
            continue
        if r.get("verdict_with_theory") != r.get("verdict_experimental_only"):
            demoted.append(
                "  %s: with_theory=%s experimental_only=%s"
                % (r["path"], r.get("verdict_with_theory"),
                   r.get("verdict_experimental_only"))
            )

    assert not demoted, (
        "these rows carry a theory uncertainty, are not marked load-bearing, "
        "and yet score differently with and without it -- so load_bearing is "
        "not identifying what it claims to:\n" + "\n".join(sorted(demoted))
    )


def test_the_same_number_no_longer_gets_two_verdicts():
    """gauge.sin2_theta_w_geometric vs G12 -- both 0.23190478152123015."""
    rows = {r["path"]: r for r in _report()["validations"]}
    row = rows.get("gauge.sin2_theta_w_geometric")
    if row is None:
        pytest.skip("row not present")
    assert row["verdict"] == "FAIL", (
        "the validation row disagrees with G12, which reports COMPUTED_FAIL "
        "on the identical value"
    )
    assert row["sigma_experimental_only"] == pytest.approx(17.1195, abs=1e-3)


def test_all_three_scoreboards_are_published():
    """The guard against shopping for the flattering policy.

    Every alternative is visible beside the active one, so a reader can see
    what the choice costs without rebuilding.
    """
    tp = _report()["theory_uncertainty_policy"]
    for key in ("scoreboard_if_always", "scoreboard_if_experimental_only"):
        assert tp[key], f"{key} missing"
    assert tp["active"] and tp["rule"]


def test_every_load_bearing_row_reports_both_sigmas():
    for row in _report()["theory_uncertainty_policy"]["load_bearing_rows"]:
        assert row["sigma_with_theory"] is not None
        assert row["sigma_experimental_only"] is not None
        assert row["verdict_with_theory"] != row["verdict_experimental_only"]
