"""Tests for the bibliography audit.

WHY THIS EXISTS
---------------
reference_check.json verified that formula IDS resolve; nothing checked the
bibliography itself. Two defects had accumulated behind that gap: 228 of 230
entries are cited by nothing, and 22 titles are duplicated across 66 ids
(Planck 2018 VI appears eleven times under eleven spellings).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from metaphysica.generators.generate_reference_integrity import (
    _normalise_title,
    audit_references,
)


def _write(tmp_path, refs, **extra):
    ag = tmp_path / "AutoGenerated"
    ag.mkdir(parents=True, exist_ok=True)
    (ag / "references.json").write_text(
        json.dumps({"references": refs}), encoding="utf-8"
    )
    for name, blob in extra.items():
        (ag / f"{name}.json").write_text(json.dumps(blob), encoding="utf-8")
    return ag


def test_title_normalisation_collapses_spelling_noise():
    a = _normalise_title("Planck 2018 results. VI. Cosmological parameters")
    b = _normalise_title("planck 2018 Results  VI  cosmological parameters.")
    assert a == b


def test_duplicate_titles_are_detected(tmp_path):
    ag = _write(tmp_path, {
        "planck2018": {"title": "Planck 2018 results. VI.", "url": "u"},
        "planck_2018": {"title": "planck 2018 results VI", "url": "u"},
        "other": {"title": "Something Else", "url": "u"},
    })
    out = audit_references(ag)
    assert out["totals"]["duplicate_titles"] == 1
    assert out["totals"]["entries_in_duplicate_groups"] == 2
    assert {c["id"]: c["status"] for c in out["checks"]}["no_duplicate_titles"] == "FAIL"


def test_a_clean_bibliography_passes(tmp_path):
    """The audit must be able to come out clean, or it says nothing."""
    ag = _write(
        tmp_path,
        {"only": {"title": "A Unique Paper", "arxiv": "1234.5678"}},
        formulas={"f1": {"references": ["only"]}},
    )
    out = audit_references(ag)
    assert out["n_fail"] == 0, out["checks"]
    assert out["totals"]["orphans"] == 0


def test_orphans_are_detected(tmp_path):
    ag = _write(tmp_path, {"unused": {"title": "Nobody Cites Me", "url": "u"}},
                formulas={"f1": {"latex": "x"}})
    out = audit_references(ag)
    assert out["totals"]["orphans"] == 1
    assert "unused" in out["orphans"]


def test_source_simulation_does_not_count_as_a_citation(tmp_path):
    """Provenance is not citation.

    Every entry records which module registered it, so treating that as a
    citation would make the check vacuous -- it would pass for all 230 while
    no claim pointed at any paper.
    """
    ag = _write(tmp_path,
                {"r": {"title": "T", "url": "u", "source_simulation": "sim_x"}},
                formulas={"f1": {"latex": "x"}})
    out = audit_references(ag)
    assert out["totals"]["orphans"] == 1


def test_entry_without_any_identifier_fails(tmp_path):
    ag = _write(tmp_path, {"vague": {"title": "No Way To Find This"}})
    out = audit_references(ag)
    assert out["totals"]["without_identifier"] == 1
    assert {c["id"]: c["status"] for c in out["checks"]}["every_reference_is_identifiable"] == "FAIL"


def test_missing_bibliography_skips_rather_than_fails(tmp_path):
    (tmp_path / "AutoGenerated").mkdir(parents=True)
    assert audit_references(tmp_path / "AutoGenerated")["status"] == "SKIPPED"


def test_caveat_records_the_false_positive_class():
    """Title matching cannot tell a deliberate duplicate from an accident.

    The seven CODATA entries cite one release for seven constants, which is
    defensible; the eleven Planck ids are one paper under inconsistent
    spellings, which is not. The report must not present the raw count as a
    verdict.
    """
    ag = Path("H:/Github/PrincipiaMetaphysica/AutoGenerated")
    if not (ag / "references.json").is_file():
        pytest.skip("live bibliography not available")
    out = audit_references(ag)
    assert "CODATA" in out["duplicate_caveat"]
    assert "not a verdict" in out["duplicate_caveat"]


# ── module-level attribution (the orphan fix) ───────────────────────────────


def test_module_join_attaches_a_modules_own_references():
    """Both sides record source_simulation, so the join invents nothing."""
    from metaphysica.simulations.run_all_simulations import (
        _attach_module_references,
    )

    data = {
        "formulas": {"f1": {"source_simulation": "sim_a"},
                     "f2": {"source_simulation": "sim_b"}},
        "parameters": {"p1": {"source_simulation": "sim_a"}},
        "references": [
            {"id": "r_a", "source_simulation": "sim_a"},
            {"id": "r_b", "source_simulation": "sim_b"},
        ],
    }
    _attach_module_references(data)
    assert data["formulas"]["f1"]["references"] == ["r_a"]
    assert data["formulas"]["f2"]["references"] == ["r_b"]
    assert data["parameters"]["p1"]["references"] == ["r_a"]


def test_explicit_references_are_never_overwritten():
    """A simulation that does the finer-grained work must keep it."""
    from metaphysica.simulations.run_all_simulations import (
        _attach_module_references,
    )

    data = {
        "formulas": {"f1": {"source_simulation": "sim_a",
                            "references": ["hand_picked"]}},
        "references": [{"id": "r_a", "source_simulation": "sim_a"}],
    }
    _attach_module_references(data)
    assert data["formulas"]["f1"]["references"] == ["hand_picked"]
    assert data["formulas"]["f1"]["references_are_module_level"] is False


def test_module_level_attribution_is_flagged_as_such():
    """The weaker claim must be labelled, not passed off as per-claim
    sourcing. 'This formula comes from a module that declared these papers'
    is not 'this paper proves this line'."""
    from metaphysica.simulations.run_all_simulations import (
        _attach_module_references,
    )

    data = {
        "formulas": {"f1": {"source_simulation": "sim_a"}},
        "references": [{"id": "r_a", "source_simulation": "sim_a"}],
    }
    _attach_module_references(data)
    assert data["formulas"]["f1"]["references_are_module_level"] is True


def test_a_module_with_no_references_gets_an_empty_list_not_a_flag():
    from metaphysica.simulations.run_all_simulations import (
        _attach_module_references,
    )

    data = {"formulas": {"f1": {"source_simulation": "lonely"}},
            "references": [{"id": "r_a", "source_simulation": "other"}]}
    _attach_module_references(data)
    assert data["formulas"]["f1"]["references"] == []
    assert data["formulas"]["f1"]["references_are_module_level"] is False


def test_shipped_bibliography_has_no_orphans():
    """The requirement: every reference is cited by something."""
    ag = Path("H:/Github/PrincipiaMetaphysica/AutoGenerated")
    if not (ag / "references.json").is_file():
        pytest.skip("live bibliography not available")
    out = audit_references(ag)
    assert out["totals"]["orphans"] == 0, out["orphans"][:10]
