"""Ratchet on b3-root coverage of the formula dependency graphs.

WHY THIS EXISTS
---------------
The framework's central claim is that its formulas trace to the single
topological seed b3 = 24. An external advisory proposed a gate that FAILS any
formula whose leaf set lacks b3. That blanket rule is wrong — experimental
anchors (PDG masses, NuFIT angles) legitimately do NOT trace to b3, and
forcing them to would manufacture fake provenance. What is right is a
RATCHET: the measured coverage must never silently regress.

The advisory also quoted "277 of 419 formulas trace to b3". The real numbers
from the live artifacts are pinned below and differ in both directions:

    arithma walk:  366 / 422 b3-rooted, 55 non-rooted, 1 ambiguous
                   ... and the walk ran DEGRADED (arithma_available=false,
                   12 degraded walks) because the optional `arithma` package
                   is not installed — despite arithma 2.0.2 being on PyPI.
    EML walk:      102 / 422 b3-rooted, 320 non-rooted, 6 ambiguous

That second line deserves attention on its own: by the EML walker's
accounting, over three quarters of formulas do NOT trace to the seed. Either
the walker under-detects (likely, given the arithma walker sees 366) or the
"everything from b3" narrative is much weaker than advertised. The ratchet
records both honestly rather than averaging them into comfort.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

_AUTOGEN = [
    Path(__file__).resolve().parents[1] / "AutoGenerated",
    Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
]


def _load(name: str):
    for base in _AUTOGEN:
        p = base / name
        if p.is_file():
            return json.loads(p.read_text(encoding="utf-8"))
    pytest.skip(f"{name} not available; run the build first")


#: Baselines measured 2026-08-24. Direction of the ratchet:
#:   b3_rooted may only grow, non-rooted / ambiguous / degraded may only
#:   shrink. Improving a walker updates these numbers UPWARD deliberately.
#: non_b3_max 55 -> 56 and ambiguous_max 1 -> 0 on 2026-09-05. This is a
#: measurement correction, not a loosening, and the four formulas that moved
#: are named so the change is auditable:
#:
#:   bulk-metric-ratio           ambiguous -> rooted   (gained)
#:   decad3-projection           non       -> rooted   (gained)
#:   chirality-reversal-operator rooted    -> non      (lost)
#:   dead-mans-switch            rooted    -> non      (lost)
#:
#: The two losses are the point. Both declared an input naming no registry
#: parameter, so the walker could not see that edge, skipped it, and reached
#: b3 by another route -- counting them rooted through a dependency that did
#: not exist. Clearing the phantom made the edge real and the walk now
#: terminates honestly. They were never b3-rooted; the old number was
#: inflated by the gap.
#:
#: b3_rooted_min is deliberately NOT lowered: it stays 366, so a genuine
#: loss of coverage still fails. ambiguous_max TIGHTENS to 0.
# 2026-09-06 (a): b3_rooted_min 366 -> 350, non_b3_max 56 -> 72. A CORRECTION
# TO THE MEASUREMENT. Until then ZERO of 422 formulas carried an arithma tree
# -- every arithma expression failed to serialise, so all walks fell through
# to a substring scan of the human-written `latex` field, where prose was
# enough to count as rooted. With arithma fixed, 17 formulas turned out to
# contain no b3 whatever (generation-theorem is 3 x 8; c37cp-strong-cp-lock,
# gauge-unification-sum, cabibbo-angle-geometric and
# higgs-effective-potential-v19 are each a literal 0).
#
# 2026-09-06 (b): total 422 -> 569, b3_rooted_min 350 -> 381,
# non_b3_max 72 -> 180, ambiguous_max 0 -> 8, degraded_max 12 -> 49.
# NINE simulation modules had never run: each was imported inside
# `except ImportError` under a class name with a `V19` suffix the module
# never defined, so the run summary said "85 simulations, all passed" while
# lagrangian_master, the three sector_complete derivations and appendices
# M/N/O/P/Q were silently absent. Reviving them added 147 formulas.
#
# The ceilings rise because there is MORE CONTENT, not because coverage got
# worse: b3-rooted went UP, 350 -> 381. The revived formulas are largely
# tensor-calculus and vielbein constructions that legitimately do not reach
# b3 and legitimately carry no symbolic tree, which is what moves non_b3 and
# degraded. Both floors still bite: below 381 rooted is a regression.
_ARITHMA_BASELINE = {"total": 569, "b3_rooted_min": 381,
                     "non_b3_max": 180, "ambiguous_max": 8,
                     "degraded_max": 49}
_EML_BASELINE = {"total": 569, "b3_rooted_min": 109,
                 "non_b3_max": 460, "ambiguous_max": 7}


def test_arithma_b3_coverage_never_regresses():
    d = _load("dependency_chains.json")
    assert d["total_formulas"] >= _ARITHMA_BASELINE["total"]
    assert d["b3_rooted_count"] >= _ARITHMA_BASELINE["b3_rooted_min"], (
        f"b3-rooted coverage fell from >= {_ARITHMA_BASELINE['b3_rooted_min']} "
        f"to {d['b3_rooted_count']} — a formula lost its path to the seed"
    )
    assert d["non_b3_rooted_count"] <= _ARITHMA_BASELINE["non_b3_max"]
    assert d["ambiguous_count"] <= _ARITHMA_BASELINE["ambiguous_max"]


#: Formulas that supply NO symbolic tree in either dialect, so the walker has
#: nothing to walk and must fall back to scanning a latex string. Every one is
#: a Jordan-algebra, E7/E8 or Clifford construction whose content is a
#: reduction over an indexed family -- the same quantities withheld from the
#: EML cross-check, for the same reason.
_NO_SYMBOLIC_TREE_COUNT = 49  # see test_arithma_walk_degradation_is_bounded


def test_arithma_walk_degradation_is_bounded():
    """Degradation is caused by MISSING EXPRESSIONS, not a missing package.

    This test used to say the opposite -- "arithma 2.0.2 is on PyPI, so this
    is fixable by installing it, at which point degraded_walks drops to 0" --
    and it never fired, because the artifact recorded
    ``arithma_available: false`` and the assertion sat behind that flag.

    Both halves were wrong. arithma imports fine; what was failing was every
    arithma EXPRESSION, so no formula carried a tree and all 422 walks
    degraded to a substring scan of human-written latex. With that fixed 169
    formulas now carry real trees, and the 12 that still degrade are the 12
    that declare no symbolic expression in either dialect. Installing a
    package cannot change that; writing expressions for them can.
    """
    d = _load("dependency_chains.json")
    assert d["degraded_walks"] <= _ARITHMA_BASELINE["degraded_max"]
    # Degradation must equal the number of formulas that supply NO symbolic
    # tree in either dialect -- computed from the artifacts, not listed by
    # name, so it stays true as the formula set grows. If a formula that HAS
    # a tree is degrading, that points at the walker rather than the set.
    formulas = _load("formulas.json")["formulas"]
    eml = _load("eml_trees.json").get("f", {})
    treeless = sum(
        1 for fid, f in formulas.items()
        if not f.get("arithma_compact")
        and not isinstance(eml.get(fid, {}).get("c"), list)
    )
    assert d["degraded_walks"] == treeless, (
        f"{d['degraded_walks']} walks degrade but {treeless} formulas lack a "
        f"symbolic tree in either dialect"
    )


def test_eml_b3_coverage_never_regresses():
    """The uncomfortable one: the EML walker roots only 102 of 422.

    Recorded at its real value, not smoothed. If the walker improves, raise
    the floor; if coverage falls further, that is a finding, not noise.
    """
    d = _load("eml_dependency_chains.json")
    assert d["b3_rooted_count"] >= _EML_BASELINE["b3_rooted_min"]
    assert d["non_b3_rooted_count"] <= _EML_BASELINE["non_b3_max"]
    assert d["ambiguous_count"] <= _EML_BASELINE["ambiguous_max"]


def test_the_two_walkers_disagree_and_that_is_recorded():
    """366 vs 102 b3-rooted from the same 422 formulas is itself a defect.

    Two instruments measuring the same property disagree by 3.6x. This test
    pins the disagreement so it cannot be quietly forgotten; resolving WHICH
    walker is right (or fixing both) removes this test deliberately.
    """
    a = _load("dependency_chains.json")
    e = _load("eml_dependency_chains.json")
    assert a["total_formulas"] == e["total_formulas"], "walkers see different formula sets"
    ratio = a["b3_rooted_count"] / max(e["b3_rooted_count"], 1)
    assert ratio > 3.0, (
        "the walkers now agree within 3x — good; replace this test with a "
        "consistency assertion and tighten both baselines"
    )
