"""Statuses must survive export, and inputs must not be labelled derivations.

WHY THIS EXISTS
---------------
Two faults that compounded each other.

**The anchors were all labelled geometric.** ``geometric_anchors.py``
registered every entry of ``get_all_anchors()`` with ``status="GEOMETRIC"``,
``"fundamental": True`` and ``"tuning_free": True``, without exception. Some
of those anchors are raw experimental input: the three NuFIT mixing angles,
the SH0ES H0, the Planck matter density, the DESI w0, and two openly
phenomenological fit values. All shipped as tuning-free consequences of
b3 = 24.

The correct per-parameter classification *already existed* — a
``measured_params`` set in ``geometric_anchors_core.py``, complete with a
docstring explaining exactly this distinction. It sat inside a method named
``register_to_registry`` that is not defined on the class and is called from
nowhere. The whole block was dead code, so the right answer was in the
repository the entire time and never executed. It is now
``MEASURED_ANCHORS`` at module level, consulted by the loop that actually
runs.

``theta_13`` is the sharpest case, because it is also a published headline:
the property returns a hardcoded ``8.54`` whose own comment at line 1450 of
that module reads ``8.54 deg (NuFIT)``, and its ``eml_description`` is the
bare literal ``eml_scalar(8.54)``. Binding it to the NuFIT anchor would have
scored the anchor against itself.

**The export laundered the fix away.** The status whitelist in
``run_all_simulations.py`` rewrites any status it does not explicitly name
to ``DERIVED``. It already carried a comment about FALSIFIED having been
laundered that way — the label survived in the description while the
machine-readable status lied — and ``MEASURED`` walked into the identical
trap. The upstream fix was correct and invisible: metadata changed,
``status`` did not.

The failure mode is silence in both cases, which is why these are pinned.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for path in candidates:
        if path.is_dir() and (path / "parameters.json").is_file():
            return path
    pytest.skip("no parameters.json found; run the build first")


def _params() -> dict:
    return json.loads((_autogen() / "parameters.json")
                      .read_text(encoding="utf-8"))["parameters"]


# -- the classification itself ----------------------------------------------


def test_measured_anchors_is_non_empty_and_contains_the_inputs():
    from metaphysica.simulations.PM.geometry.geometric_anchors_core import (
        MEASURED_ANCHORS,
    )

    assert MEASURED_ANCHORS, "the set is empty; nothing would be classified"
    for name in ("theta_12", "theta_13", "theta_23", "H0_local",
                 "Omega_matter", "w0_observed_DESI"):
        assert name in MEASURED_ANCHORS, (
            f"{name} is raw experimental input but is not listed"
        )


def test_the_dead_block_and_the_live_loop_share_one_source():
    """They must not be able to drift apart again."""
    import inspect

    from metaphysica.simulations.PM.geometry import geometric_anchors_core as core

    src = inspect.getsource(core)
    assert "measured_params = MEASURED_ANCHORS" in src, (
        "the in-method set has been re-inlined; it can now diverge from the "
        "module-level one the live loop reads"
    )


# -- what actually ships -----------------------------------------------------


def test_measured_anchors_ship_as_measured():
    """The export whitelist must not launder the label back to DERIVED."""
    from metaphysica.simulations.PM.geometry.geometric_anchors_core import (
        MEASURED_ANCHORS,
    )

    params = _params()
    wrong = []
    for name in sorted(MEASURED_ANCHORS):
        entry = params.get(f"geometry.{name}")
        if entry is None:
            continue
        if entry.get("status") != "MEASURED":
            wrong.append((name, entry.get("status")))
    assert not wrong, (
        f"experimental inputs shipped under the wrong status: {wrong}. The "
        f"export whitelist rewrites any status it does not name."
    )


def test_no_experimental_input_claims_to_be_tuning_free():
    """tuning_free on a NuFIT value is a claim about the wrong thing."""
    from metaphysica.simulations.PM.geometry.geometric_anchors_core import (
        MEASURED_ANCHORS,
    )

    params = _params()
    offenders = []
    for name in sorted(MEASURED_ANCHORS):
        entry = params.get(f"geometry.{name}")
        if entry is None:
            continue
        meta = entry.get("metadata") or {}
        if meta.get("tuning_free") or meta.get("fundamental"):
            offenders.append(name)
    assert not offenders, (
        f"these are experimental inputs but are marked tuning_free or "
        f"fundamental: {offenders}"
    )


def test_theta_13_is_not_scored_against_its_own_anchor():
    """It restates nufit.theta_13, so scoring it would measure nothing."""
    params = _params()
    entry = params.get("geometry.theta_13")
    if entry is None:
        pytest.skip("geometry.theta_13 absent")
    assert entry.get("experimental_value") is None, (
        "geometry.theta_13 has acquired an experimental binding. Its value "
        "is a hardcoded copy of the NuFIT central value, so any sigma "
        "computed for it is the anchor compared with itself."
    )
    assert entry.get("status") == "MEASURED"


# -- the whitelist's silent-rewrite property ---------------------------------


def test_every_declared_status_survives_export():
    """An unnamed status is silently rewritten, which hides the omission.

    The set began as a seven-name inline tuple while 27 distinct statuses
    were declared across the tree, so 20 were being rewritten to DERIVED --
    an epistemic UPGRADE applied by accident. FITTED (19 parameters),
    ANSATZ (7, including gauge.su2_sin2_theta_W), SPECULATIVE (3),
    PLAUSIBLE (6) and TOPOLOGY_CANDIDATE (1) all shipped as derivations.

    This walks the AST for every Parameter(status=...) literal rather than
    listing names, so a newly introduced status cannot slip past.
    """
    import ast as _ast
    import pathlib

    from metaphysica.simulations.run_all_simulations import (
        PRESERVED_PARAMETER_STATUSES,
    )

    root = pathlib.Path(__file__).resolve().parents[1] / "src" / "metaphysica"
    if not root.is_dir():
        pytest.skip("source tree not available")
    declared = set()
    for path in root.rglob("*.py"):
        try:
            tree = _ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in _ast.walk(tree):
            if (isinstance(node, _ast.Call)
                    and getattr(node.func, "id", "") == "Parameter"):
                for kw in node.keywords:
                    if kw.arg == "status" and isinstance(kw.value, _ast.Constant):
                        declared.add(kw.value.value)
    missing = sorted(declared - PRESERVED_PARAMETER_STATUSES)
    assert not missing, (
        f"these statuses are declared in the tree but not preserved at "
        f"export, so they ship as DERIVED: {missing}"
    )


def test_no_shipped_status_was_invented_at_export():
    """Catches statuses set at runtime rather than as a literal."""
    from metaphysica.simulations.run_all_simulations import (
        PRESERVED_PARAMETER_STATUSES,
    )

    shipped = {v.get("status") for v in _params().values()} - {None}
    unknown = sorted(shipped - PRESERVED_PARAMETER_STATUSES)
    assert not unknown, (
        f"the artifact carries statuses the export does not preserve: "
        f"{unknown}. They survived by some other route and would be "
        f"rewritten if they ever passed through the whitelist branch."
    )


def test_falsified_still_survives_export():
    """The original instance of this bug, kept pinned."""
    params = _params()
    falsified = [k for k, v in params.items()
                 if v.get("status") == "FALSIFIED"]
    assert falsified, (
        "no FALSIFIED rows reached the artifact -- the whitelist is "
        "laundering them again"
    )
