"""A declared pass-through must actually be one.

WHAT THIS CAUGHT
----------------
``cosmology.H0_early_normalized`` = 67.4000176934533 scored **0.0000 sigma
PASS** against Planck 67.4 +/- 0.5 with status PREDICTED. The agreement is
arithmetic, not physics::

    H(z)              = H0_eff(z) * E(z)
    H0_early_inferred = H(z_cmb) / E(z_cmb)        <- the SAME E(z)
                      = H0_eff(z_cmb)
                      = H0_late*f + H0_early*(1 - f)

E(z) cancels identically, so Omega_m, Omega_de and z_cmb cannot affect the
result at all. With f(1100) = 3.1371e-06 that is

    67.4 + 3.1371e-06 * (73.04 - 67.4) = 67.4000176934533

reproducing the published value to all thirteen digits, where 67.4 is
``geometry.H0_early`` -- an INPUT to the interpolation. The "verification"
confirmed that 67.4 equals 67.4.

``CERTIFICATES.py`` already carried a CIRCULARITY WARNING saying exactly this
on the gate that consumes the row. The honesty lived in that docstring and in
neither of the two places the published artifact reads.

WHY A DECLARATION RATHER THAN A WIDER TOLERANCE
The generator already demotes round-trips through ``_is_roundtrip_identity``,
but its bound is a principled 1e-10 -- machine precision, floating-point
noise. This row's relative deviation is 2.6e-07, so it escaped. Widening
1e-10 until it were caught would be tuning a tolerance until it produced the
verdict wanted, which is the defect being removed, and it would sweep in
genuine near misses.

The pass-through is provable algebraically, so it is *declared*:
``Parameter(passthrough_of="geometry.H0_early")``. This test is the other half
of that bargain -- a declaration nobody checks is just a comment. It verifies
the named input really is reproduced, so the claim cannot quietly become
false, and it verifies the declaration is honoured in the published verdict.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

#: A pass-through may carry a small genuine admixture -- H0_early_normalized
#: mixes in f(1100) = 3.1e-06 of H0_late -- but if it has drifted this far
#: from the input it names, it is no longer returning it and the declaration
#: is wrong.
_MAX_REL_DRIFT = 1e-3


def _autogen() -> Path:
    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    for c in candidates:
        if (c / "validation_report.json").is_file():
            return c
    pytest.skip("no AutoGenerated build; run the build first")


def _rows():
    data = json.loads(
        (_autogen() / "validation_report.json").read_text(encoding="utf-8")
    )["validations"]
    return list(data.values()) if isinstance(data, dict) else data


def _parameters():
    f = _autogen() / "parameters.json"
    if not f.is_file():
        pytest.skip("parameters.json not built")
    data = json.loads(f.read_text(encoding="utf-8"))
    if isinstance(data, dict) and "parameters" in data:
        data = data["parameters"]
    if isinstance(data, dict):
        return data
    return {r["path"]: r for r in data if isinstance(r, dict) and "path" in r}


def _declared():
    out = {}
    for path, rec in _parameters().items():
        meta = rec.get("metadata") or {}
        target = meta.get("passthrough_of")
        if target:
            out[path] = target
    return out


def test_at_least_one_passthrough_is_declared():
    """The mechanism must reach real data, or the checks below pass vacuously.

    This whole file exists because a check that cannot fire is the bug class
    under repair; it would be a poor joke to add another one.
    """
    declared = _declared()
    assert declared, (
        "no parameter declares passthrough_of. Either the field stopped "
        "propagating from Parameter into registry metadata, or the "
        "declaration on cosmology.H0_early_normalized was dropped -- in "
        "which case that row is scoring against its own input again."
    )
    assert "cosmology.H0_early_normalized" in declared, sorted(declared)


def test_a_declared_passthrough_reproduces_the_input_it_names():
    """The declaration has to be true, not merely present."""
    params = _parameters()
    wrong = []
    for path, target in _declared().items():
        rec = params.get(path) or {}
        src = params.get(target)
        if src is None:
            wrong.append("  %s names %s, which is not a registry path"
                         % (path, target))
            continue
        v, s = rec.get("value"), src.get("value")
        if not isinstance(v, (int, float)) or not isinstance(s, (int, float)):
            continue
        if s == 0:
            continue
        drift = abs(float(v) - float(s)) / abs(float(s))
        if drift > _MAX_REL_DRIFT:
            wrong.append(
                "  %s = %r declares passthrough_of=%s = %r, but differs by "
                "%.3g relative -- it is not returning that input"
                % (path, v, target, s, drift)
            )
    assert not wrong, (
        "a declared pass-through does not reproduce the input it names:\n"
        + "\n".join(sorted(wrong))
    )


def test_a_declared_passthrough_is_not_scored():
    """Returning an input must not be published as agreement with it."""
    declared = _declared()
    scored = [
        "  %s: verdict=%s sigma=%s against %s"
        % (r["path"], r.get("verdict"), r.get("sigma"),
           r.get("experimental_source"))
        for r in _rows()
        if r.get("path") in declared
        and r.get("verdict") in {"PASS", "FAIL", "TENSION", "MARGINAL"}
    ]
    assert not scored, (
        "these rows declare that they return one of their own inputs, and "
        "are still published with a scoring verdict against it:\n"
        + "\n".join(sorted(scored))
        + "\nA value handed to the derivation is not evidence for it."
    )
