"""Every optional simulation import must actually resolve.

WHY THIS EXISTS
---------------
``run_all_simulations`` registers each optional simulation as::

    try:
        from ...some_module import SomeClass
        SOME_FLAG = True
    except ImportError:
        SOME_FLAG = False

which cannot distinguish "this module is genuinely absent" from "the class
name is misspelled". On 2026-09-06 a sweep found **nine** modules disabled by
the second case. Every one asked for a class with a ``V19`` suffix the module
never defined:

    lagrangian_master              LagrangianMasterDerivationV19
    gauge_sector_complete          GaugeSectorCompleteV19
    matter_sector_complete         MatterSectorCompleteV19
    cosmology_sector_complete      CosmologySectorCompleteV19
    appendix_m_tensor_calc         AppendixMTensorCalcV19
    appendix_n_vielbein            AppendixNVielbeinV19
    appendix_o_kk_reduction        AppendixOKKReductionV19
    appendix_p_g2_holonomy         AppendixPG2HolonomyV19
    appendix_q_index_theorem       AppendixQIndexTheoremV19

The run summary reported "85 simulations, all passed" the entire time. The
absence surfaced only indirectly: ``g2_holonomy.b2`` was missing from the
registry while ``topology.b2 = 4`` sat beside it, which is what led to
Appendix P and then to the other eight.

Three of the nine then failed on ``required_inputs`` naming registry paths
that do not exist -- ``constants.M_STAR``, ``gauge.alpha_gut``,
``geometry.sophian_modulus``, ``geometry.barbelo_modulus``. Those are the
same phantom-path class the formula audit already tracks, but
``required_inputs`` is not walked by it, so they had never been seen.

This test resolves each import for real, so a rename fails here rather than
quietly shrinking the run.
"""
from __future__ import annotations

import ast
import importlib
from pathlib import Path

import pytest

_RUNNER = (Path(__file__).resolve().parents[1] / "src" / "metaphysica"
           / "simulations" / "run_all_simulations.py")

#: Audit helpers rather than simulations; they live outside the package and
#: are legitimately optional.
_NOT_SIMULATIONS = {"ValueContextAuditor", "GhostLiteralScanner"}


def _guarded_imports():
    """Yield (module, name) for each `try: from X import Y / except ImportError`."""
    tree = ast.parse(_RUNNER.read_text(encoding="utf-8"))
    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Try):
            continue
        if not any(
            isinstance(h.type, ast.Name) and h.type.id == "ImportError"
            for h in node.handlers
        ):
            continue
        for stmt in node.body:
            if isinstance(stmt, ast.ImportFrom) and stmt.module:
                for alias in stmt.names:
                    found.append((stmt.module, alias.name))
    return found


def test_the_scan_finds_the_guarded_imports():
    """If this returns nothing the test below is vacuous."""
    assert len(_guarded_imports()) >= 40


def test_every_guarded_simulation_import_resolves():
    """A misspelled class silently removes a simulation from the run."""
    broken = []
    for module, name in _guarded_imports():
        if name in _NOT_SIMULATIONS:
            continue
        try:
            mod = importlib.import_module(module)
        except ImportError:
            continue  # genuinely optional dependency
        if not hasattr(mod, name):
            broken.append(f"{module} has no {name}")
    assert not broken, (
        "these imports are swallowed by `except ImportError`, so the "
        "simulation is dropped from the run and the summary still says "
        "everything passed:\n  " + "\n  ".join(broken)
    )


def test_required_inputs_name_real_registry_paths():
    """`required_inputs` is not covered by the formula phantom-path audit.

    Three revived modules declared four paths that exist nowhere. The formula
    audit walks `input_params`/`output_params` and never sees these, so they
    can rot indefinitely while the module is disabled.
    """
    import json
    import os

    raw = os.environ.get("METAPHYSICA_OUT")
    candidates = []
    if raw:
        candidates.append(Path(raw) / "AutoGenerated")
    candidates += [
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated"),
        Path(__file__).resolve().parents[1] / "AutoGenerated",
    ]
    params_file = next(
        (c / "parameters.json" for c in candidates
         if (c / "parameters.json").is_file()), None)
    if params_file is None:
        pytest.skip("no parameters.json; run the build first")
    known = set(json.loads(params_file.read_text(encoding="utf-8"))["parameters"])

    from metaphysica.simulations.PM.derivations import (  # noqa: F401
        cosmology_sector_complete, gauge_sector_complete, lagrangian_master,
    )

    offenders = []
    for module in (lagrangian_master, gauge_sector_complete,
                   cosmology_sector_complete):
        for obj_name in dir(module):
            obj = getattr(module, obj_name)
            if not isinstance(obj, type) or not hasattr(obj, "required_inputs"):
                continue
            try:
                needed = obj().required_inputs
            except Exception:
                continue
            if not isinstance(needed, (list, tuple)):
                continue
            for path in needed:
                if path not in known:
                    offenders.append(f"{module.__name__}.{obj_name}: {path}")
    assert not offenders, (
        "required_inputs naming paths no registry holds:\n  "
        + "\n  ".join(sorted(set(offenders)))
    )
