"""metaphysica — Speculative G₂-manifold theoretical physics model.

Research status
---------------
**Principia Metaphysica is a speculative theoretical model. It has not
been peer-reviewed and is not scientifically validated.** All
derivations, predictions, and "closures" produced by this package are
candidate proposals awaiting experimental confirmation and independent
expert review. The package is intended for exploration and research
purposes only; no output represents established scientific fact.

Overview
--------
The package bundles three things:

* the simulation engine (under :mod:`metaphysica.simulations`) — proposes
  candidate derivations for ~125 physical constants from G₂ topology
  plus a small number of seeds;
* the generators (under :mod:`metaphysica.generators`) that turn those
  simulation outputs into JSON, JS, HTML and plot artefacts;
* the website templates (under :mod:`metaphysica.website`) — the static
  HTML / CSS / JS files that render the model in a browser.

The :func:`build` entry point composes all three: it runs the sims,
runs every generator, and copies the bundled website assets into a
user-supplied output directory.

Public datasheet API
--------------------
:func:`Get` is the EML-stack-uniform name for "give me the datasheet for
this thing". It dispatches by name kind — quark vs physics constant —
and returns a JSON-serialisable dict (or string with ``as_json=True``).

>>> import metaphysica
>>> metaphysica.Get('Up')['Mass_MeVc2']           # 2.16
>>> metaphysica.Get('Top')['pm_prediction']['phi_scaling_N']   # 0
>>> metaphysica.Get('m_planck')['value']          # 2.435e18

Available namespaces:

* ``metaphysica.list_quarks()``     — 12 names (6 SM + 6 anti)
* ``metaphysica.list_constants()``  — ~35 curated physics constants
                                       (any flat parameters.json key works too)

Quick start (build pipeline)
----------------------------
>>> from metaphysica import build
>>> from pathlib import Path
>>> build(out_dir=Path("./site"))   # populates ./site/ with a full website

Or from the shell::

    metaphysica-build --out ./site
"""
from __future__ import annotations

from typing import Any, Dict, Union

__version__ = "2.2.1"
__author__ = "Andrew Keith Watts"

# Companion-app launcher — `metaphysica.Launch()` finds/clones metaphysica-app and runs it.
from metaphysica._launcher import launch as Launch


# ── Optional Rust acceleration ───────────────────────────────────────────────
# The Rust core (``metaphysica._physica_core``, built from
# ``rust/physica_core/`` via maturin) is strictly opt-in — see the
# README's "Optional Rust acceleration" section for build instructions.
# When the extension is missing (the default slim install) we transparently
# fall back to the pure-Python implementation, so importing this module is
# always safe.
# Rust dispatch is wired via _dispatch.py. _HAS_RUST re-exported for inspection.
from metaphysica._dispatch import _HAS_RUST, _native  # noqa: F401


# ── Build pipeline ───────────────────────────────────────────────────────────
# Heavy import deferred to first call so `import metaphysica` stays cheap.

def build(out_dir=None, *, fast: bool = False, skip_sims: bool = False, only=None) -> int:
    """Run the full simulation + generation pipeline into *out_dir*.

    Returns 0 on success, non-zero on any step's failure (matching the
    failing step's exit code).
    """
    from metaphysica.build import build as _build
    from metaphysica._catalog import set_last_build_dir
    from pathlib import Path as _Path

    # First-time import of the ``metaphysica.build`` SUBMODULE above makes
    # the import machinery bind that module object over this wrapper on the
    # package namespace (parent setattr happens after submodule exec). Rebind
    # the wrapper so ``metaphysica.build`` stays callable for later callers —
    # without this, any call to build() breaks the public API for the rest
    # of the process.
    globals()["build"] = _build_wrapper

    rc = _build(out_dir=out_dir, fast=fast, skip_sims=skip_sims, only=only)
    # On success, plumb the build target through to the catalog so
    # subsequent ``metaphysica.get()`` calls see the freshly-built
    # registries without requiring the user to also set METAPHYSICA_OUT.
    if rc == 0:
        target = _Path(out_dir).resolve() if out_dir is not None else _Path.cwd().resolve()
        set_last_build_dir(target)
    return rc


# Stable reference to the wrapper for the rebind inside build() above.
_build_wrapper = build


def run_all(out_dir=None, *, quiet: bool = False) -> int:
    """Run just the simulation suite (no HTML/PDF generation) into *out_dir*.

    Thin subprocess wrapper around
    ``python -m metaphysica.simulations.run_all_simulations`` that sets the
    ``METAPHYSICA_OUT`` env-var contract so the simulations write their
    ``AutoGenerated/*.json`` outputs into the requested directory. This is
    the lightweight entry point used by tests, the Phase H sprint smoke
    tests, and external callers that want sim outputs without the full
    website/PDF pipeline.

    Parameters
    ----------
    out_dir : str | Path | None
        Output directory. Created if missing. Defaults to the current
        working directory.
    quiet : bool, default False
        Pass ``--quiet`` to the underlying runner.

    Returns
    -------
    int
        The runner's exit code (0 on success).
    """
    import os
    import subprocess
    import sys
    from pathlib import Path

    target = Path(out_dir).resolve() if out_dir is not None else Path.cwd().resolve()
    target.mkdir(parents=True, exist_ok=True)
    (target / "AutoGenerated").mkdir(exist_ok=True)

    env = os.environ.copy()
    env["METAPHYSICA_OUT"] = str(target)

    cmd = [sys.executable, "-m", "metaphysica.simulations.run_all_simulations"]
    if quiet:
        cmd.append("--quiet")

    proc = subprocess.run(cmd, cwd=str(target), env=env, check=False)
    return proc.returncode


# ── Datasheet API (Get + listings) ───────────────────────────────────────────

def Get(name: str, *, as_json: bool = False) -> Union[Dict[str, Any], str]:
    """Return a JSON datasheet for the named quark or physics constant.

    Dispatch order:

    1. If *name* matches a known quark (case-insensitive: ``"Up"``,
       ``"up"``, ``"u"``, ``"Up Quark"`` all map to up), return the quark
       datasheet (periodica-compatible schema + ``pm_prediction`` block).
    2. Otherwise treat *name* as a physics-constant lookup — Rust backend
       when available, pure-Python fallback otherwise.

    Parameters
    ----------
    name : str
        The quark or constant name to look up.
    as_json : bool, default False
        Return a JSON-encoded string instead of a dict (convenience for
        shell users).

    Raises
    ------
    KeyError
        If *name* matches neither a quark nor a known constant.
    """
    from metaphysica.datasheets.quark import (
        canonical_quark_name, build_quark_datasheet,
    )
    from metaphysica.datasheets.constant import build_constant_datasheet

    # 1. Try quark dispatch first (cheap; in-memory table).
    try:
        canonical_quark_name(name)
        result = build_quark_datasheet(name)
    except KeyError:
        # 2. Fall through to constant — Rust fast path for known registry names.
        if _HAS_RUST and _native is not None:
            fn = getattr(_native, "py_get_constant", None)
            if fn is not None:
                try:
                    result = fn(name)
                    if as_json:
                        import json
                        return json.dumps(result, indent=2, ensure_ascii=False, default=str)
                    return result
                except (KeyError, Exception):
                    pass  # Fall through to Python.
        result = build_constant_datasheet(name)

    if as_json:
        import json
        return json.dumps(result, indent=2, ensure_ascii=False, default=str)
    return result


def list_quarks() -> list:
    """Return all canonical quark names recognised by :func:`Get`.

    Always returns the 12 SM names: 6 quarks + 6 anti-quarks. The Rust
    backend only registers the 6 SM flavours, so we merge with the Python
    :data:`metaphysica.datasheets.quark.KNOWN_QUARKS` table (which carries
    both) to expose the full anti-particle set documented in the module
    docstring.
    """
    from metaphysica.datasheets.quark import KNOWN_QUARKS
    names: set[str] = set(KNOWN_QUARKS)
    if _HAS_RUST and _native is not None:
        fn = getattr(_native, "py_list_quarks", None)
        if fn is not None:
            try:
                names.update(fn())
            except Exception:
                pass
    return sorted(names)


def list_constants() -> list:
    """Return curated physics-constant names recognised by :func:`Get`.

    The Python alias table (``KNOWN_CONSTANTS``) and the Rust
    ``FormulasRegistry`` each carry a different curated slice — the
    Python list focuses on user-friendly aliases (``m_planck``,
    ``alpha_em``, ``V_us`` …), while the Rust registry exposes raw
    pillar / derived keys (``phi``, ``b3``, ``chi_eff`` …). Both are
    valid inputs to :func:`Get`, so this function returns the union.

    Note: this is not exhaustive — any flat key from
    ``AutoGenerated/parameters.json`` (e.g. ``"constants.M_PLANCK"``,
    ``"geometry.higgs_vev"``) is also accepted by :func:`Get`.
    """
    from metaphysica.datasheets.constant import KNOWN_CONSTANTS
    names: set[str] = set(KNOWN_CONSTANTS)
    if _HAS_RUST and _native is not None:
        fn = getattr(_native, "py_list_constants", None)
        if fn is not None:
            try:
                names.update(fn())
            except Exception:
                pass
    return sorted(names)


# ── Unified Get* dispatcher (v2.2.0 Sprint 1) ────────────────────────────────
# Format-aware lookup that works across formulas, parameters, gates,
# certificates, sections, plots, particles, derivations, references, and
# simulations. See _get.py for the dispatcher and _catalog.py for the
# entity index. Format constants (JSON / YAML / LATEX / ...) are
# re-exported so ``metaphysica.PNG`` etc. tab-complete in IDEs.
from metaphysica._get import (  # noqa: E402,F401
    get,
    GetJSON,
    GetYAML,
    GetLaTeX,
    GetArithma,
    GetEML,
    GetFloat,
    GetSVG,
    GetPNG,
    GetPDF,
    GetHTML,
    GetMarkdown,
    JSON, YAML, LATEX, ARITHMA, EML, FLOAT, SVG, PNG, PDF, HTML, MD,
    SUPPORTED_FORMATS,
    get_supported_formats,
)
from metaphysica._catalog import (  # noqa: E402,F401
    reset_catalog,
    list_kind,
    KINDS,
)
from metaphysica._listing import (  # noqa: E402,F401
    list_formulas,
    list_parameters,
    list_gates,
    list_certificates,
    list_sections,
    list_plots,
    list_derivations,
    list_references,
    list_simulations,
    list_particles,
    list_all,
    iter_kind,
    iter_formulas,
    iter_parameters,
    iter_gates,
    iter_sections,
    iter_plots,
    iter_all,
)
from metaphysica._errors import (  # noqa: E402,F401
    MetaphysicaError,
    MetaphysicaKeyError,
    MetaphysicaAmbiguityError,
    MetaphysicaFormatError,
    MetaphysicaBackendError,
)
from metaphysica._help import help  # noqa: E402,F401


__all__ = [
    "__version__",
    "build",
    "run_all",
    "Get",
    "list_quarks",
    "list_constants",
    "Launch",
    # v2.2.0 Sprint 1 — unified dispatcher
    "get",
    "GetJSON",
    "GetYAML",
    "GetLaTeX",
    "GetArithma",
    "GetEML",
    "GetFloat",
    "GetSVG",
    "GetPNG",
    "GetPDF",
    "GetHTML",
    "GetMarkdown",
    "JSON", "YAML", "LATEX", "ARITHMA", "EML", "FLOAT",
    "SVG", "PNG", "PDF", "HTML", "MD",
    "SUPPORTED_FORMATS",
    "get_supported_formats",
    "list_kind",
    "reset_catalog",
    "KINDS",
    # S5 — per-kind list helpers
    "list_formulas",
    "list_parameters",
    "list_gates",
    "list_certificates",
    "list_sections",
    "list_plots",
    "list_derivations",
    "list_references",
    "list_simulations",
    "list_particles",
    "list_all",
    # S5 — entity iterators (yield EntityRef with payload + source)
    "iter_kind",
    "iter_formulas",
    "iter_parameters",
    "iter_gates",
    "iter_sections",
    "iter_plots",
    "iter_all",
    # Errors
    "MetaphysicaError",
    "MetaphysicaKeyError",
    "MetaphysicaAmbiguityError",
    "MetaphysicaFormatError",
    "MetaphysicaBackendError",
    # S6 — interactive help
    "help",
]
