"""One-stop builder for the Principia Metaphysica static website.

Runs the full simulation pipeline and every downstream JSON / JS / HTML /
plot generator into a chosen output directory. The output directory ends
up with the bundled website assets (``index.html``, ``Pages/``, ``css/``,
``js/``) plus the regenerated ``AutoGenerated/`` JSON tree — i.e. a
self-contained static site ready to serve.

Public API
----------
>>> from metaphysica import build
>>> build(out_dir="./site")             # full build, writes everything into ./site

Console
-------
    metaphysica-build                   # rebuild into the current directory
    metaphysica-build --out ./site      # rebuild into ./site
    metaphysica-build --fast            # skip plot regeneration (faster)
    metaphysica-build --skip-sims       # only re-run downstream generators
    metaphysica-build --only "EML"      # run only steps whose label contains EML
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Optional, Tuple

# (label, argv, is_extra)
#   - core steps run always
#   - extra steps run unless --fast is passed
#   - order matters: each step may depend on outputs of earlier ones
# Steps whose label appears in NON_FATAL exit non-zero only as a diagnostic
# signal (e.g. eml_param_crosscheck reports real disagreements via exit 1
# but still writes its output). The build keeps going past these.
NON_FATAL = {"EML parameter cross-check"}

# Steps that only run when their corresponding opt-in flag is passed.
# Maps step label -> CLI flag name (the build() kwarg uses underscores).
HQ_ONLY = {"Generate high-quality PDF (playwright)": "hq_pdf"}

# Steps that need optional extras → skipped with a friendly message if those
# packages aren't installed. Maps step label -> (pip-extra-name, importable-modules).
OPTIONAL_DEPS = {
    "Run all simulations":              ("sims",  ("eml_spectral",)),
    "Build gates JSON":                 ("sims",  ("eml_spectral",)),
    "Build gate certificates":          ("sims",  ("eml_spectral",)),
    "Build validation statistics":      ("sims",  ("eml_spectral",)),
    "EML parameter cross-check":        ("sims",  ("eml_spectral",)),
    "Pre-render EML operator trees":    ("sims",  ("eml_spectral",)),
    "Pre-render formula multi-format renders": ("sims", ("eml_math",)),
    "Generate all visualization plots": ("plots", ("matplotlib", "pandas")),
    "Generate PDF paper":               ("pdf",   ("xhtml2pdf",)),
    "Generate high-quality PDF (playwright)": ("hq-pdf", ("playwright", "pypdf")),
}


def _optional_deps_available(modules: tuple) -> bool:
    import importlib
    for m in modules:
        try:
            importlib.import_module(m)
        except ImportError:
            return False
    return True

STEPS: List[Tuple[str, List[str], bool]] = [
    # ── Stage 0: copy bundled website templates so the JS loaders have a home ──
    ("Copy bundled website templates", ["__copy_static__"], False),

    # ── Core sim run: produces theory_output, parameters, sections, formulas, refs ──
    ("Run all simulations",
     [sys.executable, "-m", "metaphysica.simulations.run_all_simulations"],
     False),

    # ── Gate certification chain ─────────────────────────────────────────────
    ("Build gates JSON",
     [sys.executable, "-m", "metaphysica.generators.generate_72gates_json"],
     False),
    ("Build gate certificates",
     [sys.executable, "-m", "metaphysica.generators.generate_72_certificates"],
     False),
    ("Build named per-category certificates",
     [sys.executable, "-m", "metaphysica.generators.generate_named_certificates"],
     False),
    ("Build validation statistics",
     [sys.executable, "-m", "metaphysica.generators.generate_statistics"],
     False),

    # ── EML cross-check + tree pre-render ────────────────────────────────────
    ("EML parameter cross-check",
     [sys.executable, "-m", "metaphysica.generators.eml_param_crosscheck"],
     False),
    ("Pre-render EML operator trees",
     [sys.executable, "-m", "metaphysica.generators.generate_eml_trees"],
     False),
    ("Pre-render formula multi-format renders",
     [sys.executable, "-m", "metaphysica.generators.generate_formula_renders"],
     False),
    ("Walk dependency chains back to b3=24 (Arithma)",
     [sys.executable, "-m", "metaphysica.generators.generate_arithma_dependency_walker"],
     False),
    ("Walk dependency chains back to b3=24 (EML)",
     [sys.executable, "-m", "metaphysica.generators.generate_eml_dependency_walker"],
     False),
    ("Scan formulas for triple-track mismatches",
     [sys.executable, "-m", "metaphysica.generators.generate_mismatches"],
     False),

    # ── Sprint 5 #7: ProofLedger — registry-wide proof completeness audit ───
    ("Build proof-completeness ledger",
     [sys.executable, "-m", "metaphysica.generators.generate_proof_completeness"],
     False),

    # ── Sprint T1 #9: Shadow-derivation safeguard ────────────────────────────
    # Cross-checks the registry for any physical observable that has two
    # disagreeing formulas (the n_s / eta_B / H0 class of bug that Sprint T1
    # fixed manually). scripts/ isn't a package so we invoke by path.
    ("Audit shadow derivations across the registry",
     [sys.executable, str(Path(__file__).resolve().parents[2] / "scripts" / "audit_shadow_derivations.py")],
     False),

    # ── Generate quark + constant datasheets (JSON snapshots for Get()) ──────
    ("Generate quark + constant datasheets",
     [sys.executable, "-m", "metaphysica.generators.generate_datasheets"],
     False),

    # ── Frontend artefacts: interactive HTML + JS constants ──────────────────
    ("Generate interactive formula HTML",
     [sys.executable, "-m", "metaphysica.generators.generate_interactive_html"],
     False),
    ("Generate JS constants from parameters",
     [sys.executable, "-m", "metaphysica.generators.generate_js_constants"],
     False),

    # ── Plot regeneration (matplotlib heavy; skip with --fast) ───────────────
    ("Generate all visualization plots",
     [sys.executable, "-m", "metaphysica.generators.all_plots"],
     True),

    # ── Sprint T6 #8: indices that the frontend page loaders fetch ───────────
    # plots-manifest.json is consumed by js/pm-plots-loader.js;
    # simulations-index.json is consumed by Pages/simulations.html +
    # js/pm-simulation-loader.js. Both generators were landed earlier but
    # not wired into the build until T6.8 visual-regression triage caught
    # the fetch-404 on the visualization-index and simulations pages.
    ("Build plots manifest",
     [sys.executable, "-m", "metaphysica.generators.generate_plots_manifest"],
     False),
    ("Build simulations index",
     [sys.executable, "-m", "metaphysica.generators.generate_simulations_index"],
     False),

    # ── PDF paper export (renders bundled HTML pages to a single PDF) ────────
    ("Generate PDF paper",
     [sys.executable, "-m", "metaphysica.generators.generate_pdf_paper"],
     True),

    # ── High-quality PDF via Playwright (Chromium prints the JS-driven pages,
    #    capturing MathJax / dynamic formula renders). Second output alongside
    #    the xhtml2pdf one; gated by --hq-pdf so it's opt-in (~5min full run).
    ("Generate high-quality PDF (playwright)",
     [sys.executable, "-m", "metaphysica.generators.generate_pdf_playwright"],
     True),
]


def _copy_static(out_dir: Path) -> None:
    """Copy bundled website templates (index.html, Pages/, css/, js/) into out_dir."""
    from metaphysica.website import copy_static
    copy_static(out_dir)


def _run(label: str, cmd: List[str], cwd: Path) -> float:
    print(f"\n=== {label} ===")
    if cmd == ["__copy_static__"]:
        print(f"$ python -c 'metaphysica.website.copy_static({cwd!s})'")
        t0 = time.perf_counter()
        _copy_static(cwd)
        return time.perf_counter() - t0
    # Plain-script steps (e.g. dev-time auditors under repo-root scripts/):
    # if the script doesn't exist (likely because this build is running
    # from an installed wheel rather than the source tree), skip cleanly.
    if len(cmd) >= 2 and cmd[1].endswith(".py") and not Path(cmd[1]).exists():
        print(f"  - {label}: SKIPPED (source-only script not present at {cmd[1]})")
        return 0.0
    print(f"$ {' '.join(cmd)}")
    t0 = time.perf_counter()
    # Generators / sims discover the output directory via the METAPHYSICA_OUT
    # env var. cwd is set to out_dir so any legacy `Path("AutoGenerated/...")`
    # references resolve into the right place.
    env = os.environ.copy()
    env["METAPHYSICA_OUT"] = str(cwd)
    subprocess.run(cmd, cwd=cwd, env=env, check=True)
    return time.perf_counter() - t0


def build(
    out_dir: Optional[Path] = None,
    *,
    fast: bool = False,
    skip_sims: bool = False,
    only: Optional[str] = None,
    hq_pdf: bool = False,
) -> int:
    """Run the full simulation + generation pipeline into *out_dir*.

    Returns 0 on success, the failing step's exit code on failure.
    """
    out_dir = Path(out_dir or Path.cwd()).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "AutoGenerated").mkdir(parents=True, exist_ok=True)

    selected = []
    opt_in_flags = {"hq_pdf": hq_pdf}
    for label, cmd, is_extra in STEPS:
        if only:
            if only.lower() not in label.lower():
                continue
        else:
            if skip_sims and label == "Run all simulations":
                continue
            if fast and is_extra:
                continue
            # Opt-in-only steps (e.g. the playwright HQ PDF) are skipped
            # unless their flag is set, even when --fast is off.
            if label in HQ_ONLY and not opt_in_flags.get(HQ_ONLY[label], False):
                continue
        # Skip steps whose optional deps are not installed.
        if label in OPTIONAL_DEPS:
            extra, modules = OPTIONAL_DEPS[label]
            if not _optional_deps_available(modules):
                print(f"  - {label}: SKIPPED (install with `pip install metaphysica[{extra}]`)")
                continue
        selected.append((label, cmd))

    if not selected:
        print("No build steps selected.")
        return 1

    print(f"Build plan: {len(selected)} step(s) -> {out_dir}")
    for label, _ in selected:
        print(f"  - {label}")

    timings = []
    overall = time.perf_counter()
    for label, cmd in selected:
        try:
            elapsed = _run(label, cmd, out_dir)
            timings.append((label, elapsed, "OK"))
        except subprocess.CalledProcessError as exc:
            if label in NON_FATAL:
                timings.append((label, 0.0, f"WARN ({exc.returncode})"))
                print(f"\n*** {label} exited with code {exc.returncode} "
                      "(non-fatal — output may still be partially written)")
                continue
            timings.append((label, 0.0, f"FAILED ({exc.returncode})"))
            print(f"\n*** Build halted: {label} exited with code {exc.returncode}")
            _summarise(timings, time.perf_counter() - overall)
            return exc.returncode
        except Exception as exc:
            timings.append((label, 0.0, "FAILED"))
            print(f"\n*** Build halted: {label} raised {type(exc).__name__}: {exc}")
            _summarise(timings, time.perf_counter() - overall)
            return 1

    _summarise(timings, time.perf_counter() - overall)
    print(f"\nBuild complete. Open {out_dir / 'index.html'} or `cd {out_dir} && python -m http.server 8000`.")
    return 0


def _summarise(timings, total: float) -> None:
    print("\n--- Build summary ---")
    for label, elapsed, status in timings:
        print(f"  {status:14s}  {elapsed:7.1f}s   {label}")
    print(f"  {'TOTAL':14s}  {total:7.1f}s")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="metaphysica-build: regenerate the full static website",
    )
    parser.add_argument("--out", type=Path, default=None,
                        help="output directory (default: current working directory)")
    parser.add_argument("--fast", action="store_true",
                        help="skip plot regeneration")
    parser.add_argument("--skip-sims", action="store_true",
                        help="skip the simulation run; only refresh downstream generators")
    parser.add_argument("--only", metavar="STEP",
                        help="run only the step whose label contains STEP (case-insensitive substring match)")
    parser.add_argument("--hq-pdf", action="store_true", dest="hq_pdf",
                        help="also generate the high-quality playwright-rendered PDF "
                             "(opt-in: ~5min full render, captures MathJax / JS output)")
    args = parser.parse_args()
    return build(out_dir=args.out, fast=args.fast,
                 skip_sims=args.skip_sims, only=args.only,
                 hq_pdf=args.hq_pdf)


if __name__ == "__main__":
    sys.exit(main())
