"""SOURCE vs OUTPUT manifest for the PrincipiaMetaphysica output repository.

PrincipiaMetaphysica becomes a generated-output repo once the cutover lands:
its working tree is overwritten on every ``metaphysica.build(out_dir=...)``
call. This manifest is the contract between the lib and the repo about which
files are off-limits (hand-maintained) versus which are regenerated.

The lists are intentionally short and explicit. Anything not in SOURCE_PATHS
is treated as OUTPUT (the build may freely create, overwrite, or delete it).

Used by:
* :mod:`metaphysica.build` — to skip overwriting SOURCE_PATHS.
* The pre-commit hook installed in the output repo — to warn / refuse on
  edits to OUTPUT_PATHS.
* :func:`metaphysica.website.diff_regenerability` (Phase D.3 verification).
"""
from __future__ import annotations

from pathlib import Path

# Files the lib will NEVER touch. These are hand-maintained in the output
# repo and survive every build. Anyone editing files outside this list in
# the output repo is editing generated content that the next build wipes.
SOURCE_PATHS: tuple[str, ...] = (
    "README.md",
    "LICENSE",
    "CNAME",
    "_redirects",
    ".gitignore",
    ".gitattributes",
    "CLAUDE.md",
    "build.bat",
    "build.py",
    ".github/",
    ".git/",
)

# Top-level paths under the output dir that the build owns end-to-end.
# Listed for documentation and for the pre-commit hook's allow/deny logic.
OUTPUT_PATHS: tuple[str, ...] = (
    "index.html",
    "Pages/",
    "css/",
    "js/",
    "components/",
    "foundations/",
    "images/",
    "AutoGenerated/",
)


def is_source(relpath: str | Path) -> bool:
    """Return True if *relpath* is a hand-maintained source file."""
    p = str(relpath).replace("\\", "/").lstrip("./")
    for src in SOURCE_PATHS:
        if src.endswith("/"):
            if p.startswith(src):
                return True
        elif p == src:
            return True
    return False


def is_output(relpath: str | Path) -> bool:
    """Return True if *relpath* falls under a build-owned output tree."""
    p = str(relpath).replace("\\", "/").lstrip("./")
    for out in OUTPUT_PATHS:
        if out.endswith("/"):
            if p.startswith(out):
                return True
        elif p == out:
            return True
    return False


__all__ = ["SOURCE_PATHS", "OUTPUT_PATHS", "is_source", "is_output"]
