"""
metaphysica.simulations.PM.analysis — Post-processing analysis modules.
========================================================================

This sub-package houses *non-physics* analyses that run on top of the
already-derived FormulasRegistry / PMRegistry. They consume parameters,
formulas, EML trees, and other AutoGenerated artefacts and produce
audit-style reports (proof-completeness ledgers, Bayesian uncertainty
scans, maturity dashboards) for the website and the paper appendices.

Sprint 5 task #7 introduces :mod:`proof_completeness`, the
ProofLedger.  It classifies every registered parameter as

* ``fully_derived``    — an EML operator tree (legacy or v25.0) is on
                         file for this parameter.
* ``numerical_agreement`` — registry holds a value but no EML tree.
* ``fitted``           — legacy markers ``theta_13_*`` / ``delta_CP_*``.
* ``open_tension``     — validation_status is TENSION/FAIL.

…and runs a 1000-sample Gaussian-prior posterior scan (σ = 1 % of value)
to surface a per-parameter uncertainty proxy.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""
from __future__ import annotations

__all__ = [
    "proof_completeness",
]
