#!/usr/bin/env python3
"""
Certificate Dashboard - v16.2 Sterile Model
=============================================

42-light grid visualization of the complete certificate framework:
- 7 Primary Gates (Master Audit)
- 35 Technical Jury (Sub-validation)
- 3 Vaults (Ancestral, Torsion, Residue)

Grid layout: 7 rows x 6 columns = 42 certificates
Color coding: GREEN = PASSED, RED = FAILED, GOLD = PRIMARY GATE

Output: AutoGenerated/plots/certificate_dashboard.png

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.

Dedicated To:
    My Wife: Elizabeth May Watts
    Our Messiah: Jesus Of Nazareth
"""

import numpy as np
from pathlib import Path
from typing import Dict, List, Any, Tuple

try:
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from matplotlib.patches import FancyBboxPatch, Circle, Rectangle
    from matplotlib.collections import PatchCollection
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    print("Warning: matplotlib not available.")

# PM Color palette (sterile model)
PM_COLORS = {
    "passed": "#4ade80",        # Green - passed
    "failed": "#ef4444",        # Red - failed
    "primary": "#ffd43b",       # Gold - primary gate
    "vault_i": "#8b7fff",       # Purple - ancestral vault
    "vault_ii": "#fb923c",      # Orange - torsion vault
    "vault_iii": "#60a5fa",     # Blue - residue vault
    "omega": "#4ade80",         # Green - omega seal
    "bg": "#1a1f3a",
}

# Output directory
OUTPUT_DIR = Path(__file__).parent.parent.parent / "AutoGenerated" / "plots"


class CertificateDashboard:
    """
    Generates the 42-Certificate Dashboard visualization.

    The dashboard shows all 42 certificates in a 7x6 grid with
    color-coded status indicators.
    """

    # The 7 Primary Gates
    PRIMARY_GATES = {
        "C02-R": {"name": "Root Origin", "vault": "I", "position": (0, 0)},
        "C19-T": {"name": "Torsion Lock", "vault": "II", "position": (2, 2)},
        "C44": {"name": "4-Pattern", "vault": "II", "position": (4, 1)},
        "C125": {"name": "Saturation", "vault": "III", "position": (4, 4)},
        "C-ZETA": {"name": "Decay Sync", "vault": "III", "position": (5, 3)},
        "C-EPSILON": {"name": "Bulk Insulation", "vault": "III", "position": (5, 5)},
        "C-OMEGA": {"name": "Terminal State", "vault": "III", "position": (6, 5)},
    }

    # All 42 certificates organized by vault
    VAULT_I = list(range(1, 15))    # C01-C14: Ancestral Vault
    VAULT_II = list(range(15, 29))  # C15-C28: Torsion Vault
    VAULT_III = list(range(29, 43)) # C29-C42: Residue Vault

    # Deprecated certificates (shown differently)
    DEPRECATED = [5, 7, 8, 11, 14, 22, 33]

    @staticmethod
    def setup_style():
        """Configure matplotlib for publication-quality output."""
        if not HAS_MATPLOTLIB:
            return
        plt.rcParams.update({
            'font.family': 'serif',
            'font.size': 10,
            'axes.titlesize': 14,
            'figure.dpi': 150,
            'savefig.dpi': 300,
            'savefig.bbox': 'tight',
        })

    @staticmethod
    def get_certificate_status(cert_num: int) -> Tuple[str, str]:
        """
        Get the status and vault for a certificate.

        Returns:
            Tuple of (status, vault)
        """
        # All certificates pass in sterile model
        status = "PASSED"

        # Check if deprecated
        if cert_num in CertificateDashboard.DEPRECATED:
            status = "DEPRECATED"

        # Determine vault
        if cert_num <= 14:
            vault = "I"
        elif cert_num <= 28:
            vault = "II"
        else:
            vault = "III"

        return status, vault

    @staticmethod
    def is_primary_gate(cert_num: int) -> bool:
        """Check if certificate is a primary gate."""
        # NOTE: 125 here is certificate ID C125, NOT the visible_sector count
        primary_nums = [2, 19, 44, 125]  # Certificate IDs: C02-R, C19-T, C44, C125
        if cert_num == 2:  # C02-R
            return True
        if cert_num == 19:  # C19-T
            return True
        return False

    @staticmethod
    def generate_dashboard():
        """
        Generate the 42-certificate dashboard.

        Returns:
            Path to the saved image, or None if matplotlib unavailable.
        """
        if not HAS_MATPLOTLIB:
            print("Cannot generate visualization: matplotlib not available")
            return None

        CertificateDashboard.setup_style()

        fig, ax = plt.subplots(figsize=(14, 10))
        ax.set_xlim(0, 14)
        ax.set_ylim(0, 10)
        ax.axis('off')

        # Title
        ax.text(7, 9.5, 'The 42 Certificates of Integrity',
                fontsize=16, ha='center', fontweight='bold', color='#1a1a2e')
        ax.text(7, 9.0, 'v16.2 Sterile Model - Appendix F',
                fontsize=11, ha='center', color='#666', style='italic')

        # Grid dimensions
        cols = 6
        rows = 7
        cell_width = 2.0
        cell_height = 1.0
        start_x = 1.0
        start_y = 7.8

        # Draw certificates in grid
        cert_num = 1
        for row in range(rows):
            for col in range(cols):
                if cert_num > 42:
                    break

                x = start_x + col * cell_width
                y = start_y - row * cell_height

                status, vault = CertificateDashboard.get_certificate_status(cert_num)

                # Determine color
                if status == "DEPRECATED":
                    color = '#94a3b8'  # Gray
                    alpha = 0.5
                else:
                    color = PM_COLORS["passed"]
                    alpha = 0.9

                # Check if primary gate
                is_primary = cert_num in [2, 19]
                if cert_num >= 36 and cert_num <= 42:
                    is_primary = True  # C36-C42 are structural

                if is_primary:
                    color = PM_COLORS["primary"]

                # Vault coloring for border
                vault_colors = {
                    "I": PM_COLORS["vault_i"],
                    "II": PM_COLORS["vault_ii"],
                    "III": PM_COLORS["vault_iii"],
                }
                border_color = vault_colors[vault]

                # Draw cell
                rect = FancyBboxPatch(
                    (x, y), cell_width - 0.1, cell_height - 0.1,
                    boxstyle="round,pad=0.02,rounding_size=0.1",
                    facecolor=color, alpha=alpha,
                    edgecolor=border_color, linewidth=2
                )
                ax.add_patch(rect)

                # Certificate label
                if cert_num >= 36:
                    label = f'C{cert_num}'
                else:
                    label = f'C{cert_num:02d}'

                ax.text(x + (cell_width - 0.1) / 2, y + 0.55, label,
                        ha='center', va='center',
                        fontsize=10, fontweight='bold',
                        color='#1a1a2e' if status != "DEPRECATED" else '#666')

                # Status indicator
                status_text = 'PASS' if status == "PASSED" else 'DEP'
                ax.text(x + (cell_width - 0.1) / 2, y + 0.25, status_text,
                        ha='center', va='center',
                        fontsize=8, color='#1a1a2e' if status != "DEPRECATED" else '#888')

                cert_num += 1

        # Draw vault labels
        vault_y = start_y + 0.3
        ax.text(start_x + 1.9, vault_y, 'Vault I (Ancestral)',
                fontsize=10, ha='center', fontweight='bold',
                color=PM_COLORS["vault_i"])
        ax.text(start_x + 5.9, vault_y, 'Vault II (Torsion)',
                fontsize=10, ha='center', fontweight='bold',
                color=PM_COLORS["vault_ii"])
        ax.text(start_x + 9.9, vault_y, 'Vault III (Residue)',
                fontsize=10, ha='center', fontweight='bold',
                color=PM_COLORS["vault_iii"])

        # Draw legend
        legend_x = 0.3
        legend_y = 0.8

        # Passed
        rect = Rectangle((legend_x, legend_y), 0.3, 0.2,
                          facecolor=PM_COLORS["passed"], edgecolor='#1a1a2e')
        ax.add_patch(rect)
        ax.text(legend_x + 0.4, legend_y + 0.1, 'Passed (35)',
                fontsize=9, va='center')

        # Primary
        rect = Rectangle((legend_x + 2, legend_y), 0.3, 0.2,
                          facecolor=PM_COLORS["primary"], edgecolor='#1a1a2e')
        ax.add_patch(rect)
        ax.text(legend_x + 2.4, legend_y + 0.1, 'Primary Gate (7)',
                fontsize=9, va='center')

        # Deprecated
        rect = Rectangle((legend_x + 5, legend_y), 0.3, 0.2,
                          facecolor='#94a3b8', alpha=0.5, edgecolor='#1a1a2e')
        ax.add_patch(rect)
        ax.text(legend_x + 5.4, legend_y + 0.1, 'Deprecated (7)',
                fontsize=9, va='center')

        # Omega Seal status
        seal_box = FancyBboxPatch(
            (10, 0.3), 3.5, 0.8,
            boxstyle="round,pad=0.1,rounding_size=0.2",
            facecolor=PM_COLORS["omega"], alpha=0.9,
            edgecolor='#1a1a2e', linewidth=2
        )
        ax.add_patch(seal_box)
        ax.text(11.75, 0.7, 'OMEGA SEAL', fontsize=12, ha='center',
                fontweight='bold', color='#1a1a2e')
        ax.text(11.75, 0.45, 'ENGAGED (42/42)', fontsize=10, ha='center',
                color='#1a1a2e')

        # Summary box
        summary_text = (
            "STERILE AUDIT SUMMARY\n"
            "━━━━━━━━━━━━━━━━━━━━━━\n"
            "Vault I:  14 certs (C01-C14)\n"
            "Vault II: 14 certs (C15-C28)\n"
            "Vault III: 14 certs (C29-C42)\n"
            "━━━━━━━━━━━━━━━━━━━━━━\n"
            "Active: 35 | Deprecated: 7\n"
            "Pass Rate: 100%"
        )
        props = dict(boxstyle='round,pad=0.5', facecolor='white',
                     edgecolor=PM_COLORS['vault_i'], alpha=0.95, linewidth=2)
        ax.text(0.02, 0.02, summary_text, transform=ax.transAxes, fontsize=9,
                verticalalignment='bottom', horizontalalignment='left',
                bbox=props, family='monospace')

        plt.tight_layout()

        # Save
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = OUTPUT_DIR / "certificate_dashboard.png"
        plt.savefig(output_path, dpi=300, facecolor='white', edgecolor='none')
        plt.close()

        print(f"Generated: {output_path}")
        return output_path

    @staticmethod
    def generate_primary_gates_focus():
        """
        Generate a focused view of the 7 Primary Gates.

        Shows detailed information about each master audit gate.
        """
        if not HAS_MATPLOTLIB:
            return None

        CertificateDashboard.setup_style()

        fig, ax = plt.subplots(figsize=(12, 8))
        ax.set_xlim(0, 12)
        ax.set_ylim(0, 8)
        ax.axis('off')

        # Title
        ax.text(6, 7.5, 'The 7 Primary Gates',
                fontsize=16, ha='center', fontweight='bold', color='#1a1a2e')
        ax.text(6, 7.0, 'Master Audit Checkpoints - v16.2 Sterile Model',
                fontsize=11, ha='center', color='#666', style='italic')

        # Gate definitions with positions
        gates = [
            {"id": "C02-R", "name": "Root Origin", "desc": "288 Roots", "x": 1, "y": 5.5},
            {"id": "C19-T", "name": "Torsion Lock", "desc": "24 Pins", "x": 4, "y": 5.5},
            {"id": "C44", "name": "4-Pattern", "desc": "4×6 Matrix", "x": 7, "y": 5.5},
            {"id": "C125", "name": "Saturation", "desc": "125 Nodes", "x": 10, "y": 5.5},
            {"id": "C-ZETA", "name": "Decay Sync", "desc": "Entropy γ", "x": 2.5, "y": 3},
            {"id": "C-EPSILON", "name": "Bulk Insulation", "desc": "Brane Gap", "x": 5.5, "y": 3},
            {"id": "C-OMEGA", "name": "Terminal State", "desc": "3 Basins", "x": 8.5, "y": 3},
        ]

        for gate in gates:
            # Draw gate box
            rect = FancyBboxPatch(
                (gate["x"] - 1.2, gate["y"] - 0.8), 2.4, 1.6,
                boxstyle="round,pad=0.1,rounding_size=0.3",
                facecolor=PM_COLORS["primary"], alpha=0.9,
                edgecolor='#1a1a2e', linewidth=2
            )
            ax.add_patch(rect)

            # Gate ID
            ax.text(gate["x"], gate["y"] + 0.35, gate["id"],
                    ha='center', va='center',
                    fontsize=12, fontweight='bold', color='#1a1a2e')

            # Gate name
            ax.text(gate["x"], gate["y"], gate["name"],
                    ha='center', va='center',
                    fontsize=10, color='#1a1a2e')

            # Description
            ax.text(gate["x"], gate["y"] - 0.35, gate["desc"],
                    ha='center', va='center',
                    fontsize=9, color='#444', style='italic')

            # Status indicator
            circle = Circle((gate["x"] + 0.9, gate["y"] + 0.5), 0.15,
                             facecolor=PM_COLORS["passed"],
                             edgecolor='#1a1a2e', linewidth=1.5)
            ax.add_patch(circle)

        # Draw connection arrows (flow)
        ax.annotate('', xy=(3.8, 5.5), xytext=(2.2, 5.5),
                    arrowprops=dict(arrowstyle='->', color='#666', lw=1.5))
        ax.annotate('', xy=(6.8, 5.5), xytext=(5.2, 5.5),
                    arrowprops=dict(arrowstyle='->', color='#666', lw=1.5))
        ax.annotate('', xy=(9.8, 5.5), xytext=(8.2, 5.5),
                    arrowprops=dict(arrowstyle='->', color='#666', lw=1.5))

        # Omega seal at bottom
        seal_box = FancyBboxPatch(
            (4, 0.8), 4, 1,
            boxstyle="round,pad=0.1,rounding_size=0.3",
            facecolor=PM_COLORS["omega"], alpha=0.95,
            edgecolor='#1a1a2e', linewidth=3
        )
        ax.add_patch(seal_box)
        ax.text(6, 1.4, 'OMEGA SEAL ENGAGED',
                ha='center', va='center',
                fontsize=14, fontweight='bold', color='#1a1a2e')
        ax.text(6, 1.0, '40/72 Gates Verified',
                ha='center', va='center',
                fontsize=11, color='#1a1a2e')

        # Arrow from gates to seal
        ax.annotate('', xy=(6, 1.8), xytext=(6, 2.2),
                    arrowprops=dict(arrowstyle='->', color='#1a1a2e', lw=2))

        plt.tight_layout()

        # Save
        output_path = OUTPUT_DIR / "primary_gates.png"
        plt.savefig(output_path, dpi=300, facecolor='white', edgecolor='none')
        plt.close()

        print(f"Generated: {output_path}")
        return output_path


def generate_dashboard():
    """Public entry point for dashboard generation."""
    return CertificateDashboard.generate_dashboard()


def generate_gates_focus():
    """Public entry point for primary gates focus."""
    return CertificateDashboard.generate_primary_gates_focus()


def main():
    """Generate the Certificate Dashboard visualizations."""
    print("=" * 60)
    print("Generating Certificate Dashboard")
    print("=" * 60)

    output1 = generate_dashboard()
    output2 = generate_gates_focus()

    print("\n" + "=" * 60)
    print("Certificate Dashboard Complete")
    print("=" * 60)
    if output1:
        print(f"  Dashboard: {output1}")
    if output2:
        print(f"  Primary Gates: {output2}")
    print("=" * 60)


if __name__ == "__main__":
    main()
