#!/usr/bin/env python3
"""
Figure 2: Global Convergence Scatter Plot
==========================================

Predicted-vs-experimental scatter for every testable PM parameter,
colored by validation status (PASS / MARGINAL / FAIL).

Outputs (both):
- ``AutoGenerated/plots/figure2_convergence_scatter.png``
- ``AutoGenerated/plots/figure2_convergence_scatter.pdf``

Data dependency:
    ``AutoGenerated/parameters.json`` (produced by the simulation
    pipeline). If absent, ``main()`` returns 1 and logs the missing
    artifact -- it does not synthesize fake data.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

from metaphysica.simulations.visualizations._submission_common import (
    apply_publication_rcparams,
    load_parameters,
    plots_dir,
)


def generate_figure2_convergence_scatter(
    params_data: Dict[str, Any],
) -> tuple[Path, Path] | None:
    """Generate Figure 2 as both PNG and PDF.

    Args:
        params_data: Parsed ``parameters.json`` content with a
            ``"parameters"`` mapping.

    Returns:
        ``(png_path, pdf_path)`` on success, ``None`` on failure.
    """
    try:
        import matplotlib.pyplot as plt
        from matplotlib.lines import Line2D
    except ImportError:
        print("Warning: matplotlib not available.")
        return None

    apply_publication_rcparams()
    print("\n[Figure 2] Generating Global Convergence Scatter Plot...")

    params = params_data.get("parameters", {})
    testable: List[Dict[str, Any]] = []

    for param_id, data in params.items():
        if (
            data.get("experimental_value") is not None
            and data.get("value") is not None
            and data.get("validation_status") in ("PASS", "MARGINAL", "FAIL")
        ):
            # Skip exact-identity rows (likely inputs).
            if data["value"] == data["experimental_value"]:
                continue
            sigma_dev = data.get("sigma_deviation", 0) or 0
            uncertainty = data.get("experimental_uncertainty", 0) or 0
            if uncertainty == 0:
                # 1% default fallback.
                uncertainty = abs(data["value"] - data["experimental_value"]) * 0.01
            testable.append({
                "id": param_id,
                "predicted": data["value"],
                "experimental": data["experimental_value"],
                "uncertainty": uncertainty,
                "status": data.get("validation_status", "UNKNOWN"),
                "sigma": abs(sigma_dev),
            })

    print(f"  Found {len(testable)} testable parameters")
    if len(testable) == 0:
        print("  WARNING: No testable parameters found!")
        return None

    predicted = np.array([p["predicted"] for p in testable])
    experimental = np.array([p["experimental"] for p in testable])
    uncertainties = np.array([p["uncertainty"] for p in testable])
    statuses = np.array([p["status"] for p in testable])

    fig, ax = plt.subplots(figsize=(12, 12))

    color_map = {"PASS": "green", "MARGINAL": "orange", "FAIL": "red"}
    colors = [color_map.get(s, "gray") for s in statuses]

    nonzero = predicted[predicted != 0]
    use_log = (
        nonzero.size > 0
        and np.max(np.abs(predicted)) / np.min(np.abs(nonzero)) > 1000
    )

    if use_log:
        ax.set_xscale("log")
        ax.set_yscale("log")
        mask = (predicted > 0) & (experimental > 0)
        pred_p = predicted[mask]
        exp_p = experimental[mask]
        unc_p = uncertainties[mask]
        col_p = [colors[i] for i in range(len(colors)) if mask[i]]

        ax.scatter(pred_p, exp_p, c=col_p,
                   s=100, alpha=0.7, edgecolors="black", linewidth=1.5, zorder=3)
        ax.errorbar(pred_p, exp_p, yerr=unc_p,
                    fmt="none", ecolor="gray", alpha=0.4, capsize=3, zorder=2)
        if pred_p.size > 0:
            min_val = float(min(np.min(pred_p), np.min(exp_p)))
            max_val = float(max(np.max(pred_p), np.max(exp_p)))
            ax.plot([min_val, max_val], [min_val, max_val],
                    "k--", linewidth=2, label="Perfect Agreement (y = x)", zorder=1)
    else:
        ax.scatter(predicted, experimental, c=colors,
                   s=100, alpha=0.7, edgecolors="black", linewidth=1.5, zorder=3)
        ax.errorbar(predicted, experimental, yerr=uncertainties,
                    fmt="none", ecolor="gray", alpha=0.4, capsize=3, zorder=2)
        min_val = float(min(np.min(predicted), np.min(experimental)))
        max_val = float(max(np.max(predicted), np.max(experimental)))
        ax.plot([min_val, max_val], [min_val, max_val],
                "k--", linewidth=2, label="Perfect Agreement (y = x)", zorder=1)

    # Annotate the 5 highest-deviation rows.
    key_params = sorted(testable, key=lambda p: p["sigma"], reverse=True)[:5]
    for param in key_params:
        if use_log and (param["predicted"] <= 0 or param["experimental"] <= 0):
            continue
        label = param["id"].split(".")[-1]
        ax.annotate(
            label,
            xy=(param["predicted"], param["experimental"]),
            xytext=(10, 10), textcoords="offset points",
            fontsize=9, alpha=0.8,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.5),
            arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=0.2",
                            color="black", lw=1),
        )

    ax.set_xlabel("PM Predicted Values", fontsize=16, fontweight="bold")
    ax.set_ylabel("Experimental Values", fontsize=16, fontweight="bold")
    ax.set_title(
        f"Global Convergence: PM Predictions vs. Experiment\n"
        f"({len(testable)} Testable Parameters)",
        fontsize=18, fontweight="bold", pad=20,
    )

    legend_elements = [
        Line2D([0], [0], marker="o", color="w", label="PASS (<=2 sigma)",
               markerfacecolor="green", markersize=10, markeredgecolor="black"),
        Line2D([0], [0], marker="o", color="w", label="MARGINAL (2-3 sigma)",
               markerfacecolor="orange", markersize=10, markeredgecolor="black"),
        Line2D([0], [0], marker="o", color="w", label="FAIL (>3 sigma)",
               markerfacecolor="red", markersize=10, markeredgecolor="black"),
        Line2D([0], [0], color="black", linestyle="--", linewidth=2,
               label="Perfect Agreement"),
    ]
    ax.legend(handles=legend_elements, loc="upper left", fontsize=12, framealpha=0.9)
    ax.grid(True, alpha=0.3, linestyle="--", linewidth=0.8)

    pass_count = int(np.sum(statuses == "PASS"))
    marginal_count = int(np.sum(statuses == "MARGINAL"))
    fail_count = int(np.sum(statuses == "FAIL"))
    total = len(testable)
    stats_text = (
        "Statistics:\n"
        f"PASS: {pass_count} ({100 * pass_count / total:.1f}%)\n"
        f"MARGINAL: {marginal_count} ({100 * marginal_count / total:.1f}%)\n"
        f"FAIL: {fail_count} ({100 * fail_count / total:.1f}%)"
    )
    ax.text(0.98, 0.02, stats_text,
            transform=ax.transAxes, fontsize=11,
            verticalalignment="bottom", horizontalalignment="right",
            bbox=dict(boxstyle="round", facecolor="white", alpha=0.8,
                      edgecolor="black"))

    out_dir = plots_dir()
    png_path = out_dir / "figure2_convergence_scatter.png"
    pdf_path = out_dir / "figure2_convergence_scatter.pdf"
    plt.savefig(png_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.savefig(pdf_path, bbox_inches="tight", facecolor="white")
    plt.close()

    print(f"  OK Saved: {png_path}")
    print(f"  OK Saved: {pdf_path}")
    return png_path, pdf_path


def main() -> int:
    """Generate Figure 2 (PNG + PDF). Requires parameters.json."""
    print("=" * 60)
    print("Generating Figure 2: Convergence Scatter")
    print("=" * 60)

    try:
        params_data = load_parameters()
    except FileNotFoundError as exc:
        print(f"  [SKIP] {exc}")
        return 1

    result = generate_figure2_convergence_scatter(params_data)
    if result is None:
        return 1
    png_path, _pdf_path = result
    size = Path(png_path).stat().st_size
    print(f"[viz] OK figure2_convergence_scatter.png ({size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
