#!/usr/bin/env python3
"""
Figure 3: ALP Discovery Window (IAXO Sensitivity)
==================================================

Mass-vs-coupling parameter space showing CAST excluded region, BabyIAXO
projected sensitivity, IAXO 2025-2028 sensitivity, and the PM prediction
point at ``m_a = 3.51 meV, g_a-gamma-gamma = 1e-11 GeV^-1``.

Outputs (both):
- ``AutoGenerated/plots/figure3_alp_discovery_window.png``
- ``AutoGenerated/plots/figure3_alp_discovery_window.pdf``

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

from metaphysica.simulations.visualizations._submission_common import (
    apply_publication_rcparams,
    plots_dir,
)


def generate_figure3_alp_discovery_window() -> tuple[Path, Path] | None:
    """Generate Figure 3 as both PNG and PDF."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("Warning: matplotlib not available.")
        return None

    apply_publication_rcparams()
    print("\n[Figure 3] Generating ALP Discovery Window...")

    fig, ax = plt.subplots(figsize=(12, 10))

    # Mass range (meV).
    m_a = np.logspace(-1, 1, 200)  # 0.1 to 10 meV

    # CAST exclusion limit (approximate).
    cast_limit = np.full_like(m_a, 0.66e-10)
    cast_limit[m_a > 20] = np.nan

    # IAXO projected sensitivity (2025-2028).
    iaxo_sensitivity = np.full_like(m_a, 1.5e-11)
    iaxo_sensitivity[m_a < 0.5] = 1.5e-11 * (0.5 / m_a[m_a < 0.5]) ** 0.3
    iaxo_sensitivity[m_a > 10] = np.nan

    # BabyIAXO sensitivity (intermediate step).
    babyiaxo_sensitivity = np.full_like(m_a, 1.5e-10)
    babyiaxo_sensitivity[m_a > 15] = np.nan

    # PM Prediction: m_a = 3.51 meV, g_agg = 1e-11 GeV^-1.
    pm_mass = 3.51
    pm_coupling = 1.0e-11
    pm_mass_error = 0.5
    pm_coupling_error = 0.3e-11

    # CAST excluded region.
    ax.fill_between(m_a, cast_limit, 1e-8, where=~np.isnan(cast_limit),
                    alpha=0.4, color="red", label="CAST Excluded (2017)")
    ax.plot(m_a, cast_limit, "r-", linewidth=2)

    # Future sensitivities.
    ax.plot(m_a, babyiaxo_sensitivity, "b--", linewidth=2.5,
            label="BabyIAXO Projected (2024-2025)")
    ax.plot(m_a, iaxo_sensitivity, "purple", linewidth=3,
            label="IAXO Projected (2025-2028)")
    ax.fill_between(m_a, iaxo_sensitivity, 1e-13, where=~np.isnan(iaxo_sensitivity),
                    alpha=0.2, color="purple")

    # PM Prediction with error box.
    ax.errorbar(pm_mass, pm_coupling,
                xerr=pm_mass_error, yerr=pm_coupling_error,
                fmt="*", color="red", markersize=25,
                markeredgecolor="darkred", markeredgewidth=2,
                ecolor="darkred", elinewidth=3, capsize=8, capthick=3,
                label="PM Prediction", zorder=10)

    ax.annotate(
        "Detection Window\n2025-2028",
        xy=(pm_mass, pm_coupling), xytext=(1.2, 5e-11),
        fontsize=13, fontweight="bold", color="purple",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="yellow", alpha=0.7,
                  edgecolor="purple", linewidth=2),
        arrowprops=dict(arrowstyle="->", lw=3, color="purple",
                        connectionstyle="arc3,rad=0.3"),
    )

    ax.text(pm_mass, pm_coupling * 0.3, "Principia Metric\nPrediction",
            ha="center", fontsize=11, fontweight="bold", color="darkred",
            bbox=dict(boxstyle="round,pad=0.4", facecolor="white", alpha=0.8,
                      edgecolor="red", linewidth=1.5))

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel(r"ALP Mass $m_a$ (meV)", fontsize=16, fontweight="bold")
    ax.set_ylabel(r"Photon Coupling $g_{a\gamma\gamma}$ (GeV$^{-1}$)",
                  fontsize=16, fontweight="bold")
    ax.set_title(
        "ALP Discovery Window: IAXO Sensitivity vs. PM Prediction\n"
        r"Axion-Like Particle Detection Prospects (2025-2028)",
        fontsize=18, fontweight="bold", pad=20,
    )
    ax.set_xlim(0.1, 10)
    ax.set_ylim(1e-12, 1e-8)
    ax.legend(loc="upper right", fontsize=12, framealpha=0.9,
              edgecolor="black", fancybox=True)
    ax.grid(True, which="both", alpha=0.3, linestyle="--", linewidth=0.8)

    out_dir = plots_dir()
    png_path = out_dir / "figure3_alp_discovery_window.png"
    pdf_path = out_dir / "figure3_alp_discovery_window.pdf"
    plt.savefig(png_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.savefig(pdf_path, bbox_inches="tight", facecolor="white")
    plt.close()

    print(f"  OK Saved: {png_path}")
    print(f"  OK Saved: {pdf_path}")
    return png_path, pdf_path


def main() -> int:
    """Generate Figure 3 (PNG + PDF)."""
    print("=" * 60)
    print("Generating Figure 3: ALP Discovery Window")
    print("=" * 60)

    result = generate_figure3_alp_discovery_window()
    if result is None:
        return 1
    png_path, _pdf_path = result
    size = Path(png_path).stat().st_size
    print(f"[viz] OK figure3_alp_discovery_window.png ({size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
