"""
eml_math — thin operator-tree adapter for v25.0 physics modules.
================================================================

Purpose
-------
The Sprint 4 v25.0 physics lift (`yukawa_derivation`, `re_t_sector`,
`vacuum_selection`, `strong_cp_axion`, `baryogenesis`, `soft_susy_breaking`)
needs a single, uniform call site for recording the symbolic derivation tree
of every parameter it computes. Those modules use this pattern::

    tree = eml_operator_tree("yukawa_derivation")
    tree.register_derivation(
        param="theta_13_rad",
        formula="arcsin(sqrt(2)/3) - delta_b3",
        value=0.1485,
    )

This module is a thin adapter on top of the existing
:mod:`metaphysica.simulations.core.eml_integration` so it does **not**
duplicate the EML operator wrappers — it just provides the
``eml_operator_tree`` class with an ``register_derivation`` /
``get_tree`` API, persists results into ``AutoGenerated/eml_trees_v25.json``
(overlay-safe), and cross-links the formula text to ``b3_leaf()`` whenever
the formula text mentions ``b3``, ``b_3``, or the literal ``24``.

Persistence layout
------------------
``AutoGenerated/eml_trees_v25.json`` follows the shape::

    {
        "yukawa_derivation": {
            "theta_13_rad": {
                "formula": "arcsin(sqrt(2)/3) - delta_b3",
                "value": 0.1485,
                "b3_traceback": true
            },
            ...
        },
        "re_t_sector": { ... },
        ...
    }

The file is kept *separate* from the main ``eml_trees.json`` so the Sprint 3
``arithma_dependency_walker`` and the Sprint 4 dependency resolver can pick
up v25.0 derivations without having to disambiguate them against the legacy
EML trees.

Overlay-safe semantics
----------------------
``register_derivation`` does an in-place merge:

1. Load existing JSON if the file exists.
2. Ensure ``self.name`` slot is present (dict).
3. Update *only* the ``param`` key under ``self.name``.
4. Save back.

Two trees with different names never collide; two registrations under the
same name + same param simply overwrite the prior entry for that param.

Public surface
--------------

* :class:`eml_operator_tree` — construct via ``eml_operator_tree(name)``.
* :meth:`eml_operator_tree.register_derivation` — append a derivation.
* :meth:`eml_operator_tree.get_tree` — return the in-memory tree dict.

Re-exports
----------
For convenience the most-commonly-used EML operator factories from
:mod:`eml_integration` are re-exported so v25.0 modules can do::

    from metaphysica.simulations.core.eml_tree_adapter import (
        eml_operator_tree, eml_scalar, eml_add, eml_mul, b3_leaf,
    )

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict

# Re-export the canonical operator wrappers so v25.0 modules have a single
# import surface (`from ...core.eml_math import ...`) rather than reaching
# into eml_integration directly.
from metaphysica.simulations.core.eml_integration import (  # noqa: F401
    EML_AVAILABLE,
    b3_leaf,
    eml_add,
    eml_compute,
    eml_div,
    eml_exp,
    eml_ln,
    eml_mul,
    eml_neg,
    eml_pi,
    eml_pow,
    eml_scalar,
    eml_sin,
    eml_sqrt,
    eml_sub,
)

# ── Persistence file --------------------------------------------------------

#: Name of the on-disk JSON file under ``AutoGenerated/`` that this adapter
#: writes into. v25.0 derivations are kept *separate* from the legacy
#: ``eml_trees.json`` so the dependency walker can pick them up without
#: disambiguation logic.
TREES_FILENAME = "eml_trees_v25.json"


# ── b3 traceback detector ---------------------------------------------------

#: Pre-compiled detector for any formula text that mentions b3 / b_3 / 24.
#: Used by :meth:`eml_operator_tree.register_derivation` to flag derivations
#: that cross-link back to the G2 third Betti number seed.
#:
#: Word-boundary on either side to avoid matching ``24`` inside ``2400`` or
#: ``b3`` inside ``b30``. Whitespace, brackets, math operators, dots, and
#: end-of-string all count as boundaries.
_B3_PATTERN = re.compile(
    r"(?:\b|^)(?:b3|b_3|b_\{3\}|24)(?:\b|$)",
    re.IGNORECASE,
)


def _formula_has_b3_traceback(formula: str) -> bool:
    """Return True iff *formula* text mentions b3 / b_3 / 24."""
    if not formula:
        return False
    return bool(_B3_PATTERN.search(formula))


# ── On-disk helpers ---------------------------------------------------------


def _trees_path() -> Path:
    """Resolve the on-disk path for ``eml_trees_v25.json``.

    Defers import of :func:`metaphysica.generators._common.autogen_dir` to call
    time so importing this module never has the side effect of creating
    ``AutoGenerated/``.
    """
    from metaphysica.generators._common import autogen_dir

    return autogen_dir() / TREES_FILENAME


def _load_trees() -> Dict[str, Dict[str, Dict[str, Any]]]:
    """Load the on-disk tree dict, or return an empty dict if missing."""
    path = _trees_path()
    if not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except json.JSONDecodeError:
        # Corrupt file — treat as empty rather than crashing the build.
        return {}
    if not isinstance(data, dict):
        return {}
    return data


def _save_trees(trees: Dict[str, Dict[str, Dict[str, Any]]]) -> None:
    """Write *trees* out as pretty JSON."""
    path = _trees_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(trees, fh, indent=2, sort_keys=True)
        fh.write("\n")


# ── Public adapter class ----------------------------------------------------


class eml_operator_tree:
    """Thin adapter that records v25.0 EML derivations to disk.

    Parameters
    ----------
    name:
        Logical name of the physics module owning these derivations
        (e.g. ``"yukawa_derivation"``, ``"re_t_sector"``). Two adapters
        with the same name share the same on-disk slot — registrations
        merge rather than collide.

    Example
    -------
    >>> tree = eml_operator_tree("re_t_sector")
    >>> tree.register_derivation(
    ...     param="ReT_VEV",
    ...     formula="b3 * exp(-S_inst) / (2*pi)",
    ...     value=10.86,
    ... )  # doctest: +SKIP
    >>> tree.get_tree()["ReT_VEV"]["b3_traceback"]  # doctest: +SKIP
    True
    """

    __slots__ = ("name",)

    def __init__(self, name: str) -> None:
        if not isinstance(name, str) or not name:
            raise ValueError(
                f"eml_operator_tree(name=...) requires a non-empty string, "
                f"got {name!r}"
            )
        self.name = name

    # ── Recording API ------------------------------------------------------

    def register_derivation(
        self,
        param: str,
        formula: str,
        value: Any,
    ) -> Dict[str, Any]:
        """Record a single ``param → (formula, value)`` derivation.

        The entry is stored under ``trees[self.name][param]`` in
        ``AutoGenerated/eml_trees_v25.json``. The operation is overlay-safe:
        existing entries under other names are preserved verbatim; existing
        entries under the same name + different param are preserved;
        existing entries under the same name + same param are overwritten.

        A ``b3_traceback`` flag is added to the entry when the formula text
        mentions ``b3``, ``b_3``, or ``24`` — see :func:`_formula_has_b3_traceback`.

        Parameters
        ----------
        param:
            Canonical parameter name (e.g. ``"theta_13_rad"``).
        formula:
            Free-form symbolic / EML-style string describing the derivation
            (e.g. ``"arcsin(sqrt(2)/3) - delta_b3"``).
        value:
            Numerical value (typically ``float``, but ``int`` / ``str`` are
            accepted for non-numeric / placeholder cases). Must be
            JSON-serialisable.

        Returns
        -------
        dict
            The entry as written, including the ``b3_traceback`` flag.
        """
        if not isinstance(param, str) or not param:
            raise ValueError(
                f"register_derivation(param=...) requires a non-empty string, "
                f"got {param!r}"
            )
        if not isinstance(formula, str):
            raise TypeError(
                f"register_derivation(formula=...) requires a string, "
                f"got {type(formula).__name__}"
            )

        entry: Dict[str, Any] = {
            "formula": formula,
            "value": value,
            "b3_traceback": _formula_has_b3_traceback(formula),
        }

        trees = _load_trees()
        bucket = trees.setdefault(self.name, {})
        if not isinstance(bucket, dict):
            # Defensive: replace a malformed slot rather than crashing.
            bucket = {}
            trees[self.name] = bucket
        bucket[param] = entry
        _save_trees(trees)
        return entry

    # ── Read API -----------------------------------------------------------

    def get_tree(self) -> Dict[str, Dict[str, Any]]:
        """Return the in-memory mapping of ``param → entry`` for this tree.

        Loads fresh from disk on every call (cheap, and keeps semantics
        clean when multiple adapters share the same name across processes).
        """
        trees = _load_trees()
        bucket = trees.get(self.name, {})
        if not isinstance(bucket, dict):
            return {}
        return bucket

    # ── Dunders ------------------------------------------------------------

    def __repr__(self) -> str:  # pragma: no cover - trivial
        return f"eml_operator_tree(name={self.name!r})"


__all__ = [
    "eml_operator_tree",
    "TREES_FILENAME",
    # Re-exports from eml_integration so v25.0 modules have a single
    # import surface.
    "EML_AVAILABLE",
    "b3_leaf",
    "eml_add",
    "eml_compute",
    "eml_div",
    "eml_exp",
    "eml_ln",
    "eml_mul",
    "eml_neg",
    "eml_pi",
    "eml_pow",
    "eml_scalar",
    "eml_sin",
    "eml_sqrt",
    "eml_sub",
]
