"""The free-variable ledger: one measured count of what is not derived.

WHY THIS EXISTS
---------------
The framework publishes "zero fitted parameters". Three places in the tree
answer the question "how many free variables?" and they do not agree:

* ``validation.calibrated_count`` = 0 -- a literal in
  ``PM/paper/abstract.py``, annotated "EDOF=3: calibrations are
  scale-setting, not fitted".
* ``StatisticalRigorValidator.calculate_effective_dof`` returns 3, and its
  own body says ``# ANSATZ: EDOF=3 is a judgment ... not a numerical
  computation``.
* ``abstract.calibration_inputs`` = 3, whose description names the three as
  "(VEV, alpha_GUT, Re(T))" while
  ``PM/validation/information_bottleneck_distiller.py`` names a *different*
  three, ``["M_Planck", "alpha_EM", "m_H"]``.

None of the three is computed. This module is the measuring instrument that
replaces them: it sweeps the tree for every quantity that is not derived,
records where it lives and what it does, and emits
``AutoGenerated/free_variables.json``. The count is a ``len()`` over rows
that were found, never a literal -- add a fit to the tree and the number
moves on the next build.

WHAT COUNTS AS A ROW
--------------------
Three populations, swept separately because they are declared differently.
A row is a *quantity*, not a declaration: five paths are declared twice and
are merged, because a count of declarations is not a count of free
variables.

1. ``Parameter(...)`` calls whose ``status=`` literal is one of
   :data:`NON_DERIVED_STATUSES`. The operative status vocabulary is
   ``PRESERVED_PARAMETER_STATUSES`` in ``run_all_simulations.py``; the five
   named here are the subset that admits the value did not come out of the
   geometry.
2. The geometric anchors registered with ``status="MEASURED"`` by
   ``geometric_anchors_core.register_anchors`` -- raw NuFIT / Planck /
   SH0ES / PDG / DESI numbers. These never appear as a ``Parameter(...)``
   ``status`` literal, so an AST sweep of declarations alone misses all of
   them.
3. ``registry.set_param(status=...)`` calls, which write straight into the
   registry and bypass the ``Parameter`` surface entirely. This population
   was found by the ledger gate in ``tests/test_free_variable_ledger.py``,
   not by design: ``bridge_ede.entropy_damping.classification`` (FITTED)
   and ``yukawa.phi_fit`` (ANSATZ) had never appeared in any count.

One declaration cannot become a row: ``register_anchors``' own loop, whose
``path`` is a variable. It writes the twenty anchors of population 2, which
are already covered by name; it is reported by :func:`unnamed_declarations`
rather than dropped, because a registration surface no sweep can see is how
a count goes stale.

ROLES
-----
Every row gets exactly one role, and for rows 2 the role is *derived from a
traced consumer*, never asserted:

``PERMITTED_OR_SCALE``
    A reduction- or scale-setting quantity. The one permitted bucket: a
    theory is allowed to be told what its units are.
``COMPARISON_ONLY``
    A measured value read only to score a prediction against it. Costs
    nothing -- the prediction still had to be made without it.
``LOAD_BEARING_INPUT``
    A measured or chosen value that flows into a derivation whose result is
    itself registered. This is the expensive bucket: every one of these is a
    number the framework was told rather than derived, and downstream
    "predictions" inherit it.
``UNRESOLVED``
    No consumer could be traced, or the row's own description contradicts
    its declared status. Deliberately not a synonym for "harmless".

HOW A CONSUMER IS TRACED
------------------------
:func:`trace_consumers` finds every *executing* read of a registry path --
``registry.get("geometry.X")``, ``_reg_value(...)``, ``_get_param(...)`` --
and ignores mentions inside prose, ``eml_description`` strings and comments,
which are not consumers. From the assignment target of each read it
taint-propagates through the enclosing function; if a tainted name reaches a
**value position in a returned dict whose keys are registry paths**, the
read fed a registered output and the row is ``LOAD_BEARING_INPUT``.
Otherwise the read only ever reached a comparison and the row is
``COMPARISON_ONLY``. The same taint runs over ``self.<anchor>`` inside
``GeometricAnchors``, because an anchor consumed by another anchor property
that ``get_all_anchors`` exports is load-bearing without leaving the file.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""
from __future__ import annotations

import ast
import json
import os
import re
from dataclasses import asdict, dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Sequence, Set, Tuple

__all__ = [
    "ROLES",
    "ROLE_PERMITTED_OR_SCALE",
    "ROLE_COMPARISON_ONLY",
    "ROLE_LOAD_BEARING_INPUT",
    "ROLE_UNRESOLVED",
    "NON_DERIVED_STATUSES",
    "DERIVATION_CLAIMING_STATUSES",
    "FIT_ADMISSION_PATTERNS",
    "FIT_EXONERATION_PATTERNS",
    "LedgerRow",
    "Consumer",
    "admits_a_fit",
    "iter_parameter_calls",
    "sweep_parameter_rows",
    "sweep_anchor_rows",
    "trace_consumers",
    "build_ledger",
    "write_ledger",
    "unnamed_declarations",
    "free_variable_count",
    "published_free_variable_count",
    "simulations_root",
]

# --------------------------------------------------------------------------
# roles
# --------------------------------------------------------------------------

ROLE_PERMITTED_OR_SCALE = "PERMITTED_OR_SCALE"
ROLE_COMPARISON_ONLY = "COMPARISON_ONLY"
ROLE_LOAD_BEARING_INPUT = "LOAD_BEARING_INPUT"
ROLE_UNRESOLVED = "UNRESOLVED"

ROLES = (
    ROLE_PERMITTED_OR_SCALE,
    ROLE_COMPARISON_ONLY,
    ROLE_LOAD_BEARING_INPUT,
    ROLE_UNRESOLVED,
)

#: Statuses from ``PRESERVED_PARAMETER_STATUSES`` that admit the value was
#: not derived. Each is a different way of not deriving something:
#:
#:   FITTED            -- fitted to data
#:   FITTED_COMPOSITE  -- a composite of fitted pieces
#:   CALIBRATED        -- set to reproduce one measurement
#:   ANSATZ            -- asserted, with a stated reason but no derivation
#:   MEASURED          -- read straight out of an experiment
#:
#: Anything outside this set claims, at some strength, to have come out of
#: the geometry, and so is not a free variable *by its own declaration*.
#: Whether that declaration is true is the honesty guard's business, not
#: this set's.
NON_DERIVED_STATUSES = frozenset({
    "FITTED",
    "FITTED_COMPOSITE",
    "CALIBRATED",
    "ANSATZ",
    "MEASURED",
})

#: Statuses whose whole content is the claim "this came out of the theory".
#: A description that admits a fit under one of these is a contradiction
#: inside a single ``Parameter(...)`` call.
DERIVATION_CLAIMING_STATUSES = frozenset({
    "DERIVED", "GEOMETRIC", "PREDICTED", "PREDICTIONS", "EXACT", "COMPUTED",
    "COMPUTATIONAL", "FOUNDATIONAL", "ESTABLISHED", "TERMINAL", "VALIDATED",
})

# --------------------------------------------------------------------------
# the honesty guard's vocabulary
# --------------------------------------------------------------------------

#: Phrases that are an *admission* that a number was chosen to match, in the
#: affirmative. Deliberately narrow: a bare mention of the word "fitted" is
#: not an admission -- half the tree's prose says "not a fitted quantity" or
#: "originally fitted, now DERIVED", and a guard that fired on those would
#: be noise a reader learns to ignore.
FIT_ADMISSION_PATTERNS: Tuple[str, ...] = (
    r"\bis\s+(?:a\s+)?fitted\b",
    r"\bare\s+fitted\b",
    r"\bfitted\s+to\s+(?:data|the\s|experiment|observation|NuFIT|PDG|Planck|DESI|SH0ES)",
    r"\bfit\s+to\s+data\b",
    r"\bphenomenological\s+fit\b",
    r"\btuned\s+to\b",
    r"\bcalibrated\s+to\b",
    r"\bback-?solved\b",
    r"\bchosen\s+so\b",
    r"\bchosen\s+to\s+(?:produce|match|reproduce|give)\b",
)

#: Contexts in which an admission phrase is not an admission: a denial, a
#: historical note, or a superseded value being named in order to be
#: disowned.
FIT_EXONERATION_PATTERNS: Tuple[str, ...] = (
    r"\bnot\s+(?:a\s+)?fitted\b",
    r"\brather\s+than\s+fitted\b",
    r"\boriginally\s+fitted,\s*now\b",
    r"\bno\s+longer\s+fitted\b",
    r"\bsuperseded\b",
    r"\bsemi-fitted\)\s*to\s+DERIVED\b",
)

_ADMIT_RE = tuple(re.compile(p, re.IGNORECASE) for p in FIT_ADMISSION_PATTERNS)
_EXON_RE = tuple(re.compile(p, re.IGNORECASE) for p in FIT_EXONERATION_PATTERNS)


def admits_a_fit(text: str) -> List[str]:
    """Return the admission phrases in ``text``, or ``[]``.

    An admission that sits inside an exonerating context returns ``[]`` --
    "not a fitted quantity" is a denial, not a confession.
    """
    if not text:
        return []
    if any(rx.search(text) for rx in _EXON_RE):
        return []
    return [rx.pattern for rx in _ADMIT_RE if rx.search(text)]


# --------------------------------------------------------------------------
# rows
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Consumer:
    """One traced use of a quantity, with enough detail to re-check it."""

    location: str          # "<file>:<line>", repo-relative
    function: str          # enclosing function or property
    kind: str              # READ_INTO_REGISTERED_OUTPUT | READ_FOR_COMPARISON
                           # | ANCHOR_FEEDS_EXPORTED_ANCHOR | CROSS_CHECK_GROUP
    detail: str            # what the trace actually saw


@dataclass
class LedgerRow:
    """One quantity this framework did not derive."""

    name: str
    value: Any
    location: str                       # "<file>:<line>", repo-relative
    status: str                         # as declared in the tree
    source_kind: str                    # PARAMETER_CALL | GEOMETRIC_ANCHOR
    role: str
    role_evidence: List[Dict[str, str]] = field(default_factory=list)
    closing_derivation: str = ""
    description: str = ""
    notes: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# --------------------------------------------------------------------------
# locating the tree
# --------------------------------------------------------------------------


def _package_root() -> Path:
    """``src/metaphysica`` for a checkout, the installed package otherwise."""
    return Path(__file__).resolve().parents[2]


def simulations_root() -> Path:
    return _package_root() / "simulations"


def _rel(path: Path) -> str:
    """Repo-relative when we are in a checkout, package-relative otherwise."""
    root = _package_root()
    try:
        return str(Path("src/metaphysica") / path.resolve().relative_to(root))
    except ValueError:
        return str(path)


def _iter_python_files(root: Path) -> Iterator[Path]:
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        yield path


def _parse(path: Path) -> Optional[ast.Module]:
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):  # pragma: no cover - defensive
        return None


def _const(node: Optional[ast.AST]) -> Optional[Any]:
    return node.value if isinstance(node, ast.Constant) else None


# --------------------------------------------------------------------------
# population 1: Parameter(...) calls
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class ParameterCall:
    """One ``Parameter(...)`` call site, reduced to its literal metadata."""

    path: Optional[str]
    status: Optional[str]
    description: str
    file: Path
    lineno: int
    #: kwargs that are not fields of ``simulation_base.Parameter``. A call
    #: carrying any of these cannot execute -- see
    #: :func:`sweep_parameter_rows`.
    foreign_kwargs: Tuple[str, ...] = ()
    #: ``classification=`` where present. A second, undeclared status
    #: vocabulary rides in on the foreign-kwarg calls.
    classification: Optional[str] = None
    #: The callee the declaration was made through. ``Parameter`` is the
    #: declarative surface; ``set_param`` writes straight into the registry
    #: at run time and bypasses it entirely.
    callee: str = "Parameter"


#: Fields of ``metaphysica.simulations.base.simulation_base.Parameter``.
#: Resolved live so this cannot drift from the dataclass.
def _parameter_fields() -> Set[str]:
    from dataclasses import fields as _fields

    from metaphysica.simulations.base.simulation_base import Parameter

    return {f.name for f in _fields(Parameter)}


#: Callees through which a quantity enters the registry with a status.
#: ``set_param`` is here because a sweep that only reads ``Parameter(...)``
#: misses every value written straight into the registry at run time -- the
#: ledger gate found two that way, ``bridge_ede.entropy_damping.classification``
#: (FITTED) and ``yukawa.phi_fit`` (ANSATZ), neither of which has ever
#: appeared in any count.
_DECLARING_CALLEES = frozenset({"Parameter", "set_param"})


def iter_parameter_calls(root: Optional[Path] = None) -> Iterator[ParameterCall]:
    """Yield every status-carrying declaration under ``root``.

    Literal metadata only: a ``status=`` built at runtime yields ``None``
    and is reported rather than guessed at.
    """
    root = root or simulations_root()
    known = _parameter_fields()
    for path in _iter_python_files(root):
        tree = _parse(path)
        if tree is None:
            continue
        # `from ... import Parameter as Knob` must not hide a declaration
        # behind the local name. Resolved per file rather than assumed away.
        aliases = {c: c for c in _DECLARING_CALLEES}
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                for alias in node.names:
                    if alias.name in _DECLARING_CALLEES and alias.asname:
                        aliases[alias.asname] = alias.name
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            fn = node.func
            local = fn.id if isinstance(fn, ast.Name) else getattr(fn, "attr", None)
            name = aliases.get(local)
            if name is None:
                continue
            kw = {k.arg: k.value for k in node.keywords if k.arg}
            # Only Parameter has a fixed field set to be foreign to.
            foreign = tuple(sorted(set(kw) - known)) if name == "Parameter" else ()
            ident = _const(kw.get("path"))
            if ident is None:
                ident = _const(kw.get("id"))
            yield ParameterCall(
                path=ident,
                status=_const(kw.get("status")),
                description=(_const(kw.get("description"))
                             or _const(kw.get("source")) or ""),
                file=path,
                lineno=node.lineno,
                foreign_kwargs=foreign,
                classification=_const(kw.get("classification")),
                callee=name,
            )


# --------------------------------------------------------------------------
# population 2: the geometric anchors
# --------------------------------------------------------------------------


def _anchors_core_path() -> Path:
    return simulations_root() / "PM" / "geometry" / "geometric_anchors_core.py"


def _anchor_property_lines() -> Dict[str, int]:
    """Anchor name -> the line its property is defined on."""
    tree = _parse(_anchors_core_path())
    out: Dict[str, int] = {}
    if tree is None:  # pragma: no cover - defensive
        return out
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            out.setdefault(node.name, node.lineno)
    return out


def _anchor_source(name: str) -> str:
    """Docstring + body source of an anchor property, comments included.

    The comments matter: ``alpha_T_phenomenological`` says nothing in its
    docstring about being a fit, and everything in the trailing
    ``# From fit to data``.
    """
    src = _anchors_core_path().read_text(encoding="utf-8")
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == name:
            seg = ast.get_source_segment(src, node)
            if seg:
                return seg
    return ""


# --------------------------------------------------------------------------
# consumer tracing
# --------------------------------------------------------------------------

#: Accessors that read a registry path at run time. A path named anywhere
#: else -- prose, an ``eml_description``, a comment -- is a mention, not a
#: consumer, and must not be allowed to promote a row to load-bearing.
_REGISTRY_READERS = frozenset({
    "get", "_reg_value", "_get_param", "get_param", "get_value", "value_of",
})


def _annotate_parents(tree: ast.AST) -> None:
    for parent in ast.walk(tree):
        for child in ast.iter_child_nodes(parent):
            child.__dict__["_fvl_parent"] = parent


def _enclosing_function(node: ast.AST) -> Optional[ast.AST]:
    cur = node.__dict__.get("_fvl_parent")
    while cur is not None:
        if isinstance(cur, (ast.FunctionDef, ast.AsyncFunctionDef)):
            return cur
        cur = cur.__dict__.get("_fvl_parent")
    return None


def _assignment_target(node: ast.AST) -> Optional[str]:
    """The single Name a read is assigned to, if it is assigned to one."""
    cur = node.__dict__.get("_fvl_parent")
    while cur is not None and not isinstance(cur, ast.stmt):
        cur = cur.__dict__.get("_fvl_parent")
    if isinstance(cur, ast.Assign) and len(cur.targets) == 1:
        tgt = cur.targets[0]
        if isinstance(tgt, ast.Name):
            return tgt.id
    if isinstance(cur, ast.AnnAssign) and isinstance(cur.target, ast.Name):
        return cur.target.id
    return None


_REGISTRY_PATH_RE = re.compile(r"^[a-z_][a-z0-9_]*\.[A-Za-z_][A-Za-z0-9_.]*$")


def _returned_registry_values(fn: ast.AST) -> List[ast.AST]:
    """Value expressions of returned dicts whose keys look like registry paths.

    A module registers its outputs by returning ``{"cosmology.x": value}``.
    Reaching a value position in one of those dicts is what makes an input
    load-bearing: the published number now depends on it.
    """
    out: List[ast.AST] = []
    for node in ast.walk(fn):
        if not isinstance(node, ast.Return) or not isinstance(node.value, ast.Dict):
            continue
        for key, val in zip(node.value.keys, node.value.values):
            k = _const(key)
            if isinstance(k, str) and _REGISTRY_PATH_RE.match(k):
                out.append(val)
    return out


def _taint(fn: ast.AST, seed: str) -> Set[str]:
    """Names in ``fn`` that carry ``seed``'s value, by assignment closure.

    Deliberately a fixed point over plain assignments only. It under-reports
    rather than over-reports: a value laundered through a container or a
    helper call will be missed and the row stays COMPARISON_ONLY, which is
    the conservative direction for a count that is meant to be a floor on
    honesty, not a ceiling.
    """
    tainted = {seed}
    changed = True
    while changed:
        changed = False
        for node in ast.walk(fn):
            if not isinstance(node, (ast.Assign, ast.AnnAssign)):
                continue
            value = node.value
            if value is None:
                continue
            used = {n.id for n in ast.walk(value) if isinstance(n, ast.Name)}
            if not (used & tainted):
                continue
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for tgt in targets:
                for n in ast.walk(tgt):
                    if isinstance(n, ast.Name) and n.id not in tainted:
                        tainted.add(n.id)
                        changed = True
    return tainted


def _reaches_registered_output(fn: ast.AST, seed: str) -> bool:
    tainted = _taint(fn, seed)
    for val in _returned_registry_values(fn):
        for n in ast.walk(val):
            if isinstance(n, ast.Name) and n.id in tainted:
                return True
    return False


#: Names under which a module declares what it PRODUCES. A path listed
#: there is the module naming its own output, which is the opposite of a
#: consumer -- counting it made every fitted CKM element look like it was
#: being compared against something.
_OUTPUT_DECLARATION_NAMES = frozenset({
    "output_params", "outputs", "get_outputs", "output_parameters",
    "provides", "registered_paths", "REGISTERED_PATHS", "run", "run_eml",
    "generate_parameters", "get_parameters", "get_output_param_definitions",
})

#: Names under which a module declares what it CONSUMES.
_INPUT_DECLARATION_NAMES = frozenset({
    "required_inputs", "requires", "inputs", "REQUIRED_INPUTS",
    "required_params",
})

#: Names that render a path into the paper or the website. Being printed is
#: not being used: a number quoted in a formula caption or a section body
#: has not entered any computation, and letting presentation count as a
#: consumer is exactly how a displayed experimental value comes to look
#: like a working part of the theory.
_PRESENTATION_NAMES = frozenset({
    "formulas", "get_formulas", "get_section_content", "content",
    "PARAM_REFS", "param_refs", "paramRefs", "get_content",
    "section_content", "blocks", "get_references",
})


def _container_context(node: ast.AST) -> str:
    """The nearest enclosing name that says what a path list is FOR.

    Looks at the assignment target, then the enclosing function. A path in
    ``required_inputs`` means something different from the same path in
    ``output_params``, and only the surrounding name distinguishes them.
    """
    cur = node.__dict__.get("_fvl_parent")
    while cur is not None:
        if isinstance(cur, ast.Assign) and len(cur.targets) == 1:
            tgt = cur.targets[0]
            if isinstance(tgt, ast.Name):
                return tgt.id
            if isinstance(tgt, ast.Attribute):
                return tgt.attr
        if isinstance(cur, ast.AnnAssign) and isinstance(cur.target, ast.Name):
            return cur.target.id
        if isinstance(cur, (ast.FunctionDef, ast.AsyncFunctionDef)):
            return cur.name
        cur = cur.__dict__.get("_fvl_parent")
    return ""


def _declaration_kind(node: ast.AST, parent: ast.AST) -> Optional[Tuple[str, str]]:
    """Classify a path that sits in a literal container, or drop it.

    Returns ``None`` when the mention says nothing about consumption.
    """
    if isinstance(parent, ast.Dict):
        # A key is a registration: "this module produces this path". Values
        # are looked at elsewhere. Either way, not a consumer.
        return None
    if not isinstance(parent, (ast.List, ast.Tuple, ast.Set)):
        return None
    ctx = _container_context(node)
    if ctx in _OUTPUT_DECLARATION_NAMES or ctx in _PRESENTATION_NAMES:
        return None
    if ctx in _INPUT_DECLARATION_NAMES:
        return ("DECLARED_AS_INPUT",
                f"listed in {ctx}: the declaring simulation states it needs "
                f"this value to run")
    if "output" in ctx.lower() or "produce" in ctx.lower():
        return None
    return ("CROSS_CHECK_GROUP",
            f"listed in {ctx or '<module-level list>'}: a curated group, "
            f"read for cross-checking rather than fed into a derivation")


_CONSUMER_INDEX: Dict[Tuple[str, str], Dict[str, List[Consumer]]] = {}


def _build_consumer_index(root: Path) -> Dict[str, List[Consumer]]:
    """One pass over the tree, indexing every path mention by path.

    Built once and cached: tracing each of the ~sixty ledger rows with its
    own full-tree walk turned a second of work into minutes.
    """
    index: Dict[str, List[Consumer]] = {}
    for path in _iter_python_files(root):
        tree = _parse(path)
        if tree is None:
            continue
        _annotate_parents(tree)
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Constant) and isinstance(node.value, str)):
                continue
            key = node.value
            if not _REGISTRY_PATH_RE.match(key):
                continue
            parent = node.__dict__.get("_fvl_parent")
            if not isinstance(parent, ast.Call):
                declared = _declaration_kind(node, parent)
                if declared is not None:
                    kind, detail = declared
                    fn = _enclosing_function(node)
                    index.setdefault(key, []).append(Consumer(
                        location=f"{_rel(path)}:{node.lineno}",
                        function=getattr(fn, "name", "<module>"),
                        kind=kind,
                        detail=detail,
                    ))
                continue
            fnode = parent.func
            reader = fnode.attr if isinstance(fnode, ast.Attribute) else getattr(fnode, "id", "")
            if reader not in _REGISTRY_READERS:
                continue
            enclosing = _enclosing_function(node)
            target = _assignment_target(node)
            if enclosing is not None and target and _reaches_registered_output(enclosing, target):
                kind = "READ_INTO_REGISTERED_OUTPUT"
                detail = (
                    f"{reader}(...) -> {target}, which reaches a value position "
                    f"in a returned registry dict"
                )
            else:
                kind = "READ_FOR_COMPARISON"
                detail = (
                    f"{reader}(...)"
                    + (f" -> {target}" if target else "")
                    + ", never reaches a returned registry value"
                )
            index.setdefault(key, []).append(Consumer(
                location=f"{_rel(path)}:{node.lineno}",
                function=getattr(enclosing, "name", "<module>"),
                kind=kind,
                detail=detail,
            ))
    return index


def trace_consumers(
    registry_path: str,
    root: Optional[Path] = None,
    skip_file: Optional[Path] = None,
) -> List[Consumer]:
    """Every executing read of ``registry_path``, classified by what it feeds.

    Mentions in prose and ``eml_description`` strings are not returned: they
    do not execute, and treating them as consumers is precisely how a
    displayed number gets mistaken for a used one.
    """
    root = root or _package_root()
    cache_key = (str(root.resolve()), "")
    if cache_key not in _CONSUMER_INDEX:
        _CONSUMER_INDEX[cache_key] = _build_consumer_index(root)
    found = _CONSUMER_INDEX[cache_key].get(registry_path, ())
    if skip_file is None:
        return list(found)
    # The defining file is not a consumer of its own parameter: counting it
    # would make every row load-bearing on itself.
    skip_rel = _rel(skip_file)
    return [c for c in found if c.location.rsplit(":", 1)[0] != skip_rel]


def _anchor_internal_consumers(anchor: str, exported: Set[str]) -> List[Consumer]:
    """Anchors that consume ``anchor`` and are themselves exported.

    ``get_all_anchors`` is excluded on purpose: it exports everything, so
    counting it as a consumer would make every anchor load-bearing and the
    classification would carry no information.
    """
    path = _anchors_core_path()
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    out: List[Consumer] = []
    for fn in ast.walk(tree):
        if not isinstance(fn, ast.FunctionDef) or fn.name in ("get_all_anchors", anchor):
            continue
        if fn.name not in exported:
            continue
        for node in ast.walk(fn):
            if (isinstance(node, ast.Attribute)
                    and isinstance(node.value, ast.Name)
                    and node.value.id == "self"
                    and node.attr == anchor):
                out.append(Consumer(
                    location=f"{_rel(path)}:{node.lineno}",
                    function=fn.name,
                    kind="ANCHOR_FEEDS_EXPORTED_ANCHOR",
                    detail=(
                        f"self.{anchor} is read by {fn.name}, which "
                        f"get_all_anchors exports and register_anchors "
                        f"registers as geometry.{fn.name}"
                    ),
                ))
                break
    return out


# --------------------------------------------------------------------------
# role assignment
# --------------------------------------------------------------------------

#: Rows whose own description declares them a unit- or scale-setting choice.
#: This is the one permitted bucket, so entry is by the row's *own words*,
#: matched here, and never by a hand-kept list of paths -- a list would let
#: a row be waved into the permitted bucket without saying anything about
#: itself.
_SCALE_DECLARATION_RE = re.compile(
    r"\bscale\s+calibration\b|\bsetting\s+physical\s+scales\b"
    r"|\bscale-setting\b|\bcoefficient\s+relating\b.*\bscale\b"
    r"|\bsets?\s+the\s+(?:overall\s+)?(?:unit|scale)\b"
    r"|\breduction\s+scale\b",
    re.IGNORECASE,
)


#: Evidence kinds that make a row load-bearing, strongest first. A value
#: that reaches a registered output, or that a simulation declares it needs
#: in order to run, is one the framework was told rather than derived.
_LOAD_BEARING_KINDS = frozenset({
    "READ_INTO_REGISTERED_OUTPUT",
    "ANCHOR_FEEDS_EXPORTED_ANCHOR",
    "DECLARED_AS_INPUT",
})

#: Evidence kinds that only ever reach a comparison.
_COMPARISON_KINDS = frozenset({"READ_FOR_COMPARISON", "CROSS_CHECK_GROUP"})


def _role_from_consumers(consumers: Sequence[Consumer]) -> str:
    """Role from traced evidence only.

    No evidence means UNRESOLVED, never a default. A fitted value that
    nothing reads is still a free variable; calling it COMPARISON_ONLY
    would be a guess dressed as a finding.
    """
    kinds = {c.kind for c in consumers}
    if _LOAD_BEARING_KINDS & kinds:
        return ROLE_LOAD_BEARING_INPUT
    if _COMPARISON_KINDS & kinds:
        return ROLE_COMPARISON_ONLY
    return ROLE_UNRESOLVED


# --------------------------------------------------------------------------
# sweeps
# --------------------------------------------------------------------------


def _registry_values() -> Dict[str, Any]:
    """Values from whichever parameters.json artifact is available."""
    candidates = []
    out = os.environ.get("METAPHYSICA_OUT")
    if out:
        candidates.append(Path(out) / "AutoGenerated" / "parameters.json")
    candidates.append(_package_root().parents[1] / "AutoGenerated" / "parameters.json")
    candidates.append(_package_root() / "data" / "parameters.json")
    for cand in candidates:
        try:
            if cand.is_file():
                data = json.loads(cand.read_text(encoding="utf-8"))
                params = data.get("parameters", data)
                return {k: v.get("value") if isinstance(v, dict) else v
                        for k, v in params.items()}
        except (OSError, ValueError):  # pragma: no cover - defensive
            continue
    return {}


def _closing_derivation_for_status(status: str, name: str) -> str:
    """What would have to exist for this row to stop being a free variable.

    Stated as a requirement on evidence, never as a guess at the physics:
    inventing the missing derivation here would be the same failure the
    ledger exists to measure.
    """
    if status == "MEASURED":
        return (
            f"An expression for {name} in terms of the framework's own "
            f"invariants that reproduces the registered value without "
            f"reading the experimental number back in."
        )
    if status in ("FITTED", "FITTED_COMPOSITE"):
        return (
            f"A closed form replacing the fitted literal, derived before "
            f"the comparison and scored against {name}'s datasource row "
            f"rather than tuned to it."
        )
    if status == "CALIBRATED":
        return (
            f"Either a derivation of {name} from the geometry, or an "
            f"explicit ruling that it is one of the permitted "
            f"scale-setting inputs -- it is currently neither."
        )
    if status == "ANSATZ":
        return (
            f"A proof of the asserted step. The module states the "
            f"assertion; nothing yet derives it."
        )
    return f"Unclassified status {status!r}: no closing condition stated."


def sweep_parameter_rows(root: Optional[Path] = None) -> List[LedgerRow]:
    """Ledger rows for every non-derived ``Parameter(...)`` declaration."""
    values = _registry_values()
    rows: List[LedgerRow] = []
    for call in iter_parameter_calls(root):
        status = call.status
        notes: List[str] = []

        if call.foreign_kwargs:
            # These calls pass kwargs that Parameter has no field for, so
            # they raise TypeError the moment they execute -- they are
            # unreachable. They are kept rather than dropped because one of
            # them declares classification="FITTED" with the source
            # "Chosen to produce reasonable GUT-scale corrections": a fit
            # that no count has ever included because the code around it
            # cannot run.
            if call.classification not in NON_DERIVED_STATUSES:
                continue
            status = call.classification
            notes.append(
                "UNREACHABLE: this Parameter(...) call passes "
                + ", ".join(call.foreign_kwargs)
                + ", none of which is a field of Parameter, so it raises "
                  "TypeError if executed. The fit is declared but never runs."
            )

        if call.callee == "set_param":
            notes.append(
                "Registered directly with registry.set_param, bypassing the "
                "Parameter(...) declaration surface. A sweep of parameter "
                "declarations alone does not see it."
            )

        if status not in NON_DERIVED_STATUSES:
            continue

        if call.path is None:
            # A declaration whose path is a variable. The only one in the
            # tree is register_anchors' own loop, which writes the twenty
            # MEASURED anchors that sweep_anchor_rows already covers by
            # name. Counting it would add a phantom row; dropping it
            # silently would hide a whole registration surface, so it is
            # reported separately by :func:`unnamed_declarations`.
            continue

        name = call.path
        consumers = (
            trace_consumers(call.path) if call.path else []
        )
        if _SCALE_DECLARATION_RE.search(call.description or ""):
            role = ROLE_PERMITTED_OR_SCALE
            evidence = [{
                "location": f"{_rel(call.file)}:{call.lineno}",
                "function": "<own description>",
                "kind": "SELF_DECLARED_SCALE_SETTING",
                "detail": "the row's own description declares it scale-setting",
            }]
        else:
            role = _role_from_consumers(consumers)
            evidence = [asdict(c) for c in consumers]

        admissions = admits_a_fit(call.description or "")
        if admissions and status not in NON_DERIVED_STATUSES:  # pragma: no cover
            notes.append(f"description admits a fit: {admissions}")

        rows.append(LedgerRow(
            name=name,
            value=values.get(call.path) if call.path else None,
            location=f"{_rel(call.file)}:{call.lineno}",
            status=status,
            source_kind="PARAMETER_CALL",
            role=role,
            role_evidence=evidence,
            closing_derivation=_closing_derivation_for_status(status, name),
            description=(call.description or "")[:400],
            notes=notes,
        ))
    return rows


def sweep_anchor_rows() -> List[LedgerRow]:
    """Ledger rows for the anchors registered with ``status="MEASURED"``."""
    from metaphysica.simulations.PM.geometry.geometric_anchors_core import (
        MEASURED_ANCHORS,
        GeometricAnchors,
    )

    anchors = GeometricAnchors(24)
    exported = set(anchors.get_all_anchors())
    lines = _anchor_property_lines()
    core = _anchors_core_path()

    rows: List[LedgerRow] = []
    for name in sorted(MEASURED_ANCHORS):
        consumers = _anchor_internal_consumers(name, exported)
        consumers += trace_consumers(f"geometry.{name}", skip_file=core)
        role = _role_from_consumers(consumers)

        notes: List[str] = []
        admissions = admits_a_fit(_anchor_source(name))
        if admissions or "phenom" in name.lower():
            # Declared MEASURED, but the property's own source calls it a
            # fit. A fit is not a measurement: no experiment reports it, and
            # nothing external constrains it. The role is forced to
            # UNRESOLVED so it cannot be waved through as a free
            # COMPARISON_ONLY row, and the contradiction is recorded for the
            # author rather than resolved here -- changing the registered
            # status is a published-provenance change and belongs to them.
            role = ROLE_UNRESOLVED
            notes.append(
                "DECLARED MEASURED BUT IS A FIT: the property source says "
                "so in its own words. Not a measurement; open ruling."
            )

        if not consumers:
            notes.append(
                "No executing consumer traced: registered and exported to "
                "the website, but nothing reads it into a computation."
            )

        rows.append(LedgerRow(
            name=f"geometry.{name}",
            value=anchors.get_all_anchors().get(name),
            location=f"{_rel(core)}:{lines.get(name, 0)}",
            status="MEASURED",
            source_kind="GEOMETRIC_ANCHOR",
            role=role,
            role_evidence=[asdict(c) for c in consumers],
            closing_derivation=_closing_derivation_for_status("MEASURED", name),
            description=_anchor_source(name).split("\n")[1].strip()[:400]
            if "\n" in _anchor_source(name) else "",
            notes=notes,
        ))
    return rows


def _derived_from_free_variables() -> List[Dict[str, Any]]:
    """Anchors registered ``GEOMETRIC``/``tuning_free`` that read a MEASURED one.

    Not ledger rows -- they are consequences, not free variables. Recorded
    because ``register_anchors`` stamps every non-MEASURED anchor with
    ``"derivation": "Derived from b3=24 topological invariant"`` and
    ``"tuning_free": True``, and for these the b3 input does no work at all:
    they are arithmetic on experimental numbers.
    """
    from metaphysica.simulations.PM.geometry.geometric_anchors_core import (
        MEASURED_ANCHORS,
        GeometricAnchors,
    )

    tree = ast.parse(_anchors_core_path().read_text(encoding="utf-8"))
    deps: Dict[str, Set[str]] = {}
    for fn in ast.walk(tree):
        if not isinstance(fn, ast.FunctionDef):
            continue
        deps[fn.name] = {
            n.attr for n in ast.walk(fn)
            if isinstance(n, ast.Attribute)
            and isinstance(n.value, ast.Name)
            and n.value.id == "self"
            and n.attr != fn.name
        }

    def taint(name: str, seen: Optional[Set[str]] = None) -> Set[str]:
        seen = seen or set()
        if name in seen:
            return set()
        seen.add(name)
        found: Set[str] = set()
        for dep in deps.get(name, ()):
            if dep in MEASURED_ANCHORS:
                found.add(dep)
            elif dep in deps:
                found |= taint(dep, seen)
        return found

    out = []
    for name in sorted(GeometricAnchors(24).get_all_anchors()):
        if name in MEASURED_ANCHORS or name == "get_all_anchors":
            continue
        inherited = sorted(taint(name))
        if inherited:
            out.append({
                "name": f"geometry.{name}",
                "registered_as": "GEOMETRIC (fundamental=True, tuning_free=True)",
                "inherits_from": [f"geometry.{d}" for d in inherited],
                "finding": (
                    "registered as a tuning-free consequence of b3 = 24, but "
                    "its value is arithmetic on experimental input; b3 does "
                    "no work in it"
                ),
            })
    return out


# --------------------------------------------------------------------------
# the ledger
# --------------------------------------------------------------------------


def unnamed_declarations(root: Optional[Path] = None) -> List[Dict[str, str]]:
    """Non-derived declarations whose path is computed, not literal.

    They cannot become rows -- there is no name to put in one -- but they
    are a registration surface, and a surface that no sweep can see is
    exactly how a count goes stale. Reported so the absence is visible.
    """
    out = []
    for call in iter_parameter_calls(root):
        status = call.status or (call.classification if call.foreign_kwargs else None)
        if status in NON_DERIVED_STATUSES and call.path is None:
            out.append({
                "location": f"{_rel(call.file)}:{call.lineno}",
                "callee": call.callee,
                "status": status,
                "note": (
                    "path is a variable, so no row can name it; check by "
                    "hand that the quantities it writes are covered"
                ),
            })
    return out


def _merge_duplicate_rows(rows: List[LedgerRow]) -> List[LedgerRow]:
    """One row per quantity, not per declaration.

    Five paths in this tree are declared twice -- once as
    ``Parameter(status=...)`` and again as ``registry.set_param(status=...)``
    -- and counting both would inflate the free-variable count by counting
    declarations instead of free variables. The surviving row keeps every
    location and every note, so the second declaration is still visible.
    """
    merged: Dict[str, LedgerRow] = {}
    for row in rows:
        existing = merged.get(row.name)
        if existing is None:
            merged[row.name] = row
            continue
        if row.location not in existing.notes:
            existing.notes.append(
                f"ALSO DECLARED AT {row.location} (status {row.status})"
            )
        seen = {(e.get("location"), e.get("kind")) for e in existing.role_evidence}
        for ev in row.role_evidence:
            if (ev.get("location"), ev.get("kind")) not in seen:
                existing.role_evidence.append(ev)
        for note in row.notes:
            if note not in existing.notes:
                existing.notes.append(note)
        if existing.value is None:
            existing.value = row.value
        existing.role = _role_from_consumers([
            Consumer(location=e.get("location", ""), function=e.get("function", ""),
                     kind=e.get("kind", ""), detail=e.get("detail", ""))
            for e in existing.role_evidence
        ]) if existing.role != ROLE_PERMITTED_OR_SCALE else existing.role
    return list(merged.values())


def build_ledger(root: Optional[Path] = None) -> Dict[str, Any]:
    """Sweep the tree and return the ledger.

    Every count in the result is a ``len()`` over rows that were found.
    """
    rows = _merge_duplicate_rows(sweep_parameter_rows(root) + sweep_anchor_rows())
    rows.sort(key=lambda r: (r.role, r.status, r.name))

    by_role: Dict[str, int] = {role: 0 for role in ROLES}
    by_status: Dict[str, int] = {}
    for row in rows:
        by_role[row.role] = by_role.get(row.role, 0) + 1
        by_status[row.status] = by_status.get(row.status, 0) + 1

    permitted = by_role[ROLE_PERMITTED_OR_SCALE]
    return {
        "schema": "free_variables/1",
        "generator": "metaphysica.simulations.core.free_variable_ledger",
        "what_this_counts": (
            "Quantities this framework did not derive, swept from the tree. "
            "free_variable_count is len(rows) -- no literal anywhere in this "
            "file states it."
        ),
        "free_variable_count": len(rows),
        "free_variable_count_excluding_permitted": len(rows) - permitted,
        "count_by_role": by_role,
        "count_by_status": dict(sorted(by_status.items())),
        "roles": {
            ROLE_PERMITTED_OR_SCALE:
                "reduction/scale-setting choice; the one permitted bucket",
            ROLE_COMPARISON_ONLY:
                "measured value read only to score a prediction against it",
            ROLE_LOAD_BEARING_INPUT:
                "measured or chosen value that flows into a registered output",
            ROLE_UNRESOLVED:
                "no consumer traced, or the row contradicts its own status",
        },
        "superseded_claims": {
            "validation.calibrated_count": 0,
            "statistical_rigor_validator.calculate_effective_dof": 3,
            "abstract.calibration_inputs": 3,
            "note": (
                "All three were literals. None was computed. They are "
                "recorded here so the replacement is auditable, not so the "
                "old numbers keep circulating."
            ),
        },
        "derived_from_free_variables": _derived_from_free_variables(),
        "unnamed_declarations": unnamed_declarations(root),
        "rows": [r.to_dict() for r in rows],
    }


def free_variable_count(root: Optional[Path] = None) -> int:
    """The one number: how many quantities the framework did not derive."""
    return build_ledger(root)["free_variable_count"]


def _ledger_artifacts() -> Iterator[Path]:
    out = os.environ.get("METAPHYSICA_OUT")
    if out:
        yield Path(out) / "AutoGenerated" / "free_variables.json"
    yield _package_root().parents[1] / "AutoGenerated" / "free_variables.json"
    yield _package_root() / "data" / "free_variables.json"


@lru_cache(maxsize=1)
def published_free_variable_count() -> int:
    """The single published free-variable count, for parameter definitions.

    Reads ``AutoGenerated/free_variables.json`` when the build has written
    it and falls back to sweeping the tree when it has not. Same shape as
    ``registry_paths``: the artifact is the fast path, the sweep is the
    truth, and neither is a hand-maintained literal.

    Cached because a parameter table is built many times per run and the
    sweep costs seconds.
    """
    for cand in _ledger_artifacts():
        try:
            if cand.is_file():
                data = json.loads(cand.read_text(encoding="utf-8"))
                value = data.get("free_variable_count")
                if isinstance(value, int):
                    return value
        except (OSError, ValueError):  # pragma: no cover - defensive
            continue
    return free_variable_count()


def write_ledger(out_dir: Path, root: Optional[Path] = None) -> Path:
    """Emit ``<out_dir>/AutoGenerated/free_variables.json``."""
    ledger = build_ledger(root)
    target = Path(out_dir) / "AutoGenerated"
    target.mkdir(parents=True, exist_ok=True)
    path = target / "free_variables.json"
    path.write_text(json.dumps(ledger, indent=2, sort_keys=False) + "\n",
                    encoding="utf-8")
    return path


def main(argv: Optional[Sequence[str]] = None) -> int:  # pragma: no cover
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--out",
        default=os.environ.get("METAPHYSICA_OUT") or ".",
        help="directory to write AutoGenerated/ into (default: $METAPHYSICA_OUT)",
    )
    args = ap.parse_args(argv)

    ledger = build_ledger()
    path = write_ledger(Path(args.out))
    print(f"free_variables.json -> {path}")
    print(f"free variable count: {ledger['free_variable_count']}")
    for role, n in ledger["count_by_role"].items():
        print(f"  {role:22} {n}")
    print("  by status: " + ", ".join(
        f"{k}={v}" for k, v in ledger["count_by_status"].items()))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
