"""Audit the registry for shadow derivations of the same physical observable.

A *shadow derivation* is when two (or more) registered parameters claim to
compute the same physical observable but produce numerically different
values. Sprint T1 surfaced three such conflicts during a manual audit
(``n_s``, ``eta_B``, ``H0``); this script is the automated safeguard that
would have caught them.

The script clusters parameters by physical observable using the explicit
``OBSERVABLE_GROUPS`` map below (heuristic but transparent), pulls every
group member's value out of ``AutoGenerated/parameters.json`` and flags a
group as a CONFLICT whenever the max pairwise percentage difference
exceeds the effective tolerance for that group. Default is
``TOLERANCE_PCT`` (2%); individual observables can widen or tighten that
bound via ``TOLERANCE_OVERRIDES`` for physically-motivated cases.

Outputs:
    scripts/_audit_shadow_derivations.json   - structured report
    stdout                                   - human summary table

Exit code:
    0  if every checked observable group is internally consistent.
    1  if at least one group has a shadow conflict.

Usage:
    python scripts/audit_shadow_derivations.py
    python scripts/audit_shadow_derivations.py --tolerance-pct 1.0
    python -m metaphysica.scripts.audit_shadow_derivations   # (if packaged)
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_JSON = REPO_ROOT / "scripts" / "_audit_shadow_derivations.json"

# Default tolerance: two derivations of the same observable must agree
# to within 2% to be considered "consistent" (tightened from the
# original 5% in Sprint T2 to surface sub-threshold concerns flagged
# by the T1 audit log). Anything outside the effective per-group
# tolerance is treated as a shadow conflict that needs human review.
TOLERANCE_PCT = 2.0

# Per-observable tolerance overrides. Most groups should agree to the
# default 2%, but a few have physically-motivated reasons to allow a
# wider (or narrower) window:
#   - g_a_gamma: ``alp.coupling_GeV_inv`` is the bare order-of-magnitude
#     anchor (``"10⁻¹¹"`` GeV^-1) and ``alp.coupling_GeV_inv_value`` is
#     the IAXO-window mid-point (``"2.9×10⁻¹¹"`` GeV^-1). The framework
#     only claims order-of-magnitude agreement here, so we widen to
#     200% to permit the up-to-3× factor between the bare 10^n anchor
#     and the placed-in-discovery-window value.
#   - sigma_m_nu: ``geometry.sum_m_nu`` (pure-topology prediction from
#     the b3=24 spectrum) vs ``spectral.sum_m_nu`` (m_1+m_2+m_3 from
#     the Dirac spectral chain) are two distinct derivation paths that
#     fold in different inputs; the established quoted spread is ~30%
#     so we widen the window accordingly.
#   - S8: predictions should genuinely agree; tighten to 2% (matches
#     the default but documents the deliberate intent).
# All other observables fall through to ``TOLERANCE_PCT``.
TOLERANCE_OVERRIDES: Dict[str, float] = {
    "g_a_gamma": 200.0,
    "sigma_m_nu": 40.0,
    "S8": 2.0,
}



#: Conflicts surfaced on 2026-08-24 when the auditor stopped trusting the
#: curated allowlist and began checking the effective groups. Every one is an
#: open Tier-1 item in docs/OUTSTANDING_ISSUES.md that had been documented in
#: prose while the machine reported the codebase conflict-free.
#:
#: This is a RATCHET, not an acceptance. Each entry needs an author ruling on
#: which derivation is canonical; a SIXTH conflict fails the build. Removing
#: an entry once its ruling lands is the intended direction of travel.
KNOWN_CONFLICTS = {
    # register 1.1 -- 9.594 deg has no surviving derivation (9.31 sigma),
    # while particle.theta_13_deg carries 8.669. Two live predictions.
    "theta_13",
    # register 1.7, after triage: the 76.34 Ricci variant turned out to
    # carry a PRIOR documented-alternative ruling (fitted 31-deg angle) under
    # a stale parameter name, so it is dispositioned DISTINCT. The residual
    # conflict is the framework prediction 71.55 against the 73.04 SH0ES
    # anchor family -- 2.06%, just over the 2% tolerance, the same 1.43-sigma
    # MARGINAL the validation layer reports. Ruling still open: does the
    # anchor belong inside the shadow group at all?
    "H0_local",
    # register 1.4 -- 0.7841 (5.13% friction suppression) against 0.8333.
    # Reconciling the suppression branches is worth ~0.5 sigma, not the
    # ~1.5 the register estimates.
    "S8",
    # slow-roll n_s (0.9996) against the canonical 0.9636. The inflation
    # module itself registers this as a documented_divergence -- the
    # disagreement is real and self-acknowledged; the ruling is whether
    # the potential or the canonical chain wins.
    "n_s",
    # found 2026-08-24 while building the DE plane gate: neutrino.mass_sum
    # (0.1012 eV, the register 1.5 headline) had escaped token discovery --
    # its name contains neither m_nu nor sum_m_nu. Once discovered it
    # conflicts with spectral.sum_m_nu (0.0598) at 40.9% against the 40%
    # override. THREE registered mass sums (0.060 / 0.082 / 0.101) need a
    # canonical ruling; note the choice decides whether the framework sits
    # above or below the DESI LCDM bound of 0.072 eV.
    "sigma_m_nu",
}

def _effective_tolerance(observable: str, default_pct: float) -> float:
    """Return the tolerance window (in %) to apply for ``observable``."""
    return TOLERANCE_OVERRIDES.get(observable, default_pct)

# Observable-group mapping is now sourced from the shared module
# ``metaphysica.simulations.core.observable_groups`` so the shadow
# detector and the proof-completeness ledger (which exposes a
# ``Duplicate_Derivations`` column listing the alternate parameter IDs
# per observable) stay in sync. To extend the set, edit
# ``OBSERVABLE_GROUPS`` in that module — both consumers pick it up
# automatically.
#
# Fallback: when this script is invoked from a checkout where the
# ``metaphysica`` package isn't on ``sys.path`` (e.g. raw `python
# scripts/audit_shadow_derivations.py` from the repo root before
# `pip install -e .`), we add ``src/`` to ``sys.path`` and retry.
try:
    from metaphysica.simulations.core.observable_groups import OBSERVABLE_GROUPS
except ModuleNotFoundError:  # pragma: no cover — dev-machine convenience.
    _SRC = REPO_ROOT / "src"
    if _SRC.is_dir() and str(_SRC) not in sys.path:
        sys.path.insert(0, str(_SRC))
    from metaphysica.simulations.core.observable_groups import OBSERVABLE_GROUPS


# ──────────────────────────────────────────────────────────────────────
# parameters.json loading
# ──────────────────────────────────────────────────────────────────────
def _find_parameters_json() -> Path:
    """Locate AutoGenerated/parameters.json.

    Resolution order:
      1. ``METAPHYSICA_OUT`` env var (the build pipeline sets this).
      2. Current working directory.
      3. Repo-root ``AutoGenerated/``.
    """
    candidates: List[Path] = []
    env_out = os.environ.get("METAPHYSICA_OUT")
    if env_out:
        candidates.append(Path(env_out) / "AutoGenerated" / "parameters.json")
    candidates.append(Path.cwd() / "AutoGenerated" / "parameters.json")
    candidates.append(REPO_ROOT / "AutoGenerated" / "parameters.json")

    for p in candidates:
        if p.is_file():
            return p
    raise FileNotFoundError(
        "Could not locate AutoGenerated/parameters.json. Tried:\n  "
        + "\n  ".join(str(c) for c in candidates)
    )


def _load_parameters() -> Dict[str, Any]:
    path = _find_parameters_json()
    with open(path, "r", encoding="utf-8") as fh:
        doc = json.load(fh)
    params = doc.get("parameters", {})
    if not isinstance(params, dict):
        raise ValueError(f"{path}: 'parameters' is not a dict")
    return params


# ──────────────────────────────────────────────────────────────────────
# Numeric coercion
# ──────────────────────────────────────────────────────────────────────

# UTF-8 superscript digits (and the unicode minus) commonly used in the
# registry to express order-of-magnitude couplings like ``"10⁻¹¹"`` or
# ``"2.9×10⁻¹¹"``. We map them back to ASCII so the resulting string can
# be matched by a plain mantissa/exponent regex.
_SUPERSCRIPT_DIGITS: Dict[str, str] = {
    "⁰": "0", "¹": "1", "²": "2", "³": "3", "⁴": "4",
    "⁵": "5", "⁶": "6", "⁷": "7", "⁸": "8", "⁹": "9",
    "⁻": "-", "⁺": "+",
}

# ``mantissa × 10^exp`` / ``10^exp`` after superscript normalisation.
# Accepts the unicode times sign as well as ASCII ``x``/``*`` so the
# raw registry strings parse without a separate normalisation pass.
import re as _re

_SCI_PATTERN = _re.compile(
    r"^\s*([+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)?\s*[×x*]?\s*10\s*\^?\s*([+-]?\d+)\s*$"
)


def _coerce_string_value(s: str) -> Optional[float]:
    """Parse registry shorthand like ``"10⁻¹¹"`` / ``"2.9×10⁻¹¹"`` into a float.

    Sprint T5 #8: a handful of registry slots (notably the ALP-photon
    coupling) store order-of-magnitude couplings as UTF-8 superscript
    strings rather than floats, which silently broke the shadow auditor
    -- the group landed in ``INSUFFICIENT_DATA`` with zero numeric
    members. This helper translates the superscript digits / unicode
    minus / unicode times sign back to ASCII and then matches a relaxed
    ``mantissa × 10^exp`` pattern. Returns the parsed float, or None
    when the string is not in a recognised scientific-notation shape so
    the caller can treat it as a non-numeric record.
    """
    if not s:
        return None
    normalized = s
    for sup, ascii_char in _SUPERSCRIPT_DIGITS.items():
        normalized = normalized.replace(sup, ascii_char)
    m = _SCI_PATTERN.match(normalized)
    if not m:
        return None
    mantissa_raw, exp_raw = m.group(1), m.group(2)
    # Bare ``10^N`` (no mantissa, or a stray sign) → mantissa = 1.
    if mantissa_raw is None or mantissa_raw in ("", "+", "-"):
        mantissa = -1.0 if mantissa_raw == "-" else 1.0
    else:
        try:
            mantissa = float(mantissa_raw)
        except ValueError:
            return None
    try:
        exp = int(exp_raw)
    except ValueError:
        return None
    try:
        v = mantissa * (10.0 ** exp)
    except OverflowError:
        return None
    return v if math.isfinite(v) else None


def _as_float(value: Any) -> Optional[float]:
    """Best-effort coercion of a registry value to a float.

    Registry values are usually floats but a few are stored as strings
    (e.g. ``"10⁻¹¹"`` for ALP coupling) or as dicts. Strings that look
    like plain numbers are tried with ``float()`` first; if that fails
    we fall back to :func:`_coerce_string_value` for UTF-8 superscript
    scientific-notation shorthand. Anything we still can't cleanly
    turn into a finite real number is skipped (returns None).
    """
    if value is None:
        return None
    if isinstance(value, bool):
        # bools are ints in Python; we don't want to compare them numerically.
        return None
    if isinstance(value, (int, float)):
        v = float(value)
        return v if math.isfinite(v) else None
    if isinstance(value, str):
        try:
            v = float(value)
            return v if math.isfinite(v) else None
        except ValueError:
            return _coerce_string_value(value)
    return None


def _pct_diff(a: float, b: float) -> float:
    """Symmetric percentage difference of two non-equal-zero values."""
    denom = max(abs(a), abs(b))
    if denom == 0.0:
        return 0.0
    return abs(a - b) / denom * 100.0


# ──────────────────────────────────────────────────────────────────────
# Cross-check
# ──────────────────────────────────────────────────────────────────────
def _check_group(
    observable: str,
    members: List[str],
    params: Dict[str, Any],
    tolerance_pct: float,
) -> Dict[str, Any]:
    """Check one observable group; return a result dict."""
    present: Dict[str, float] = {}
    skipped: Dict[str, str] = {}

    for pid in members:
        rec = params.get(pid)
        if rec is None:
            skipped[pid] = "not_in_registry"
            continue
        if not isinstance(rec, dict):
            skipped[pid] = "registry_record_not_dict"
            continue
        v = _as_float(rec.get("value"))
        if v is None:
            skipped[pid] = "value_not_numeric"
            continue
        present[pid] = v

    if len(present) < 2:
        return {
            "observable": observable,
            "values": present,
            "skipped": skipped,
            "verdict": "INSUFFICIENT_DATA",
            "max_pct_diff": None,
            "tolerance_pct": tolerance_pct,
        }

    # Compute the max pairwise percentage difference.
    items = list(present.items())
    max_pct = 0.0
    worst_pair: Tuple[str, str] = ("", "")
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            d = _pct_diff(items[i][1], items[j][1])
            if d > max_pct:
                max_pct = d
                worst_pair = (items[i][0], items[j][0])

    verdict = "CONFLICT" if max_pct > tolerance_pct else "CONSISTENT"
    return {
        "observable": observable,
        "values": present,
        "skipped": skipped,
        "verdict": verdict,
        "max_pct_diff": max_pct,
        "worst_pair": list(worst_pair),
        "tolerance_pct": tolerance_pct,
    }


# ──────────────────────────────────────────────────────────────────────
# Reporting
# ──────────────────────────────────────────────────────────────────────
def _fmt_value(v: float) -> str:
    """Format a number for the terminal summary."""
    if v == 0.0:
        return "0"
    av = abs(v)
    if av >= 1e4 or av < 1e-3:
        return f"{v:.4e}"
    return f"{v:.6g}"


def _print_summary(results: List[Dict[str, Any]], tolerance_pct: float) -> None:
    print()
    print("=== Shadow-derivation audit ===")
    print(f"  Default tolerance: +/- {tolerance_pct:.2f}%")
    overridden = sorted(
        obs for obs in TOLERANCE_OVERRIDES if any(r["observable"] == obs for r in results)
    )
    if overridden:
        print("  Per-observable overrides:")
        for obs in overridden:
            print(f"    {obs:<12s}  +/- {TOLERANCE_OVERRIDES[obs]:.2f}%")
    print(f"  Observable groups checked: {len(results)}")

    counts = {"CONSISTENT": 0, "CONFLICT": 0, "INSUFFICIENT_DATA": 0}
    for r in results:
        counts[r["verdict"]] = counts.get(r["verdict"], 0) + 1
    print(f"  Consistent:        {counts['CONSISTENT']}")
    print(f"  Conflicts:         {counts['CONFLICT']}")
    print(f"  Insufficient data: {counts['INSUFFICIENT_DATA']}")

    conflicts = [r for r in results if r["verdict"] == "CONFLICT"]
    if conflicts:
        print()
        print(f"=== {len(conflicts)} shadow conflict(s) ===")
        for r in conflicts:
            pair = r.get("worst_pair") or ["?", "?"]
            print(
                f"  - {r['observable']:<12s} "
                f"max diff = {r['max_pct_diff']:.2f}%  "
                f"(tol {r['tolerance_pct']:.2f}%)  "
                f"({pair[0]} vs {pair[1]})"
            )
            for pid, v in r["values"].items():
                print(f"      {pid:<40s}  =  {_fmt_value(v)}")

    insufficient = [r for r in results if r["verdict"] == "INSUFFICIENT_DATA"]
    if insufficient:
        print()
        print(f"=== {len(insufficient)} group(s) with <2 numeric members ===")
        for r in insufficient:
            n_present = len(r["values"])
            n_skipped = len(r["skipped"])
            print(
                f"  - {r['observable']:<12s} "
                f"({n_present} numeric, {n_skipped} skipped)"
            )


# ──────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────
def _parse_args(argv: Optional[List[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit the registry for shadow derivations of the same observable.",
    )
    parser.add_argument(
        "--tolerance-pct",
        type=float,
        default=TOLERANCE_PCT,
        help=(
            "Default percentage tolerance for shadow-derivation agreement "
            f"(default: {TOLERANCE_PCT:g}%%). Per-observable overrides in "
            "TOLERANCE_OVERRIDES still apply on top of this value."
        ),
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = _parse_args(argv)
    default_tol = args.tolerance_pct

    try:
        params = _load_parameters()
    except FileNotFoundError as exc:
        # No parameters.json means the simulations never ran -- which is the
        # normal state wherever the `sims` extra is unavailable, including CI
        # (eml-spectral is pinned above what PyPI serves, so the build skips
        # the simulation steps). There is nothing to audit, and failing here
        # blocks the pipeline on a missing OPTIONAL extra.
        #
        # Reported as SKIPPED, not as a pass: an auditor that silently returns
        # success on an empty dataset is a vacuous gate, and this file exists
        # to catch exactly that class of problem elsewhere. Once eml-spectral
        # is installable the simulations run, parameters.json exists, and this
        # gates for real.
        print("SKIPPED: no AutoGenerated/parameters.json -- the simulations "
              "did not run, so there are no derivations to audit.",
              file=sys.stderr)
        print(f"  ({exc})", file=sys.stderr)
        return 0
    except ValueError as exc:
        # A malformed parameters.json IS a real failure -- the file is there
        # and unreadable, which is different from it being absent.
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print(f"Loaded {len(params)} parameter records.")

    # Check the EFFECTIVE groups, not the curated lists. The curated map is
    # a human allowlist and had drifted toward what already agreed: the
    # H0 group held two entries that were both 73.04 (reporting CONSISTENT
    # while 71.55 and 76.34 were also registered), and the S8 group held one
    # entry (reporting "insufficient data" against four registered values).
    # effective_groups() folds in every candidate the disposition ledger
    # marks MEMBER, so omission can no longer hide a contradiction.
    try:
        from metaphysica.simulations.core.observable_groups import (
            audit_dispositions, effective_groups,
        )
        groups = effective_groups(params)
        disposition_audit = audit_dispositions(params)
    except ImportError:
        groups = dict(OBSERVABLE_GROUPS)
        disposition_audit = {"undisposed": [], "untriaged": []}

    results: List[Dict[str, Any]] = []
    for observable, members in groups.items():
        tol = _effective_tolerance(observable, default_tol)
        results.append(_check_group(observable, members, params, tol))

    if disposition_audit["undisposed"]:
        print()
        print("=== parameters with NO disposition "
              "(add them to observable_groups.DISPOSITIONS) ===")
        for name in disposition_audit["undisposed"]:
            print(f"  {name}")
    if disposition_audit["untriaged"]:
        print()
        print("=== explicitly UNTRIAGED (awaiting an author call) ===")
        for name in disposition_audit["untriaged"]:
            print(f"  {name}")

    conflicts = [r for r in results if r["verdict"] == "CONFLICT"]
    consistent = [r for r in results if r["verdict"] == "CONSISTENT"]
    insufficient = [r for r in results if r["verdict"] == "INSUFFICIENT_DATA"]

    _print_summary(results, default_tol)

    report = {
        "version": "1.1",
        "tolerance_pct": default_tol,
        "tolerance_overrides": dict(TOLERANCE_OVERRIDES),
        "observable_groups_checked": len(results),
        "undisposed_parameters": disposition_audit["undisposed"],
        "untriaged_parameters": disposition_audit["untriaged"],
        "n_conflicts": len(conflicts),
        "n_consistent": len(consistent),
        "n_insufficient": len(insufficient),
        "shadow_conflicts": [
            {
                "observable": r["observable"],
                "values": r["values"],
                "max_pct_diff": r["max_pct_diff"],
                "worst_pair": r.get("worst_pair"),
                "tolerance_pct": r["tolerance_pct"],
                "tolerance_used": r["tolerance_pct"],
                "verdict": "CONFLICT",
                "skipped": r["skipped"],
            }
            for r in conflicts
        ],
        "consistent_observables": [
            {
                "observable": r["observable"],
                "values": r["values"],
                "max_pct_diff": r["max_pct_diff"],
                "tolerance_pct": r["tolerance_pct"],
                "tolerance_used": r["tolerance_pct"],
                "verdict": "CONSISTENT",
                "skipped": r["skipped"],
            }
            for r in consistent
        ],
        "insufficient_data": [
            {
                "observable": r["observable"],
                "values": r["values"],
                "skipped": r["skipped"],
                "tolerance_used": next(
                    (rr["tolerance_pct"] for rr in results if rr["observable"] == r["observable"]),
                    default_tol,
                ),
                "verdict": "INSUFFICIENT_DATA",
            }
            for r in insufficient
        ],
    }

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, "w", encoding="utf-8") as fh:
        json.dump(report, fh, ensure_ascii=False, indent=2, default=str)
    try:
        rel = OUTPUT_JSON.relative_to(REPO_ROOT)
    except ValueError:
        rel = OUTPUT_JSON
    print(f"\nFull report written to {rel}")

    # Also mirror the report into the active build output so the website
    # (and downstream consumers) can surface it. Honours the standard
    # METAPHYSICA_OUT env var that every generator subprocess sees.
    out_env = os.environ.get("METAPHYSICA_OUT")
    if out_env:
        autogen_path = Path(out_env) / "AutoGenerated" / "shadow_derivations_report.json"
        autogen_path.parent.mkdir(parents=True, exist_ok=True)
        with open(autogen_path, "w", encoding="utf-8") as fh:
            json.dump(report, fh, ensure_ascii=False, indent=2, default=str)
        print(f"Build-output mirror written to {autogen_path}")

    # Ratchet: the five conflicts surfaced on 2026-08-24 are recorded above
    # and await author rulings, so they do not fail the build. Anything NEW
    # does -- this class of defect must not grow while the known ones are
    # being resolved.
    new_conflicts = [r for r in conflicts
                     if r["observable"] not in KNOWN_CONFLICTS]
    stale = KNOWN_CONFLICTS - {r["observable"] for r in conflicts}
    if stale:
        print()
        print("=== recorded conflicts that no longer conflict "
              "(remove them from KNOWN_CONFLICTS) ===")
        for name in sorted(stale):
            print(f"  {name}")
    if new_conflicts:
        print()
        print("=== NEW conflicts (not in the recorded baseline) ===")
        for r in new_conflicts:
            print(f"  {r['observable']}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
