#!/usr/bin/env python3
"""
Final Verification Script - v24.1 Principia Metaphysica
=======================================================

Scans the repository's JSON architecture to enforce strict academic terminology
regarding the 27D -> (24+1) + (0,2) decomposition.

Purpose:
    Ensures every mention of "27D" includes proper topological context:
    - M²⁷(26,1) = (24+1) ⊕ (0,2)
    - (24+1) = Leech Lattice Λ₂₄ + Unified Time T¹ (Kinetic Backbone)
    - (0,2) = Euclidean Information Sector S_EIS (Consciousness Field)

    This prevents reviewers from flagging PM as "unmotivated dimensionality."

Output:
    Console report with flagged entries requiring manual correction

Copyright (c) 2026 Andrew Keith Watts. All rights reserved.
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# Add parent directory to path
REPO_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


class DimensionalityAuditor:
    """
    Scans the repository's JSON architecture to enforce strict academic terminology
    regarding the 27D -> (24+1) + (0,2) decomposition.
    """

    def __init__(self, autogenerated_dir: Path = None):
        """
        Initialize dimensionality auditor.

        Args:
            autogenerated_dir: Path to AutoGenerated directory
        """
        if autogenerated_dir is None:
            autogenerated_dir = REPO_ROOT / "AutoGenerated"

        self.autogenerated_dir = autogenerated_dir

        # Target files in the AutoGenerated directory
        self.target_files = [
            "formulas.json",
            "parameters.json",
            "sections.json",
            "theory_output.json"
        ]

        # Regex patterns to find 27D mentions
        self.target_pattern = re.compile(
            r"27[- ]?D|27 dimensions|27-dimensional|M\^?\{?27\}?|M_27",
            re.IGNORECASE
        )

        # Regex patterns that MUST exist nearby to validate the claim
        self.validation_patterns = [
            re.compile(r"24\+1|24\s*\+\s*1|\(24,1\)"),              # Kinetic backbone
            re.compile(r"0,2|\(0,2\)|0\s*,\s*2"),                   # Euclidean sector
            re.compile(r"Leech|Λ_?24|Lambda_24|Conway", re.IGNORECASE),  # Lattice
            re.compile(r"Euclidean Bridge|S_\{?EIS\}?|Information Sector", re.IGNORECASE),  # EIS
            re.compile(r"kinetic.*backbone|matter.*time", re.IGNORECASE),  # Physical interpretation
            re.compile(r"⊕|oplus|direct sum", re.IGNORECASE)       # Mathematical operator
        ]

        self.flags = []

    def audit_files(self) -> Tuple[int, List[Dict]]:
        """
        Audit all target files for 27D terminology compliance.

        Returns:
            Tuple of (total_flags, list of flagged entries)
        """
        print("=" * 70)
        print(" PRINCIPIA METAPHYSICA: 27D TERMINOLOGY AUDIT")
        print("=" * 70)
        print(f" Scanning: {self.autogenerated_dir}")
        print(f" Target files: {len(self.target_files)}")
        print("=" * 70)
        print()

        total_flags = 0

        for filename in self.target_files:
            filepath = self.autogenerated_dir / filename

            if not filepath.exists():
                print(f"[SKIP] {filename} not found.")
                continue

            print(f"[SCAN] {filename}...")

            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    flags = self._search_dict(data, filename)
                    total_flags += flags

                    if flags == 0:
                        print(f"  ✓ PASS: No unverified 27D mentions")
                    else:
                        print(f"  ✗ FLAGGED: {flags} unverified 27D mention(s)")

            except json.JSONDecodeError as e:
                print(f"  [ERROR] Could not parse {filename}: {e}")
            except Exception as e:
                print(f"  [ERROR] Unexpected error in {filename}: {e}")

        print()
        print("=" * 70)
        print(f" AUDIT COMPLETE: {total_flags} unverified 27D mentions flagged")
        print("=" * 70)

        if total_flags == 0:
            print(" STATUS: PUBLICATION READY")
            print(" All 27D references are rigorously grounded in (24+1)⊕(0,2) topology.")
        else:
            print(" STATUS: REVISION REQUIRED")
            print(" Update flagged entries to include (24+1) kinetic or (0,2) context.")

        print("=" * 70)

        return total_flags, self.flags

    def _search_dict(self, d, filename: str, path: str = "") -> int:
        """
        Recursively search dictionary for 27D mentions.

        Args:
            d: Dictionary, list, or string to search
            filename: Name of file being searched
            path: JSON path to current location

        Returns:
            Number of flags found
        """
        flags = 0

        if isinstance(d, dict):
            for k, v in d.items():
                flags += self._search_dict(v, filename, path + f"['{k}']")

        elif isinstance(d, list):
            for i, v in enumerate(d):
                flags += self._search_dict(v, filename, path + f"[{i}]")

        elif isinstance(d, str):
            # If the string mentions 27D
            if self.target_pattern.search(d):
                # Check if it lacks the rigorous terminology
                if not any(vp.search(d) for vp in self.validation_patterns):
                    # Flag this entry
                    snippet = d[:200] + "..." if len(d) > 200 else d

                    flag_entry = {
                        "file": filename,
                        "path": path,
                        "text": d,
                        "snippet": snippet
                    }

                    self.flags.append(flag_entry)

                    print(f"\n  [FLAG] In {filename} at {path}:")
                    print(f"  Text: \"{snippet}\"")
                    print(f"  Issue: Mentions 27D but lacks (24+1) kinetic or (0,2) Euclidean context.")
                    print()

                    flags += 1

        return flags

    def generate_correction_report(self, output_path: Path = None) -> Path:
        """
        Generate detailed correction report with suggestions.

        Args:
            output_path: Path to save report

        Returns:
            Path to saved report
        """
        if output_path is None:
            output_path = REPO_ROOT / "AutoGenerated" / "terminology_audit.json"

        report = {
            "framework": "Principia Metaphysica v24.1",
            "audit_type": "27D Terminology Compliance",
            "total_files_scanned": len(self.target_files),
            "total_flags": len(self.flags),
            "status": "PUBLICATION READY" if len(self.flags) == 0 else "REVISION REQUIRED",
            "required_terminology": {
                "full_expression": "M²⁷(26,1) = (24+1) ⊕ (0,2)",
                "kinetic_backbone": "(24+1) = Leech Lattice Λ₂₄ + Unified Time T¹",
                "euclidean_sector": "(0,2) = Euclidean Information Sector (S_EIS)",
                "alternative_names": [
                    "Kinetic Ancestor",
                    "Matter-Time Backbone",
                    "Observer Sector",
                    "Consciousness Field (deprecated - use S_EIS)"
                ]
            },
            "validation_keywords": [
                "24+1",
                "(0,2)",
                "Leech Lattice",
                "Euclidean Bridge",
                "S_EIS",
                "kinetic backbone",
                "⊕ (direct sum)"
            ],
            "flagged_entries": self.flags,
            "correction_examples": [
                {
                    "old": "The Fine Structure Constant is derived from the projection of the 27D ancestral roots down to 4D spacetime.",
                    "new": "The Fine Structure Constant is derived via the projection of the M²⁷ bulk manifold, where the (24+1) kinetic sector (Leech Lattice) stabilizes the gauge couplings, and the (0,2) Euclidean Information Sector preserves the unitary trace during the 4D descent."
                },
                {
                    "old": "27-dimensional manifold with signature (26,1)",
                    "new": "M²⁷(26,1) manifold decomposed as (24+1) ⊕ (0,2), where (24+1) is the kinetic backbone and (0,2) is the Euclidean Bridge"
                },
                {
                    "old": "The 27D bulk manifold generates the Standard Model",
                    "new": "The M²⁷ bulk manifold, specifically the (24+1) Leech Lattice sector, generates the Standard Model gauge symmetries via G₂ triality"
                }
            ],
            "peer_review_guidance": {
                "why_this_matters": "Physicists look for specific keywords to determine if a paper is 'crank science' or a serious topological proposition. F-theory papers frequently use 12D constructions broken into (10+2) or similar split signatures. By standardizing to (24+1)⊕(0,2), reviewers will map PM to established high-energy physics frameworks.",
                "key_phrases": [
                    "Leech Lattice Λ₂₄ (Conway group Co₀)",
                    "Euclidean Information Sector (S_EIS)",
                    "(24+1) kinetic backbone with unified time T¹",
                    "(0,2) Euclidean Bridge for holographic information storage",
                    "Direct sum decomposition M²⁷ = P₂₄₊₁ ⊕ E₀,₂"
                ]
            }
        }

        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        print(f"\nDetailed report saved: {output_path}")

        return output_path

    def print_summary_statistics(self):
        """Print summary statistics of audit."""
        if not self.flags:
            return

        print("\n" + "=" * 70)
        print(" FLAGGED ENTRIES BY FILE")
        print("=" * 70)

        # Count flags by file
        flags_by_file = {}
        for flag in self.flags:
            filename = flag["file"]
            flags_by_file[filename] = flags_by_file.get(filename, 0) + 1

        for filename, count in sorted(flags_by_file.items()):
            print(f"  {filename}: {count} flag(s)")

        print("=" * 70)


def main():
    """Run 27D terminology audit."""
    print()

    auditor = DimensionalityAuditor()
    total_flags, flagged_entries = auditor.audit_files()

    # Generate detailed report
    report_path = auditor.generate_correction_report()

    # Print summary statistics
    auditor.print_summary_statistics()

    print()

    # Exit code: 0 if clean, 1 if flags found
    return 1 if total_flags > 0 else 0


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
