"""Push candidate b_3 values through the downstream chain and show the path.

WHY A SWEEP RATHER THAN AN ARGUMENT
===================================
b_3 = 24 lost its DERIVED status on 2026-09-14: nothing on the books derives
it. The candidate origins in the `b3_origin` fork all reproduce the integer 24
without exhibiting 24 three-cycles, so none clears the A4 bar, and arguing
between them from the armchair has not worked.

What can be done instead is make the DEPENDENCE visible: take each candidate
integer a geometric structure actually supplies, push it through the chain of
quantities that consume b_3, and report every outcome side by side. Then the
shape of the dependence -- which observables care about b_3 at all, and how
steeply -- is a computed table rather than a belief.

THE ANTI-TUNING RULE, WHICH THIS MODULE MUST NOT BREAK
=====================================================
variants.py states it: a comparison reports EVERY option's outcome, never
returns "the best one", and never orders options by agreement with experimental
anchors. This sweep obeys that literally.

  * Rows are emitted in declaration order, never sorted by any residual.
  * No row is marked preferred, recommended, best or closest.
  * Residuals against registered anchors ARE computed, because hiding them
    would be its own dishonesty -- but they are reported per row, alongside
    every other row, and `verdict` is always the same string: the sweep does
    not adjudicate.

Reading a winner out of this table is the reader's act, and it would be
anchor-shopping. The table exists to show which downstream quantities b_3
controls, and how sensitively.

WHERE THE CANDIDATE INTEGERS COME FROM
======================================
Each is the count a named structure delivers, sourced not invented:

  24   the framework's incumbent: |S4| arc stabiliser, D4 root count,
       24-cell vertices, Hurwitz unit count, Leech rank -- all give 24
   7   the derived flat contribution alone (joyce_orbifold R3), i.e. what
       b_3 would be with no twisted sector at all
  21   7 flat + 14 = dim g2
  23   7 flat + 16, the largest family count the corrected survey admits
  31   7 flat + 24
  20   7 flat + 13, a two-shadow reading
 155   the top of the TCS exhibited range, for scale

The 7 is the only entry that is DERIVED. The rest are candidate totals, and
the sweep says so per row.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import math
from typing import Any, Dict, List, Optional, Tuple

__all__ = [
    "CANDIDATES",
    "downstream_of",
    "sweep",
    "sensitivity_report",
]

#: (value, the structure that supplies it, whether it is derived)
CANDIDATES: Tuple[Tuple[int, str, bool], ...] = (
    (7, "the derived flat contribution alone (joyce_orbifold R3)", True),
    (20, "7 flat + 13, a two-shadow reading", False),
    (21, "7 flat + 14 = dim g2", False),
    (23, "7 flat + 16, the largest family count the survey admits", False),
    (24, "the incumbent: |S4|, D4 roots, 24-cell, Hurwitz units, Leech rank",
     False),
    (31, "7 flat + 24", False),
    (155, "the top of the TCS exhibited range, for scale", False),
)


def _registry() -> Dict[str, Any]:
    import glob
    import json
    from pathlib import Path

    candidates = [
        Path(__file__).resolve().parents[4] / "AutoGenerated" / "parameters.json",
        Path("H:/Github/PrincipiaMetaphysica/AutoGenerated/parameters.json"),
    ]
    candidates += [Path(p) for p in glob.glob("AutoGenerated/parameters.json")]
    for p in candidates:
        try:
            if p.is_file():
                return json.loads(p.read_text(encoding="utf-8"))["parameters"]
        except OSError:
            continue
    return {}


def _anchor(params: Dict[str, Any], path: str) -> Optional[float]:
    row = params.get(path)
    value = row.get("value") if isinstance(row, dict) else None
    return float(value) if isinstance(value, (int, float)) else None


def downstream_of(b3: int, params: Optional[Dict[str, Any]] = None
                  ) -> Dict[str, Any]:
    """Every registered relation that consumes b_3, evaluated at this b_3.

    The relations are the framework's own, each named with its formula so the
    chain is auditable rather than opaque. Nothing here is a fit.
    """
    params = params if params is not None else _registry()
    d_bulk = _anchor(params, "dimensions.D_bulk")

    out: Dict[str, Any] = {
        "b3": b3,
        "w0": -(b3 - 1) / b3,
        "w0_formula": "-(b_3 - 1)/b_3",
        "n_gen": b3 / 8.0,
        "n_gen_formula": "b_3 / 8",
        "n_gen_is_integer": abs(b3 / 8.0 - round(b3 / 8.0)) < 1e-12,
        "wa_thawing": -4.0 / math.sqrt(b3),
        "wa_formula": "-4 / sqrt(b_3)  [formula RETIRED; shown for continuity]",
        "freudenthal_quartic": 16.0 * (b3 / 27.0) ** 2,
        "quartic_formula": "16 (b_3 / 27)^2",
        "racetrack_a": 2.0 * math.pi / b3,
        "racetrack_a_formula": "2 pi / b_3",
        "k_bary_cycles": b3 - 14,
        "k_bary_formula": "b_3 - 14 (effective baryogenesis cycles)",
    }
    if d_bulk:
        out["bulk_minus_b3"] = d_bulk - b3
        out["bulk_identity_holds"] = abs((d_bulk - b3) - 2) < 1e-12
        out["bulk_identity_formula"] = "D_bulk - b_3 = 2 (the '+2' identity)"
    return out


def sweep(params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """The full table: every candidate, every downstream quantity, no ordering.

    Residuals are attached per row where a registered anchor exists. They are
    NOT used to sort, filter or flag; see the module docstring.
    """
    params = params if params is not None else _registry()
    w0_obs = _anchor(params, "geometry.w0_observed_DESI")
    w0_err = _anchor(params, "geometry.w0_error_DESI")

    rows: List[Dict[str, Any]] = []
    for value, provenance, derived in CANDIDATES:
        row = downstream_of(value, params)
        row["provenance"] = provenance
        row["is_derived"] = derived
        if w0_obs is not None and w0_err:
            row["w0_residual_sigma"] = abs(row["w0"] - w0_obs) / w0_err
            row["residual_note"] = (
                "reported for every row; NOT used to order or select"
            )
        rows.append(row)

    return {
        "what_this_is": (
            "A dependence map, not a selection. Rows are in declaration "
            "order. No row is marked preferred and no residual orders them."
        ),
        "anti_tuning_rule": (
            "variants.py: a comparison reports every option's outcome, never "
            "returns the best one, and never orders by agreement with anchors."
        ),
        "n_candidates": len(rows),
        "rows": rows,
        "verdict": "NO_SELECTION_MADE",
        "integrality_filter": (
            "n_gen = b_3/8 is an integer only for b_3 in multiples of 8 -- a "
            "STRUCTURAL constraint, independent of any measurement, and the "
            "one legitimate discriminator visible here."
        ),
    }


def structural_constraints(params: Optional[Dict[str, Any]] = None
                           ) -> Dict[str, Any]:
    """The constraints that need NO measurement, and what they leave standing.

    This is the one part of the sweep that can legitimately narrow b_3,
    because neither constraint refers to an experimental anchor:

      C1  n_gen = b_3 / 8 must be a positive INTEGER. A generation count is
          a number of things. So 8 | b_3.
      C2  D_bulk - b_3 = 2, the framework's own '+2' identity, with D_bulk
          read from the registry.

    Taken together over any plausible range they leave exactly one value, and
    the sweep reports which. That is a CONDITIONAL derivation, and the
    conditions are named: it assumes the relation n_gen = b_3/8 (the 8 being
    dim O) and the registered D_bulk. Neither is established here, so this is
    not a derivation of b_3 from nothing -- it is a reduction of b_3's freedom
    to those two prior commitments, which is a strictly better position than a
    bare input and strictly weaker than a geometric derivation.
    """
    params = params if params is not None else _registry()
    d_bulk = _anchor(params, "dimensions.D_bulk")

    survivors_c1 = [v for v in range(1, 201) if v % 8 == 0]
    survivors_both = (
        [v for v in survivors_c1 if d_bulk and abs((d_bulk - v) - 2) < 1e-12]
        if d_bulk else []
    )
    return {
        "C1": "n_gen = b_3 / 8 integral, i.e. 8 divides b_3",
        "C2": ("D_bulk - b_3 = 2 with D_bulk = %s from dimensions.D_bulk"
               % d_bulk),
        "n_surviving_C1_to_200": len(survivors_c1),
        "surviving_both": survivors_both,
        "unique": len(survivors_both) == 1,
        "value_if_unique": survivors_both[0] if len(survivors_both) == 1 else None,
        "status": "CONDITIONAL",
        "conditions": [
            "the relation n_gen = b_3 / 8 (the 8 being dim O) is assumed, "
            "not derived here",
            "dimensions.D_bulk is taken from the registry; its own status is "
            "GEOMETRIC and the register records that the 26 as critical "
            "dimension was withdrawn",
        ],
        "what_it_is_not": (
            "Not a geometric derivation of b_3 and not an appeal to data. "
            "Neither constraint mentions an experimental anchor, so this is "
            "not anchor-shopping; but both are prior commitments, so b_3's "
            "freedom is reduced to theirs rather than eliminated."
        ),
    }


def sensitivity_report(params: Optional[Dict[str, Any]] = None
                       ) -> Dict[str, Any]:
    """How steeply each downstream quantity depends on b_3 near the incumbent.

    This is the part that tells you where b_3 actually matters. Computed as a
    relative logarithmic derivative across b_3 -> b_3 + 1, so quantities that
    barely move are visible as such.
    """
    params = params if params is not None else _registry()
    base = downstream_of(24, params)
    step = downstream_of(25, params)
    out: Dict[str, float] = {}
    for key, value in base.items():
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            continue
        other = step.get(key)
        if not isinstance(other, (int, float)) or isinstance(other, bool):
            continue
        if value == 0:
            continue
        out[key] = abs(other - value) / abs(value)
    return {
        "fractional_change_per_unit_b3": dict(sorted(out.items(),
                                                     key=lambda kv: kv[0])),
        "note": (
            "Sorted by NAME, not by magnitude, so this cannot be read as a "
            "ranking. A small number means b_3 barely controls that "
            "quantity, which is information about the model's structure."
        ),
    }
