"""The two b_3 paths, side by side, with honest derived-vs-input accounting.

WHY THERE ARE NOW TWO
=====================
derived_contribution_table settled the reachable Betti numbers of a Joyce
(Z/2)^3 resolution of T^7/Gamma, with Gamma the diagonal stabiliser of the
framework's own phi:

    b_3 = 7 + 3 n_T3,  n_T3 in {0, 4, 8, 12}   =>   b_3 in {7, 19, 31, 43}
    b_3 = 7 (mod 12),  and 24 = 0 (mod 12)

So b_3 = 24 is not reachable, and (12, 43) -- which IS reachable -- is also the
Betti pair of Joyce's canonical published example, reproduced by machinery that
was never told it.

That leaves two live paths, and this module runs both:

  seed_24        b_3 = 24 as an INPUT, its origin open. The status quo.
  seed_43_joyce  b_3 = 43, b_2 = 12, DERIVED from the resolution count.

WHAT THE 43 PATH BUYS, AND IT IS THE POINT
==========================================
b_3 stops being an input. It becomes 7 + 3*12 where the 7 is the derived flat
contribution (joyce_orbifold R3) and the 12 is the derived count of A1 T^3
families. And b_2 = 12 arrives derived at the same time, from the same count.

The generation count survives, but MOVES. At b_3 = 24, n_gen = b_3/8 = 3. At
b_3 = 43 that fails -- 43/8 is not an integer, and a generation count is a
number of things. But b_2 = 12 is now available, and

    n_gen = b_2 / n_faces = 12 / 4 = 3

with n_faces = 4 derived as the moved coordinates of an involution (R2). So the
43 path does not lose the three generations; it relocates their origin from
b_3 and dim O to b_2 and the faces, and both sides of that are derived.

WHAT IT COSTS, STATED PLAINLY
=============================
  w_0 = -(b_3-1)/b_3 moves from -0.958333 to -0.976744, i.e. from 0.017 sigma
  to 0.94 sigma against the registry's DESI anchor. Worse agreement -- and
  derived rather than input, which is the trade the framework's own
  dark_energy_betti ruling already chose once, deliberately, "which is the
  point".

  The '+2' identity D_bulk - b_3 = 2 BREAKS: 26 - 43 = -17. Either D_bulk is
  not 26 on this path, or the identity was never structural. It is recorded as
  broken rather than quietly dropped, and a test asserts it.

  Everything with b_3 in it moves: the racetrack exponent 2pi/b_3, k_bary =
  b_3 - 14, chi/b_3, alpha_T. Those are consequences, not costs -- they follow
  from the seed whatever it is.

NOT ADOPTED. seed_24 remains the adopted branch so no published number moves
until the author rules. This module exists so the 43 path can be RUN.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import math
import os
from typing import Any, Dict, List, Optional, Tuple

__all__ = [
    "PATHS",
    "resolve_path",
    "seed_values",
    "downstream",
    "compare_paths",
    "n_gen_report",
]

#: path id -> (b_3, b_2, how each was obtained)
PATHS: Dict[str, Dict[str, Any]] = {
    "seed_24": {
        "b3": 24,
        "b2": 4,
        "b3_provenance": "INPUT, origin open (2026-09-14 ruling)",
        "b2_provenance": "h^{1,1} of TCS #187, previously FITTED",
        "n_gen_source": "b3_over_dim_O",
        "reachable_by_joyce": False,
    },
    "seed_43_joyce": {
        "b3": 43,
        "b2": 12,
        "b3_provenance": (
            "DERIVED: 7 flat (joyce_orbifold R3) + 3 x 12 A1 families "
            "(derived_contribution_table)"
        ),
        "b2_provenance": "DERIVED: one exceptional 2-class per A1 family, 12",
        "n_gen_source": "b2_over_faces",
        "reachable_by_joyce": True,
    },
}


def resolve_path() -> str:
    """Which path is in force. Adopted is seed_24 until the author rules.

    Narrowed from `except Exception` on 2026-09-22. This is the most widely
    consumed fork read in the geometry tree -- `seed_values`, `n_gen_report`
    and `geometry_narration.betti_claim` all route through it -- so a
    swallowed KeyError or ValueError here would put the ADOPTED seed under
    every downstream number while an override said otherwise, which is the
    worst possible place for a silent default. Only the import cycle is
    tolerated.
    """
    try:
        from metaphysica.simulations.core.variants import resolve
    except ImportError:                    # import cycle: the one real case
        return "seed_24"
    return resolve("b3_seed")


def seed_values(path: Optional[str] = None) -> Tuple[int, int]:
    """(b_3, b_2) for a path."""
    spec = PATHS[path or resolve_path()]
    return spec["b3"], spec["b2"]


def _registry(path: str):
    """One registry row's value, or None when the artifact or row is absent.

    The lookup used to be open-coded here as a CWD-relative
    `AutoGenerated/parameters.json` plus an absolute path from the author's
    machine, so off that machine and outside the repository root it returned
    None and every cross-check it fed was silently skipped. It now goes through
    `parameter_artifact`, which is the single resolver -- `free_set` carried a
    second, differently-broken copy of the same lookup.
    """
    from metaphysica.simulations.core.parameter_artifact import parameter_value

    return parameter_value(path)


def n_gen_report(path: Optional[str] = None) -> Dict[str, Any]:
    """Where three generations come from on this path, and whether it holds.

    A generation count must be a positive integer -- that is structural and
    references no measurement, which is why it is the decisive discriminator
    between the paths rather than w_0.
    """
    key = path or resolve_path()
    b3, b2 = seed_values(key)
    n_faces = 4                      # derived: moved coordinates of an involution
    dim_o = 8                        # dim of the octonions

    from_b3 = b3 / dim_o
    from_b2 = b2 / n_faces

    # The n_gen_source fork was INERT: this line read PATHS[key]["n_gen_source"]
    # and nothing ever called resolve("n_gen_source"), so the fork was slaved to
    # b3_seed and could not select anything. That also made the coupling between
    # the two forks unfalsifiable -- no inconsistent state was reachable, so a
    # guard against one could not fire, and a check that cannot fire is a defect.
    #
    # The fork is now live, with the path's own declaration as the default. An
    # EXPLICIT override selects the other source, which makes the inconsistent
    # combination reachable and therefore checkable: seed_43_joyce with
    # b3_over_dim_O gives 43/8 = 5.375, not a generation count.
    declared = PATHS[key]["n_gen_source"]
    try:
        from metaphysica.simulations.core.variants import _ENV_PREFIX, resolve
    except ImportError:                    # import cycle: the one real case
        pass
    else:
        # Narrowed from `except Exception` on 2026-09-22. The override is the
        # whole point of this block -- it is what makes the inconsistent
        # combination reachable and therefore checkable -- so a fork that has
        # been renamed or an option that does not exist must NOT leave the
        # declaration silently in place while the environment says otherwise.
        # resolve() raises KeyError for an undeclared fork and ValueError for
        # an unknown option, and both now surface.
        if os.environ.get(_ENV_PREFIX + "N_GEN_SOURCE"):
            declared = resolve("n_gen_source")

    value = from_b3 if declared == "b3_over_dim_O" else from_b2

    def integral(x: float) -> bool:
        return abs(x - round(x)) < 1e-12

    return {
        "path": key,
        "declared_source": declared,
        "n_gen": value,
        "is_integer": integral(value),
        "equals_three": integral(value) and round(value) == 3,
        "b3_over_dim_O": {"value": from_b3, "integer": integral(from_b3),
                          "formula": "b_3 / 8, the 8 being dim O"},
        "b2_over_faces": {"value": from_b2, "integer": integral(from_b2),
                          "formula": "b_2 / 4, the 4 being the faces (R2)"},
        "why_this_decides": (
            "a generation count is a number of things, so integrality is a "
            "structural constraint referencing no measurement -- unlike w_0, "
            "which cannot discriminate (it moves 0.0017 per unit b_3)"
        ),
    }


def downstream(path: Optional[str] = None) -> Dict[str, Any]:
    """Every registered relation that consumes the seed, on this path."""
    key = path or resolve_path()
    b3, b2 = seed_values(key)
    d_bulk = _registry("dimensions.D_bulk")
    chi = _registry("topology.mephorash_chi")
    w0_obs = _registry("geometry.w0_observed_DESI")
    w0_err = _registry("geometry.w0_error_DESI")

    w0 = -(b3 - 1) / b3
    gen = n_gen_report(key)
    out: Dict[str, Any] = {
        "path": key,
        "b3": b3,
        "b2": b2,
        "b3_provenance": PATHS[key]["b3_provenance"],
        "b2_provenance": PATHS[key]["b2_provenance"],
        "reachable_by_joyce": PATHS[key]["reachable_by_joyce"],
        "w0": w0,
        "w0_formula": "-(b_3 - 1)/b_3",
        "n_gen": gen["n_gen"],
        "n_gen_source": gen["declared_source"],
        "n_gen_holds": gen["equals_three"],
        "racetrack_exponent": 2.0 * math.pi / b3,
        "k_bary_cycles": b3 - 14,
        "wa_thawing": -4.0 / math.sqrt(b3),
    }
    if w0_obs is not None and w0_err:
        out["w0_sigma_vs_desi"] = abs(w0 - w0_obs) / w0_err
    if chi:
        out["chi_over_b3"] = chi / b3
    if d_bulk:
        gap = d_bulk - b3
        out["d_bulk_minus_b3"] = gap
        out["plus_two_identity_holds"] = abs(gap - 2) < 1e-9
        if not out["plus_two_identity_holds"]:
            out["plus_two_identity_note"] = (
                "BROKEN on this path: D_bulk - b_3 = %g, not 2. Either D_bulk "
                "is not %g here, or the identity was never structural. "
                "Recorded, not dropped." % (gap, d_bulk)
            )
    return out


def narration(path: Optional[str] = None) -> Dict[str, str]:
    """Paper wording generated FROM the active path, not hardcoded.

    The appendices narrated "b3 = 24 from TCS #187 yields exactly 3
    generations". Two things are wrong with that sentence and both are fixed by
    generating it:

      * the TCS provenance is false. fano_tcs exhibits 71 <= b_3 <= 155, so it
        does not supply 24 at all -- the register has carried that exclusion
        for several passes while the paper kept citing it.
      * it hardcodes the seed, so the text cannot follow a ruling.

    Every string here is built from the path's own values, so switching
    b3_seed rewrites the paper's claim instead of contradicting it.
    """
    key = path or resolve_path()
    b3, b2 = seed_values(key)
    gen = n_gen_report(key)
    n_faces, dim_o = 4, 8

    if gen["declared_source"] == "b3_over_dim_O":
        gen_sentence = (
            "n_gen = b_3 / %d = %d / %d = %g" % (dim_o, b3, dim_o, gen["n_gen"])
        )
        gen_basis = "the %d being dim O" % dim_o
    else:
        gen_sentence = (
            "n_gen = b_2 / %d = %d / %d = %g" % (n_faces, b2, n_faces,
                                                 gen["n_gen"])
        )
        gen_basis = (
            "the %d being the faces, derived as the moved coordinates of an "
            "involution" % n_faces
        )

    if key == "seed_43_joyce":
        seed_sentence = (
            "b_3 = %d and b_2 = %d are DERIVED from the resolution of "
            "T^7/(Z/2)^3: b_3 = 7 flat invariants + 3 x %d A1 families, and "
            "b_2 = %d from one exceptional 2-class per family. The pair "
            "(%d, %d) is Joyce's canonical example."
            % (b3, b2, b2, b2, b2, b3)
        )
    else:
        seed_sentence = (
            "b_3 = %d is an INPUT whose origin is open. It is NOT supplied by "
            "TCS #187, which exhibits 71 <= b_3 <= 155, and it is not "
            "reachable by a Joyce (Z/2)^3 resolution, which reaches only "
            "b_3 = 7 (mod 12). b_2 = %d traces to a previously fitted h^{1,1}."
            % (b3, b2)
        )

    return {
        "path": key,
        "seed_sentence": seed_sentence,
        "n_gen_sentence": gen_sentence,
        "n_gen_basis": gen_basis,
        "n_gen_assertion": "Fermion generation count %s (exact)" % gen_sentence,
        "n_gen_condition": "%s, %s" % (gen_sentence, gen_basis),
        "provenance_correction": (
            "Earlier wording attributed b_3 = 24 to TCS #187. That is false: "
            "fano_tcs exhibits 71 <= b_3 <= 155. Corrected here."
        ),
    }


def compare_paths() -> Dict[str, Any]:
    """Both paths side by side. Reports; does not choose.

    Per variants.py's standing rule this never orders by agreement with
    experiment. The one discriminator applied is structural: whether the
    generation count is an integer.
    """
    rows = [downstream(key) for key in sorted(PATHS)]
    structural_pass = [r["path"] for r in rows if r["n_gen_holds"]]
    return {
        "rows": rows,
        "ordering": "path id; never by agreement with experiment",
        "structural_discriminator": (
            "n_gen must be a positive integer. This references no measurement."
        ),
        "paths_passing_structural": structural_pass,
        "both_pass_structurally": len(structural_pass) == len(rows),
        "note_on_w0": (
            "w_0 residuals are reported per row because hiding them would be "
            "its own dishonesty, but they order nothing: w_0 moves only 0.0017 "
            "per unit b_3 and cannot discriminate."
        ),
        "verdict": "NO_SELECTION_MADE",
        "what_the_author_is_ruling_on": (
            "seed_24 keeps the better w_0 and an INPUT b_3 whose origin has no "
            "geometric home left among the declared constructions. "
            "seed_43_joyce derives b_3 AND b_2 from the resolution count, "
            "reproduces Joyce's canonical published pair, relocates the "
            "generation count from b_3/8 to b_2/4 (still exactly 3), and pays "
            "for it with w_0 at ~0.94 sigma and a broken +2 identity."
        ),
    }
