"""pi_1 of the resolved orbifold, from the live enumeration. The Wilson-line dock.

WHY THIS EXISTS
===============
The flavour layer is blocked because chiral zero-modes need an object the
enumeration lacks: intersection-localised couplings died with admissibility
(disjointness IS the admissibility predicate), and codimension-7 conical
points are absent (zero_mode_spec). The one remaining KNOWN mechanism that
needs neither is a discrete Wilson line: a homomorphism pi_1(Y) -> G_gauge
breaking symmetry with no local singularity at all. Whether that dock is open
is a question about pi_1 of the resolved manifold -- pure topology, metric
free, fork free -- and it is computable from the same enumeration data that
fixed b_2 and b_3.

THE COMPUTATION (Armstrong)
===========================
The quotient T^7/Gamma is R^7/G for the affine group G generated by the
integer translations and the shifted lifts (x -> sigma x + s_sigma). By
Armstrong's theorem, the fundamental group of the QUOTIENT SPACE is

    pi_1(T^7/Gamma) = G / E,   E = normal closure of elements with fixed points.

Resolving the A_1 loci does not change pi_1: the Eguchi-Hanson interior is
simply connected and pi_1 of its RP^3 boundary dies inside it, so van Kampen
leaves the group alone. An affine element (n + s_sigma, sigma) has a fixed
point iff n_i + s_i = 0 is solvable on every +1 coordinate of sigma -- with
shifts in {0, 1/2} that means s_i = 0 there, which is EXACTLY the enumeration's
"singular" condition. So E is generated by the singular elements' translates,
and both of the following are computed from the live assignment:

  * H_1(Y) = (G/E)^ab, by Smith normal form over the presentation
        t_1..t_7, g_sigma  |  2 t_i = 0 (i flipped by anything),
        g_sigma + g_tau = g_{sigma tau} + c(sigma, tau) . t   (the shift cocycle),
        g_sigma = 0 and t_i = 0 (i flipped by sigma), for each SINGULAR sigma.
  * a sufficient criterion for pi_1(Y) = 1 EXACTLY, not just H_1 = 0:
    if the singular elements span Gamma over F_2 AND their flipped
    coordinates cover all 7, then every generator of G lies in E, so G = E.

A4 BAR
======
t_i are deck translations (homotopy classes of loops), g_sigma are lifts of
GROUP ELEMENTS, H_1 counts abelianised deck classes, and the triviality
criterion counts group elements and an F_2 span. None of these is a Betti
number and none is converted into one: b_1 = 0 (derived, R5) says the FREE
rank vanishes; the torsion is what this module computes.

WHAT THE ANSWER MEANS
=====================
pi_1(Y) = 1 on the adopted path closes the Wilson-line dock by DERIVATION:
Hom(pi_1, G_gauge) is trivial, so no discrete Wilson line exists, and flavour
data on this path is a costed boundary input until some future layer supplies
a genuinely new object. Joyce's construction papers state simple connectivity
for his examples; landing pi_1 = 1 here from the enumeration alone reproduces
that independently (calibration by computation, as with (12, 43)).

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Tuple

__all__ = [
    "abelianization_presentation",
    "h1_of_resolution",
    "pi1_triviality_criterion",
    "surviving_directions",
    "pi1_finiteness",
    "wilson_line_verdict",
    "fundamental_group_report",
]

_IDENTITY = (0, 0, 0)


def _point() -> Dict[str, Any]:
    from metaphysica.simulations.PM.geometry.intersection_tensor import (
        canonical_point,
    )

    return canonical_point()


def _nonidentity(elements: Dict[Tuple[int, ...], Any]) -> List[Tuple[int, ...]]:
    return sorted(label for label in elements if any(label))


def _compose_label(a: Sequence[int], b: Sequence[int]) -> Tuple[int, ...]:
    return tuple((x + y) % 2 for x, y in zip(a, b))


def _cocycle(elements, sigma, tau) -> List[int]:
    """Integer translation carried by lift(sigma) lift(tau) lift(sigma tau)^-1.

    Shifts are stored in HALF-UNITS (1 means 1/2). The composite's shift is
    s_sigma + sigma . s_tau, and subtracting the stored shift of sigma tau
    must leave an INTEGER vector or the lifts do not close into a group --
    asserted, because a broken assignment must be loud, not absorbed.
    """
    signs_s, h_s = elements[tuple(sigma)]
    _, h_t = elements[tuple(tau)]
    _, h_st = elements[_compose_label(sigma, tau)]
    out: List[int] = []
    for i in range(7):
        twice = h_s[i] + signs_s[i] * h_t[i] - h_st[i]
        if twice % 2 != 0:
            raise ValueError(
                "shift cocycle is not integral at coordinate %d for %s * %s: "
                "the assignment's lifts do not close into a group"
                % (i, tuple(sigma), tuple(tau))
            )
        out.append(twice // 2)
    return out


def abelianization_presentation(point: Optional[Dict[str, Any]] = None
                                ) -> Dict[str, Any]:
    """Integer relation rows for (G/E)^ab over t_1..t_7, g_sigma (7 lifts)."""
    point = point if point is not None else _point()
    elements = {tuple(k): v for k, v in point["elements"].items()} \
        if isinstance(point["elements"], dict) else dict(point["elements"])
    labels = _nonidentity(elements)
    col = {("t", i): i for i in range(7)}
    col.update({("g", lab): 7 + j for j, lab in enumerate(labels)})
    n_cols = 7 + len(labels)

    rows: List[List[int]] = []

    def _row() -> List[int]:
        return [0] * n_cols

    # 2 t_i = 0 for every coordinate flipped by SOME element (coinvariance).
    flipped_by_any = set()
    for lab in labels:
        signs, _ = elements[lab]
        for i in range(7):
            if signs[i] == -1:
                flipped_by_any.add(i)
    for i in sorted(flipped_by_any):
        r = _row()
        r[col[("t", i)]] = 2
        rows.append(r)

    # g_sigma + g_tau - g_{sigma tau} - c . t = 0, for all ordered pairs.
    for sigma in labels:
        for tau in labels:
            c = _cocycle(elements, sigma, tau)
            r = _row()
            r[col[("g", sigma)]] += 1
            r[col[("g", tau)]] += 1
            st = _compose_label(sigma, tau)
            if any(st):
                r[col[("g", st)]] -= 1
            for i in range(7):
                r[col[("t", i)]] -= c[i]
            rows.append(r)

    # Armstrong: each SINGULAR element dies, and so do the translations on
    # its flipped coordinates (its fixed-point translates differ by exactly
    # those). Fixed coordinates carry shift 0 for a singular element -- that
    # is what singular MEANS -- asserted rather than trusted.
    singular_labels = []
    for entry in point["singular"]:
        lab = tuple(entry[0])
        singular_labels.append(lab)
        signs, halves = elements[lab]
        for i in range(7):
            if signs[i] == 1 and halves[i] % 2 != 0:
                raise ValueError(
                    "element %s is listed singular but carries a half shift "
                    "on its fixed coordinate %d, so it acts freely" % (lab, i))
        r = _row()
        r[col[("g", lab)]] = 1
        rows.append(r)
        for i in range(7):
            if signs[i] == -1:
                r = _row()
                r[col[("t", i)]] = 1
                rows.append(r)

    return {
        "columns": (["t_%d" % i for i in range(7)]
                    + ["g_%s" % (lab,) for lab in labels]),
        "rows": rows,
        "n_generators": n_cols,
        "singular_labels": singular_labels,
        "what_generators_are": (
            "t_i are deck translations (loop classes); g_sigma are lifts of "
            "group elements. Neither is a Betti number."
        ),
    }


def h1_of_resolution(point: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """H_1(Y, Z) of the resolved quotient, by Smith normal form."""
    from sympy import Matrix
    from sympy.matrices.normalforms import smith_normal_form

    pres = abelianization_presentation(point)
    m = Matrix(pres["rows"])
    snf = smith_normal_form(m.T)  # columns = generators after transpose
    n_gen = pres["n_generators"]

    diag = [int(snf[i, i]) for i in range(min(snf.rows, snf.cols))]
    invariant_factors = [abs(d) for d in diag if abs(d) > 1]
    rank_of_relations = sum(1 for d in diag if d != 0)
    free_rank = n_gen - rank_of_relations

    return {
        "invariant_factors": sorted(invariant_factors),
        "free_rank": free_rank,
        "is_trivial": free_rank == 0 and not invariant_factors,
        "n_generators": n_gen,
        "n_relations": len(pres["rows"]),
        "note": (
            "free_rank must agree with b_1 = 0 (derived, R5) whenever the "
            "assignment is on the Joyce family; the torsion is information "
            "b_1 cannot see"
        ),
    }


def pi1_triviality_criterion(point: Optional[Dict[str, Any]] = None
                             ) -> Dict[str, Any]:
    """Sufficient criterion for pi_1(Y) = 1 EXACTLY, in the full group.

    If (a) the singular elements span Gamma = (Z/2)^3 over F_2, and (b) every
    coordinate is flipped by at least one singular element, then every
    generator of G lies in E: singular lifts directly; each t_i as a quotient
    of two fixed-point translates of a singular element flipping i; every
    remaining lift as a product of singular lifts and killed translations.
    Then G = E and pi_1 is trivial -- not merely its abelianisation.
    """
    point = point if point is not None else _point()
    elements = {tuple(k): v for k, v in point["elements"].items()} \
        if isinstance(point["elements"], dict) else dict(point["elements"])
    singular_labels = [tuple(e[0]) for e in point["singular"]]

    # (a) F_2 span of the singular labels, by closure under composition.
    span = set()
    span.add((0, 0, 0))
    for lab in singular_labels:
        span |= {_compose_label(lab, s) for s in list(span)}
    spans_gamma = len(span) == 8

    # (b) coverage of the 7 coordinates by singular flips.
    covered = set()
    for lab in singular_labels:
        signs, _ = elements[lab]
        covered |= {i for i in range(7) if signs[i] == -1}
    covers_all = covered == set(range(7))

    return {
        "singular_span_is_gamma": spans_gamma,
        "singular_flips_cover_all_coordinates": covers_all,
        "pi1_provably_trivial": spans_gamma and covers_all,
        "counts": (
            "the span counts GROUP ELEMENTS over F_2; the coverage counts "
            "COORDINATES; neither is a cohomology class"
        ),
    }


def surviving_directions(point: Optional[Dict[str, Any]] = None
                         ) -> Tuple[int, ...]:
    """Coordinates fixed by EVERY singular involution.

    Along such a coordinate c no element with a fixed point moves anything:
    it acts on x_c with sign +1, and its shift there is 0 exactly, because a
    fixed point needs x_c + v_c = x_c in R, not merely mod 1 (that is the
    enumeration's `is_singular` condition, re-checked below). So projecting
    the affine group G onto the c-th coordinate, G -> Isom(R), kills every
    generator of E and therefore E, while the translation t_c goes to
    x -> x + 1, which has infinite order. t_c survives in pi_1 = G/E with
    infinite order: each surviving coordinate is a WITNESS that pi_1 is
    infinite, not a heuristic.
    """
    point = point if point is not None else _point()
    singular = [e for _lab, e in point["singular"]]
    out = []
    for c in range(7):
        if all(signs[c] > 0 for signs, _h in singular):
            if any(h[c] != 0 for _signs, h in singular):
                raise ValueError(
                    "a singular element carries a shift on its own fixed "
                    "coordinate %d; it has no fixed point and the enumeration "
                    "is inconsistent" % c)
            out.append(c)
    return tuple(out)


def pi1_finiteness(point: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Is pi_1 of the resolved quotient finite? Decided both ways.

    Infinite is witnessed by a surviving direction (surviving_directions).
    With none, the singular involutions leave no coordinate unflipped; since
    the seven coordinates carry the seven non-trivial characters of Gamma
    bijectively, that happens exactly when their span is all of Gamma, and
    pi1_triviality_criterion then gives pi_1 = 1.

    The two sides are LOGICALLY EQUIVALENT ("no surviving coordinate",
    "the singular span is Gamma" and "the flips cover all seven" are the same
    condition), so `sides_agree` checks the implementation, not the
    mathematics twice. Recorded after the 2026-09-30 red-team review.

    The number of surviving directions k is the rank of a finite-index free
    abelian subgroup of pi_1 = G/E. That needs E = ker p for the projection
    p onto the surviving coordinates, not merely E inside ker p. Proof of the
    other inclusion: an element of ker p has its linear part in the singular
    span, so it is a product of singular lifts times a translation supported
    on the flipped coordinates, and each such unit translation t_a equals
    (t_a sigma) sigma^-1, a product of two elements with fixed points. So
    pi_1(Y) is isomorphic to p(G), a crystallographic group of rank k; by the
    Cheeger-Gromoll splitting k is also the number of flat directions of the
    universal cover.
    """
    point = point if point is not None else _point()
    dirs = surviving_directions(point)
    crit = pi1_triviality_criterion(point)
    finite = not dirs
    return {
        "surviving_directions": dirs,
        "flat_rank_k": len(dirs),
        "pi1_finite": finite,
        "pi1_trivial": crit["pi1_provably_trivial"],
        "sides_agree": finite == crit["pi1_provably_trivial"],
        "counts": (
            "surviving directions count COORDINATES of T^7, i.e. loops of "
            "infinite order; k is the rank of a free abelian subgroup of pi_1"
        ),
    }


def wilson_line_verdict(point: Optional[Dict[str, Any]] = None
                        ) -> Dict[str, Any]:
    """Is the discrete-Wilson-line dock open on this assignment?"""
    h1 = h1_of_resolution(point)
    crit = pi1_triviality_criterion(point)

    if crit["pi1_provably_trivial"]:
        status = "CLOSED_BY_DERIVATION"
        sentence = (
            "pi_1(Y) = 1: the singular elements span Gamma and their flips "
            "cover every coordinate, so G = E exactly. Hom(pi_1, G_gauge) is "
            "trivial and NO discrete Wilson line exists on this assignment. "
            "With intersection couplings dead (admissibility IS disjointness) "
            "and no codimension-7 conical points, this closes the last known "
            "singularity-free flavour mechanism; flavour data on this path is "
            "a costed boundary input."
        )
    elif h1["is_trivial"]:
        status = "H1_TRIVIAL_PI1_UNRESOLVED"
        sentence = (
            "H_1(Y) = 0 but the triviality criterion does not apply, so a "
            "perfect-group pi_1 is not excluded by this computation alone; "
            "the dock is not open for ABELIAN Wilson lines, and the "
            "non-abelian question is recorded as unresolved."
        )
    else:
        status = "OPEN"
        sentence = (
            "H_1(Y) = %s (+ free rank %d): pi_1 is nontrivial, so discrete "
            "Wilson lines EXIST on this assignment and the flavour boundary "
            "acquires a second dock that needs no singularity at all."
            % (["Z/%d" % d for d in h1["invariant_factors"]], h1["free_rank"])
        )

    return {
        "status": status,
        "h1": h1,
        "criterion": crit,
        "sentence": sentence,
        "layer": "TOPOLOGICAL",
        "fork_dependence": (
            "none: pi_1 of the resolved manifold depends on the assignment's "
            "group data only, not on any metric or form convention"
        ),
    }


def fundamental_group_report(point: Optional[Dict[str, Any]] = None
                             ) -> Dict[str, Any]:
    """Everything the enumeration determines about pi_1(Y), in one place."""
    point = point if point is not None else _point()
    verdict = wilson_line_verdict(point)
    return {
        "h1_invariant_factors": verdict["h1"]["invariant_factors"],
        "h1_free_rank": verdict["h1"]["free_rank"],
        "pi1_provably_trivial": verdict["criterion"]["pi1_provably_trivial"],
        "wilson_line_dock": verdict["status"],
        "sentence": verdict["sentence"],
        "external_crosscheck": (
            "Joyce proves his JDG I example T^7/(Z/2)^3 simply connected; "
            "pi_1 = 1 here is derived from the enumeration alone, so the "
            "agreement is a reproduction, not a citation. Simple "
            "connectivity is example-specific: his JDG II Examples 1 and 2 "
            "have pi_1 = Z^3 and Z"
        ),
        "method": "Armstrong on the affine group; SNF for the abelianisation",
    }
