"""Where the false-on-this-branch geometry wording lives, source and published.

WHY THIS IS A MODULE AND NOT A GREP
===================================
The wording debt has been measured three times in this campaign and each
measurement was typed somewhere by hand, which is how a ceiling got pinned at
90 against a real 92. So the measurement is code now: one function, read from
`geometry_narration.forbidden_phrases()`, callable by the ratchets and by the
next pass.

It is also why the phrase list is never written down here. `forbidden_phrases()`
is generated from the LIVE fork -- it is EMPTY on `octonion_derived`, where the
holonomy claim is true -- so a hardcoded blacklist would keep flagging correct
prose after a fork switch. Everything below derives from that function.

The phrases are also never spelled out in this file's prose, for a reason that
sounds pedantic and is not: a scanner that matches its own source inflates
every count it reports by its own tooling. Both numbers below are counts of the
corpus, not of the instrument.

THE TWO NUMBERS, AND WHAT EACH ONE COUNTS
=========================================
They are not the same measurement and neither replaces the other:

  SOURCE FILE COUNT   how many .py files under src/metaphysica contain at
                      least one phrase. A count of FILES. This is the older
                      ratchet's measure. It moves by one when a whole file is
                      cleaned or a new file offends, and it is insensitive to
                      how much a file says -- 43 occurrences in one file
                      counts as 1.

  PUBLISHED OCCURRENCES  how many times a phrase appears in the built JSON
                      artifacts. A count of STRING OCCURRENCES in the output
                      that is actually served. This is the measure the author
                      directed to be primary, because it counts what a reader
                      of the site can encounter, weighted by how often.

A third number is reported and is NOT a ratchet target: SOURCE OCCURRENCES,
the total across source files, which sits between the two and is the size of
the editing job.

ON-PATH, MEASURED RATHER THAN ASSUMED
=====================================
"Fix only the on-path sources" needs on-path to be decidable. The test applied
here is whether a source file's phrase-bearing text REACHES a published
artifact: if it does, the file is executed under the adopted fork settings and
its wording is being served. Measured 2026-09-22 on the adopted branch, that
test does not reduce the set at all -- **0 of the phrase-bearing source files
are off-path**. The debt is entirely on-path, so the narrowing has to come
from the assertion-versus-description reading instead, which is what
`classify_line` provides and what the older ratchet's docstring already said.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.
"""

from __future__ import annotations

import json
import pathlib
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

__all__ = [
    "phrases",
    "classify_line",
    "source_occurrences",
    "source_file_count",
    "find_artifact_roots",
    "published_occurrences",
    "audit_report",
]

#: Substitutions applied to each generated phrase to catch the typographic
#: variants the corpus actually uses. Generated FROM the phrase, so a new
#: forbidden phrase picks these up without being listed anywhere.
_TYPOGRAPHIC = (("G2", "G₂"),)

_SRC_ROOT = pathlib.Path(__file__).resolve().parents[3]

#: Places a build may have left its JSON artifacts, in the order they are
#: preferred. The site output of `python -m metaphysica.build --out ./site` is
#: first because it is what the host repository publishes.
_ARTIFACT_CANDIDATES = (
    "site/AutoGenerated",
    "AutoGenerated",
    "../PrincipiaMetaphysica/AutoGenerated",
)

#: Line markers that make a mention something other than a bare assertion.
#: Ordered: the first matching class wins.
_DENIAL = ("not ", "no ", "cannot", "false", "refut", "may_claim", "forbidden",
           "never", "withdraw", "stale", "denies", "deny", "instead of",
           "rather than", "is wrong", "must not")
_ATTRIBUTED = ("joyce", "kovalev", "tcs", "twisted connected", "bryant",
               "corti", "haskins", "nordstrom", "pacini", "acharya", "witten",
               "atiyah", "literature", "theorem", "et al", "(20", "(19",
               "m-theory on", "reference", "cite")
_CONDITIONAL = ("if ", "would", "intend", "target", "requires", "require",
                "assum", "candidate", "proposed", "should", "expect",
                "octonion_derived", "branch")


def phrases() -> Dict[str, str]:
    """Every phrase to scan for, with the reason, generated from the live fork.

    Returns the mapping `forbidden_phrases()` gives, extended with the
    typographic variants of each key. EMPTY when the fork in force makes the
    claims true, which is the behaviour the ratchets depend on: they must stop
    firing rather than keep flagging correct prose.
    """
    from metaphysica.simulations.PM.geometry.geometry_narration import (
        forbidden_phrases,
    )

    out: Dict[str, str] = {}
    for phrase, reason in forbidden_phrases().items():
        out[phrase] = reason
        for src, dst in _TYPOGRAPHIC:
            if src in phrase:
                out[phrase.replace(src, dst)] = reason
    return out


def classify_line(line: str) -> str:
    """DENIAL / ATTRIBUTED / CONDITIONAL / ASSERTION for one source line.

    A line-local heuristic, and it says so: a denial spread over two lines
    reads as an ASSERTION here. It is used to SIZE and PRIORITISE the reading
    task, never to decide that a site is fine -- which is why no ratchet
    thresholds on it.
    """
    low = line.lower()
    if any(m in low for m in _DENIAL):
        return "DENIAL"
    if any(m in low for m in _ATTRIBUTED):
        return "ATTRIBUTED"
    if any(m in low for m in _CONDITIONAL):
        return "CONDITIONAL"
    return "ASSERTION"


def _count(text: str, keys: Iterable[str]) -> int:
    return sum(text.count(k) for k in keys)


def source_occurrences(src_root: Optional[pathlib.Path] = None
                       ) -> Dict[str, Any]:
    """Per-file occurrence counts and per-line classification, over the source.

    A4 bar: `files` counts FILES, `occurrences` counts SUBSTRING OCCURRENCES,
    and `by_class` counts occurrences again (not lines) so the four classes sum
    to the occurrence total.
    """
    root = pathlib.Path(src_root) if src_root else _SRC_ROOT
    keys = list(phrases())
    per_file: Dict[str, int] = {}
    by_class: Dict[str, int] = {"ASSERTION": 0, "ATTRIBUTED": 0,
                                "CONDITIONAL": 0, "DENIAL": 0}
    sites: List[Dict[str, Any]] = []

    if keys:
        for path in sorted(root.rglob("*.py")):
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            n = _count(text, keys)
            if not n:
                continue
            rel = path.relative_to(root).as_posix()
            per_file[rel] = n
            for lineno, line in enumerate(text.splitlines(), 1):
                hits = _count(line, keys)
                if not hits:
                    continue
                cls = classify_line(line)
                by_class[cls] += hits
                sites.append({"file": rel, "line": lineno, "class": cls,
                              "hits": hits, "text": line.strip()[:200]})

    return {
        "root": str(root),
        "phrases": keys,
        "files": len(per_file),
        "occurrences": sum(per_file.values()),
        "per_file": dict(sorted(per_file.items(), key=lambda kv: -kv[1])),
        "by_class": by_class,
        "sites": sites,
        "counts_what": ("`files` counts FILES; `occurrences` and `by_class` "
                        "count SUBSTRING OCCURRENCES"),
    }


def source_file_count(src_root: Optional[pathlib.Path] = None) -> int:
    """How many source FILES carry at least one phrase. The older ratchet's measure."""
    return source_occurrences(src_root)["files"]


def find_artifact_roots(start: Optional[pathlib.Path] = None
                        ) -> List[pathlib.Path]:
    """Directories of built JSON artifacts, in preference order.

    Returns an empty list when no build has run. Callers must treat that as a
    MISSING PRECONDITION and not as a clean corpus -- the register records that
    `python -m metaphysica.build --out ./site` has to precede pytest on a fresh
    checkout, because `AutoGenerated/` is gitignored and carries no tracked
    files.
    """
    base = pathlib.Path(start) if start else _SRC_ROOT.parents[1]
    found = []
    for candidate in _ARTIFACT_CANDIDATES:
        path = (base / candidate).resolve()
        if path.is_dir() and any(path.rglob("*.json")):
            found.append(path)
    return found


def published_occurrences(roots: Optional[Sequence[pathlib.Path]] = None
                          ) -> Dict[str, Any]:
    """Phrase occurrences in the built JSON artifacts.

    Counts raw substring occurrences in the file text rather than walking the
    parsed JSON, because a phrase can sit in a key, in a value, or inside an
    HTML fragment that is itself a value, and all three are served to a reader.
    """
    keys = list(phrases())
    roots = list(roots) if roots is not None else find_artifact_roots()

    per_root: Dict[str, Any] = {}
    for root in roots:
        per_file: Dict[str, int] = {}
        n_json = 0
        for path in sorted(pathlib.Path(root).rglob("*.json")):
            n_json += 1
            if not keys:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            n = _count(text, keys)
            if n:
                per_file[path.relative_to(root).as_posix()] = n
        per_root[str(root)] = {
            "json_files_scanned": n_json,
            "files_with_a_phrase": len(per_file),
            "occurrences": sum(per_file.values()),
            "per_file": dict(sorted(per_file.items(), key=lambda kv: -kv[1])),
        }

    return {
        "roots_found": [str(r) for r in roots],
        "phrases": keys,
        "by_root": per_root,
        "occurrences": max((v["occurrences"] for v in per_root.values()),
                           default=0),
        "counts_what": ("SUBSTRING OCCURRENCES in built JSON artifact text, "
                        "not files and not JSON nodes"),
    }


def audit_report() -> Dict[str, Any]:
    """Both ratchet numbers, the editing-job size, and what each one counts."""
    src = source_occurrences()
    pub = published_occurrences()
    return {
        "branch_makes_any_claim_forbidden": bool(src["phrases"]),
        "phrases": src["phrases"],
        "source_file_count": src["files"],
        "source_occurrences": src["occurrences"],
        "source_by_class": src["by_class"],
        "published_occurrences": pub["occurrences"],
        "published_roots": pub["roots_found"],
        "published_detail": pub["by_root"],
        "the_two_numbers": (
            "source_file_count counts FILES and moves by one when a file is "
            "cleaned; published_occurrences counts STRING OCCURRENCES in the "
            "served artifacts and is the author's primary measure. "
            "source_occurrences is neither ratchet's target -- it is the size "
            "of the editing job."
        ),
        "on_path": (
            "measured 0 off-path source files on the adopted branch: every "
            "phrase-bearing source file's text reaches a published artifact, so "
            "the on-path/off-path axis does not narrow the set and the reading "
            "that does is assertion-versus-description (see classify_line)."
        ),
        "if_empty": (
            "an empty phrase list means the fork in force makes the claims "
            "TRUE, not that the corpus was cleaned. Both counts are then 0 by "
            "construction and neither ratchet has anything to say."
        ),
    }
