"""
Principia Metaphysica - Simulation Framework

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.

Dedicated To:
    My Wife: Elizabeth May Watts
    Our Messiah: Jesus Of Nazareth

===========================================

This package provides the simulation infrastructure for the Principia Metaphysica
theoretical framework, a G2 manifold-based unification of fundamental physics.

Current Production Framework: v22.0 (12-PAIR-BRIDGE)
-----------------------------------------------------
All production simulations use the v22 framework with SOLID architecture:

v24.2 Key Updates (M^{26}(24,2) Framework):
- Bulk: M^{26}(24,2) = T¹ ×_fiber (⊕_{i=1}^{12} B_i^{2,0}) ⊕ S^{2,0}
- Metric: ds² = -dt² + ∑_{i=1}^{12} (dy_{1i}² + dy_{2i}²) + (ds₁² + ds₂²)
- Distributed OR: ⊗_{i=1}^{12} R_⊥_i (objective reduction across bridge pairs)
- Topological activation: 6→12 bridge pairs via geometric coupling
- Sampler data fields: S^{2,0} provides global cross-shadow averaging
- OR coherence threshold: minimum 6 active pairs for τ>25ms stability

Core Framework:
- Unified SimulationBase interface
- PMRegistry for parameter/formula/section management
- JSON schema validation
- Provenance tracking (source, timestamp, status)
- Dependency resolution
- Self-documenting formulas and sections

Quick Start:
------------
    >>> from metaphysica.simulations.base import PMRegistry
    >>> from metaphysica.simulations.base.established import EstablishedPhysics
    >>> from metaphysica.simulations.v21.gauge import GaugeUnificationSimulation
    >>>
    >>> # Create registry and load ESTABLISHED physics
    >>> registry = PMRegistry.get_instance()
    >>> EstablishedPhysics.load_into_registry(registry)
    >>>
    >>> # Run simulation
    >>> sim = GaugeUnificationSimulation()
    >>> results = sim.execute(registry, verbose=True)
    >>>
    >>> # Access results
    >>> M_GUT = results['gauge.M_GUT']
    >>> print(f"M_GUT = {M_GUT:.3e} GeV")

Available v21 Simulations (8 domains):
---------------------------------------
1. gauge:     Gauge coupling unification → M_GUT, alpha_GUT
2. higgs:     Higgs mass from moduli stabilization
3. proton:    Proton decay lifetime with geometric suppression
4. neutrino:  Neutrino mixing from G2 spinor geometry
5. fermion:   Three fermion generations from topology
6. cosmology: Dark matter and dark energy
7. geometric: G2 manifold geometry and topology
8. pneuma:    Pneuma field dynamics

All simulations:
- Implement SimulationBase interface
- Track dependencies (inputs/outputs)
- Define formulas with LaTeX and derivation chains
- Generate section content for paper
- Validate against experimental bounds

Directory Structure:
--------------------
simulations/
├── ARCHITECTURE.md         # Technical architecture (READ THIS FIRST)
├── SIMULATION_GUIDE.md     # Guide for adding new simulations
├── base/                   # Core framework (SimulationBase, PMRegistry)
│   ├── simulation_base.py
│   ├── registry.py
│   ├── validator.py
│   ├── injector.py
│   └── established.py
├── v21/                    # Production simulations (USE THIS)
│   ├── README.md           # v16 overview with dependency graph
│   ├── gauge/              # Gauge unification
│   ├── higgs/              # Higgs mass
│   ├── proton/             # Proton decay
│   ├── neutrino/           # Neutrino mixing
│   ├── fermion/            # Fermion generations
│   ├── cosmology/          # Cosmology
│   ├── geometric/          # G2 geometry
│   └── pneuma/             # Pneuma mechanism
├── deprecated/             # Archived legacy code (v12-v15)
├── validation/             # Validation utilities
└── Constants/              # Physical constants

Documentation:
--------------
- Architecture:      simulations/ARCHITECTURE.md
- Simulation Guide:  simulations/SIMULATION_GUIDE.md
- v16 Overview:      simulations/v21/README.md
- Foundation Schema: FOUNDATION_SCHEMA_README.md
- Quick Start:       FOUNDATION_QUICK_START.md

Execution Order (Topological):
-------------------------------
1. ESTABLISHED physics (PDG, NuFIT, TCS topology)
2. Tier 1: G2Geometry, GaugeUnification, Pneuma (parallel)
3. Tier 2: Proton, Higgs, Neutrino, Fermion (parallel)
4. Tier 3: Cosmology

Total execution time: ~200 ms for all 8 domains
"""

# Version information
__version__ = "24.2"
__framework_version__ = "v24.2"
__author__ = "Andrew Keith Watts"

# ── Output redirection ──────────────────────────────────────────────────────
# Many sub-simulation modules compute their output path as
# ``Path(__file__).resolve().parent.parent / "AutoGenerated"`` etc., which
# would land inside the installed package on disk — wrong for editable,
# wheel, and zipped installs alike. We honour ``METAPHYSICA_OUT`` (set by
# ``metaphysica.build``) and create a junction/symlink from the legacy
# in-package location to the user-chosen output dir so every "old" path
# resolves correctly without rewriting 40+ source files.
import os as _os
import sys as _sys
from pathlib import Path as _Path

def _bind_output_dir():
    out = _os.environ.get("METAPHYSICA_OUT")
    if not out:
        return
    real = (_Path(out) / "AutoGenerated").resolve()
    real.mkdir(parents=True, exist_ok=True)
    pkg_dir = _Path(__file__).resolve().parent
    legacy = pkg_dir / "AutoGenerated"
    # If a stale dir already exists at legacy and isn't pointing at real, replace it.
    if legacy.exists():
        try:
            if legacy.is_symlink():
                # already a symlink — check target
                if _Path(_os.readlink(legacy)).resolve() == real:
                    return
                legacy.unlink()
            elif legacy.is_dir():
                # On Windows a directory junction looks like a regular dir.
                # Check via an inode/realpath comparison.
                if legacy.resolve() == real:
                    return
                # Real directory → don't clobber, but warn.
                print(f"[metaphysica] WARNING: {legacy} exists as a real dir; "
                      f"sims may write here instead of {real}", file=_sys.stderr)
                return
        except OSError:
            return
    # Create a junction (Windows) or symlink (POSIX) from legacy → real.
    try:
        if _sys.platform == "win32":
            # Use a directory junction — no admin needed.
            _os.system(f'mklink /J "{legacy}" "{real}" >NUL 2>&1')
        else:
            _os.symlink(real, legacy, target_is_directory=True)
    except OSError as exc:
        print(f"[metaphysica] could not link {legacy} -> {real}: {exc}",
              file=_sys.stderr)

_bind_output_dir()
# v24.2: M^{26}(24,2) = T¹ ×_fiber (⊕_{i=1}^{12} B_i^{2,0}) ⊕ S^{2,0}
# 24 physics dims (12 bridge pairs) + 1 time + 2 shadow-time directions
# Sampler data fields S^{2,0}: global cross-shadow OR averaging sector
# OR coherence via distributed ⊗_{i=1}^{12} R_⊥_i (objective reduction)

# Export v23 production framework
from . import PM

# Export key infrastructure modules
from . import base
from . import validation

# Export base framework classes for convenience
from .base import (
    # Core classes
    SimulationBase,
    SimulationMetadata,
    PMRegistry,

    # Data structures
    ContentBlock,
    SectionContent,
    Formula,
    Parameter,
    RegistryEntry,
    FormulaEntry,
    SectionEntry,

    # Validation
    ValidationResult,
    SimulationValidator,
    RegistryValidator,

    # Injection utilities
    inject_param,
    inject_formula,
    inject_section,
)

# Try to import PM simulations (optional)
try:
    from .PM.gauge.gauge_unification import GaugeUnificationSimulation
    from .PM.particle.higgs_mass import HiggsMassSimulation
    from .PM.particle.proton_decay import ProtonDecaySimulation
    from .PM.particle.neutrino_mixing import NeutrinoMixingSimulation
    from .PM.particle.fermion_generations import FermionGenerationsV16 as FermionGenerationsSimulation
    from .PM.cosmology.multi_sector import MultiSectorV16 as MultiSectorCosmologySimulation
    from .PM.geometry.g2_geometry import G2GeometryV16 as G2GeometrySimulation
    from .PM.field_dynamics.pneuma_mechanism import PneumaMechanismV16 as PneumaMechanismSimulation
    _V23_SIMULATIONS_AVAILABLE = True
except ImportError as e:
    _V23_SIMULATIONS_AVAILABLE = False
    import warnings
    warnings.warn(f"Some v23 simulations could not be imported: {e}")

# Define public API
__all__ = [
    # Version info
    '__version__',
    '__framework_version__',
    '__author__',

    # Modules
    'v23',
    'base',
    'validation',

    # Base framework classes
    'SimulationBase',
    'SimulationMetadata',
    'PMRegistry',
    'ContentBlock',
    'SectionContent',
    'Formula',
    'Parameter',
    'RegistryEntry',
    'FormulaEntry',
    'SectionEntry',
    'ValidationResult',
    'SimulationValidator',
    'RegistryValidator',
    'inject_param',
    'inject_formula',
    'inject_section',
]

# Add v23 simulations to __all__ if available
if _V23_SIMULATIONS_AVAILABLE:
    __all__.extend([
        'GaugeUnificationSimulation',
        'HiggsMassSimulation',
        'ProtonDecaySimulation',
        'NeutrinoMixingSimulation',
        'FermionGenerationsSimulation',
        'MultiSectorCosmologySimulation',
        'G2GeometrySimulation',
        'PneumaMechanismSimulation',
    ])


# Convenience functions
def list_simulations():
    """
    List all available v21 simulations.

    Returns:
        List of tuples: (domain, class_name, description, section)
    """
    simulations = [
        ("gauge", "GaugeUnificationSimulation", "Gauge coupling unification to M_GUT and alpha_GUT", "3"),
        ("higgs", "HiggsMassSimulation", "Higgs mass from moduli stabilization", "4.4"),
        ("proton", "ProtonDecaySimulation", "Proton decay lifetime with geometric suppression", "4.6"),
        ("neutrino", "NeutrinoMixingSimulation", "Neutrino mixing from G2 spinor geometry", "4.5"),
        ("fermion", "FermionGenerationsSimulation", "Three fermion generations from topology", "4.3"),
        ("cosmology", "MultiSectorCosmologySimulation", "Dark matter and dark energy", "5"),
        ("geometric", "G2GeometrySimulation", "G2 manifold geometry and topology", "2"),
        ("pneuma", "PneumaMechanismSimulation", "Pneuma field dynamics", "2"),
    ]

    if not _V23_SIMULATIONS_AVAILABLE:
        warnings.warn("Some v21 simulations are not available")

    return simulations


def print_info():
    """Print information about the simulation framework."""
    print("=" * 70)
    print(f"PRINCIPIA METAPHYSICA SIMULATIONS v{__version__}")
    print("=" * 70)
    print()
    print("Available v16 Simulations:")
    print()

    for domain, class_name, description, section in list_simulations():
        print(f"  [{section:4s}] {domain:12s}: {class_name}")
        print(f"         {description}")
        print()

    print("Documentation:")
    print("  - Architecture:      simulations/ARCHITECTURE.md")
    print("  - Simulation Guide:  simulations/SIMULATION_GUIDE.md")
    print("  - v16 Overview:      simulations/v21/README.md")
    print()
    print("Quick Start:")
    print("  >>> from metaphysica.simulations.base import PMRegistry")
    print("  >>> from metaphysica.simulations.base.established import EstablishedPhysics")
    print("  >>> from metaphysica.simulations import GaugeUnificationSimulation")
    print("  >>> registry = PMRegistry.get_instance()")
    print("  >>> EstablishedPhysics.load_into_registry(registry)")
    print("  >>> sim = GaugeUnificationSimulation()")
    print("  >>> results = sim.execute(registry)")
    print()
    print("=" * 70)

# Deprecation warnings for common legacy import patterns
import warnings


def _warn_deprecated_import():
    """Issue deprecation warning if attempting to import from deprecated modules."""
    warnings.warn(
        "Importing from metaphysica.simulations.core.* is deprecated. "
        "All v12.x-v15.x simulations have been moved to simulations/deprecated/core/. "
        "Please update your code to use simulations.v21.* instead. "
        "See simulations/deprecated/README.md for migration information.",
        DeprecationWarning,
        stacklevel=3
    )


# simulations.core is a legitimate subpackage (FormulasRegistry, demon_lock_guard, etc.)
# It was moved from root core/ during v23 consolidation.
from . import core
