#!/usr/bin/env python3
"""
Cosmological Tensions Resolver — H0 / S8 via mirror-sector dark energy.
=======================================================================

Sprint 5 task #5 (Phase H). Implements the
:class:`CosmologicalTensionsResolver` template from
``PossibleImprovements.txt`` (lines 1170-1249): a Sprint 4 ReT-anchored,
Sprint 5.1 mirror-coupling-driven correction to the dark-energy equation
of state that simultaneously shifts H₀ upward and S₈ downward, relaxing
the long-standing H₀ and S₈ tensions in a parameter-free way.

Physics summary
---------------
The G₂ + Z₂ mirror framework predicts that the mirror sector contributes
an extra component to the dark-energy density at late times (or as early
dark energy from the 26D bulk during the radiation/matter era). This
extra component modifies the expansion history H(z) and the linear
growth rate fσ₈:

    Δw_mirror = 0.012 · exp(−Re(T) / 200) · g_mirror

where:

* Re(T) = 174.033 GeV — the Higgs-VEV-anchored volume-modulus stabilised
  in Sprint 4 task #3 (:mod:`metaphysica.simulations.PM.geometry.re_t_sector`).
* g_mirror = 1.2 × 10⁻¹⁰ — the Sprint 5.1 mirror-DM relic coupling
  strength (the same Z₂ bridge coupling that fixes the relic abundance).
* The 0.012 prefactor is the standard late-time mirror DE amplitude
  fixed by the bridge geometry; the exponential suppression encodes the
  fact that the mirror sector contributes only weakly once Re(T) is
  stabilised at its v_target.

The shifts in the observable tensions are then linear-response:

    ΔH₀ = 5.8 · Δw_mirror             [km/s/Mpc per unit Δw]
    ΔS₈ = −0.085 · Δw_mirror          [growth-suppression factor]

with baseline ``H₀ = 73.04 km/s/Mpc`` (the SH0ES anchor, matching
``H0_BASELINE_KM_S_MPC``) and ``S₈ = 0.83`` (Planck baseline).

Numerical reality check
~~~~~~~~~~~~~~~~~~~~~~~
At the canonical inputs (Re(T) = 174.033, g_mirror = 1.2e-10) the
exponential pre-factor exp(−174.033 / 200) ≈ 0.41896, so

    Δw_mirror ≈ 6.0319 × 10⁻¹³

i.e. the mirror correction is *exponentially small* in this regime. The
resolved tensions are therefore numerically indistinguishable (to ~12
decimals) from the baseline values:

    H₀_resolved ≈ 73.0400000004 km/s/Mpc
    S₈_resolved ≈ 0.8299999999

This is the *honest* answer from the template's coupling strengths: at
the stabilised Re(T) value the mirror DE contribution is too small to
move H₀ or S₈ by an observationally meaningful amount. The module
nevertheless implements the full pipeline exactly as specified in the
template because:

* The shapes / signs / limit behaviours are correct (positive ΔH₀,
  negative ΔS₈, both monotone in g_mirror).
* The resolved values still pass the documented validation gates
  (65 < H₀ < 75 and 0.7 < S₈ < 0.9) — i.e. the framework does not
  over-shoot or destabilise the baseline.
* A future tightening of g_mirror (or a different Re(T) regime, e.g. an
  early-DE branch at higher Re(T)) can produce the percent-level shifts
  the v25.0 narrative claims, without changing this module's API.

Validation gates (per Sprint 5 task #5):
    * 65 < H0_resolved < 75
    * 0.7 < S8_resolved < 0.9

Both are satisfied by construction at the canonical inputs.

Observational comparison (June 2026)
------------------------------------
* H₀ — SH0ES 2022 (Riess et al.) (local, distance-ladder): 73.04 ± 1.04 km/s/Mpc
  DESI 2025 (BAO + CMB-anchored): 68.5 ± 0.7 km/s/Mpc
  Planck 2018 (CMB): 67.4 ± 0.5 km/s/Mpc
  → Resolved H₀ = 73.040 sits at the SH0ES central value, exactly on
  the local-distance-ladder anchor used as the baseline.
* S₈ — KiDS-1000 + DES-Y3 weak-lensing: 0.766 ± 0.020
  Planck 2018 (CMB): 0.83 ± 0.013
  → Resolved S₈ = 0.830 sits at the Planck CMB value, exactly on the
  CMB-anchored baseline used in the linear-response template.

So the *current numerical output* matches the SH0ES (H₀) / Planck (S₈)
end of each tension; the framework does not currently produce a
self-consistent compromise value between SH0ES and DESI for H₀, nor
between Planck and KiDS/DES for S₈. This divergence from the
template's narrative claim of "~4-6 km/s/Mpc upward shift" and
"~0.05-0.1 S₈ suppression" is documented here rather than hidden by
a fudge factor.

Module surface
--------------
* :class:`CosmologicalTensionsResolver` — main class, parameterised by
  ``mirror_coupling`` and ``ReT_stabilized`` (defaults match the
  v25.0 / v26.0 anchors).
* :meth:`mirror_dark_energy_contribution` — returns Δw_mirror.
* :meth:`resolve_H0_tension` — returns H₀_resolved given Δw.
* :meth:`resolve_S8_tension` — returns S₈_resolved given Δw.
* :meth:`derive_tension_resolution` — full pipeline, returns the dict
  ``{"delta_w_mirror", "H0_resolved_km_s_Mpc", "S8_resolved", "status"}``.
* :func:`resolve_cosmological_tensions` — module entry point.

Each step registers an EML tree entry via
``eml_operator_tree("cosmological_tensions")`` so the derivation chain
appears in ``AutoGenerated/eml_trees_v25.json`` and is consumed by the
Sprint 3 dependency walker.

Copyright (c) 2025-2026 Andrew Keith Watts. All rights reserved.

Dedicated To:
    My Wife: Elizabeth May Watts
    Our Messiah: Jesus Of Nazareth
"""

from __future__ import annotations

import math
from typing import Any, Dict

from metaphysica.simulations.core.eml_tree_adapter import eml_operator_tree


# ── Module constants --------------------------------------------------------

#: Default Sprint 5.1 mirror-sector coupling strength. Sourced from the
#: v26.0 mirror-DM relic module (the Z₂ bridge coupling fixed by the
#: bridge geometry); fully geometric, not a fit parameter.
DEFAULT_MIRROR_COUPLING: float = 1.2e-10

#: Default Sprint 4 stabilised volume modulus Re(T), in GeV. Matches
#: ``RE_T_VEV_TARGET`` from
#: :mod:`metaphysica.simulations.PM.geometry.re_t_sector`.
DEFAULT_RET_STABILIZED: float = 174.033

#: Baseline H₀ in km/s/Mpc. The SH0ES local distance-ladder anchor used as
#: the starting point of the linear-response shift.
H0_BASELINE_KM_S_MPC: float = 73.04

#: Remaining H₀ tension in σ (from the older / live cosmology derivation in
#: :mod:`metaphysica.simulations.PM.cosmology`). The mirror-coupling template
#: produces a Δw ≈ 10⁻¹³ shift, which is ~12 orders of magnitude too small
#: to relax this tension; the value is therefore reported unchanged.
H0_TENSION_REMAINING_SIGMA: float = 3.17

#: Remaining S₈ tension in σ. Conservative estimate from the same older
#: cosmology derivation (KiDS-1000 / DES-Y3 vs Planck 2018). Unmoved by
#: the mirror coupling at its present magnitude.
S8_TENSION_REMAINING_SIGMA: float = 2.5

#: Δw_mirror magnitude that would actually be needed to shift H₀ from the
#: SH0ES baseline (73.04) down to a DESI/Planck-compatible value
#: (~67.0 km/s/Mpc), via the linear-response coefficient 5.8:
#:     ΔH₀_target ≈ −6.96 km/s/Mpc  →  Δw_needed ≈ −1.2 × 10⁻²
#: The currently computed Δw is ~6 × 10⁻¹³, i.e. ~10¹³× too small.
DELTA_W_NEEDED_TO_RESOLVE_H0: float = -0.012

#: Baseline S₈ from Planck 2018 (CMB-anchored). Used as the starting
#: point of the linear-response shift.
S8_BASELINE: float = 0.83

#: Decay scale of the mirror DE contribution in Re(T), in GeV. The
#: 200-GeV scale is just above the Higgs-VEV anchor so the exponential
#: provides an O(1) suppression at the stabilised Re(T).
RET_DECAY_SCALE_GEV: float = 200.0

#: Late-time mirror DE amplitude prefactor (dimensionless). Set by the
#: bridge geometry of the Z₂ mirror sector — see the template at
#: ``PossibleImprovements.txt`` lines 1193-1196.
MIRROR_DE_AMPLITUDE: float = 0.012

#: Linear-response coefficient for H₀ shift per unit Δw, in km/s/Mpc.
#: Standard DESI-like analysis coefficient.
H0_LINEAR_RESPONSE: float = 5.8

#: Linear-response coefficient for S₈ suppression per unit Δw.
S8_LINEAR_RESPONSE: float = 0.085


# ── Sprint T6 #3 — Tier 3 architectural KK early-dark-energy mechanism -----
#
# Reference: TIER_2_3_ROADMAP.md §T3.4 (mechanism b).
#
# Sprint 5.5's mirror-coupling Δw is ~10^13 too small; T3.4 identifies the
# physical origin of the larger coupling. Mechanism (b) is early dark energy
# (EDE) from a tower of 26D-bulk Kaluza-Klein modes with mass scale m_KK ~
# 1/R_26 set by the compactification radius. When m_KK crosses the
# radiation temperature T at z ~ 3000 the modes become non-relativistic and
# briefly dominate as dark energy, raising the inferred H₀ (Karwal &
# Kamionkowski 2016, Schoneberg et al. 2022 "H₀ Olympics").

#: Number of KK modes in the bridge sector. The naive 26D framework count
#: is 12 bridges · b₃ = 288 (one mode per bridge × per b₃ Betti generator);
#: see :data:`N_KK_BRIDGES` for the physical-tower count used in the
#: honest mechanism below.
N_KK_FULL_TOWER: int = 288

#: Number of *physically active* KK modes near m_KK ~ T_recomb. The b₃ =
#: 24 cohomology classes are *labels*, not independent thermal degrees of
#: freedom — only the 12 bridge pairs supply distinct KK towers in the
#: 26D bulk. The natural EDE multiplicity is therefore 12, not 288.
N_KK_BRIDGES: int = 12

#: Radiation-era effective relativistic degrees of freedom at z ~ 1100
#: (recombination): photons (2) + neutrinos (7/8 · 2 · 3 · (4/11)^(4/3))
#: ≈ 3.36. Used in the KK / radiation energy-density ratio.
G_STAR_RECOMB: float = 3.36

#: Pre-factor in ρ_KK / ρ_rad per KK mode at threshold (m_KK ~ T): the
#: ratio of a non-relativistic Bose gas energy density (ζ(3)·g·T³·m / π²)
#: to a single relativistic-d.o.f. radiation density (π²/30 · T⁴) at
#: m_KK = T:
#:     (30 · ζ(3)) / π⁴ ≈ 0.3702
#: This is the standard threshold-crossing prefactor.
RHO_KK_THRESHOLD_PREFACTOR: float = 0.3702

#: Linear-response coefficient: ΔH₀ in km/s/Mpc per unit f_EDE. From
#: Schoneberg et al. 2022 "H₀ Olympics" Table 1 — peak EDE fraction
#: f_EDE = 0.10 yields ΔH₀ ≈ 4.5 km/s/Mpc, so dH₀/df_EDE ≈ 45.
H0_PER_F_EDE: float = 45.0

#: Target f_EDE (Planck-DESI midpoint resolution). A peak EDE fraction of
#: ~2 % at z ~ 3000 raises inferred H₀ by ~0.9 km/s/Mpc; ~7 % is the upper
#: edge of the viable window before CMB damping-tail constraints bite.
F_EDE_TARGET_RESOLUTION: float = 0.02

#: Recombination radiation temperature in eV (T_rec ≈ 0.26 eV, z ≈ 1100).
T_RECOMB_EV: float = 0.26


# ── Cosmological tensions resolver ------------------------------------------


class CosmologicalTensionsResolver:
    """Resolve H₀ and S₈ tensions via mirror-sector dark energy.

    Combines the Sprint 4 stabilised Re(T) value with the Sprint 5.1
    mirror coupling to predict the late-time / early-DE shift of the
    dark-energy equation of state, and propagates that shift to H₀ and
    S₈ via linear-response coefficients fixed by the DESI / KiDS
    analyses.

    Parameters
    ----------
    mirror_coupling:
        The Z₂ mirror-sector coupling strength (dimensionless). Defaults
        to :data:`DEFAULT_MIRROR_COUPLING` (``1.2e-10``), the value from
        the v26.0 mirror-DM relic module.
    ReT_stabilized:
        The stabilised volume modulus Re(T) in GeV. Defaults to
        :data:`DEFAULT_RET_STABILIZED` (``174.033``), the v25.0 Higgs-VEV
        anchor.

    Notes
    -----
    Both inputs are upstream geometric quantities (no fit parameters
    introduced here). The output is an anchored baseline plus predicted
    shift Δw (only Δw ≈ 6e-13 is derived; the 73.04 baseline is the
    SH0ES anchor) — see the module docstring for the numerical reality
    check and observational comparison.

    Examples
    --------
    >>> result = CosmologicalTensionsResolver().derive_tension_resolution()
    >>> 65.0 < result["H0_resolved_km_s_Mpc"] < 75.0
    True
    >>> 0.7 < result["S8_resolved"] < 0.9
    True
    """

    __slots__ = ("mirror_coupling", "ReT", "tension_tree")

    def __init__(
        self,
        mirror_coupling: float = DEFAULT_MIRROR_COUPLING,
        ReT_stabilized: float = DEFAULT_RET_STABILIZED,
    ) -> None:
        if mirror_coupling <= 0:
            raise ValueError(
                "CosmologicalTensionsResolver.__init__: mirror_coupling "
                f"must be positive, got {mirror_coupling!r}"
            )
        if ReT_stabilized <= 0:
            raise ValueError(
                "CosmologicalTensionsResolver.__init__: ReT_stabilized "
                f"must be positive, got {ReT_stabilized!r}"
            )
        self.mirror_coupling: float = float(mirror_coupling)
        self.ReT: float = float(ReT_stabilized)
        self.tension_tree = eml_operator_tree("cosmological_tensions")

    # ── Core derivations ---------------------------------------------------

    def mirror_dark_energy_contribution(self) -> float:
        """Compute the extra Δw from the mirror sector at late times.

        Formula (per :data:`MIRROR_DE_AMPLITUDE`,
        :data:`RET_DECAY_SCALE_GEV`):

            Δw_mirror = 0.012 · exp(−Re(T) / 200) · g_mirror

        Returns
        -------
        float
            The dimensionless Δw contribution from the Z₂ mirror sector.
        """
        delta_w = (
            MIRROR_DE_AMPLITUDE
            * math.exp(-self.ReT / RET_DECAY_SCALE_GEV)
            * self.mirror_coupling
        )
        self.tension_tree.register_derivation(
            param="delta_w_mirror",
            formula=(
                "0.012 * exp(-Re(T) / 200) * g_mirror  "
                "-- mirror-sector DE from Z2 bridge "
                "(Re(T) anchored at b3 = 24 via Sprint 4 #3)"
            ),
            value=float(delta_w),
        )
        return float(delta_w)

    def resolve_H0_tension(self, delta_w: float) -> float:
        """Apply the linear-response H₀ shift given Δw.

            H₀_resolved = 73.04 + 5.8 · Δw_mirror     [km/s/Mpc]

        Anchored baseline plus predicted shift Δw: only Δw ≈ 6e-13 is
        derived; the 73.04 baseline is the SH0ES anchor.

        Parameters
        ----------
        delta_w:
            The mirror Δw contribution from
            :meth:`mirror_dark_energy_contribution`.

        Returns
        -------
        float
            The resolved H₀ in km/s/Mpc.
        """
        H0_shift = H0_LINEAR_RESPONSE * float(delta_w)
        H0_resolved = H0_BASELINE_KM_S_MPC + H0_shift
        self.tension_tree.register_derivation(
            param="H0_resolved_km_s_Mpc",
            formula=(
                "73.04 + 5.8 * delta_w_mirror  "
                "-- H0 + DESI-linear-response shift "
                "(delta_w from b3 = 24 anchored mirror sector; "
                "magnitude currently ~10^13x too small to resolve tension)"
            ),
            value=float(H0_resolved),
        )
        return float(H0_resolved)

    def resolve_S8_tension(self, delta_w: float) -> float:
        """Apply the linear-response S₈ suppression given Δw.

            S₈_resolved = 0.83 − 0.085 · Δw_mirror

        Anchored baseline plus predicted shift Δw: only Δw ≈ 6e-13 is
        derived; the 0.83 baseline is the Planck anchor.

        Parameters
        ----------
        delta_w:
            The mirror Δw contribution from
            :meth:`mirror_dark_energy_contribution`.

        Returns
        -------
        float
            The resolved S₈ (dimensionless).
        """
        S8_suppression = S8_LINEAR_RESPONSE * float(delta_w)
        S8_resolved = S8_BASELINE - S8_suppression
        self.tension_tree.register_derivation(
            param="S8_resolved",
            formula=(
                "0.83 - 0.085 * delta_w_mirror  "
                "-- S8 + KiDS/DES growth-suppression "
                "(delta_w from b3 = 24 anchored mirror sector)"
            ),
            value=float(S8_resolved),
        )
        return float(S8_resolved)

    # ── Sprint T6 #3 — Tier 3 architectural EDE mechanism --------------

    def compute_kk_early_dark_energy(
        self,
        T_recomb: float = T_RECOMB_EV,
        m_kk_recomb: float = 0.5,
    ) -> Dict[str, Any]:
        """Early dark energy from the 26D-bulk Kaluza-Klein tower.

        Reference: TIER_2_3_ROADMAP.md §T3.4, mechanism (b).

        Physical picture
        ----------------
        The 26D bulk admits a Kaluza-Klein tower with mass scale
        ``m_KK ~ 1 / R_26 ~ M_GUT``. Most KK modes are far above any
        cosmological temperature scale and decouple, but if the lightest
        modes have eV-scale masses they cross ``m_KK ~ T`` at z ~ 3000
        (recombination), briefly contributing an EDE-like component that
        raises the inferred H₀ (Karwal & Kamionkowski 2016).

        The honest accounting (per-mode threshold contribution):

            ρ_KK / ρ_rad  =  N_active · (30 · ζ(3) / π⁴ · g_*⁻¹) · (m_KK / T)

        where the threshold prefactor ``30 · ζ(3) / π⁴ ≈ 0.3702`` is the
        ratio of a non-relativistic Bose gas (ρ ~ ζ(3)·T³·m/π²) to one
        relativistic d.o.f. of radiation (ρ ~ π²/30·T⁴) at m = T, and
        ``g_* ≈ 3.36`` is the radiation-era effective d.o.f. count at
        recombination.

        Naive 288-mode result (per the user-proposed template formula
        ``f_EDE = N_KK · (M_KK / T)⁻¹`` with M_KK = T):

            f_EDE_naive = 288 · (0.5 / 0.26)⁻¹ ≈ 150

        This is physically impossible (f_EDE must be < 1) — the template
        formula omits the radiation-d.o.f. normalisation and the
        ζ(3) / π⁴ prefactor, and treats *every* mode in the b₃ = 24
        cohomology as a thermal d.o.f.

        Honest accounting
        -----------------
        b₃ = 24 labels cohomology classes (KK *winding numbers*), not
        independent thermal d.o.f. The genuine multiplicity is the 12
        bridge pairs (``N_KK_BRIDGES``). With proper radiation-d.o.f.
        normalisation:

            f_EDE = (RHO_KK_THRESHOLD_PREFACTOR / G_STAR_RECOMB)
                    · N_KK_BRIDGES · (m_KK / T_recomb)

        At m_KK = T_recomb (peak threshold crossing):
            f_EDE = 0.3702 / 3.36 · 12 · 1.0 ≈ 1.32

        Still too large by a factor of ~10 at full crossing — but the
        framework's natural sub-threshold operating regime is
        m_KK ≪ T_recomb (the bridge sector decouples thermally before
        recombination). At m_KK / T ~ 0.015 the 12 bridges deliver
        f_EDE ≈ 0.02, matching the Planck-DESI midpoint resolution.

        Parameters
        ----------
        T_recomb:
            Radiation temperature at recombination, eV. Default
            :data:`T_RECOMB_EV` ≈ 0.26 eV (z ~ 1100).
        m_kk_recomb:
            Effective KK mass at recombination, eV. Default 0.5 eV — the
            template's threshold-crossing condition. Override with the
            physically sub-threshold value (~0.004 eV) to land at the
            target f_EDE.

        Returns
        -------
        dict
            ``{"f_EDE_naive", "f_EDE_honest", "delta_H0_pct_naive",
            "delta_H0_pct_honest", "delta_H0_km_s_Mpc",
            "m_kk_for_target_f_EDE_eV", "mechanism_viable",
            "carried_to_v28", "status"}``.
        """
        if T_recomb <= 0:
            raise ValueError(
                "compute_kk_early_dark_energy: T_recomb must be "
                f"positive, got {T_recomb!r}"
            )
        if m_kk_recomb <= 0:
            raise ValueError(
                "compute_kk_early_dark_energy: m_kk_recomb must be "
                f"positive, got {m_kk_recomb!r}"
            )

        # ── Naive template formula (as proposed in the T3.4 brief) ----
        # f_EDE = N_KK / (M_KK / T)    when M_KK ~ T
        f_ede_naive = float(N_KK_FULL_TOWER) / (m_kk_recomb / T_recomb)
        delta_H0_pct_naive = 4.5 * f_ede_naive  # per template

        # ── Honest physics: per-mode threshold contribution ----------
        # f_EDE = (30 ζ(3) / π⁴ g_*) · N_bridges · (m_KK / T)
        threshold_ratio = m_kk_recomb / T_recomb
        f_ede_honest = (
            RHO_KK_THRESHOLD_PREFACTOR
            / G_STAR_RECOMB
            * float(N_KK_BRIDGES)
            * threshold_ratio
        )
        delta_H0_km_s_Mpc = H0_PER_F_EDE * f_ede_honest
        delta_H0_pct_honest = (
            100.0 * delta_H0_km_s_Mpc / H0_BASELINE_KM_S_MPC
        )

        # Invert: what m_KK / T would yield f_EDE = 0.02 (target)?
        f_ede_per_threshold = (
            RHO_KK_THRESHOLD_PREFACTOR
            / G_STAR_RECOMB
            * float(N_KK_BRIDGES)
        )
        m_kk_for_target = (
            F_EDE_TARGET_RESOLUTION / f_ede_per_threshold * T_recomb
        )

        # The mechanism is "viable" if a physically sensible m_KK
        # (i.e. 0 < m_kk_for_target < T_recomb, i.e. sub-threshold) lands
        # at the target. With N_bridges = 12 the required m_KK/T ratio
        # is ~0.015, which is sub-threshold and physically achievable —
        # but it requires a v28 derivation of why the lightest bridge
        # mass should sit at this specific scale, which the current
        # framework does not supply.
        ratio_for_target = m_kk_for_target / T_recomb
        mechanism_viable = 0.0 < ratio_for_target < 1.0
        carried_to_v28 = not (
            # Naturalness check: the framework would need to derive
            # m_kk_for_target ~ 4e-3 eV from b3 / k_gimel without fit.
            # That derivation does not yet exist.
            False
        )

        status = (
            "KK_EDE_MECHANISM_SCOPED_V28: "
            f"naive 288-mode formula gives f_EDE = {f_ede_naive:.3g} "
            "(unphysical: >> 1); honest 12-bridge accounting gives "
            f"f_EDE = {f_ede_honest:.3g} at m_KK = T_recomb; to land at "
            f"f_EDE = {F_EDE_TARGET_RESOLUTION:.2g} needs m_KK / T = "
            f"{ratio_for_target:.3g} -- sub-threshold and viable, but the "
            "v27 framework does not yet derive this specific mass scale "
            "from b3 = 24 / k_gimel without fit. Carried to v28."
        )

        result: Dict[str, Any] = {
            "f_EDE_naive": float(f_ede_naive),
            "f_EDE_honest": float(f_ede_honest),
            "f_EDE_target": float(F_EDE_TARGET_RESOLUTION),
            "delta_H0_pct_naive": float(delta_H0_pct_naive),
            "delta_H0_pct_honest": float(delta_H0_pct_honest),
            "delta_H0_km_s_Mpc": float(delta_H0_km_s_Mpc),
            "m_kk_recomb_eV": float(m_kk_recomb),
            "T_recomb_eV": float(T_recomb),
            "m_kk_for_target_f_EDE_eV": float(m_kk_for_target),
            "N_KK_full_tower": int(N_KK_FULL_TOWER),
            "N_KK_bridges": int(N_KK_BRIDGES),
            "mechanism_viable": bool(mechanism_viable),
            "carried_to_v28": bool(carried_to_v28),
            "status": status,
        }

        # Register both the naive and honest derivations in the EML tree
        # with the b3 = 24 traceback so the cross-check report can
        # detect the v27 → v28 architectural gap.
        self.tension_tree.register_derivation(
            param="f_EDE_kk_naive_288",
            formula=(
                "N_KK / (m_KK / T)  -- naive 288-mode template "
                "(b3 = 24 * 12 bridges); UNPHYSICAL (>> 1)"
            ),
            value=float(f_ede_naive),
        )
        self.tension_tree.register_derivation(
            param="f_EDE_kk_honest_12bridges",
            formula=(
                "(30 zeta(3) / pi^4 g_*) * N_bridges * (m_KK / T)  "
                "-- 12 bridge KK towers with proper radiation "
                "normalisation; rooted at b3 = 24 cohomology"
            ),
            value=float(f_ede_honest),
        )
        self.tension_tree.register_derivation(
            param="m_kk_for_target_f_EDE",
            formula=(
                "F_EDE_TARGET / [(30 zeta(3) / pi^4 g_*) * N_bridges] "
                "* T_recomb  -- inverted; b3 = 24 cohomology rooted, "
                "needs v28 derivation of natural m_KK"
            ),
            value=float(m_kk_for_target),
        )
        return result

    def derive_tension_resolution(self) -> Dict[str, Any]:
        """Run the full tension-documentation pipeline.

        Combines :meth:`mirror_dark_energy_contribution`,
        :meth:`resolve_H0_tension`, and :meth:`resolve_S8_tension`, and
        writes a summary entry to the EML tree.

        Honest accounting (Sprint T1 task #6)
        -------------------------------------
        The Sprint 5.5 mirror-coupling template produces a Δw_mirror of
        order 10⁻¹³ at the stabilised Re(T) — roughly 10¹³× too small to
        produce the ~4 km/s/Mpc H₀ shift required to relax the tension.
        The signs and shapes of the shifts are correct, but the
        magnitudes are not. This method therefore returns the *baseline*
        SH0ES H₀ (73.04 km/s/Mpc) and Planck S₈ (0.83), the *unchanged*
        tension significances from the older live derivation
        (3.17σ / 2.5σ), and a ``documented_divergence`` sub-dict
        recording the size of the gap between the template's Δw and the
        Δw that would actually be needed. The status string contains
        ``DOCUMENTED_TENSION`` so downstream consumers can detect that
        the framework has *not* resolved these tensions at v26.x and
        needs a v27.0 architectural lift.

        Returns
        -------
        dict
            Full documentation payload — see the source for the exact
            key list.

        Raises
        ------
        ValueError
            If the (essentially unchanged) values escape the documented
            validation windows (65 < H₀ < 75 and 0.7 < S₈ < 0.9). This
            protects downstream callers from silently consuming
            numerically corrupt inputs (e.g. a future regression that
            flips a sign).
        """
        delta_w = self.mirror_dark_energy_contribution()
        H0_resolved = self.resolve_H0_tension(delta_w)
        S8_resolved = self.resolve_S8_tension(delta_w)

        if not (65.0 < H0_resolved < 75.0):
            raise ValueError(
                "CosmologicalTensionsResolver: H0_resolved="
                f"{H0_resolved!r} falls outside the validation window "
                "65 < H0 < 75."
            )
        if not (0.7 < S8_resolved < 0.9):
            raise ValueError(
                "CosmologicalTensionsResolver: S8_resolved="
                f"{S8_resolved!r} falls outside the validation window "
                "0.7 < S8 < 0.9."
            )

        # Honest status: the template formally returns H₀ = 73.04 and
        # S₈ ≈ 0.83 unchanged, because Δw is ~10⁻¹³ rather than the
        # ~10⁻² that would actually be needed to shift H₀ by ~7 km/s/Mpc.
        _status_msg = (
            "DOCUMENTED_TENSION: mirror coupling too small by ~10^13 "
            "to actually shift H0/S8 -- needs v27.0 architectural lift"
        )

        # Magnitude gap: ratio of "needed" Δw to "actual" Δw. Guard
        # against division by zero with a generous floor (1e-30) so the
        # ratio remains finite even if a downstream override zeros Δw.
        _magnitude_gap = DELTA_W_NEEDED_TO_RESOLVE_H0 / max(
            abs(float(delta_w)), 1e-30
        )

        documented_divergence: Dict[str, Any] = {
            "delta_w_needed_to_resolve_H0": float(
                DELTA_W_NEEDED_TO_RESOLVE_H0
            ),
            "delta_w_actual": float(delta_w),
            "magnitude_gap": float(_magnitude_gap),
            "note": (
                "Template coupling produces 10^13x too-small shifts; "
                "signs/shapes correct, magnitudes need architectural fix"
            ),
        }

        results: Dict[str, Any] = {
            "delta_w_mirror": float(delta_w),
            "H0_baseline_km_s_Mpc": float(H0_BASELINE_KM_S_MPC),
            "H0_resolved_km_s_Mpc": float(H0_resolved),
            "S8_baseline": float(S8_BASELINE),
            "S8_resolved": float(S8_resolved),
            "H0_tension_remaining_sigma": float(
                H0_TENSION_REMAINING_SIGMA
            ),
            "S8_tension_remaining_sigma": float(
                S8_TENSION_REMAINING_SIGMA
            ),
            # Per-module status key avoids the `cosmology.status` collision
            # in PMRegistry.load_v26_modules() (mirror_dm_relic, inflation
            # and cosmological_tensions all share the ``cosmology.`` prefix).
            "cosmological_tensions_status": _status_msg,
            # Kept for human display / backwards compatibility.
            "status": _status_msg,
            "documented_divergence": documented_divergence,
        }

        # Summary entry — formula text mentions ``b3`` so the
        # ``_formula_has_b3_traceback`` flag fires, cross-linking the
        # entry to the b₃ = 24 seed via Re(T).
        self.tension_tree.register_derivation(
            param="full_cosmological_tension_resolution",
            formula=(
                "mirror DE / early DE from 26D bulk + Re(T); "
                "Re(T) anchored at b3 = 24 (Sprint 4 #3); "
                "DOCUMENTED_TENSION -- magnitudes ~10^13x too small"
            ),
            value=float(H0_resolved),
        )
        return results


# ── Module entry point ------------------------------------------------------


def resolve_cosmological_tensions() -> Dict[str, Any]:
    """Module-level entry: derive H₀ / S₈ resolution with defaults.

    Equivalent to
    ``CosmologicalTensionsResolver().derive_tension_resolution()``.

    Returns
    -------
    dict
        Same shape as
        :meth:`CosmologicalTensionsResolver.derive_tension_resolution`.
    """
    return CosmologicalTensionsResolver().derive_tension_resolution()


__all__ = [
    "CosmologicalTensionsResolver",
    "DEFAULT_MIRROR_COUPLING",
    "DEFAULT_RET_STABILIZED",
    "H0_BASELINE_KM_S_MPC",
    "S8_BASELINE",
    "RET_DECAY_SCALE_GEV",
    "MIRROR_DE_AMPLITUDE",
    "H0_LINEAR_RESPONSE",
    "S8_LINEAR_RESPONSE",
    "H0_TENSION_REMAINING_SIGMA",
    "S8_TENSION_REMAINING_SIGMA",
    "DELTA_W_NEEDED_TO_RESOLVE_H0",
    # Sprint T6 #3 — Tier 3 KK early-dark-energy mechanism (T3.4 b)
    "N_KK_FULL_TOWER",
    "N_KK_BRIDGES",
    "G_STAR_RECOMB",
    "RHO_KK_THRESHOLD_PREFACTOR",
    "H0_PER_F_EDE",
    "F_EDE_TARGET_RESOLUTION",
    "T_RECOMB_EV",
    "resolve_cosmological_tensions",
]

# Alias for registry.load_v26_modules entry-point contract.
resolve_tensions = resolve_cosmological_tensions
